src/Message/OpenMP.h, src/QMCHamiltonians/ECPotentialBuilder.cpp
omp_get_nested is deprecated in OpenMP >=5.0. Implementations now create warnings. Use the recommended replacement call which has been present since at least 3.0.
- New feature
- No
nitrogen, llvm12.
=> Replace deprecated OpenMP get nested call

src/QMCHamiltonians/tests/test_bare_kinetic.cpp, src/QMCHamiltonians/tests/test_coulomb_CUDA.cpp, src/QMCHamiltonians/tests/test_coulomb_pbcAA.cpp, src/QMCHamiltonians/tests/test_coulomb_pbcAA_ewald.cpp, src/QMCHamiltonians/tests/test_coulomb_pbcAB.cpp, src/QMCHamiltonians/tests/test_coulomb_pbcAB_ewald.cpp, src/QMCHamiltonians/tests/test_ecp.cpp, src/QMCHamiltonians/tests/test_force.cpp, src/QMCHamiltonians/tests/test_spacewarp.cpp, src/QMCHamiltonians/tests/test_stress.cpp, src/io/hdf/hdf_archive.h
1. remove ParticleSetPool dependency in most Hamiltonian unit tests
2. Use SFINAE to remove read functions when containers are const. The error message is much more readable than tons of template compilation failure.
- No
epyc-server
=> Clean up ham unit tests

src/Numerics/OneDimCubicSpline.h, src/Numerics/OneDimGridBase.h, src/Numerics/OneDimGridFactory.cpp, src/Numerics/OneDimGridFunctor.h, src/Numerics/OneDimQuinticSpline.h, src/Numerics/tests/test_grid_functor.cpp, src/Numerics/tests/test_one_dim_cubic_spline.cpp, src/Numerics/tests/test_transform.cpp, src/Particle/LongRange/LRCoulombSingleton.cpp, src/QMCHamiltonians/CoulombPBCAB.cpp, src/QMCHamiltonians/ECPComponentBuilder.1.cpp, src/QMCHamiltonians/ECPComponentBuilder.2.cpp, src/QMCHamiltonians/ECPComponentBuilder.cpp, src/QMCHamiltonians/ECPComponentBuilder.h, src/QMCHamiltonians/ECPComponentBuilder_L2.cpp, src/QMCHamiltonians/ECPotentialBuilder.cpp, src/QMCWaveFunctions/LCAO/CuspCorrectionConstruction.cpp, src/QMCWaveFunctions/LCAO/RadialOrbitalSetBuilder.h, src/QMCWaveFunctions/tests/test_multiquintic_spline.cpp
This fixes most direct leaks found in deterministic-unit_test_hamiltonian_force by clang address sanitizer.
I didn't fix the leak in src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp:343 since @williamfgc already has a branch that changes the return type from a raw pointer to a unique_ptr. 
This is part of #3083.
- Bugfix
- …
=> Fix direct memory leaks in deterministic-unit_test_hamiltonian_force

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step.sh
- This PR enables GPU CI using legacy CUDA on deterministic tests running on sulfur as a self-hosted runner on GitHub Actions.
- Set new workflow configuration file to trigger with current on-demand workflow: "Test this please" as PR comment by authorized user. Currently the new status will only show up if triggered.
- Set LD_LIBRARY_PATH to point at CUDA runtime libraries
To verify/understand:
- New feature (GPU CI test)
- Testing changes (new CI workflow to test with `-DQMC_CUDA=1` on self-hosted runner)
- No
sulfur locally, entire workflow must run on GitHub Actions
- No. This PR adds tests to cover any new code, or …
=> Enable GPU CI on GitHub Actions self-hosted runner

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step.sh
Address CI changes from feedback in #3260 targeting self-hosted runners.
Move general checks early to report `issue_comment` event checks as skipped
Always issue check status in case of failure
Add `set -x` to CI script for output trace
- Testing changes (e.g. new unit/integration/performance tests) CI self-hosted
- No
Must pass and be tested on CI
=> CI changes

tests/test_automation/github-actions/ci/run_step.sh
Affect self-hosted runners which must rerun in a clean directory every time
Add log messages
From feedback in #3260 when testing CI on self-hosted runners
- No
Must pass GitHub Actions CI
=> Check for out-of-source build directory existence in GitHub Action CI config step

src/.clang-tidy, src/Containers/OhmmsSoA/VectorSoaContainer.h, src/Particle/ParticleSetPool.cpp, src/Particle/ParticleSetPool.h, src/QMCDrivers/QMCDriverInput.h, src/Utilities/NewTimer.h, src/type_traits/TypeRequire.hpp
After setting up clang-tidy #3269, It tried a few other checks. Warnings from [performance-noexcept-move-constructor](https://clang.llvm.org/extra/clang-tidy/checks/performance-noexcept-move-constructor.html) caught my attention. I don't know if any of these objects are used in STL containers, but adding this is good practice. 
Marking the defaulted move constructor …
=> Move constructors marked noexcept

src/QMCDrivers/DMC/DMC_CUDA.h, src/QMCDrivers/VMC/VMC_CUDA.h, src/QMCDrivers/WFOpt/QMCCostFunctionCUDA.h, src/QMCHamiltonians/BareKineticEnergy.h, src/QMCHamiltonians/ChiesaCorrection.h, src/QMCHamiltonians/ConservedEnergy.h, src/QMCHamiltonians/CoulombPBCAA_CUDA.h, src/QMCHamiltonians/CoulombPBCAB_CUDA.h, src/QMCHamiltonians/CoulombPotential_CUDA.h, src/QMCHamiltonians/LocalECPotential_CUDA.h, src/QMCHamiltonians/MPC_CUDA.h, src/QMCHamiltonians/NonLocalECPotential_CUDA.h, src/QMCHamiltonians/SkEstimator_CUDA.h, src/QMCWaveFunctions/CompositeSPOSet.cpp, src/QMCWaveFunctions/CompositeSPOSet.h, src/QMCWaveFunctions/Fermion/DiracDeterminantCUDA.h, src/QMCWaveFunctions/Jastrow/OneBodyJastrowOrbitalBspline.h, src/QMCWaveFunctions/Jastrow/TwoBodyJastrowOrbitalBspline.h
Followup to #3269. I used the clang-tidy check `modernize-use-override` to all update all member functions in the legacy `QMC_CUDA=1` build.
Fixes issue #3262.
- No
sulfur
_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate …
=> Add override to functions in legacy QMC_CUDA build

CMake/ClangCompilers.cmake
`-Wsuggest-override` was added in clang-11
https://reviews.llvm.org/D82728
https://clang.llvm.org/docs/DiagnosticsReference.html#wsuggest-override
This adds a check so we only add the warning where it is available.
- Bugfix
- No …
=> Check clang version before adding -Wsuggest-override

src/QMCTools/QMCFiniteSize/QMCFiniteSize.cpp, src/QMCTools/tests/CMakeLists.txt, src/einspline/nubspline_create.c, src/einspline/nubspline_create.h
Fix leaks in `deterministic-unit-test-tools` test.
Remove `noasan` label reinstating test to asan CI checks
Leaks are due to interaction with C-based spline functions in `QMCTools/QMCFiniteSize`
Add function to free `NUBspline_1d_d` (spline might need future refactoring as more tests are added).
This is part of #3083 
- Bugfix: leak
- Testing changes: add `deterministic-unit-test-tools` test to asan CI checks
- No
Ubuntu 18.04, need to pass CI
=> Fix leaks in unit-test-tools adding test to asan checks

src/QMCDrivers/tests/CMakeLists.txt, src/QMCHamiltonians/tests/CMakeLists.txt, src/QMCWaveFunctions/tests/CMakeLists.txt
Adds to asan/lsan checks the following unit-tests after leaks are fixed by removing the `noasan` label
- ~deterministic-unit_test_wavefunction_trialwf~ not yet, due to #3077 
- deterministic-unit_test_hamiltonian_coulomb
- deterministic-unit_test_hamiltonian_force
- deterministic-unit_test_new_drivers
Related to #3083 
- Testing changes (e.g. new unit/integration/performance tests) asan added unit tests
- No
Ubuntu 18.04, must pass CI 
=> Add fixed unit tests to asan checks

src/QMCWaveFunctions/BsplineFactory/BsplineReaderBase.cpp, src/QMCWaveFunctions/BsplineFactory/BsplineReaderBase.h, src/QMCWaveFunctions/BsplineFactory/SplineSetReader.h, src/QMCWaveFunctions/EinsplineSpinorSetBuilder.cpp, src/QMCWaveFunctions/einspline_helper.hpp, src/QMCWaveFunctions/tests/test_einset_spinor.cpp
This PR addresses the bug for splined spinors that has prevented the SOC applied to solids. 
The issue was specific to the splines, in that an orbital rotation was being applied to balance the real and imaginary components of the splines. In the spinor case, since the spinor has the form phi_up e^{is} + phi_dn e^{-is}, if the splined phi_up and phi_dn are modified, the spin functions further alter the phase from the spin functions...and ultimately results in a bias in the spinors and therefore the entire wavefunction. This PR adds a bypass to the orbital rotation in the EinsplineSpinorSetBuilder.
I also had to modify the einspline spinor unit test to reflect this rotation not being applied, and instead used an external python tool to directly evaluate the plane wave orbitals/spinors and …
=> Spline bugfix for spinors

src/QMCWaveFunctions/LCAO/AOBasisBuilder.cpp, src/QMCWaveFunctions/LCAO/RadialOrbitalSetBuilder.h
Two minor changes are proposed. The first is a confusing logging call that logs a variable that is changed after it is logged. The second is a minor typo.
For the logging:
```
old logging position <input node="atomicBasisSet" name="H" expandYlm="natural" angular="spherical" elementType="H" normalized="no" type="Numerical" expM="0" />
new logging position <input node="atomicBasisSet" name="H" expandYlm="natural" angular="spherical" elementType="H" normalized="no" type="Numerical" expM="1" />
```
- Bugfix (sort of?)
- No
Ryzen workstation
- Yes. This PR is up to date with current the current …
=> Correct logging call print location and fix a typo

src/Particle/DistanceTableData.h, src/Particle/InitMolecularSystem.cpp, src/Particle/Lattice/ParticleBConds3DSoa.h, src/Particle/SoaDistanceTableAA.h, src/Particle/SoaDistanceTableAAOMPTarget.h, src/Particle/SoaDistanceTableAB.h, src/Particle/SoaDistanceTableABOMPTarget.h, src/Particle/createDistanceTable.h, src/Particle/createDistanceTableAA.cpp, src/Particle/createDistanceTableAAOMPTarget.cpp, src/Particle/createDistanceTableAB.cpp, src/Particle/createDistanceTableABOMPTarget.cpp, src/Particle/tests/CMakeLists.txt, src/Particle/tests/test_SoaDistanceTableAA.cpp, src/Particle/tests/test_particle.cpp
review after #3287
Keep the table up-to-date and symmetry is costly in human effort, memory and computational cost. So I changed all the
lower triangle only.
The displacements has been changed to lower triangle when SoA was developed. Now just make one more step.
- No
epyc-server
=> Keep only lower triangle in AA distances

src/QMCTools/QMCFiniteSize/SkParserBase.cpp, src/QMCTools/QMCFiniteSize/SkParserBase.h, src/QMCTools/QMCFiniteSize/SkParserHDF5.cpp, src/QMCTools/qmcfinitesize.cpp
This closes #3285 
The SkAll estimator is written to the stat.h5 with whatever name the user chooses in the qmcpack xml file. 
Previous behavior assumed the name was always "skall".
This adds an input argument to `qmcfinitesize` to set the SkAll groupname to whatever was it is in the stat.h5 file.
The default also now assumes it is SkAll, which is consistent with the example in the manual. 
Also I added some more detailed usage information for qmcfinitesize
- New feature/bugfix
- No
my workstation, gnu 9.2.0
- Yes. …
=> qmcfinitesize fix for SkAll group name in hdf5

nexus/lib/pwscf_analyzer.py
This PR adds to the function `plot_bandstructure` in `./nexus/lib/pwscf_analyzer.py`. It allows the user to provide a custom set of labels for the high symmetry k-points (in the form k_labels=['GAMMA','','','','M','','',...]) where the length of the label array should match the number of k-points in the analyzer object. When custom labels are give, spglib is no longer used since it is assume that the k-points in the analyzer object are different from the ones that would be generated by spglib.
- New feature
- No
Laptop. Linux …
=> Nexus: Allow bandstructure plotting with custom k-path

CMake/ClangCompilers.cmake, CMake/GNUCompilers.cmake, CMake/IntelCompilers.cmake, CMake/PGICompilers.cmake
A Debug build is intended to debug QMCPACK source code rather than a compiler option. For this reason, Debug build should carry compiler options as similar to Release build.
GNU/Clang -ffast-math and NVHPC -fast are applied to Debug build as well. So apply them direct to CMAKE_CXX_FLAGS
- No
epyc-server
=> Debug build use consistent options.

src/Particle/MCWalkerConfiguration.cpp, src/Particle/MCWalkerConfiguration.h, src/Particle/SampleStack.cpp, src/Particle/SampleStack.h, src/QMCDrivers/CorrelatedSampling/CSVMC.cpp, src/QMCDrivers/QMCDriver.cpp, src/QMCDrivers/QMCDriver.h, src/QMCDrivers/VMC/VMC.cpp
Switch `HDF5WalkerOutput` member object from raw to `std::unique` in `QMCDriver`
Address leak observed in deterministic tests
Related to #3312
- Bugfix
- Testing: fixing leaks in deterministic tests
- No
=> Switch HDFWalkerOutput raw pointer to std::unique to address leak

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step.sh
Existing tests only run on mixed precision on self-hosted CI
Now run the following combinations: (4 in total, 2 before)
real: full, mixed
complex: full, mixed
This PR must be merged into `develop` before changes take effect on CI.
- Testing changes: Add CUDA Legacy configurations on self-hosted CI
- No
sulfur, all 4 configurations must pass CI
=> Add full precision CUDA legacy tests on self-hosted CI

src/Containers/OhmmsPETE/OhmmsMatrix.h, src/Containers/OhmmsPETE/OhmmsVector.h, src/Containers/OhmmsSoA/VectorSoaContainer.h, src/Platforms/DualAllocator.hpp, src/Platforms/OMPTarget/OMPallocator.hpp
DualAllocator needed a change to really work for dual space Ohmms containers
This seems to me to be a more consistent and logical arrangement of const. Still need one const_cast.
Also did a rename since `getDevicePtr()` simply returns a private member variable and my convention is that it be `get_device_ptr()` both were floating around in the code.
follows from #3271 
- Yes
Leconte
=> DualAllocator Fix and Better const consistency for Dual space containers

src/QMCHamiltonians/ECPComponentBuilder_L2.cpp, src/QMCHamiltonians/L2Potential.h
This fixes memory leaks in 
415 - deterministic-Co_L2_std-vmc_dmc-1-1 (Failed)
426 - deterministic-Co_L2_L2-vmc_dmc-1-1 (Failed)
Part of issue #3312 
- Bugfix
- No
_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask. …
=> Fix memory leaks in L2 tests

src/QMCDrivers/WFOpt/QMCCostFunctionBase.h, src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp, src/QMCDrivers/WFOpt/QMCCostFunctionBatched.h, src/QMCDrivers/tests/test_QMCCostFunctionBatched.cpp
Add a member variable (`numSamples_`) to track the number of samples local to each MPI rank.  Previously the number of samples was obtained from the SampleStack variable (`samples_`) every time.  For testing this required full initializing of the SampleStack.  Now, depending on the function being tested, it may only requires initialization of the `numSamples_` variable.
Sequence of calls:
- constructor (SampleStack does not have any collected samples at this point, don't know actual number of samples)
- getConfigurations - initializes dLogPsi and d2LogPsi (used to get WF derivatives). These are sized to the number of samples.
- checkConfigurations - initializes RecordsOnNode, DerivRecords, and HDerivRecords and fills those in via WF and Hamiltonian evaluation (which use samples)
- …
=> Add member for number of rank-local samples.

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/DriverWalkerTypes.h, src/QMCDrivers/QMCDriverNew.cpp, src/QMCDrivers/VMC/VMCBatched.cpp, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/NonLocalECPotential.h, src/QMCHamiltonians/OperatorBase.h, src/QMCHamiltonians/QMCHamiltonian.cpp, src/QMCHamiltonians/QMCHamiltonian.h, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h, src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminant.h, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h, src/QMCWaveFunctions/Fermion/SlaterDet.cpp, src/QMCWaveFunctions/Fermion/SlaterDet.h, src/QMCWaveFunctions/Jastrow/J2OMPTarget.cpp, src/QMCWaveFunctions/Jastrow/J2OMPTarget.h, src/QMCWaveFunctions/SPOSet.h, src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/TrialWaveFunction.h, src/QMCWaveFunctions/WaveFunctionComponent.h, src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
Adopt the same multiwalker resource management API as  #3015 for ParticleSet.
The benefit of added arguments is allowing managing views when resources are acquired and released.
It makes certain optimization possible.
Remove the resource redistribution in DMC T-moves. More static behavior should reduce potential bugs.
If something goes wrong, I should see segfault but both deterministic tests and performance tests (intended for T-moves) runs happily.
- New feature
- No
epyc-server
=> Adjust multi walker resource acquire/release API in TWF and Ham

tests/converter/CMakeLists.txt
Currently `converter-*` tests leak memory, but they are not marked as failures by `ctest` when running with asan/lsan sanitizers
Needed for implementing asan/lsan on deterministic tests
Similar to #3202
Related to #3312
Fixes to follow
- Yes
Ubuntu 20.04, should pass CI as leaks are not checked
=> Make sure converter leaks are marked as failures with ASAN/LSAN

src/QMCDrivers/WFOpt/QMCCostFunctionBase.cpp
These are the minimal changes to get `deterministic-He_ae-opt` tests passing with clang and the address sanitizer enabled.
This is part of #3312 
- Bugfix
- No
simply a reminder of what we are going to look for …
=> Fix asan test failures in deterministic-He_ae-opt

src/QMCTools/QMCGaussianParserBase.h, src/QMCTools/convert4qmc.cpp
Fix leaks associates with parser constructor in converter tests replacing raw pointer with `std::unique_ptr`.
Add virtual destructor to base class as required for `std::unique_ptr` implicit destructor. 
Related to #3312 
- Bugfix
- No
=> Replace parser raw pointer with std::unique_ptr in convert4qmc

src/QMCTools/QMCGaussianParserBase.cpp, src/QMCTools/QMCGaussianParserBase.h
`gridPtr` member in `QMCGaussianParserBase` is now a smart pointer
This addresses several leaks in converter deterministic tests.
Must provide default constructor in header due to custom deleter (passing `nullptr`).
Related to #3312 
- Bugfix
- No
=> Switch QMCGaussianParserBase::gridPtr raw pointer into a std::unique_ptr

tests/solids/diamondC_2x1x1-Gaussian_pp_MSD/CMakeLists.txt
Increase pass tolerance given observed failure trend on https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-diamondC_2x1x1-gaussian_pp_MSD-vmcbatch-dmcbatch-mwalkers_sdj-2-3-1-nonlocalecp&date=2021-08-16
- No
None
=> Increase pass tolerance for nonlocal ecp batched deterministic test

src/Numerics/OneDimGridBase.h
Adding initialization in variables due to an error when building with gcc-11.
Fixes #3364 
- Bugfix
- Yes
Ubuntu 20.10 + gcc-11 docker image on Ubuntu 20.04 host
=> Fix uninitialized variable errors when building with gcc-11

nexus/lib/hdfreader.py, tests/scripts/check_traces.py
Bug seen with python3-h5py2.10 + Ubuntu 20.10 + gcc-11 in which debian specific class types are picked up for Datasets and Groups.
In anticipation to adding gcc-11 on CI.
Fixes #3366 
- Bugfix
- No
Ubuntu 21.10 + gcc-11 + python3-h5py2.10 docker image on Ubuntu 20.04 host
=> Portable Datasets and Groups check in h5py readers

CMakeLists.txt, src/Concurrency/tests/CMakeLists.txt, src/Concurrency/tests/test_ParallelExecutorOPENMP.cpp, src/QMCDrivers/tests/CMakeLists.txt
Fix regression where unit tests written to be run with multiple threads are no longer run on multiple threads. Actually testing concurrent code concurrently is a good idea and #3373 reminded me that we should have more of this. When I went and look for an example I discovered previous tests I wrote were not actually being run with multiple threads anymore.
- Bugfix
- No
Leconte
- Yes This PR adds tests to cover any new …
=> restoring multithreaded unit tests

src/OhmmsApp/RandomNumberControl.h, src/Utilities/TimerManager.h
Fix gcc development build (broken on cdash) due to missing includes. unique_ptr is in `<memory>`
- Bugfix
- No
sulfur, no mpi build
=> Fix includes for unique_ptr

src/Particle/SoaDistanceTableAA.h, src/Particle/SoaDistanceTableAAOMPTarget.h, src/Particle/SoaDistanceTableAB.h, src/Particle/SoaDistanceTableABOMPTarget.h, src/QMCWaveFunctions/EinsplineSetBuilderESHDF.fft.cpp
This PR fixes an issue that was introduced in #3288 which causes the code to crash in the case where there is only one atom in the simulation cell. 
The distance tables function get_first_neighbor should only be called if there are actually neighbors, so an assertion is added in each of these functions. 
Also, in EinsplineSetBuilderESHDF.fft.cpp, now the …
=> fix for get_first_neighbor if there is only one particle

CMakeLists.txt, config/build_olcf_summit_Clang.sh
The default CUDA 11.0.3 after OS upgrade on Summit, caused frequent hanging with the offload code in production runs.
Stick to CUDA 10.1.243 for now.
PS: a small change on CUDA_NVCC_FLAGS is needed to allow passing additional arguments via command line.
- No
Summit
=> Downgrade Summit toolchain to cuda 10.1.243

nexus/lib/pseudopotential.py
The argument `v` is missing to the `set_component` call inside `add_L2` within `pseudopotential.py`. This PR resolves this issue.
- Bugfix
- No
Linux laptop
=> Nexus: Small fix to add_L2 function in pseudopotential.py

src/QMCWaveFunctions/Fermion/BackflowBuilder.cpp, src/QMCWaveFunctions/Fermion/Backflow_eI.h
Use `std::unique_ptr` for `Backflow_eI::uniqueRadFun` 
Failing tests with ASAN/LSAN:
508 - deterministic-bccH_2x2x2_ae_bf-opt-1-1 (Failed)
516 - deterministic-bccH_2x2x2_ae-vmc_bf-1-1 (Failed)
Related to #3312 
- Bugfix
- No
Ubuntu 20.04 , must pass CI
=> Fix memory leak in Backflow_eI member containers

src/QMCApp/QMCMain.cpp, src/QMCApp/qmcapp.cpp, src/QMCDrivers/CloneManager.cpp, src/QMCDrivers/CloneManager.h, src/QMCDrivers/tests/test_dmc_driver.cpp, src/QMCDrivers/tests/test_vmc_driver.cpp
Since #3356,
Crashes shown as https://cdash.qmcpack.org/CDash/testDetails.php?test=15105035&build=239150
are caused by freeing objects owned by CloneManager statically after CUDA runtime got destroyed (not controlled by QMCPACK).
This PR destroy those objects before exiting QMCMain.
- Bugfix
- No
epyc-server
=> Clear clones before exiting QMCMain

CMakeLists.txt
#3392 caused missing git info header in the printout.
- Bugfix
- No
epyc-server
=> Fix git info printing

src/Particle/DistanceTableData.h, src/Particle/ParticleSet.cpp, src/Particle/SoaDistanceTableAA.h, src/Particle/SoaDistanceTableAAOMPTarget.h
Had to read through some of ParticlesSet and distance table code today.  Found what looks to be a nonsense collision of default arguments to DistanceTableData::move and ParticleSet::makeVirtualMoves.  Luckily it seems to only result in some unecessary old__r_ and old_dr_ state being updated in the distance tables. 
I fix this call and fix the grammitically incorrect name of makeVirtualMove.
- Bugfix?
- No, at least according to the unit tests.  
Leconte
- Yes Code added or changed in …
=> Fix stale call to move by makeVirtualMove

src/Particle/MCWalkerConfiguration.cpp, src/Particle/MCWalkerConfiguration.h, src/QMCDrivers/RMC/RMC.cpp
Address Sanitizer reports a direct memory leak 
```
246: Direct leak of 34816 byte(s) in 256 object(s) allocated from:
246:     #0 0x4de78d in operator new(unsigned long) (/home/svh/Documents/qmcpack/build/bin/qmcpack_complex+0x4de78d)
246:     #1 0x9b0551 in qmcplusplus::RMC::resetReptiles(int, int, double) /home/svh/Documents/qmcpack/src/QMCDrivers/RMC/RMC.cpp:319:29 …
```
=> Use unique_ptr to fix memory leak in short-bccH_1x1x1_ae-rmc_sdj-1-16

src/QMCWaveFunctions/Fermion/DiracMatrixComputeCUDA.hpp, src/QMCWaveFunctions/Fermion/DiracMatrixComputeOMPTarget.hpp, src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h, src/QMCWaveFunctions/tests/test_DiracMatrixComputeCUDA.cpp, src/QMCWaveFunctions/tests/test_DiracMatrixComputeOMPTarget.cpp, src/Utilities/Resource.h, src/Utilities/tests/test_ResourceCollection.cpp
API updates for DiracDeterminantComputeCUDA and DiracDeterminantComputeOMPTarget. This is to support changes in classes above to move away from the confused 1 walker to 1 batched object and then a batched leader design which is left over from the 1 manager per walker with only the index 0 being an actual manager design of legacy.  SingleWalker API that are not exposed above DiracDeterminantBatched also have a resource argument added to allow passing in thread local resource handles making it possible to use streams to efficiently transfer and launch kernels without OMP target. An dummy resource needs to be passed by OMPtarget code.
The reason these two classes should be 1 per batch is simple. It makes sense for the batched compute objects to manage or acquire the temporary resources used …
=> Changes in advance of design update to MatrixDelayUpdateCUDA and DDB

src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp, src/QMCDrivers/WFOpt/QMCLinearOptimizeBatched.h
The value of`numParams` is obtained from `optTarget->getNumParams()` every time.  And  the value of `N` is derived from that.
These do not need to be member variables.
- No
desktop
=> Remove numParams and N member variables

src/QMCDrivers/WFOpt/QMCCostFunctionBase.cpp
This fixes a memory leak in `short-H4-opt-adaptive-1-16`. This time I used std::unique_ptr with a custom deleter and updated everything in the file following the same pattern.
```
303: Direct leak of 132 byte(s) in 12 object(s) allocated from:
303:     #0 0x4ad8cd in malloc (/home/svh/Documents/qmcpack/build/bin/qmcpack+0x4ad8cd)
303:     #1 0x7f745192e1a4 in …
```
=> Fix memory leak in short-H4-opt-adaptive-1-16

src/QMCDrivers/WFOpt/QMCCostFunctionBase.cpp
This is a continuation of #3429
Range-based for and structured bindings provide cleaner variable names than interators and pairs.
- No
simply a reminder of …
=> QMCCostFunctionBase: Use range-based for and structured bindings to clean up loops

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/QMCDriverNew.cpp, src/QMCDrivers/VMC/VMCBatched.cpp, src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp, src/QMCHamiltonians/Hdispatcher.cpp, src/QMCHamiltonians/Hdispatcher.h, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/NonLocalECPotential.h, src/QMCHamiltonians/OperatorBase.cpp, src/QMCHamiltonians/OperatorBase.h, src/QMCHamiltonians/QMCHamiltonian.cpp, src/QMCHamiltonians/QMCHamiltonian.h
Hamiltonian depends on ParticleSet and TrialWaveFunction. The former is passed in via the arguments but the latter is handled based on the actual Hamiltonian component. It is better to avoid holding any references inside an object and always pass in via argument.
So all the batched APIs have TrialWaveFunction added in this PR.
This is part of #2554
- New feature
- No
epyc-server
=> Hamiltonian batched APIs depend on TWF

src/QMCHamiltonians/OperatorBase.cpp, src/QMCHamiltonians/OperatorBase.h
Start refactoring of OperatorBase turning it into a class
Add encapsulation to existing members
Avoid warning for member assigment ordering
Breaking original PR #3412 intro smaller PRs
Related to #3411 
- No
Ubuntu 20.04 
=> Provide encapsulation to OperatorBase members

src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantFast.cpp
MSD are sensitive to numerics and cased MSD deterministic tests to fail in mixed precision builds.
So change reduction related places to use full precision. It seems help both NVHPC and OneAPI compilers.
- Bugfix
- No
epyc-server
=> Use full precision in MSD reductions to improve accuracy of mixed precision computation

src/QMCHamiltonians/tests/test_ion_derivs.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h, src/QMCWaveFunctions/Fermion/DiracMatrix.h, src/QMCWaveFunctions/Fermion/DiracMatrixComputeCUDA.hpp, src/QMCWaveFunctions/Fermion/DiracMatrixComputeOMPTarget.hpp, src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h, src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h, src/QMCWaveFunctions/Fermion/SlaterDet.cpp, src/QMCWaveFunctions/Fermion/SlaterDet.h, src/QMCWaveFunctions/Jastrow/J2OMPTarget.cpp, src/QMCWaveFunctions/SPOSet.h, src/QMCWaveFunctions/WaveFunctionComponent.h, src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp, src/QMCWaveFunctions/tests/test_DiracMatrixComputeOMPTarget.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction_He.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp, src/type_traits/template_types.hpp
For portable accelerated Determinant inversion implementations APIs should reflect whether an argument is expected to be Dual (i.e. exist on host and accelerator) or not.
Also renaming of types and some member variables for clarity and readability.
Minimum change to existing implementation possible.
API argument changes.
Rename Refactorings
- New feature
- No
Leconte
- Yes Code added or changed in the …
=> Altering DiracDeterminantBatched and friends to take Dual arguments.

src/Particle/SoaDistanceTableAA.h, src/Particle/SoaDistanceTableAAOMPTarget.h, src/Particle/tests/test_distance_table.cpp
#2913 introduced a bug which copies more elements than old_r_ has due to padding.
The issue is similar to #1334 but I'm consider a different solution by removing the padding requirement.
Alignment is always satisfied. Adding padding only removes the remainder loop.
I consider the claimed performance benefit is negligible.
I tried asan but it doesn't report invalid access. So I think somewhere in the memory management adds padding and prevents crash.
- Bugfix
- No
Epyc-server
=> Fix distance table AA out of bound

src/Particle/Lattice/ParticleBConds3DSoa.h, src/Particle/SoaDistanceTableAA.h, src/Particle/SoaDistanceTableAAOMPTarget.h, src/Particle/SoaDistanceTableAB.h, src/Particle/SoaDistanceTableABOMPTarget.h
All distance table internal change.
Update the boundary condition computeDistancesOffload API.
There will be use cases where the stride size of position array is different from the stride size of r/dr.
So it is better to keep them separate.
Also added a minor fix, I don't remember why I asked Cody to add assert(size>1) to AB table in  #3375. it should not.
- Bugfix
- No
epyc-server
=> update distance table internal API

CMakeLists.txt, src/QMCApp/CMakeLists.txt, src/QMCTools/CMakeLists.txt
Prefer per executable control. No change on the user side. No output binary gets moved.
- No
epyc-server
=> Remove CMake global output directories

src/Optimize/NRCOptimization.h, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h
Most of the removed parameters were listed under the "stale parameters" comment.
The `stepsize` variable was used in the same place as  number of similar parameters located in `NRCOptimization` for quartic optimization. so move it there.
This reduces the number of members in the `QMCFixedSampleLinearOptimizerBatched` class.
- No
desktop
- N/A. This PR adds tests to …
=> Remove stale parameters

src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h, src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
deterministic-unit_test_wavefunction_trialwf has been failing in mixed precision builds by Intel compiler since July.
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_wavefunction_trialwf&date=2021-09-24
So increase tolerance from 1e-4 to 1.3e-4 in test_TrialWaveFunction_diamondC_2x1x1.cpp
the rest is non functional change. More REQUIRE -> CHECK.
Also removed unused variable and function to kill compiler warnings in MatrixUpdateOMPTarget.h
- No
bora
=> Fix test intel

src/QMCWaveFunctions/EinsplineSetBuilder.h, src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp, src/QMCWaveFunctions/EinsplineSetBuilderESHDF.fft.cpp, src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp, src/QMCWaveFunctions/EinsplineSpinorSetBuilder.cpp
src/QMCWaveFunctions/EinsplineSetBuilderESHDF.fft.cpp contains added guard.
All the rest is renaming UseRealOrbitals to use_real_splines_ to reduce the confusion from overloaded word "orbitals"
- New feature
- No
epyc-server
=> Add a stopper to catch user requested number of orbitals exceeding what h5 provides

src/QMCHamiltonians/OperatorBase.cpp, src/QMCHamiltonians/OperatorBase.h
Refactor functions in `OperatorBase` to a single translation unit moving all definition to `OperatorBase.cpp` (ccache friendly). 
Make `OperatorBase.h` declaration only with doxygen API docs where appropriate (some missing/TODO).
Mark `const` and `noexcept` functions where appropriate.
Make constructor RAII.
Remove unused private functions.
Remove `inline`.
Component of #3412 
Related to #3411
- Build related changes (remove inline functions)
- No
Ubuntu 20.04. Must pass CI.
- No. …
=> Refactor OperatorBase into a single translation unit

src/Estimators/CMakeLists.txt, src/Estimators/InputSection.cpp, src/Estimators/InputSection.h, src/Estimators/OneBodyDensityMatricesInput.cpp, src/Estimators/OneBodyDensityMatricesInput.h, src/Estimators/tests/CMakeLists.txt, src/Estimators/tests/EstimatorTesting.cpp, src/Estimators/tests/EstimatorTesting.h, src/Estimators/tests/InvalidOneBodyDensityMatricesInput.h, src/Estimators/tests/ValidOneBodyDensityMatricesInput.h, src/Estimators/tests/test_OneBodyDensityMatricesInput.cpp, src/Estimators/tests/test_SpinDensityNew.cpp
Initial Input class for OneBodyDensityMatrices (the port of DensityMatrices1B) to the unified driver setup.
Using InputSection for parsing and simple validation.  Input class has native type and default declaration/definition.
- New feature
- No
Leconte
=> Adding OneBodyDensityMatricesInput and tests

src/QMCTools/CMakeLists.txt, src/QMCTools/tests/CMakeLists.txt, src/Sandbox/CMakeLists.txt
Executables from QMCTools should be pinned at `${qmcpack_BINARY_DIR}/bin`
- Bugfix
- No
epyc-server
=> Fix accidentally moved executables by #3467

nexus/lib/pwscf_analyzer.py, nexus/lib/qmcpack_input.py, nexus/lib/structure.py
More recent python versions now generate syntax warnings (de-linting).  Fix the few that exist so as not to scare off users.
- No
Workstation
=> Nexus: fix syntax warnings

src/Containers/OhmmsSoA/VectorSoaContainer.h, src/QMCWaveFunctions/Jastrow/BsplineFunctor.h, src/QMCWaveFunctions/Jastrow/J2OMPTarget.cpp
517dea7 adds a fix to non-deterministic behavior of offload kernel in mw_updateVGL. The commit log includes full reproducer.
The second commit adds an optimization which reduces re-computation to only on a walker which has been migrated.
5% savings in benchmarks.
- Bugfix
- Other (please describe): Optimization
- No
Epyc-sever, Summit
=> Fix and optimize offload J2

src/QMCTools/convert4qmc.cpp
Fixes #3503. When an hdf5 file is used, the "-orbitals" tag can be omitted
- Bugfix
- Yes
- Yes. This PR is up to date with current …
=> Convert4qmc guess h5 format

src/QMCTools/convert4qmc.cpp
Previous behavior was: If the tag "production" was not requested, the tag -nojastrow was ignored and both set of inputs, with and without Jastrows were generated. 
New behavior is: By default only the inputs with Jastrows are generated. If Tag "-nojastrow" is specified, then no jastrows are created.  …
=> Enforce No Jastrow tag in convert4qmc

nexus/lib/versions.py, nexus/tests/unit/test_structure.py
Fixes #3509
cif2cell depends on pycifrw, so it's necessary to check for both before running tests.
- Bugfix
- No
Local machine
simply a reminder …
=> Check if cif2cell is available before running ntest_nexus_structure

src/QMCDrivers/QMCDriverNew.cpp, src/QMCDrivers/QMCDriverNew.h, src/Utilities/StlPrettyPrint.hpp, src/Utilities/tests/CMakeLists.txt, src/Utilities/tests/for_testing/test_RandomForTest.cpp, src/Utilities/tests/test_StlPrettyPrint.cpp
Long vectors are lengthy. walkers_per_crowd has num_crowd elements. walkers_per_rank has num_rank elements.
num_crowd can be hundreds in CPU runs and num_ranks can be tens of thousands.
Usually these vectors has very limited distinct values and are better printed in collapsed style.
[3, 3, 2, 2] is printed as [3(x2), 2(x2)]
- New feature
- No
epyc-server
=> Collapsed style in StlPrettyPrint.

src/QMCHamiltonians/PairCorrEstimator.cpp
I saw this use of pi rather than the variable `M_PI` while reading the pair correlation estimator.
- No
Ryzen 5900X / Linux box
=> Remove an explicit use of pi

tests/test_automation/nightly_test_scripts/nightly_olcf_spock.sh
Looks like nightly runs on spock might need more time, so recursion can kick in. 
Changes are part of initial observations on spock and balancing core-hour usage.
Note: need to be in `develop` branch before retesting on spock.
Related to #3402 for adding AMD GPU testing
- Testing changes (e.g. new unit/integration/performance tests) nightly
- No
`spock.olcf.ornl.gov`
- No. …
=> Bump nightly wall-clock time request on spock

CMake/ClangCompilers.cmake, CMakeLists.txt, src/QMCWaveFunctions/Jastrow/BsplineFunctor.h, src/config.h.cmake.in
Need to workaround the last ROCm/AOMP bug. https://github.com/ROCm-Developer-Tools/aomp/issues/255
Introduce `QMC_OFFLOAD_ROCM_WORKAROUND_BRANCH_IN_PARALLEL` option.
This workaround hurt performance but make tests pass instead of crashing.
I would like to set `QMC_OFFLOAD_ROCM_WORKAROUND_BRANCH_IN_PARALLEL` to OFF once upstream LLVM can robustly work.
I added a bit automation which I'm comfortable with both 
`QMC_OFFLOAD_MEM_ASSOCIATED`
and
`QMC_OFFLOAD_ROCM_WORKAROUND_BRANCH_IN_PARALLEL`
being set automatically for ROCM/AOMP/upstream LLVM compilers when offload to AMD GPU is enabled.
Also with clang, if `QMC_CUDA2HIP=ON` and `ENABLE_OFFLOAD=ON`, there is no need to set the offload target to amdgcn-amd-amdhsa.
So `-DENABLE_OFFLOAD=ON -DENABLE_CUDA=ON -DQMC_CUDA2HIP=ON` adds …
=> Add ROCm compiler bug workaround and a bit more automation in CMake

CMakeLists.txt
When incorrect compile options are passed through. FindLAPACK fails simply because it is the first library which tries to invoke the compiler. So it is better to have a check before any library searching.
- New feature
- No
epyc-server
=> Test compile main after compile option setting.

nexus/tests/unit/test_simulation_module.py
Addresses #3120.  Nexus tests no longer strictly require mpirun.  If mpirun is detected in the path, it is executed in the tests ("mpirun -np 1 echo run").  Otherwise a serial test is performed ("echo run").
- Bugfix
- No
Laptop
=> Nexus: no longer require mpirun for test passage

CMake/ClangCompilers.cmake
Add a warning suppression for LLVM 14 changes. This flag will be added automatic.
- No
epyc-server
=> More friendly to upcoming changes LLVM 14.

src/Containers/OhmmsPETE/OhmmsVector.h, src/Containers/OhmmsPETE/TinyVector.h, src/Containers/OhmmsPETE/tests/test_vector.cpp, src/Estimators/tests/test_OneBodyDensityMatrices.cpp, src/Particle/ParticleBase/ParticleAttrib.h, src/Utilities/for_testing/NativeInitializerPrint.hpp, src/type_traits/template_types.hpp, src/type_traits/tests/test_template_types.cpp
Add initializer list support for ParticleAttrib so ParticleSet R can be easily initialized using the native C++ initializer list format. This requires small changes in OhmmsVector and TinyVector. I have added unit tests to cover the changes in OhmmsVector.  I have not added unit tests to TinyVector since I just added the default move constructor and move assignment to the class.
As found by @jtkrogel in #3475 There is a surprising issue with writing unit tests.
We have a global Random object to support legacy code that wants to just grab a nondeterministic random number this is bad practice for many reasons but in tests that rely on boot strapping objects through the legacy put methods i.e. with MinimalWhateverPools or larger mocking of the application environment it means you will get …
=> Support initializer list for ParticleAttrib for tests with PSet

src/QMCTools/ppconvert/src/CubicSpline.h
Proposed Werror check with RelWithDebInfo in #3596 fails
This PR fixes that error due to an uninitialized member
Able to reproduce with gcc-10, not with gcc-9
- Bugfix
- No
Ubuntu 20.04 + gcc-10, must pass CI check with gcc-11
=> Fix Werror uninitialized member error

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step.sh
Add CI for deterministic tests running on self-hosted AMD GPU hardware
Follows self-hosted workflow
Avoid cuda and cuda2hip conflict in workflow
Must be merged on develop to test CI jobs
TODO: add docs to trigger CI on a follow-up PR
Related to #3402 
- Testing changes (e.g. new unit/integration/performance tests) new CI
- No
nitrogen, must be merged to test CI
- No. This PR adds tests to cover any new code, or to catch …
=> Add GitHub Actions CI jobs on AMD hardware

src/Estimators/tests/test_MomentumDistribution.cpp
Current CI is failing on nitrogen for complex and mixed precision tests
This PR just bumps epsilon in floating point comparison
Tests were recently added in #3592 
Failure seen in #3599 
Fixes #3601 
- Bugfix
- No
nitrogen
=> Increase epsilon for complex and mixed precision test on ROCm

docs/github_actions.rst
Initial documentation on GitHub Actions CI using AMD hardware
Use this PR to trigger CI on AMD hardware
Related to #3582 and #3402 
- No
Newly CI on AMD self-hosted hardware must pass
=> Initial CI documentation on AMD Hardware

src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp
When 'nonlocalpp' is specified in the optimization section of the input file, but the Hamiltonian doesn't use pseudopotentials, `nlpp` will be null and the access will cause a segfault.
Ignoring the value in the input file (by using a null pointer test) is the same behavior as the non-batched optimizer.
The input files produced by Nexus enable `nonlocalpp` by default.
Also enable output earlier so messages about the presence or absence of the non-local Hamiltonian elements get printed.
- Bugfix
- No
desktop …
=> Fix seg fault in batched optimizer

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/DMC/DMCBatched.h, src/QMCDrivers/QMCDriverNew.h, src/QMCDrivers/SFNBranch.h, src/QMCDrivers/VMC/VMCBatched.cpp, src/QMCDrivers/VMC/VMCBatched.h
Since ParticleSet doesn't need to support the legacy t-move code single walker API calls can rely on multiwalker resources. That means estimators must be in a scope where the crowd walker element reference vectors leaders hold resources.
- Bugfix
- No
Leconte
=> If ENABLE_OFFLOAD=1 particle set move requires mw resources

tests/test_automation/nightly_test_scripts/nightly_olcf_spock.sh
Just update nightly dependencies on spock after recent OLCF packages updates on the system.
Current nightly can't find `openblas` and `cray-hdf5` modules
- Testing changes (e.g. new unit/integration/performance tests) nightly
- No
spock, must pass nightly
=> Update spock dependencies

.github/workflows/ci-github-actions.yaml
Current coverage reports on CI from Gcov are not uploaded to Codecov
This PR patches the if condition to point at the correct job names
Bug introduced by #3598
- Bugfix
- No
NA
=> Fix missing Codecov reports

src/Estimators/EstimatorManagerCrowd.cpp, src/Estimators/EstimatorManagerNew.cpp, src/Estimators/MomentumDistribution.cpp, src/Estimators/MomentumDistribution.h, src/Estimators/OneBodyDensityMatrices.cpp, src/Estimators/OneBodyDensityMatrices.h, src/Estimators/OperatorEstBase.cpp, src/Estimators/OperatorEstBase.h, src/Estimators/SpinDensityNew.cpp, src/Estimators/SpinDensityNew.h, src/Estimators/tests/EstimatorManagerNewTest.cpp, src/Estimators/tests/EstimatorManagerNewTest.h, src/Estimators/tests/EstimatorTesting.cpp, src/Estimators/tests/EstimatorTesting.h, src/Estimators/tests/FakeOperatorEstimator.cpp, src/Estimators/tests/FakeOperatorEstimator.h, src/Estimators/tests/test_MomentumDistribution.cpp, src/Estimators/tests/test_OneBodyDensityMatrices.cpp, src/Estimators/tests/test_SpinDensityNew.cpp, src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/QMCDriverNew.h, src/QMCDrivers/VMC/VMCBatched.cpp
In preparation for integration of OneBodyDensityMatrices this PR cleans up complication of OperatorEstBase derived Estimators copy constructors.  All the non copying logic is moved to the clearly named spawnCrowdClone method. The estimator data is no longer a unique_ptr to vector created on the heap but just a vector. Minor renaming is included.
- No
Leconte
=> Refactor memory locality handling out of estimators copy constructors

src/Estimators/tests/test_OneBodyDensityMatrices.cpp
Closes #3621
Reduce precision in mixed precision builds
- Bugfix
- No
Only in CI, but the precision problems have not occurred there. We will need to adjust the tolerances in later PRs if the nightlies do not pass.
=> Reduce OneBodyDM Test Precision

examples/molecules/He/CMakeLists.txt
Fix a statistical error seen a macOS build with macports llvm-13 and Apple accelerate framework:
```
Start 1271: example_He_example_wf-1-1-totenergy
1271/1273 Test #1271: example_He_example_wf-1-1-totenergy ...............................................................***Failed    0.05 sec
Tests for series 10
Testing quantity: LocalEnergy
reference mean value     :  -2.88000000
reference error bar      :   0.00400000
computed  mean value     :  -2.89218066
computed  error bar      :   0.00388356
pass tolerance           :   0.01200000  (  3.00000000 sigma)
deviation from reference :  -0.01218066  ( -3.04516603 sigma)
error bar of deviation   :   0.00557513
significance probability :   0.99767434  (gaussian statistics)
status of this test      :   fail
Test status: fail
```
- Testing …
=> Increase error bar on He example total energy test

src/QMCWaveFunctions/VariableSet.cpp, src/QMCWaveFunctions/VariableSet.h, src/QMCWaveFunctions/tests/test_variable_set.cpp
This stores the parameter names as one array and the parameter values as another array.
Upon loading, only values that already exist in the VariableSet get set a new value from the file.
This is the save/load functionality from the prototype in #3634.
- New feature
- No
desktop
=> Save and restore variational parameters in HDF

.github/workflows/ci-github-actions.yaml
Bump codecov-action to v2
Upload GCov xml coverage reports to [codecov/QMCPACK/qmcpack](https://app.codecov.io/gh/QMCPACK/qmcpack) via GitHub Actions
v1 to be [deprecated](https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1)
- Other (please describe): codecov uploader
- No
None, must pass CI and upload coverage reports
=> Bump codecov-action to v2

tests/estimator/latdev/latdev_check.py, tests/estimator/sofk/check_collectables_h5dat.py, tests/estimator/sofk/check_properties_h5dat.py
The ".value" method to an h5py Datatset was removed in version 3.
Use a different technique to convert to a numpy array.
- Bugfix
- No
=> Fix the latdev estimator failure

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step.sh
Add Intel19 AFQMC CUDA configuration for CI testing
Use self-hosted runner
Related to #3639 
- Testing changes (e.g. new unit/integration/performance tests) CI
- No
=> Add Intel19 AFQMC CUDA test to CI

src/Numerics/HDFNumericAttrib.h
Fixes #3648 by removing unused code associated with using hsize_t.
- Bugfix
- 
- No
Summit
=> removed unused struct HDFAttribIO<hsize_t> : public HDFAttribIOBase

.github/workflows/ci-github-actions-self-hosted.yaml
Remove failing CI job on sulfur preventing PRs to pass
Opened #3654 for tracking this bug
- Testing changes (e.g. new unit/integration/performance tests) CI
- No
sulfur, must pass CI 
- No. This PR is up to date with current the current state of 'develop'
=> Remove Intel19 complex CI failed tests

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step.sh
Add GCC8-MKL-NoMPI configuration to CI
Using sulfur as GItHub Actions self-hosted runner
Related to #3639 to replace ANL runners
- No
=> Add GCC8-MKL-NoMPI configuration to CI

src/Numerics/Quadrature.h
NVHPC compiler engineers identified this issue.
We define `const RealType* restrict Ylm_v = Ylm[0];` but then directly modified it via `Ylm.evaluateV(grid[k][0], grid[k][1], grid[k][2]);`
Now we just define `Ylm_v` after `Ylm.evaluateV` and removed restrict which doesn't really have benefit in this case.
- Bugfix
- No
epyc-server
=> Fix restrict type qualifier misuse.

CMake/test_labels.cmake, tests/scripts/test_labels.py
Noticed that the python script test_labels.py is being rerun each time cmake is run. This caches the result in a unique variable
This is part of #2227. I hope we can further speed up generation of TEST_LABELS.
- No
_Update the following with a yes where …
=> Cache results from slow python script test_labels.py

.github/workflows/ci-github-actions-self-hosted.yaml
Current jobs in sulfur GPU are skipped due to attempt in PR #3670 
Try Actions [jobs.\<job-name\>.needs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idneeds) to enable hierarchy in 1) CPU and 2) GPU tests
- Bugfix
- Yes
must pass CI
=> Use GitHub Actions jobs.<job-id>.needs API

src/QMCTools/QMCFiniteSize/QMCFiniteSize.cpp, src/QMCTools/QMCFiniteSize/QMCFiniteSize.h
This PR removes the dependence of qmcfinitesize on the non-uniform bsplines in favor of uniform bsplines. 
I recently noticed a bug on my mac with gnu compilers for the qmcfinitesize tool where I was getting unreasonably large error bars. I ended up removing the random resampling techniques and worked with just fixed S(k) data (which should always give the same FS correction since the input data is fixed and there is no resampling), and I would see that every few executions of the code I would get erroneous finite size corrections. I ultimately tracked this down specifically to the use of NUBspline_1d_d for the integral …
=> Update qmcfinitesize to use UBsplines instead of NUBsplines

src/QMCDrivers/BranchIO.cpp, src/io/hdf/HDFVersion.h, src/io/hdf/hdf_archive.h, src/io/hdf/hdf_dataproxy.h, src/io/hdf/hdf_dataspace.h, src/io/hdf/hdf_double_hyperslab.h, src/io/hdf/hdf_hyperslab.h, src/io/hdf/hdf_multi.h, src/io/hdf/hdf_pete.h, src/io/hdf/hdf_stl.h, src/io/hdf/hdf_wrapper_functions.h, src/io/hdf/tests/test_hdf_archive.cpp, src/io/hdf/tests/test_hdf_hyperslab.cpp, src/io/hdf/tests/test_hdf_reshape.cpp, src/spline/einspline_util.hpp
In the hdf_archive abstraction, there was an issue that writing data from a const object caused compilation failure.
```
hdf_archive h5("abc.h5");
const int a = 0;
h5.write(a, "data"); // compilation failure.
```
It was causing by the design of h5data_proxy class which keeps a reference of the data object.
By removing this reference and passing the object via arguments, const data object can be written properly.
This fix is restrict to the internal detail of hdf_archive and there is no change to the library interface.
- New feature
- No
epyc-server
- Yes. Code added or changed in the PR has been …
=> Make hdf_archive support writting data from const object.

nexus/lib/qmcpack.py
This PR provides a fix to an off-by-one error when checking that the einspline files contain the correct excitation.
- Bugfix
- No. All `nxs-test` tests pass
ALCF Theta
=> Nexus: Small fix to excitation checks

nexus/examples/qmcpack/rsqmc_misc/diamond_lowdin/lowdin.py, nexus/examples/qmcpack/rsqmc_misc/diamond_lowdin/run_lowdin.sh
Adding support file and comments to the Nexus Lowdin example in nexus (`nexus/examples/qmcpack/rsqmc_misc/diamond_lowdin`)
The support file is a short bash script that shows how to run `lowdin.py` for the different diamond examples. The comment (added to `lowdin.py`) explains what to do if `atomic_proj.xml` is not generated or does not contain the OVERLAPS element.
- Other (please describe): support file and comments added to Nexus Lowdin example
- No
Laptop
=> Nexus: Support file and comment for Lowdin example

src/QMCTools/ppconvert/src/common/Blitz.h, src/QMCWaveFunctions/ElectronGas/HEGGrid.h
Address libc++ issues detected due to missing header and type conversion (hack with `reinterpret_cast`)
Attempts to fix #3698 (note that we don't have FreeBSD CI)
- Bugfix
- Yes
Ubuntu 20.04 with clang 10 and libc++ without MPI.
Must pass CI for other configurations.
- No. Code added or changed in the PR has been clang-formatted (ppconvert)
=> Address libc++ related bugs with no MPI compilation

config/docker/dependencies/ubuntu/openmpi/Dockerfile
Update the Dockerfile of the latest Ubuntu 20 docker container used in CI
Add `numdiff` for added `ppconvert` test from #3717
Add Python `cif2cell` from #3509
Remove deprecated MAINTAINER tag
Note that container is already hosted in [DockerHub](https://hub.docker.com/layers/141931100/williamfgc/qmcpack-ci/ubuntu20-openmpi/images/sha256-efb1446b9829d85d53d5886868bd9f87579826331eca6a98ad1b579713d15b32?context=repo)
- Bugfix
- Testing changes (e.g. new unit/integration/performance tests) CI container 
- No
Docker local with a Ubuntu 20.04 host
- No. Documentation has been …
=> Update CI docker container

.github/workflows/ci-github-actions.yaml, tests/test_automation/github-actions/ci/run_step.sh
Add a debug mode configuration job to CI 
Expect to capture asserts
Need to observe runtimes on GitHub Actions CI
Related to #3691 and #3696 
- Testing changes (e.g. new unit/integration/performance tests) CI
- No
Must pass GitHub Actions CI
=> Add debug mode configuration to CI

CMakeLists.txt
fixes #3720
Prevent path being translated at CMake step.
The desired path will show up in `build/cmake_install.cmake` and become effective at make install.
- Bugfix
- No
epyc-server
=> Fix nexus install path.

src/QMCWaveFunctions/SpinorSet.cpp, src/QMCWaveFunctions/SpinorSet.h, src/QMCWaveFunctions/tests/test_einset_spinor.cpp
This is the first mw_ function in SpinorSet. I wanted to implement this first before following up with the rest of the functions to keep it small and easier to review. 
This implements mw_evaluate_notranspose. Since a SpinorSet has unique_ptr<SPOSet> for both up and down SPOSets, in order to utilize the batched evaluations for the individual spin components I had to form intermediate reference vectors. After these are formed, I simply can call mw_evaluate_notranspose for each of the spin components. Afterwards, I finish up by reconstructing the spinors from the spin components. 
Unit test is updated, I simply add a …
=> batched evaluation of evaluate_notranspose for SpinorSet

src/Particle/ParticleSet.cpp
fixes a small bug in particle set for mw_makeMove. active_spin_val_ needs to be set to the current spin, just like how it is done for the single walker API.  noticed while making a unit test for a coming PR. 
- Bugfix
- No
macOSX
- No. This PR adds …
=> set active spin val in mw_makeMove

nexus/lib/qmcpack.py
For the excitation checks in Nexus, add a bit of hardening such that the bahavior is the same regardless of whether the orbital data structure is a list or ndarray 
- Code hardening
- No. All nxs-test tests pass
Laptop, linux
=> Nexus: Harden Nexus excitation checks

CMakeLists.txt, tests/CMakeLists.txt
CMake code setting `HAVE_PYSCF` duplicates a check already done by `check_python_reqs`, but doesn't cache the result.
time cmake -G Ninja -DQMC_MPI=OFF ../
before:
(first run)
real	0m25.307s
user	0m32.837s
sys	0m30.663s
(second run)
real	0m5.391s
user	0m6.922s
sys	0m7.153s
after:
(first run)
real	0m24.239s
user	0m32.839s
sys	0m30.728s
(second run)
real	0m4.410s
user …
=> Use standard check for python library instead of HAVE_PYSCF

src/QMCWaveFunctions/EinsplineSetBuilder.h, src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp, src/QMCWaveFunctions/EinsplineSetBuilderESHDF.fft.cpp, src/QMCWaveFunctions/EinsplineSetBuilderOld.cpp, src/QMCWaveFunctions/EinsplineSetBuilderReadBands_ESHDF.cpp, src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp
Removes the developer-focused logging from EinsplineSet. This wrote TOKEN, a comment, and source code file info on the standard QMCPACK output. The output already includes sufficient output and likely errors are already appropriately trapped.
(This remake of the PR correctly has the branch in my fork)
- No
Sulfur, gcc+mpi+mkl
=> Remove token logging from EinsplineSet

tests/solids/diamondC_1x1x1_pp/CMakeLists.txt, tests/solids/diamondC_1x1x1_pp/qmc_short_optbatch.in.xml
Add a linear_batch short test mirroring the non-batched driver test. Everything is good so far.
- No
epyc-server
=> Add diamondC_1x1x1_pp/qmc_short_optbatch test

CMake/ClangCompilers.cmake, config/build_olcf_summit_Clang.sh, src/Particle/SoaDistanceTableAA.h, src/Particle/SoaDistanceTableAAOMPTarget.h, src/Particle/SoaDistanceTableAB.h, src/Particle/SoaDistanceTableABOMPTarget.h
The source code change is to make timer names more brief.
Update Summit recipe with up-to-date Clang and CUDA 11. Previously older versions of Clang may hang offload code at execution when CUDA 11 was used. This issue has been addressed in upstream and next clang 14 release (Feb) will be problem free.
Remove CMake workaround as the default installation 3.21.3 on Summit doesn't need it.
- No
Summit
=> Update timer and Summit recipe.

.github/workflows/ci-github-actions.yaml, tests/test_automation/github-actions/ci/run_step.sh
Adds small footprint sandbox configuration `-DQMC_BUILD_SANDBOX_ONLY=ON` to GitHub Actions CI
Fixes #3743 
- Testing changes (e.g. new unit/integration/performance tests) CI
- No
=> Add SANDBOX_ONLY configuration to GitHub Actions CI

config/build_nersc_cori.sh, docs/installation.rst
The version of cmake (3.14.4) in `config/build_nersc_cori.sh` is not sufficient for QMCPACK 3.12.0. This PR resolves this by loading an updated cmake version (3.21.3)
- Bugfix
- No. Verified that the build executes correctly on NERSC Cori
NERSC Cori
=> Update cmake in NERSC Cori build script

config/build_ornl_cades.sh
The version of cmake (3.12.0) in `config/build_ornl_cades.sh` is not sufficient for QMCPACK 3.12.0. This PR resolves this by loading an updated cmake version (3.18.4)
- Bugfix
- No. Tested on ORNL CADES
ORNL CADES
=> Update cmake in ORNL CADES build script

.github/workflows/ci-github-actions-self-hosted-nitrogen.yaml, .github/workflows/ci-github-actions-self-hosted-sulfur.yaml
Refactor self-hosted CI runner jobs on sulfur and nitrogen
Allow for simulataneous runs
Move CUDA jobs from sulfur to nitrogen
- No
Must pass CI
=> Reorganize self-hosted runners

tests/test_automation/github-actions/ci/run_step.sh
Set CMake `CUDACXX` environment variable, docs [here](https://cmake.org/cmake/help/latest/envvar/CUDACXX.html) to standard nvcc location in CI runners. 
- Bugfix for nitrogen-cuda CI
- No
Must pass CI on nitrogen-cuda
=> Set CMake CUDACXX in CUDA CI runners

tests/test_automation/github-actions/ci/run_step.sh
Enable ucx MPI p2p management layer for nitrogen, similar to sulfur
Converter tests are failing.
Similar to #3659 
- Bugfix
- Yes
sulfur, must work on nitrogen
=> Set ucx layer for ornl runners

src/Particle/DistanceTable.h, src/Particle/SoaDistanceTableAB.h, src/Particle/SoaDistanceTableABOMPTarget.h, src/QMCHamiltonians/NonLocalECPComponent.cpp, src/QMCHamiltonians/NonLocalECPComponent.h, src/QMCHamiltonians/NonLocalECPotential.deriv.cpp, src/QMCHamiltonians/tests/test_ecp.cpp, src/QMCWaveFunctions/Jastrow/BsplineFunctor.h, src/QMCWaveFunctions/Jastrow/FakeFunctor.h, src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.h, src/QMCWaveFunctions/Jastrow/J1Spin.h, src/QMCWaveFunctions/Jastrow/J2OMPTarget.cpp, src/QMCWaveFunctions/Jastrow/J2OMPTarget.h, src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.cpp, src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h, src/QMCWaveFunctions/Jastrow/PadeFunctors.h, src/QMCWaveFunctions/Jastrow/ShortRangeCuspFunctor.h, src/QMCWaveFunctions/Jastrow/UserFunctor.h, src/QMCWaveFunctions/OptimizableFunctorBase.h, src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/TrialWaveFunction.h, src/QMCWaveFunctions/WaveFunctionComponent.cpp, src/QMCWaveFunctions/WaveFunctionComponent.h
Implement J1 and J2. JeeI will be next.
Remove unnecessary get_neighbours in DT.
Running on diamondC_1x1x1
"use_nonlocalpp_deriv" is cheap to run now.
From "gradient_test"
```
Param_Name  Value    Numeric            Analytic       Percent
eC_0 -2.0322e-01  5.8930e-03  5.8919e-03  1.9518e-02
eC_1 -1.6256e-01  -1.5658e-03  -1.5656e-03  1.6832e-02
...
eC_6 -4.4453e-02  1.1006e-03  1.0739e-03  2.4258e+00
eC_7 -2.1351e-02  -1.5482e-01  -1.5449e-01  2.1335e-01
uu_0 2.7977e-01  -3.6705e-05  -1.0604e-04  -1.8889e+02
uu_1 2.1726e-01  7.1735e-03  6.6674e-03  7.0540e+00
...
uu_6 2.9160e-02  -3.9518e-02  -3.5624e-02  9.8537e+00
uu_7 1.2240e-02  1.6430e-01  1.6897e-01  -2.8403e+00
...
ud_6 4.1459e-02  -5.6726e-02  -5.5265e-02  2.5760e+00
ud_7 1.6906e-02  5.9920e-02  5.5935e-02  6.6501e+00
Execution …
```
=> Implement evaluateDerivRatios in J1 and J2

tests/test_automation/github-actions/ci/run_step.sh
Add the -j option to ctest in CI for GitHub Actions (2 for Linux and 3 for macOS) and ornl-hosted (16) runners.
This option can be tested on this PR (no need to merge first).
- No
Must pass CI
=> Add ctest -j parallel jobs option to all CI

src/QMCHamiltonians/CoulombPBCAA.cpp, src/QMCHamiltonians/tests/test_coulomb_pbcAA.cpp
Add the missing background term (`vs_k0`) into the Madelung constant.
This makes it correct for simple cubic and body center cubic crystals as shown by the unit tests.
- Bugfix
- No
workstation
- No. …
=> fix Madelung constant in CoulombPBCAA

src/Particle/ParticleSet.cpp, src/Particle/ParticleSet.h, src/QMCWaveFunctions/tests/test_polynomial_eeI_jastrow.cpp, src/QMCWaveFunctions/tests/test_rpa_jastrow.cpp, src/Sandbox/diff_distancetables.cpp, src/Sandbox/restart.cpp
This function is neither needed nor safe-to-use (breaks encapsulation).
Thus removal is the best option to avoid confusion like #3808
- Other (please describe): Cleaning
- No
epyc-server
=> Remove ParticleSet::setCoordinates(R)

docs/developing.rst
Emphasize the need to call `ParticleSet::update()` in the developer manual.
The coexistence of `R` and `RSoA` did not sink in for me until now.
I spent many hours trying to figure out why my unit test distance tables are garbage...
Just want to add some emphasis in the manual to help the next unfortunate soul.
- No
workstation
- No. This PR adds tests to cover any new code, or to catch a bug that …
=> emphasize update() in developer manual

CMake/ClangCompilers.cmake, CMake/GNUCompilers.cmake
Although GCC still doesn't fully work, some compiler options need update for GCC 12.
GCC 12 is not released, so it is not a hard requirement. Only WARNING is issued.
Also add a warning that GCC OpenMP offload is not ready for users.
- No
epyc-server
=> Update GCC OpenMP offload settings.

CMake/GNUCompilers.cmake
When GCC is built with OpenMP offload support. GCC turns on offload by default. This is undesired.
So turn off offload explicitly. Tested that `-foffload=disable` exists in GCC 7.0 (minimal requirement), 8,9,10,11.
- No
epyc-server
=> Disable offload explicitly in GCC

src/Particle/ParticleIO/XMLParticleIO.cpp, src/Particle/ParticleSet.h, src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.cpp, src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.h
Fixes #3820
- Bugfix
- No
epyc-server
=> Fix LCAO AO MO mismatch due to particle reordering.

tests/test_automation/github-actions/ci/run_step.sh
Add `QMC_DATA` directory to nitrogen CI tests, (QMC_DATA is already present).
Fixes #3819 
- Yes
must pass nitrogen CI
=> Add QMC_DATA to nitrogen CI

src/Particle/LongRange/StructFact.cpp, src/Particle/LongRange/StructFact.h, src/Particle/LongRange/tests/test_StructFact.cpp, src/Particle/ParticleSet.BC.cpp
Bug: the constructor takes first the number of particles and second number of species. But #3359 makes calls with these two parameters swapped. Since the number of particles is only used by StorePerParticle is turned on and turnOnStorePerParticle  actually ignores the internal num_ptlcs. Runs are just fine fine. When StorePerParticle is false, only num_species is used, since the number of particles is always larger than species, it only increases memory usage without any run failure.
When I I worked on moving StructFact::resize, one of the unit test fails and this bug got surfaced. Since I moved the resize anyway, I just get rid of StructFact internal num_ptlcs and num_species fully. Since the resize is moved into the evaluation function, the number K is up-to-date and thus the …
=> Simplify StructFact resize logic and fix a bug

src/Particle/LongRange/StructFact.cpp, src/Particle/ParticleSet.cpp, src/Particle/SoaDistanceTableAAOMPTarget.h, src/Particle/SoaDistanceTableABOMPTarget.h, src/Platforms/OMPTarget/OMPTargetMath.hpp, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp
At a point NVHPC was having issue with std::min being used inside offload region. Let's just use a simple omptarget::min and move on.
- No
epyc-server
=> Replace std::min inside target region

src/Particle/RealSpacePositionsOMPTarget.h
This was discovered when offloading to AMD GPUs with LLVM/AOMP. libomptarget tries to make a data transfer of size 0. https://github.com/llvm/llvm-project/issues/53803
- Workaround
- No
epyc-server
=> Early return to avoid undefined behavior.

src/Numerics/OneDimCubicSplineLinearGrid.h, src/Numerics/tests/CMakeLists.txt, src/Numerics/tests/test_OneDimCubicSplineLinearGrid.cpp, src/QMCHamiltonians/CoulombPBCAA.cpp, src/QMCHamiltonians/CoulombPBCAA.h
To be used in short range Coulomb PBC AA.
- New feature
- No
epyc-server
- Ye. This PR adds tests to cover any new code, or to catch a bug that is being fixed
=> Add one dim cubic spline with linear grid

src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.h, src/QMCWaveFunctions/SPOSetBuilder.cpp, src/QMCWaveFunctions/SPOSetBuilder.h, src/QMCWaveFunctions/SPOSetBuilderFactory.cpp, src/QMCWaveFunctions/SPOSetBuilderFactory.h, src/QMCWaveFunctions/SPOSetScanner.h, src/QMCWaveFunctions/tests/test_MO.cpp, src/QMCWaveFunctions/tests/test_MO_spinor.cpp, src/QMCWaveFunctions/tests/test_cartesian_ao.cpp, src/QMCWaveFunctions/tests/test_einset_spinor.cpp, src/QMCWaveFunctions/tests/test_pyscf_complex_MO.cpp, src/QMCWaveFunctions/tests/test_soa_cusp_corr.cpp
SPOSetBuilderFactory keeps an array of SPOSetBuilder pointers and each SPOSetBuilder contains a map of SPOSet. To make all the SPOSets available for lookup later, SPOSetBuilderFactory is persist and thus all the builders are persistent thought out the the whole run. This PR makes SPOSetBuilder short-lived. Once all the SPOSets from a collection are processed by a SPOSetBuilder, there is no need to keep the builder. Thus the map of SPOSets are directly kept in SPOSetBuilderFactory class.
- No
epyc-server
=> Replace vector of SPOSetBuilder with map of SPOSet

CMake/ClangCompilers.cmake, config/docker/dependencies/ubuntu22/Dockerfile
This PR is part of the efforts to enable clang+gcov for offload cases
- Fix typo in clang gcov configuration
- Add Dockerfile to test gcov with latest compilers: gcc-12 and clang-13 supporting offload. Container hosted in [Dockerhub](https://hub.docker.com/layers/193595951/williamfgc/qmcpack-ci/ubuntu22-gcc12-clang13/images/sha256-983b5ee621349102ad7920dc7ad6bc685d4a117965c92c58ff01a5d24715a626?context=repo)
Related to #3834 
- Bugfix
- No
Ubuntu 20.04
=> Enable clang gcov

src/Particle/ParticleSetPool.h, src/QMCHamiltonians/EnergyDensityEstimator.h, src/QMCHamiltonians/HamiltonianFactory.h, src/QMCHamiltonians/OrbitalImages.h, src/QMCWaveFunctions/EinsplineSetBuilder.h, src/QMCWaveFunctions/EinsplineSpinorSetBuilder.h, src/QMCWaveFunctions/Fermion/BackflowBuilder.h, src/QMCWaveFunctions/Fermion/BackflowTransformation.h, src/QMCWaveFunctions/SPOSetBuilderFactory.h, src/QMCWaveFunctions/SPOSetScanner.h, src/QMCWaveFunctions/WaveFunctionComponentBuilder.h, src/QMCWaveFunctions/WaveFunctionFactory.h, src/QMCWaveFunctions/tests/test_lattice_gaussian.cpp
Pointers should be const once being added into the pool
- No
epyc-server
=> More const in ParticleSetPool.

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.h, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
This reorders the unique determinants of each particle type by excitation level.
It also identifies the reference SlaterDeterminant as the one with the largest coefficient (in magnitude) (was previously always set to the first det in the list).
For each particle group, the reference DiracDeterminant is the one that appears in the reference SlaterDeterminant.
There is also a new data member of MultiDiracDeterminant that holds the number of unique dets at each excitation level
- New feature
- No
unix workstation (gcc 10.3.0; amd zen)
- No. Documentation has been added (if …
=> Reorder unique determinants by excitation level

src/io/hdf/hdf_archive.cpp
Update type for 1.12.0 API usage. Breaks build on some systems (discovered with macports), where the compiler will not convert between the old and new info types.
- Bugfix
- No
mac laptop, sulfur (full deterministic tests)
=> Fix h5o_info_t usage

src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp, src/QMCDrivers/WFOpt/QMCCostFunctionBatched.h, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h, src/QMCDrivers/tests/test_QMCCostFunctionBatched.cpp
Addresses #3849 
The code now uses walker_per_crowd computed the same way as VMC.
Previously the batched cost function code expected every crowd would have the same number walkers. Most of the changes come from updating the code to use different number of walkers per crowd.
- Bugfix
- No
laptop, Summit
- No. Documentation has been …
=> Split walkers among crowds in optimizer to match VMC usage

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/VMC/VMCBatched.cpp, src/QMCWaveFunctions/TWFGrads.cpp, src/QMCWaveFunctions/TWFGrads.hpp, src/QMCWaveFunctions/TWFdispatcher.cpp, src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/TrialWaveFunction.h, src/QMCWaveFunctions/WaveFunctionComponent.cpp, src/QMCWaveFunctions/WaveFunctionComponent.h, src/QMCWaveFunctions/tests/test_TWFGrads.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp, src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp
This PR moves the CoordsType abstraction down into WFC. Currently, TrialWaveFunction had mw_evalGrad,  mw_evalGradWithSpin and a mw_evalGrad<CT> to decide which version to call. Same for mw_calcRatioGrad. 
This simplifies the TrialWaveFunction API to only have the one implementation and moves the selection down into WaveFunctionComponent. WFC now has mw_evalGrad, mw_evalGradWithSpin, and a mw_evalGrad<CT> (same for mw_calcRatioGrad) to choose which one to call based on CT
Eventually, we will want to only have mw_evalGrad<CT> in WaveFunctionComponent, but trying to keep things small and manageable for easier review. …
=> Add CoordsType templates to WaveFunctionComponents

src/Particle/DistanceTable.h, src/Particle/SoaDistanceTableAAOMPTarget.h, src/QMCDrivers/QMCDriverFactory.cpp, src/QMCHamiltonians/CoulombPBCAA.cpp
#3882 mistreated CSVMC. Fixed it.
I have a local renaming commit. mw_evaluate_range -> mw_evalDistsInRange. Would like to skip a separate PR.
- Bugfix
- No
epyc-server
=> Restore CSVMC access

src/QMCWaveFunctions/WaveFunctionFactory.cpp
Fix a unused variable warning on "success"
Fix a copy elision warning due to the use of std::move.
- Bugfix
- No
epyc-server
=> Fix a few clang warning.

src/Particle/CMakeLists.txt, src/Particle/DynamicCoordinatesBuilder.cpp, src/Particle/ParticleSetPool.cpp, src/Particle/createDistanceTable.h, src/Particle/tests/test_distance_table.cpp, src/Platforms/CMakeLists.txt, src/Platforms/PlatformSelector.cpp, src/Platforms/PlatformSelector.hpp, src/Platforms/tests/CMakeLists.txt, src/Platforms/tests/test_PlatformSelector.cpp, src/QMCHamiltonians/CoulombPotentialFactory.cpp, src/QMCHamiltonians/tests/test_coulomb_pbcAA.cpp, src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp, src/QMCWaveFunctions/BsplineFactory/createComplexSingle.cpp, src/QMCWaveFunctions/BsplineFactory/createRealDouble.cpp, src/QMCWaveFunctions/BsplineFactory/createRealSingle.cpp, src/QMCWaveFunctions/CMakeLists.txt, src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp, src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp, src/io/OhmmsData/AttributeSet.h, src/io/OhmmsData/ParameterSet.cpp, src/io/OhmmsData/ParameterSet.h
As described in #2451, we need a way to select the exact implementation and being able map yes/no based on the build. So introduce PlatformSelector<CPU_OMPTARGET>.
- New feature
- No
epyc-server
=> Introduce PlatformSelector to allow both direct and indrect selection and enable offload codepath in non-offload builds.

config/build_olcf_summit_Clang.sh, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.2.cpp, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.h, src/QMCWaveFunctions/Fermion/MultiDiracDeterminantCalculator.h, src/QMCWaveFunctions/Fermion/SmallMatrixDetCalculator.h, src/QMCWaveFunctions/tests/test_multi_dirac_determinant.cpp
After sorting all the unique determinants, we can dispatch the computation by excitation level.
Before offloading to GPU, we make more functions static (callable inside kernel).
@TApplencourt made the initial change.
- No
epyc-server
=> Prepare MSD for offload

src/Particle/SoaDistanceTableAA.h, src/Particle/SoaDistanceTableAB.h, src/Particle/SoaDistanceTableABOMPTarget.h, src/QMCWaveFunctions/ExampleHeComponent.h, src/QMCWaveFunctions/Fermion/Backflow_ee.h, src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.cpp, src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h, src/QMCWaveFunctions/tests/test_polynomial_eeI_jastrow.cpp
J3 in offload was broken by #3905 because virtual particle set data transfer no more depends on NEED_TEMP_DATA_ON_HOST.
This PR adds missing flags in AA table consumers who needs data on the host.
and removes implicit NEED_TEMP_DATA_ON_HOST always forced on AA, AB tables.
- Bugfix
- No
epyc-server
=> Fix incorrect use of DTModes

config/build_olcf_summit_Clang.sh, src/Particle/SoaDistanceTableAAOMPTarget.h, src/Particle/SoaDistanceTableABOMPTarget.h, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp
The full loop iterations space is spliced into sizes of ChunkSizePerTeam to increase the number of  CUDA blocks/ workgroups on GPU.
Larger block sizes allow more resident computation and thus more efficient but lose time to solution when the number of blocks. For small problem sizes, the number of blocks is not an issue and efficiency matters more. I noticed much closer kernel performance between legacy CUDA and OpenMP offload.
A larger block size only affects iterations space larger than the block size, namely when the number of blocks changes.
The increase from 128 to 512 actually improve kernel efficiency a lot for small to medium problem sizes with smaller CUDA grid sizes. For example NiO a32 has 288 splines, so need 3 blocks of size 128, 2 blocks of 256, and 1 blocks of 512. 512 …
=> Adjust block sizes in offload kernels

docs/installation.rst
Two changes
- make the highlighting language "none" in the literal blocks (otherwise the default highlighter colors apparently random words in the text.  Okay, they're not random - they're clearly programming keywords, but it looks random when highlighted in text and not code)
- Fix the QMC_MATH_VENDOR literal block
- No
laptop
- N/A. This PR adds tests to cover any new code, or to catch a bug …
=> Minor fixes to the installation chapter

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.h, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
@shivupa reported to me this bug. Once determinants are reordered #3874.
`ReferenceDeterminant = ref_det_id;` is wrong.
The reference one should be always id 0.
I had some difficulty to add unit test.
1) reference det is chosen with the maximal weight. It is not exposed in input file.
2) current construction of MSD relies on the builder, namely the input file.
To make a test, refactoring certain code will be needed but it is better to do that after pending MSD PRs.
I did some tests by forcing refdet_id directly in SlaterDetBuilder.cpp. No failure so far.
- Bugfix
- No
epyc-server
=> Fix incorrect reference determinant id.

nexus/bin/nxs-test, nexus/tests/CMakeLists.txt, nexus/tests/unit/test_nxs_sim.py, nexus/tests/unit/test_qmca.py
I can reproduce nxs-test issue of sulfur on my workstation.
Both python interpreter and PYTHONPATH must be properly propagated to all the cmake to python and python internal calls.
Previous issues
1. `nxs-test --pythonpath` wipes out necessary PYTHONPATH
2. All nexus internal calls to python scripts doesn't enforce parent python interpreter. There might be more fixes needed. I only found those covered by ctest.
With this PR, at the CMake step, recorded python environment will be used for ctest. Even the environment is changed after cmake, ctest runs in the recorded environment. Updating test environment requires rerun cmake.
- Bugfix
- No
epyc-server
=> Nexus: Pass PYTHONPATH recorded at cmake step to nxs-test.

tests/solids/diamondC_2x1x1-Gaussian_pp_MSD/CMakeLists.txt
Increase tolerances to address https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=304790
e.g. deterministic-diamondC_2x1x1-gaussian_pp_MSD-vmcbatch-dmcbatch-mwalkers_sdj-2-2-2-*
Note that total energy has been reliable. Components have been displaying errors that cancel in the total.
Reviewer should verify that the correct tolerances for these tests are updated :-)
- No
None
=> Update tolerances in periodic gaussian MSD test

CMakeLists.txt, src/QMCWaveFunctions/Jastrow/BsplineFunctor.h, src/config.h.cmake.in
No more needed since ROCm 5.0 and AOMP 14.0-2
- Other (please describe): Cleaning
- No
epyc-server
=> Remove ROCM/AOMP workaround.

src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h, src/Utilities/ResourceHandle.h
When using multiple-walker resource, the current scheme is to add a unique_ptr. This stops compiler auto-generated copy constructor and requires extra code. In the way of using resources, we never need exact copying of individual resources. We always copy by the collection. For this reason, this PR introduces ResourceHandle to implement copy as no-op.
- New feature
- No
epyc-server
=> Add ResourceHandle

src/QMCDrivers/WFOpt/CostFunctionCrowdData.cpp, src/QMCDrivers/WFOpt/CostFunctionCrowdData.h, src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp, src/QMCHamiltonians/CoulombPBCAA.cpp, src/QMCHamiltonians/CoulombPBCAA.h, src/QMCHamiltonians/tests/test_coulomb_pbcAA.cpp
Need #3951
1. Connect CoulombPBCAA to multi walker resource. This change reduces allocation/de-allocation of value_offload but due to its low call count, performance gain is negligible. Anyway, reducing noise to the runtime is beneficial.
2. When we have two resources from coulomb and NLPP. WFOpt shows a bug of using the same resource collection for two hamiltonians. In CostFunction, h and h_0 have different components and thus cannot use the same resource collection.
- Bugfix
- New feature
- No
epyc-server
=> Connect CoulombPBCAA to multi walker resource

src/Numerics/Ylm.h, src/Numerics/tests/test_ylm.cpp, src/QMCHamiltonians/SOECPComponent.cpp
I use the Ylm's in Numerics for the spin-orbit ECP, and will need cartesian derivatives of these for ionic derivatives. The Ylm's in Numerics require cartesian vectors as input...except they **must**  unit vectors and must be in the format [z,x,y] instead of the standard ordering. 
This just adds a sphericalHarmonic wrapper which takes in any cartesian vector so the user can simply provide whatever position they want. Internally, it calculates the unit vector and reorders it to be [z,x,y] and then calls the Ylm implementation we already have. This allows me to clean up the SOECP for better readability.
I also introduce a …
=> spherical harmonic wrapper

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step.sh
Bump to Clang14  in AFQMC-Offload CI test from using a non-release commit
Fixes #3960
Add Complex tests for CUDA 11.2. 
Fixes #3953 
Complex test are broken with CUDA 11.6
Must be merged to work
- Bugfix
- No
=> Clang14 and CUDA11.2 in AFQMC-Offload CI

CMake/IntelCompilers.cmake, CMakeLists.txt
SYCL itself is not a CMake language. So it doesn't require a minimal CMake version.
However we need the llvm-based Intel compiler and I need to add a workaround for some compiler issues. The workaround will be based on compiler version which needs CMake 3.20 to determine the IntelLLVM compiler ID and version. For this reason, cmake 3.20 is required by ENABLE_SYCL.
- No
dell-laptop
=> Mandate CMake 3.20 when using SYCL and add a compiler workaround.

.github/workflows/ci-github-actions-self-hosted.yaml, .github/workflows/ci-github-actions.yaml, CMakeLists.txt
Bump GitHub Actions versions from Marketplace (permissions updated in repo).
Remove "Start testing in-house" to trigger self-hosted CI in PR comments.
Friendly CMake error message as it happens on Summit with nvhpc and cublas
Related to #3963 
- No
Must pass CI
=> Minor CI and CMake maintenance

src/Estimators/EstimatorManagerCrowd.cpp, src/Estimators/EstimatorManagerCrowd.h, src/Estimators/EstimatorManagerNew.cpp, src/Estimators/EstimatorManagerNew.h, src/Estimators/ScalarEstimatorBase.h
This drops Collectibles from the "new" Estimator code.  It isn't used and it won't be.
- No
Leconte
=> Remove unused Collectables from new Estimator code.

config/docker/dependencies/ubuntu/clang-latest/Dockerfile, config/docker/dependencies/ubuntu/openmpi/Dockerfile, tests/test_automation/github-actions/ci/run_step.sh
Bump CMake version using Kitware apt repo as a quick fix to PR #3997
Add `libomp-12-dev` to `clang-12` dependencies
Images already built and pushed to DockerHub
- Bugfix
- No
Local docker image, must pass CI
=> Update Dockerfile CI images

src/QMCWaveFunctions/Fermion/DelayedUpdateCUDA.h
Saw this bug when reading the code. The old assumption is only valid for D2H not H2D.
- Bugfix
- No
epyc-server
=> Fix DelayedUpdateCUDA::initializeInv H2D must be synchronized

src/spline2/MultiBsplineEval_helper.hpp
Add a workaround. Standalone reproducer is https://github.com/ye-luo/openmp-target/blob/master/tests/math/modf_team.cpp.
The current symptom is hang. So avoid adding the reproducer here.
- Other (please describe): bug workaround
- No
epyc-server
=> Workaroud OneAPI compiler bug.

tests/test_automation/github-actions/ci/run_step.sh
Double the job count in CI for nitrogen and sulfur for hopefully improved throughput
nitrogen is dual 32 core and sulfur is dual 24 core, and both have HT enabled, so this change will still leave the machines usable for other tasks.
- No
None
=> Increase CI jobs on nitrogen and sulfur

config/build_olcf_summit_Clang.sh
Move private modules to the global accessible space.
Also lock hdf5 version.
- No
Summit
=> Update Summit recipe modules.

config/build_alcf_theta.sh, src/Estimators/EstimatorManagerInput.cpp
Expect to fix https://github.com/QMCPACK/qmcpack/issues/3955.
Intel compiler was choked by `std::vector::insert(std::variant<>)`
- Bugfix
- No
Theta
=> Workaround intel 19.1.x compiler issue

CMakeLists.txt
Avoids CMake warnings of unset policy for CMake 3.22 onwards
- No
macports / cmake 3.22.4 / llvm 13 
=> Set CMake CMP0127 Policy

src/Estimators/EstimatorManagerNew.cpp, src/Estimators/EstimatorManagerNew.h, src/Estimators/OperatorEstBase.h, src/QMCDrivers/MultiWalkerDispatchers.h, src/QMCDrivers/QMCDriverInput.h, src/QMCDrivers/QMCDriverNew.cpp
In support of #4029 
The lighter weight replacement for per particle hamiltonian evaluation has crowd scope estimators register listener functions  with QMCHamiltonian. The hamiltonian operators use multi walker resources to manage the shared crowd level buffers on the operator side. It's necessary at runtime to be able to check this "trait" of the estimator and see if any have been added to the EstimatorManagerNew.
There is already a source of truth for walker serialization in QmcdriverInput which is strongly coupled to QMCDriverNew use that instead of adding an accessor to MultiWalkerDispatchers which is detail QMCDriverNew should know as little as possible about. 
- No
Leconte
_Update the …
=> Add listener "trait" and check if listening Estimators are instantiated, remove two sources of truth for walker serialization

src/Estimators/InputSection.h, src/Numerics/SoaCartesianTensor.h, src/Particle/DistanceTable.h, src/QMCDrivers/SFNBranch.cpp, src/QMCHamiltonians/SOECPComponent.cpp, src/QMCHamiltonians/SkPot.cpp, src/QMCHamiltonians/SkPot.h, src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.h, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.2.cpp, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp, src/QMCWaveFunctions/Fermion/SmallMatrixDetCalculator.h, src/QMCWaveFunctions/SPOSet.cpp, src/QMCWaveFunctions/SPOSet.h
It seems the code base is also improved.
- No
epyc-server
=> Reduce NVHPC warning

tests/performance/NiO/README
Found a way to directly download h5 files without going throw a browser.
- No
bora
=> Add NiO h5 download link in README.

tests/performance/NiO/CMakeLists.txt, tests/performance/adjust_qmcpack_input.py
Previously we hard-coded walker count 16 or 32. This makes benchmark harder to reflect performance of real simulations when problem size is small. Thus introduce variable counts. There is no perfect choices but I'm sure the current choice should be better than 16/32.
Mostly make small problem size runs heavier but large problem sizes unchanged.
- No
epyc-server
=> Expand NiO performance test walker counts.

CMake/macros.cmake, docs/simulationcell.rst, src/Particle/LongRange/KContainer.cpp, src/Particle/LongRange/LRCoulombSingleton.h, src/Particle/LongRange/StructFact.cpp, src/Particle/ParticleIO/LatticeIO.cpp, src/Particle/ParticleIO/tests/test_lattice_parser.cpp, src/Particle/ParticleSetPool.cpp, tests/solids/CMakeLists.txt, tests/solids/InSe_a4/CMakeLists.txt, tests/solids/InSe_a4/InSe-S1.xml
Fixes #4051. Breakage happened in #3852 785ce12
In a slab calculation (ppn) with 3d ewald, `lattice.SuperCellEnum == SUPERCELL_SLAB` is true which cannot be used to select quasi2D code paths. Introduce `LRCoulombSingleton::isQuasi2D()` for this purpose.
- Bugfix
- No
epyc-server
=> Fix slab (ppn)

src/QMCWaveFunctions/tests/CMakeLists.txt, src/QMCWaveFunctions/tests/gen_rotated_lcao_wf.py, src/QMCWaveFunctions/tests/test_RotatedSPOs_LCAO.cpp
The test system is a helium atom with two orbitals and an optional Jastrow factor.
A python script is used to generate reference values for the values of the wavefunction and derivatives at one point in space.  The script uses automatic differentiation (via autograd) to make computing the spatial and parameter derivatives straightforward.
This is the starting point for some testing of orbital rotation that should make changes and fixes more reliable (see #3977 ). 
- No
laptop
- Yes. This PR …
=> Add tests for Rotated SPOs using LCAO

src/Particle/ParticleSet.cpp, src/Particle/Walker.h
Got some issue on bora
```
/scratch2/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack-develop/src/Particle/ParticleSet.cpp(40): error: member "qmcplusplus::Walker<t_traits, p_traits>::cuda_DataSize [with t_traits=qmcplusplus::QMCTraits, p_traits=qmcplusplus::PtclOnLatticeTraits]" has already been defined
int ParticleSet::Walker_t::cuda_DataSize = 0;
^
```
- Bugfix
- No
bora
=> Fix legacy CUDA compilation issue on Bora

src/Estimators/tests/test_OneBodyDensityMatrices.cpp
This PR is to make unit_test_estimators for one-body density matrices pass for mixed-precision build on sulfur.
https://cdash.qmcpack.org/CDash/testDetails.php?test=19584585&build=319954
- No
Intel Xeon
=> Adjust tolerance for unit_test_estimators for One-body density matrices on mixed precision build

CMake/ClangCompilers.cmake, CMakeLists.txt, docs/installation.rst
The same scheme has been used for CUDA. Now implement the same scheme to derive OFFLOAD_ARCH from HIP_ARCH.
I also update OpenMP offload build instruction.
- No
epyc-server, crusher
=> Derive OpenMP OFFLOAD_ARCH based on HIP_ARCH.

src/QMCHamiltonians/ECPComponentBuilder.2.cpp
Remove the check of maxTexture1D in HIP.
The texture API is deprecated (both CUDA and HIP).
HIP will return -1 when the texture API is no loger supported.
Therefore, adopting the same magic number as for CPUs (100,000).
Removing reliance on deprecated API.
- No
AMD Radeon 7
- Yes, this PR is up to date with current the current state of 'develop'
=> Do not use cudaDeviceProp maxTexture1D in HIP

src/QMCWaveFunctions/tests/gen_rotated_lcao_wf.py, src/QMCWaveFunctions/tests/stats.py, tests/molecules/He_param/CMakeLists.txt, tests/molecules/He_param/He_orb_rot_param_grad_legacy.xml
The gen_rotated_lcao_wf.py file is extended to generate QMC averages for the parameter gradients.
A test for the legacy driver using one thread is introduced.  The same rotation is used for both up and down electrons to check the parameter gradients are the same.
The cost parameters in the input file are important (energy to 1.0 and reweightedvariance to 0.0) because the code defaults to an energy fraction of 0.9 and a reweightedvariance fraction of 0.1.  If these are left at the default, the rotation parameter gradients are around -0.29.
The error bars on the reference values were taken from a QMCPACK run 100x longer (and divided by 10).
This is an attempt to define one point where we know the code works and has a validated answer.
The test uses the legacy driver and only one thread.  It …
=> Add orbital rotation test with legacy driver

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step.sh
Add MPI configuration based on OpenMPI using ROCm clang compilers
For CI running on nitrogen
Must merge onto develop before changes take place.
Fixes #4048
- No
nitrogen, must pass CI
=> Add MPI support to ROCm legacy CI

src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h, src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h
NVHPC 22.5 recompiled two of the offload regions can caused crazy weights and blow up the calculation. In some scenarios, DMC hangs. With this PR, DMC in performance tests seems stable.
Tested also with Clang on NVIDIA and AOMP on AMD GPUs.
- Other (please describe): Compiler workaround.
- No
epyc-server
=> Rewrite loop to workaround NVHPC bugs

CMake/ClangCompilers.cmake
This removes warnings that appear with almost every compilation unit. i.e. hundreds of times with the debug offload build.  Every useless long lived warning raises the chance a useful warning will be ignored.
This drops the debug info quality especially for CUDA kernels but it should be possible to get that back with
ENABLE_CUDA=1 and ENABLE_OFFLOAD=0. 
I'm not sure of what happens with this warning in the AMD environment. This PR doesn't change what will happen there at all.
Don't add the `-fstandalone-debug` for a platform that doesn't support it.
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using …
=> Drop standalone-debug for offload builds

nexus/tests/unit/test_structure.py
Guard against divide by zero in the test_embed function of test_structure.py
This causes failures in the nightlies e.g. https://cdash.qmcpack.org/CDash/testDetails.php?test=19710670&build=322808
- Bugfix
- No
Sulfur. Nightly gccnewmpi configuration.
=> Fix test_structure divide by 0

CMakeLists.txt, src/Estimators/tests/CMakeLists.txt, src/Particle/CMakeLists.txt, src/Particle/LongRange/tests/CMakeLists.txt, src/Particle/ParticleBase/tests/CMakeLists.txt, src/Particle/ParticleIO/tests/CMakeLists.txt, src/Particle/tests/CMakeLists.txt, src/Platforms/OMPTarget/CMakeLists.txt, src/QMCApp/CMakeLists.txt, src/QMCDrivers/tests/CMakeLists.txt, src/QMCHamiltonians/tests/CMakeLists.txt, src/QMCTools/CMakeLists.txt, src/QMCTools/tests/CMakeLists.txt, src/QMCWaveFunctions/CMakeLists.txt, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.h, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp, src/QMCWaveFunctions/Jastrow/BsplineFunctor.cpp, src/QMCWaveFunctions/Jastrow/BsplineFunctor.h, src/QMCWaveFunctions/tests/CMakeLists.txt, src/QMCWaveFunctions/tests/test_J1_bspline.cpp
I've added a build workaround required by the current functional clang 15 offload compiler which cannot build offload target kernels with -O0. This breaks out the omptarget files in ParticleSet and QMCWavefunctions as separate targets. If you actually use a debugger and have experienced using it on -O3 code you'll realize there is no way we want all of ParticleSet and QMCWavefunctions compiled with -O3 in debug.
This also required refactoring BsplineFunctor.h which contained omp target and was ending up in many compilation units.  I also couldn't stand the extremely sloppy template parameter and typedef use in the class and cleaned that up.  While it looked as if T could be any scalar it in fact could only be the QMCTraits::RealType.  There were a few value_type typedefs but they were set …
=> Workaround for Debug, since omptarget requires -03 to build

src/QMCWaveFunctions/CMakeLists.txt
qmcwfs_omptarget needs platform_LA
platform_LA also needs to be PUBLIC due to exposure via header files.
- Bugfix
- No
epyc-server
=> Add missing dependency in CMake.

src/QMCTools/PyscfToQmcpack.py
Fixes #3958
I tested the changes on the F atom and the SCF vs VMC/NoJ energies agree for UHF:
```
SCF: -23.942446 Ha
VMC: -23.9427(2) Ha
```
- Bugfix
- No
OLCF/Andes
=> Add UHF/UKS support in Pyscf converter

src/QMCWaveFunctions/tests/test_RotatedSPOs_LCAO.cpp
From conversations with Ye, it may be the case the mathematics of RotatedSPOs::evaluateDerivatives assumes the current rotation angle is zero. See some of the discussion in #4083 on parameter derivatives with respect to the total rotation or delta rotation.
The equation of orbital rotation is:
C_1 = exp(X) * C_0
where C_0 is the original MO coefficient matrix, X is the skew-symmetric matrix containing the rotation parameters, exp(X) is the rotation matrix, and C_1 is the MO coefficient matrix after the rotations have been applied.
The question is whether the derivatives are computed as
* exp(0) * C_1 ( This is delta rotation )
or 
* exp(X) * C_0 ( This is total rotation )
(where the "0" in exp(0) means a matrix where all the rotation parameters are set to zero.  The resulting rotation …
=> Test more orbital rotation scenarios

docs/unit_testing.rst, src/Message/catch_main.cpp, src/Utilities/tests/CMakeLists.txt
Failing unit test was not able to report all output to cdash.
"The rest of the test output was removed since it exceeds the threshold of 100000 bytes."
https://cdash.qmcpack.org/CDash/testDetails.php?test=19984254&build=325108
So it is better to suppress output by default.
Option "--turn-on-printout" added to make the printout through if needed.
- No
epyc-server
=> Suppress QMCPACK printout in unit tests by default.

CMake/macros.cmake, tests/solids/LiH_solid_1x1x1_pp/CMakeLists.txt, tests/solids/LiH_solid_1x1x1_pp/det_ensemble_blocks_hf_vmc_LiH-gamma.txt, tests/solids/LiH_solid_1x1x1_pp/det_ensemble_blocks_hf_vmc_LiH-gamma_0.xml, tests/solids/LiH_solid_1x1x1_pp/det_ensemble_blocks_hf_vmc_LiH-gamma_1.xml, tests/solids/LiH_solid_1x1x1_pp/det_ensemble_blocks_hf_vmc_LiH-gamma_2.xml, tests/solids/LiH_solid_1x1x1_pp/det_ensemble_blocks_hf_vmc_LiH-gamma_3.xml
Add minimal test of ensemble functionality. Each run in the ensemble has a different number of blocks to catch basic MPI errors. Standard CMake macro adapted to recognize *.txt files when specified as input and treat them as ensemble inputs. Statistical output is currently unchecked. Further changes and a possibly different approach may be needed if/when simulation output is checked. While deterministic, ensemble output currently differs from non-ensemble case.
- No
Sulfur. gcc mpi new config.
- NA. …
=> Add minimal ensemble test

src/Platforms/SYCL/SYCLDeviceManager.cpp
The includes 'CL/sycl/backend.hpp' and 'CL/sycl/backend/level_zero.hpp' are already included in 'CL/sycl.hpp' in 'SYCLDeviceManager.h' such that we can remove that here. 
Also, I could not find any calls to level_zero api such that I suggest to remove this include.
This commit removes non needed includes in SYCLDeviceManager.cpp to improve code quality. 
- No
- Ubuntu 20.04
simply a reminder of what we are …
=> [SYCL] Fix SYCL includes in SYCLDeviceManager

src/QMCHamiltonians/ECPComponentBuilder.cpp, src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp
Change the defaults to only create *.pp.dat, J1.*, J2.*, uk.* files when verbosity is set to the debug level.
i.e. After this change, `qmcpack input.xml` will result in a much cleaner run directory by default while `qmcpack -verbosity=debug input.xml` will restore historical behavior. 
In previous discussions, these files are rarely used and only in debugging type situations. They are also not mentioned in the manual.
Note that the einspline.tile_* files are still created since these are mentioned in the manual and the excitations tutorial. 
- New feature
- Yes
Someone relying on these files will have to specify -verbosity=debug.
Sulfur, nightly gcc12 mpi config
- Yes. Code added or changed in the PR has been …
=> Only create gridded Jastrow and pseudopotential files at debug level verbosity

src/Containers/OhmmsPETE/TinyVector.h, src/QMCHamiltonians/NonLocalECPComponent.cpp
Current TinyVector assign operator allow implicit complex to real conversion which is error-prone. Disallow that.
Fixed NLPP accordingly.
- No
epyc-server
=> Make type conversion explicit.

docs/methods.rst, src/QMCDrivers/QMCDriver.cpp, tests/solids/diamondC_2x1x1_pp/det_qmc_short.in.xml, tests/solids/diamondC_2x1x1_pp/det_qmc_short_vmcbatch.in.xml
Change the default number of blocks between computing the wavefunction (primarily the inverse Slater matrices) for non-mixed precision builds to 10 from the current value of zero (never). Set the input parameter in a couple of tests for coverage.
QMCPACK should not have unsafe defaults, and this removes one. Closes https://github.com/QMCPACK/qmcpack/issues/3056 . Currently if this input is not set, the results are guaranteed to be wrong after a sufficiently long run due to accumulation of numerical error. Unfortunately while the error clearly is larger in larger systems, how it accumulates is not obvious, particularly for different quality wavefunctions where e.g. occasional near electron coalescence presumably risks worsening the error. Potentially some of the reported problems with …
=> Safe default for blocks_between_recompute at full precision

src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp, src/QMCWaveFunctions/RotatedSPOs.cpp, tests/molecules/He_param/CMakeLists.txt, tests/molecules/He_param/He_orb_rot_param_grad_legacy.xml
See #4083, #3977, and #4076 for previous attempts.
This is the minimal change to get the added test to pass (parameter derivative for the legacy driver when multiple threads are used).
As a result of investigations from the comment in https://github.com/QMCPACK/qmcpack/pull/4083#pullrequestreview-1036223817 , calling buildOptVariables multiple times is the culprit in resetting the global indexing in myVars.
- Bugfix
- No
desktop …
=> Orbital rotation initializes parameter only once, fixes for legacy driver with threads

tests/performance/NiO/CMakeLists.txt
Current folder and test names put tags in different orders.
old:
test name : `performance-NiO-a8-e96-cpu_driver-w512-DU16-1-16`
test work folder is at `tests/performance/NiO/dmc-a8-e96-cpu_driver-DU16`
It was painful to locate the test work directory.
Rename them to be closer.
Now
test name : `performance-NiO-a8-e96-DU16-cpu_driver-w512-1-16`
test work folder is at `tests/performance/NiO/dmc-a8-e96-DU16-cpu_driver`
Another notable change, all the J3 tests have delayed updated. Not useful to benchmark the slow code path. There are SM1 case already although without J3.
- No
epyc-server
=> Update generated folder and name of NiO peformance tests

tests/performance/C-graphite/README, tests/performance/C-molecule/CMakeLists.txt, tests/performance/C-molecule/README
This PR is a part of #4081 .
Update C-molecule performance test walker counts to more detailed performance check for the real simulation.
C-graphite performance test update will be followed with expanding its system size for the test. (Current graphite performance test has only one system size to check.)
- Other (please describe): add test
- No
Intel Xeon
- No. …
=> Update C-molecule performance test walker counts.

src/QMCWaveFunctions/tests/test_DiracDeterminant.cpp, src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp, src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp
Address https://cdash.qmcpack.org/CDash/testDetails.php?test=20251909&build=328253 failure by increasing tolerance.
Also suppress all the printout.
- No
epyc-server
=> Adjust tolerance to make deterministic-unit_test_wavefunction_trialwf pass on AMD complex build

config/build_olcf_crusher_afar.sh
Add build recipe on Crusher with the afar compiler.
If one don't have access to the customized module mpiwrappers/cray-mpich-afar.
Here is cray-mpich-afar.lua
```
conflict("mpiwrappers")
unload("PrgEnv-cray")
unload("PrgEnv-gnu")
unload("PrgEnv-amd")
unload("PrgEnv-cray-amd")
load("gcc")
load("afar")
load("craype")
load("cray-mpich")
load("cray-pals")
prepend_path("PATH", pathJoin(os.getenv("MPICH_DIR"), "bin"), ":")
setenv("MPICH_CC", "clang")
setenv("MPICH_CXX", "clang++")
setenv("MPICH_FC", "flang")
setenv("MPICH_F77", "flang")
setenv("MPICH_F90", "flang")
setenv("ROCM_PATH", pathJoin(os.getenv("OLCF_AFAR_ROOT")))
```
- Other (please describe): build script.
- No
olcf crusher.
=> Add crusher recipe using afar compiler.

src/QMCHamiltonians/CoulombPBCAB.cpp, src/QMCHamiltonians/CoulombPBCAB.h, src/QMCHamiltonians/CoulombPBCAB_CUDA.h, src/QMCHamiltonians/tests/test_coulomb_pbcAB.cpp, src/Utilities/ResourceCollection.h, src/type_traits/RefVectorWithLeader.h
This contains changes to CoulombPBCAB to support per particle Listeners and a corresponding test. Documentation is partial here but should make sense when the changes to QMCHamiltonian are PR'd. That can't really be done until all the lower level changes go in.
- New feature
- No
Leconte
- Yes Code added or changed in the PR has …
=> Add per particle listener support to CoulombPBCAB

src/QMCApp/QMCMain.cpp
Closes #4119
Report memory info when QMCPACK starts.
Please ignore `106:` which is from ctest runs.
```
106: =====================================================
106:                     QMCPACK 3.14.9
106: 
106:        (c) Copyright 2003-  QMCPACK developers
106: 
106:                     Please cite:
106:  J. Kim et al. J. Phys. Cond. Mat. 30 195901 (2018)
106:       https://doi.org/10.1088/1361-648X/aab9c3
106: 
106:   Git branch: print-mem
106:   Last git commit: 5c9a98318306951107dc084d7ff7aa8fca181699-dirty
106:   Last git commit date: Mon Jul 25 16:08:29 2022 -0500
106:   Last git commit subject: Print memory when main starts.
106: =====================================================
106:   Global options 
106: 
106:   Total number of MPI ranks = 8
106:   Number of MPI groups …
```
=> Print memory usage when QMCPACK starts

src/QMCWaveFunctions/RotatedSPOs.cpp, src/QMCWaveFunctions/RotatedSPOs.h, src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp
Add functions to compute the matrix log of a rotation matrix and extract the entries of the resulting antisymmetric matrix to a list of parameters.
This should allow us to recover rotation parameters from a rotation matrix.
- New feature
- No
desktop
=> Compute logarithm of rotation matrix

docs/installation.rst, tests/performance/NiO/README
Add documentation for variable -DQMC_PERFORMANCE_NIO_MAX_ATOMS for the performance test. This variable is to define the maximum size of the system for the performance test.
- No
Intel Xeon
=> Add documentation for MAX_ATOMS variable for the performance test

src/QMCDrivers/DMC/DMCFactory.cpp, src/QMCDrivers/DMC/DMCFactory.h, src/QMCDrivers/DMC/DMCFactoryNew.cpp, src/QMCDrivers/DMC/DMCFactoryNew.h, src/QMCDrivers/QMCDriverFactory.cpp, src/QMCDrivers/RMC/RMCFactory.cpp, src/QMCDrivers/RMC/RMCFactory.h, src/QMCDrivers/VMC/VMCFactory.cpp, src/QMCDrivers/VMC/VMCFactory.h, src/QMCDrivers/VMC/VMCFactoryNew.cpp, src/QMCDrivers/VMC/VMCFactoryNew.h, src/QMCDrivers/WFOpt/QMCWFOptFactoryNew.cpp, src/QMCDrivers/WFOpt/QMCWFOptFactoryNew.h
As suggested in #4125, this updates various factory functions to return `std::unique_ptr<T>`.
~I also moved construction of `wOut` to be earlier in the construction of` QMCDriverNew`.~
- No
local workstation: Ubuntu 20.04
_Update the …
=> Refactor Factory functions to return std::unique ptr

src/QMCWaveFunctions/BsplineFactory/BsplineSet.h, src/QMCWaveFunctions/CompositeSPOSet.h, src/QMCWaveFunctions/EinsplineSet.cpp, src/QMCWaveFunctions/EinsplineSet.h, src/QMCWaveFunctions/ElectronGas/FreeOrbital.h, src/QMCWaveFunctions/HarmonicOscillator/SHOSet.cpp, src/QMCWaveFunctions/HarmonicOscillator/SHOSet.h, src/QMCWaveFunctions/LCAO/LCAOrbitalSet.h, src/QMCWaveFunctions/PlaneWave/PWOrbitalSet.cpp, src/QMCWaveFunctions/PlaneWave/PWOrbitalSet.h, src/QMCWaveFunctions/PlaneWave/PWRealOrbitalSet.cpp, src/QMCWaveFunctions/PlaneWave/PWRealOrbitalSet.h, src/QMCWaveFunctions/SPOSet.h, src/QMCWaveFunctions/SpinorSet.cpp, src/QMCWaveFunctions/SpinorSet.h, src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/TrialWaveFunction.h, src/QMCWaveFunctions/WaveFunctionComponent.h, src/QMCWaveFunctions/tests/FakeSPO.h
Once TrialWF is built, it calls checkInVariables to query variational parameters under the TrialWF tree regardless of if running WFOpt or not. This the desired behavior.
Consequentially, checkInVariables cannot be implemented as a feature blocker. Update SPOSet and its derived classes.
- Bugfix
- No
epyc-server
=> Update SPOSet WFopt related APIs

src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.cpp
Fixes #4092. 3.13 and 3.14 releases are affected.
As @markdewing pointed out, it was caused by reordering and it seem I missed changing one function.
Still need a test, the current reproducer seems too heavy being used as a unit test.
- Bugfix
- No
epyc-server
=> Fix queryOrbitalsForSType due to reordering of ions.

src/Message/Communicate.cpp
Increase output readability in MPI jobs by not printing free memory for every single MPI task. Rely on #4130 instead. If problems ever occur we could expand the #4130 report to include max and min values.
- New feature
- No
nitrogen, nightly gcc 12 mpi configuration
=> Do not print initial memory availability for every MPI task

nexus/lib/pseudopotential.py
Previously the maximum angular channels known for pseudpotentials were: s,p,d,f,g,h,i
Extend this to the full set of 21 conventional single-lettered azimuthal quantum numbers: s,p,d,f,g,h,i,k,l,m,n,o,q,r,t,u,v,w,x,y,z
This avoids array bounds errors for potentials with a very large number of channels.
- Bugfix
- No
Workstation
=> Nexus: extend angular channels up to l_max=21

src/Particle/ParticleSetPool.cpp, src/Particle/tests/test_particle_pool.cpp
`ParticleSetPool::getWalkerSet` doesn't check `pname` if `myPool.size() == 1`. This removes the if statement and adds a test for this corner case.
- Bugfix
- No
simply a reminder of what we are going to look …
=> ParticleSetPool: Don't assume single element has the correct key

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/MCPopulation.cpp, src/QMCDrivers/MCPopulation.h, src/QMCDrivers/QMCDriverNew.cpp, src/QMCDrivers/QMCDriverNew.h, src/QMCDrivers/VMC/VMCBatched.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp, src/QMCDrivers/tests/QMCDriverNewTestWrapper.h
pset, twf, ham objects are maintained in CostFunctionCrowdData.
- No
epyc-server
=> Avoid creating driver scope walkers in the population object of WFOpt

src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp
This is a small fix to a problem @ye-luo found with PR #4075. With this change, the hybrid method should work with the legacy driver again and pass the tests.
- Bugfix
- No
Lawrencium computing cluster
=> Fix hybrid method for legacy driver

CMakeLists.txt, doxygen/config.h, src/Particle/HDFWalkerInputManager.cpp, src/Particle/HDFWalkerInputManager.h, src/QMCWaveFunctions/LCAO/LCAOSpinorBuilder.cpp, src/QMCWaveFunctions/LCAO/LCAOrbitalBuilder.cpp, src/io/OhmmsData/HDFAttribIO.h, src/io/hdf/hdf_archive.h, src/io/hdf/hdf_datatype.h
Removes the macro HAVE_LIBHDF5 which is always true.
Fixes #4155
- No …
=> Remove macro HAVE_LIBHDF5

docs/LCAO.rst, src/QMCTools/PyscfToQmcpack.py
The -pyscf option was removed in favor of the more general -orbitals in #2748.
Update a couple places the option was used in the documentation showing an example of converter use.
- No
=> Change -pyscf to -orbitals in some convert4qmc docs

src/Estimators/EstimatorManagerInput.cpp, src/Estimators/InputSection.cpp, src/Estimators/ScalarEstimatorInputs.cpp, src/Estimators/tests/test_ScalarEstimatorInputs.cpp, src/QMCDrivers/QMCDriverInput.cpp, src/QMCTools/QMCGaussianParserBase.cpp, src/QMCWaveFunctions/LCAO/MultiFunctorAdapter.h, src/Utilities/ModernStringUtils.hpp, src/Utilities/ProjectData.cpp, src/Utilities/string_utils.h, src/Utilities/tests/CMakeLists.txt, src/Utilities/tests/test_string_utils.cpp, src/io/OhmmsData/ParameterSet.cpp, src/io/OhmmsData/ParameterSet.h, src/io/OhmmsData/libxmldefs.cpp, src/io/OhmmsData/libxmldefs.h, src/io/OhmmsData/tests/test_xml.cpp
To load a vector of things, use astring to load the whole parameter content.
Then use convertStrToVec to generate the vector.
- New feature
- No
epyc-server
=> Add convertStrToVec and astring support in ParameterSet

src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h, src/QMCWaveFunctions/Jastrow/PolynomialFunctor3D.h, src/QMCWaveFunctions/tests/test_polynomial_eeI_jastrow.cpp, tests/molecules/C2_pp/CMakeLists.txt
J3(eeI) NLPP derivatives
- New feature
- No
epyc-server
=> Implement NLPP parameter derivatives in evaluateDerivRatios in JeeI

src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h, src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp
Part of #3712, this adds a unit test for DiracDeterminantBatched for the spinor orbital case. Essentially, it uses the same values from the DiracDeterminant unit test. For now, I have only added the single walker APIs for evalGradWithSpin and ratioGradWithSpin. Will add the actual mw_ APIs in a separate PR
- New feature
- No
MacBook Pro, M1 Pro chip
- Yes. This PR is up to date with …
=> DiracDeterminantBatched xxxWithSpin APIs

src/QMCWaveFunctions/LCAO/CuspCorrectionConstruction.cpp, src/QMCWaveFunctions/LCAO/CuspCorrectionConstruction.h, src/QMCWaveFunctions/LCAO/LCAOrbitalBuilder.cpp
Closes #4179
The old code behavior:
if the file with file name from cuspInfo doesn't exist or invalid, create a new file with default filename in the current work directory.
So a second run still regenerate cusp correction unless pointing to the new files or move the new files as cuspInfo indicated. 
changed behavior:
if the file exists but is invalid, error out.
if the file doesn't exist, generate the file named as cuspInfo or default if cuspInfo is not provided.
So when the file doesn't exist, the first run create the file and the second run picks up the file.
- Bugfix
- No
epyc-server
=> Change cuspInfo file name input behavior

src/Numerics/MatrixOperators.h, src/QMCHamiltonians/ForceCeperley.cpp, src/QMCHamiltonians/ForceChiesaPBCAA.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp, src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp, src/QMCWaveFunctions/PlaneWave/PWOrbitalSet.cpp, src/QMCWaveFunctions/PlaneWave/PWRealOrbitalSet.cpp, src/QMCWaveFunctions/tests/test_MO.cpp
A bug found in LCAOrbitalSet::evaluateDetRatios.
Also removed many not necessary APIs in Numerics/MatrixOperators.h
- Bugfix
- No
epyc
=> Fix LCAOrbitalSet::evaluateDetRatios and clean up Numerics/MatrixOperators.h

src/QMCHamiltonians/HamiltonianPool.cpp, src/QMCHamiltonians/QMCHamiltonian.cpp
bad, since https://github.com/QMCPACK/qmcpack/pull/4130
```
Hamiltonian h0
KineticKinetic energy
ElecElecCoulombPBCAA potential: e_e
IonIonCoulombPBCAA potential: ion0_ion0
LocalECPCoulombPBCAB potential source: ion0
NonLocalECPNonLocalECPotential: ion0
```
good.
```
Hamiltonian h0
Kinetic         Kinetic energy
ElecElec        CoulombPBCAA potential: e_e
IonIon          CoulombPBCAA potential: ion0_ion0
LocalECP        CoulombPBCAB potential source: ion0
NonLocalECP     NonLocalECPotential: ion0
```
- Bugfix
- No
epyc-server
=> Fix printing style issue.

src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp
Fix #4203
The change from the local potential to the total potential was done in the legacy driver code, but not the batched driver code.
Prior to #4194 , the nlpp energy contribution was subtracted, if present.   With the new code, the list of wavefunction-dependent Hamiltonians includes the kinetic energy in addition to the nlpp contribution.  The initialization of the ENERGY_FIXED field was changed to account for this.
- Bugfix
- No
desktop
- Yes. Code added or changed in the PR …
=> Update batch driver to fix parameter derivative

src/Containers/MinimalContainers/RecordArray.hpp, src/Containers/MinimalContainers/tests/test_RecordArray.cpp, src/QMCDrivers/WFOpt/EngineHandle.h, src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp, src/QMCHamiltonians/OperatorBase.cpp, src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/tests/test_RotatedSPOs_LCAO.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction_He.cpp
Switch from indirect access to direct access. More convenient to use views.
@markdewing I kept the RecordArray as a specialized type of Matrix.
- No
epyc-server
=> Adjust RecordArray to direct storage.

.github/workflows/ci-github-action-auto-rebase.yaml, external_codes/github_actions/auto-rebase.sh
In reference to issue: https://github.com/QMCPACK/qmcpack/issues/3862
Continuation of this PR: https://github.com/QMCPACK/qmcpack/pull/3994
Allows the rebase action to reapprove pr after autorebase is complete.  It approves specifically the SHA it pushes, so there shouldnt be an accidental approval.
- Other (please describe): Github Actions Pipeline Changes
- No
remote github runners
Tested on this PR: https://github.com/walshmm/qmcpack/pull/11
You can follow its listed history to see it was rebased and reapproved via bot before being automerged.
- Yes. This PR is up to date with current …
=> Reapprove PR after Auto Rebase Completes

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step.sh
Upgrade from LLVM 14 to LLVM 15-rc3 on sulfur and migrate CI
Remove USE_OBJECT_TARGET option
Needs to be merged to execute the new CI workflow
Related to #4128 
Closes #4211
- No
=> Sulfur CI upgrade to LLVM 15 rc3

config/build_olcf_summit_Clang.sh, docs/installation.rst
Update recipe and docs. Clang 15 (currently rc3) is the version I can recommend to all the users.
- No
epyc-server
=> Update OLCF summit recipe

src/QMCWaveFunctions/CMakeLists.txt
Minor cmake organization update.
- No
epyc-server
=> Fermion/MultiDiracDeterminant.2.cpp belongs to an offload target.

docs/methods.rst, src/QMCDrivers/WFOpt/GradientTest.cpp, src/QMCDrivers/WFOpt/GradientTestInput.cpp, src/QMCDrivers/WFOpt/GradientTestInput.h
Allow specifying the finite difference delta from the input file. Motivation for this addition comes from checking the orbital rotation gradients for Bspline SPOs.  The Bspline SPOs can be used with a precision of float or double.  The orbital rotation gradients with float precision were giving a large relative difference, and it turned out the default finite difference delta of 1e-5 was too small.  As the value of delta increased, the relative error decreased, which indicated it was in the numerical noise region.  As an alternate check, the precision of the SPOs was switched to double, and then the relative differences from the default delta were fine.
For improvements in the output formatting, the columns and headers are aligned, as requested in #3793.  The precision of the gradients …
=> Improve gradient test

CMake/macros.cmake, src/QMCDrivers/QMCDriverInput.cpp, tests/io/CMakeLists.txt
Close #4195
The checkpoint attribute wasn't being read and therefore not being used to set `dumpconfig_`. This fixes that and tries to match the behavior of the legacy driver.
What changes does this code introduce?
- Bugfix
- No
- ? This PR adds tests …
=> Disable configuration writing upon request in batched drivers 

src/QMCWaveFunctions/SpinorSet.cpp, src/QMCWaveFunctions/SpinorSet.h
This PR optimizes the existing mw_evaluateVGLandDetRatiosGrad implemented in #4208 so that we remove the data transfers to the host and instead update the spinor data on the device. 
This also adds an extractSpinComponentRefList API reduce repeated code for getting the up/down spo reference vectors. I updated a few other functions which had repeated code to use the new API
Note that there is a unit test for this API already in place. However, the problem is that the existing unit tests don't utilize splines which are the only SPOSets that are currently offloaded. 
- New feature
- No
my mac
simply a reminder of …
=> SpinorSet offload VGLandDetGradRatios

CMake/macros.cmake
At the Crusher Hackathon I ran into trouble using `-DQMC_SYMLINK_TEST_FILES=OFF`. Files were being placed inside an additional directory and not where they were expected to be located.
I believe the issue is that [file(COPY ...)]( https://cmake.org/cmake/help/latest/command/file.html#copy) asks for a destination directory and therefore has different behavior than …
=> Fix -DQMC_SYMLINK_TEST_FILES=OFF 

CMakeLists.txt
Current clang develop caused nvcc detection failure in CMake. Explicitly instructing the C++ standard used by nvcc works around the issue. See discussion in https://gitlab.kitware.com/cmake/cmake/-/issues/23971
- No
epyc-server
=> Directly set c++17 for nvcc.

src/AFQMC/HamiltonianOperations/KP3IndexFactorization.hpp, src/AFQMC/Wavefunctions/NOMSD.icc
Remove unnecessary auxiliary function in connection with deprecated functions.
- No
Ubuntu 22.04
=> remove auxiliary Sizes function

nexus/bin/qdens, nexus/examples/qmcpack/rsqmc_quantum_espresso/01_diamond_dft_vmc/diamond_lda_vmc_batched_estimators.py, nexus/lib/qmcpack_input.py, nexus/lib/testing.py, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/H2O/runs/dmc.in.xml, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/H2O/runs/opt.in.xml, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/LiH/runs/dmc.in.xml, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/LiH/runs/opt.in.xml, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/c20/runs/c20/opt/opt.in.xml, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/c20/runs/c20/qmc/qmc.in.xml, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/diamond/runs/diamond/vmc/vmc.in.xml, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/graphene/runs/graphene/opt/opt.in.xml, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/graphene/runs/graphene/qmc/qmc.in.xml, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/oxygen_dimer/scale_1.0/opt.in.xml, nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/oxygen_dimer/scale_1.0/qmc.in.xml, nexus/tests/unit/test_qmcpack_input.py
Support `driver_version` and also currently working estimators for the batched drivers.  The sole Nexus example for the batched drivers has been updated (also including Jastrow optimization) and another has been added that includes all currently working estimators: MPC, spin density, and the momentum distribution.
- New feature
- No
Laptop
=> Nexus: update to current batched driver style

CMake/IntelCompilers.cmake, config/build_alcf_polaris_Clang.sh, config/build_alcf_theta.sh
19.1.0 doesn't work on Theta. 19.1.2 works fine.
- No
Theta, Bora
=> Raise Intel classic compiler minimum version

src/AFQMC/HamiltonianOperations/KP3IndexFactorization.hpp
=> Remove more size functions from KP3Index

src/Containers/OhmmsPETE/TinyVector.h
Remove unused compile-time functionality in `TinyVector`
Some functions are still not consumed in runtime tests and need to be refactored at the consumer level
Related to #3411
- No
Ubuntu 22.04
=> Cleanup TinyVector

src/Containers/OhmmsPETE/TinyVector.h
Remove non-special specialization
- No
nitrogen, gcc 
=> Additional TinyVector cleanup

CMake/macros.cmake, CMake/unit_test.cmake, src/QMCTools/ppconvert/src/common/IOASCII.cc
OpenMP may offload to CPU when GPUs are not available. Set `OMP_TARGET_OFFLOAD=mandatory` to stop false positive test results.
- No
bora
=> Set offload mandatory in ctest

src/QMCDrivers/CorrelatedSampling/CSVMC.cpp, src/QMCDrivers/CorrelatedSampling/CSVMC.h, src/QMCDrivers/DMC/DMC.cpp, src/QMCDrivers/DMC/DMC.h, src/QMCDrivers/DMC/DMCFactory.cpp, src/QMCDrivers/DMC/DMCFactory.h, src/QMCDrivers/DMC/DMC_CUDA.cpp, src/QMCDrivers/DMC/DMC_CUDA.h, src/QMCDrivers/QMCDriver.cpp, src/QMCDrivers/QMCDriver.h, src/QMCDrivers/QMCDriverFactory.cpp, src/QMCDrivers/RMC/RMC.cpp, src/QMCDrivers/RMC/RMC.h, src/QMCDrivers/RMC/RMCFactory.cpp, src/QMCDrivers/RMC/RMCFactory.h, src/QMCDrivers/VMC/VMC.cpp, src/QMCDrivers/VMC/VMC.h, src/QMCDrivers/VMC/VMCFactory.cpp, src/QMCDrivers/VMC/VMCFactory.h, src/QMCDrivers/VMC/VMC_CUDA.cpp, src/QMCDrivers/VMC/VMC_CUDA.h, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.h, src/QMCDrivers/WaveFunctionTester.cpp, src/QMCDrivers/WaveFunctionTester.h, src/QMCDrivers/tests/test_dmc_driver.cpp, src/QMCDrivers/tests/test_vmc_driver.cpp
Enable propagating ProjectData members to:
1. derived QMCDriver classes
2. factory classes `create` functions 
Similar pattern to QMCDriversNew
Related to #3411 and #4099
- No
Ubuntu 22.04
=> Propagate ProjectData in QMCDrivers

src/QMCHamiltonians/ECPotentialBuilder.cpp, src/QMCHamiltonians/Listener.hpp, src/QMCHamiltonians/NLPPJob.h, src/QMCHamiltonians/NonLocalECPComponent.cpp, src/QMCHamiltonians/NonLocalECPComponent.h, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/NonLocalECPotential.h, src/QMCHamiltonians/NonLocalECPotential_CUDA.cpp, src/QMCHamiltonians/tests/CMakeLists.txt, src/QMCHamiltonians/tests/TestListenerFunction.h, src/QMCHamiltonians/tests/test_NonLocalECPotential.cpp
This is another MS6.9 PR.  Now adding per particle energy reporting to the NonLocalECPotential.
I removed the makeClone method for NonLocalECPComponent which makes no sense since it is never type erased, now a proper constructor takes its place which allows use of std::make_unique which makes more sense.
There is some questionable raw pointer use in NonLocalECPComponent that should be addressed at some point. I don't think this makes it worse but it still carries the potential to create a double free if there is a problem during copy construction or cloning.
Rather than add to the misnamed and legacy only integration testing in `test_ecp.cpp`. I added a closer to actual unit test test.
It also shows a real lack of sensistivity to the randomization of the pp grid which should perhaps …
=> Adding batched per particle value reporting for NonLocalECPotential

src/Estimators/EstimatorManagerBase.h, src/Estimators/EstimatorManagerCrowd.h, src/Estimators/EstimatorManagerNew.h, src/Estimators/ScalarEstimatorBase.h, src/QMCTools/QMCGaussianParserBase.cpp, src/QMCTools/QMCGaussianParserBase.h, src/QMCWaveFunctions/EinsplineSetBuilder.h, src/QMCWaveFunctions/EinsplineSetBuilderESHDF.fft.cpp, src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp, src/QMCWaveFunctions/PlaneWave/PWBasis.cpp, src/QMCWaveFunctions/PlaneWave/PWBasis.h, src/QMCWaveFunctions/PlaneWave/PWOrbitalBuilder.cpp
I removed `HDFNumericAttrib.h`, `HDFSTLAttrib.h`, and `HDFAttribIO.h` until the build failed. Then I refactored PWBasis to use hdf_archive.
This is part of https://github.com/QMCPACK/qmcpack/issues/4156.
- No
Ubuntu 20.04
_Update the …
=> Remove includes of obsolete hdf5 headers.

src/Estimators/EstimatorManagerBase.cpp, src/Estimators/EstimatorManagerBase.h, src/Estimators/EstimatorManagerNew.cpp, src/Estimators/tests/test_local_energy_est.cpp, src/QMCDrivers/CorrelatedSampling/CSVMC.cpp, src/QMCDrivers/DMC/DMC.cpp, src/QMCDrivers/RMC/RMC.cpp, src/QMCDrivers/VMC/VMC.cpp, src/QMCHamiltonians/tests/test_ObservableHelper.cpp, src/QMCWaveFunctions/PlaneWave/PWOrbitalBuilder.cpp, src/QMCWaveFunctions/PlaneWave/PWParameterSet.cpp, src/QMCWaveFunctions/PlaneWave/PWParameterSet.h
I refactored EstimatorManagerBase to use hdf_archive. I also tried replacing H5Fcreate and H5Fflush with hdf_archive::open and hdf_archive::flush, respectively.
This is part of #4156.
- Testing changes (e.g. new …
=> Refactor EstimatorManagerBase. Use hdf_archive in tests.

src/Message/CMakeLists.txt, src/Message/catch_main.cpp, src/QMCApp/QMCAppBase.cpp, src/QMCApp/QMCMain.h, src/QMCTools/convert4qmc.cpp, src/QMCTools/convertpw4qmc.cpp, src/QMCTools/qmc-extract-eshdf-kvectors.cpp, src/QMCTools/qmcfinitesize.cpp, src/Sandbox/restart.cpp, src/io/hdf/hdf_archive.cpp, src/io/hdf/hdf_archive.h, src/io/hdf/hdf_error_suppression.h, src/io/hdf/tests/CMakeLists.txt, src/io/hdf/tests/test_hdf_error_suppression.cpp
Moving error handling changes from `hdf_archive` to a separate `hdf_error_suppression` class. It suppresses HDF5 warnings throughout the lifetime of `QMCMain`.
I'd appreciate your input on this approach and any other required functionality before going further.
This fixes #4283.
- Bugfix
- Refactoring (no functional changes, no api …
=> Add hdf_error_suppression class

src/QMCWaveFunctions/BsplineFactory/BsplineSet.h, src/QMCWaveFunctions/BsplineFactory/SplineC2C.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineR2R.cpp, src/QMCWaveFunctions/EinsplineSet.cpp, src/QMCWaveFunctions/tests/eval_bspline_spo.py, src/QMCWaveFunctions/tests/test_einset.cpp
In the case of orbital rotation, the orbital set size from the H5 file may not match the number of SPOs used, which may not match the number of occupied orbitals.
In BsplineSet.h, the slices of the matrices need to have a size consistent with the size of the matrix.
In SplineR2R.cpp, use the size of psi rather than myV.  In the call to evaluate3d it doesn't matter because all the inputs are sized the same as myV, but in the following call to assign_*, the size discrepancy can cause invalid accesses.
Add a Python script for evaluating SPOs given the HDF file of coefficients.  It uses autograd to evaluate the spatial derivatives.
- Bugfix
- No
desktop …
=> Update handling of array sizes in SplineR2R and SplineC2C for rotation cases

src/QMCHamiltonians/CoulombPBCAA.h, src/QMCHamiltonians/Listener.hpp, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/QMCHamiltonian.cpp, src/QMCHamiltonians/QMCHamiltonian.h, src/QMCHamiltonians/tests/MinimalHamiltonianPool.h, src/QMCHamiltonians/tests/TestListenerFunction.h, src/QMCHamiltonians/tests/test_Listener.cpp, src/QMCHamiltonians/tests/test_QMCHamiltonian.cpp
API changes and additions to QMCHamiltonian to support per particle Listerners from Estimators.
Next PR will add an estimator that logs per particle values to illustrate the API's use.
- New feature
- No
=> QMCHamiltonian with Listener support

.github/workflows/ci-github-action-auto-rebase.yaml
I get an error from github workflows:
**Invalid workflow file: .github/workflows/ci-github-action-auto-rebase.yaml#L34**
The workflow is not valid. .github/workflows/ci-github-action-auto-rebase.yaml (Line: 34, Col: 30): Unrecognized named-value: 'QMCPACK_BOT_GPG_KEY'. Located at position 1 within expression: QMCPACK_BOT_GPG_KEY .github/workflows/ci-github-action-auto-rebase.yaml (Line: 51, Col: 30): Unrecognized named-value: 'QMCPACK_BOT_GPG_KEY'. Located at position 1 within expression: QMCPACK_BOT_GPG_KEY
It looks like QMCPACK_BOT_GPG_KEY should be in the secrets context (I checked and it does exist as a secret for the repo)
- Bugfix
- No
None
_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate …
=> Fix invalid workflow file message

src/QMCWaveFunctions/tests/gen_rotated_lcao_wf.py, src/QMCWaveFunctions/tests/run_qmc.py
Generalize the run_qmc function to an arbitrary number of electrons and extract it to a separate module.
Future validation code will use different wavefunctions and we want to reuse the run_qmc function.
The implementation of psi in the wavefunction needs to be split into two parts.  For generality, calling from run_qmc uses an array for all the electron positions.  Autograd is easier to use if each position is a separate argument.  The solution is to make psi a wrapper that extracts individual positions and calls the internal implementation.
- No
desktop
simply a reminder of …
=> Extract run_qmc to separate module

.github/workflows/ci-github-actions.yaml
The MacOS runners on GitHub Actions updated to Python 3.11. One of our dependencies, h5py, does not currently have a Python 3.11 wheel and is not successfully building from source. A new release with a new wheel is anticipated in a few weeks. See https://github.com/h5py/h5py/pull/2165 for more information.
In the meantime, I updated GitHub Actions to use Python 3.10 on …
=> Fix MacOS build, h5py failing to build.

src/QMCWaveFunctions/tests/CMakeLists.txt, src/QMCWaveFunctions/tests/eval_bspline_spo.py, src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp
The hcpBe test is the solid system with the fewest electrons (2), making it useful for validating orbital rotation with a 2x2 rotation matrix.
The test adds some point values for the system with unrotated and rotated orbitals.
The validation script adds support for this system, along with a wavefunction class usable with run_qmc.  (Eventually there will be tests using the output of run_qmc)
The convertPos function was simplified and corrected (the if-tests in the C++ code were only for a narrow special case, not a general less-than-zero case)
- No
desktop
simply a …
=> Orbital rotation test with hcp Be

src/Message/Communicate.cpp, src/Message/Communicate.h
Remove const_cast, replace by a single mutable tag.
In modern C++ an unprotected mutable member is a good indication of the context in which a class can be used. (Not usable when shared across threads).
- No
=> Make communicator member mutable

src/QMCHamiltonians/QMCHamiltonian.cpp, src/QMCTools/ppconvert/src/common/IO.cc, src/formic/utils/matrix.h
Cleanup for fewer warnings from gcc12, llvm15
IO.cc: fix the false warning from GCC12 about possible use of unitialized newSection
matrix.h: do not use deprecated std::iterator
QMCHamiltonian: remove warned about and seemingly not-needed std::move 
- No
nitrogen2, nightly gcc12 and llvm15 config
=> Fix warnings, small c++ updates

src/Message/Communicate.cpp, src/Message/Communicate.h
Remove spurious assignments that can be easily replaced by copy- (actually duplicate-) constructor.
The exact meaning of (re)assignment in BMPI3 communicator can change in the near future, so it is better to avoid it.
As well as two-phase construction in general.
- No
=> remove spurious assignment

src/AFQMC/Memory/HIP/hip_arch.cpp, src/AFQMC/Memory/HIP/hip_arch.h, src/AFQMC/Memory/HIP/hip_utilities.cpp, src/AFQMC/Memory/HIP/hip_utilities.h, src/AFQMC/Numerics/detail/HIP/Kernels/sampleGaussianRNG.hip.cpp, src/AFQMC/Numerics/detail/HIP/Kernels/sampleGaussianRNG.hip.h, src/AFQMC/Numerics/detail/HIP/hip_kernel_utils.cpp, src/AFQMC/Numerics/detail/HIP/hip_kernel_utils.h, src/AFQMC/Numerics/detail/HIP/hipblas_wrapper.hpp, src/AFQMC/Numerics/detail/HIP/hipsparse_wrapper.hpp, src/AFQMC/Numerics/detail/HIP/rocsolver_wrapper.hpp, src/Platforms/CUDA/cuBLAS.hpp, src/Platforms/CUDA_legacy/cuda_inverse.cu, src/Platforms/CUDA_legacy/gpu_misc.h, src/Platforms/ROCm/hipBLAS.hip.cpp, src/Platforms/ROCm/hipBLAS.hpp, src/Platforms/ROCm/hipblasTypeMapping.hpp, src/Platforms/ROCm/rocsolver.hpp, src/QMCWaveFunctions/detail/CUDA/cuBLAS_LU.hpp, src/QMCWaveFunctions/detail/CUDA_legacy/delayed_update.cu, src/QMCWaveFunctions/detail/CUDA_legacy/delayed_update.h
Use the modern, non-deprecated include style for hipblas and rocsolver. This fixes the current build warnings.
- New feature
- No
nitrogen, Radeon VII, ROCm 5.3.0
=> Modernize ROCm includes

src/Containers/MinimalContainers/ConstantSizeMatrix.hpp, src/Containers/MinimalContainers/tests/test_ConstantSizeMatrix.cpp, src/QMCDrivers/CloneManager.cpp, src/QMCDrivers/CloneManager.h, src/QMCDrivers/CorrelatedSampling/CSVMC.cpp, tests/solids/bccH_1x1x1_ae/CMakeLists.txt, tests/solids/bccH_1x1x1_ae/det_qmc_short_csvmc_all.in.xml
Allow increasing one dimension in ConstantSizeMatrix, as long the other dimension decreases to compensate and the new capacity is less than or equal to the existing capacity.
This fixes the WALKER_MAX_PROPERTIES error in the csvmc tests (#2509 and #2709).
(I got annoyed seeing the csvmc failures on cdash in the nightly tests.)
- Bugfix
- No
desktop
- Yes. This PR adds tests to cover any new code, or to catch a bug that …
=> Allow ConstantSizeMatrix to increase along a dimension

src/Utilities/Clock.cpp, src/Utilities/Clock.h, src/Utilities/NewTimer.cpp, src/Utilities/NewTimer.h, src/Utilities/tests/test_runtime_manager.cpp, src/Utilities/tests/test_timer.cpp
Replace timer based on gettimeofday with std::chrono timer (system_clock) in the profile timers.
Reasons:
1. I would like to add the event profile code, and it works better with std::chrono timers
2. Storing the start time as a double (since the epoch) loses precision - the elapsed time ends up being a small difference between large numbers.  This isn't as major an issue with aggregated profile data, but is noticeable in the event data.
3. Moves to a C++ standard API
The runtime manager was not switched in this PR, but could be changed in the future (and the the FakeCPUClock removed)
The test uses "chrono_literals" ( https://en.cppreference.com/w/cpp/header/chrono#Literals ), which uses C++ 11 user-defined literals ( https://en.cppreference.com/w/cpp/language/user_literal ).   The "1.1s" …
=> Use std::chrono clock in profile timers

.github/workflows/ci-github-actions.yaml
MacOS build is failing with the following error:
```
FAILED: src/io/OhmmsData/tests/test_io_ohmmsdata 
: && /usr/local/bin/g++-11 -fopenmp -foffload=disable -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -Wno-deprecated -Wvla -Wcomment -Wmisleading-indentation -Wmaybe-uninitialized -Wuninitialized -Wreorder -Wno-unknown-pragmas -Wno-sign-compare …
```
=> Use macos-11 image until macos-latest has xcode >= 14.1

src/Estimators/OneBodyDensityMatrices.cpp, src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp, src/Sandbox/determinant.hpp, src/Sandbox/einspline_spo.cpp, src/Sandbox/einspline_spo_nested.cpp, src/Sandbox/restart.cpp, src/Utilities/Clock.h
After the change to use std::chrono clocks, the include file for OpenMP is no longer needed in Clock.h.  However, several other files depend it being transitively included.  Add those includes where necessary.
Change was suggested #4334
- No
desktop
- Yes. Code …
=> Remove unused OpenMP include from Clock.h

nexus/lib/qmcpack_input.py
Add support for key inputs that control where data is stored and operated on.  Relevant operations are those that save memory by allocating work on the host/CPU instead of the GPU.  
Currently, the only two (common user) relevant points of control I've identified are 1) orbitals are stored/evaluated on CPU instead of GPU, 2) matrix inverse is performed on CPU instead of GPU.
- New feature
- No
Laptop
=> Nexus: add CPU/GPU flags for batched code

src/Estimators/LocalEnergyEstimator.cpp, src/Estimators/MomentumDistribution.cpp, src/Estimators/OneBodyDensityMatrices.cpp, src/Estimators/OperatorEstBase.cpp, src/Estimators/OperatorEstBase.h, src/Estimators/SpinDensityNew.cpp, src/QMCHamiltonians/DensityEstimator.cpp, src/QMCHamiltonians/DensityMatrices1B.cpp, src/QMCHamiltonians/EnergyDensityEstimator.cpp, src/QMCHamiltonians/ForceBase.cpp, src/QMCHamiltonians/LatticeDeviationEstimator.cpp, src/QMCHamiltonians/MomentumEstimator.cpp, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/ObservableHelper.cpp, src/QMCHamiltonians/ObservableHelper.h, src/QMCHamiltonians/OperatorBase.cpp, src/QMCHamiltonians/PairCorrEstimator.cpp, src/QMCHamiltonians/ReferencePoints.cpp, src/QMCHamiltonians/SkAllEstimator.cpp, src/QMCHamiltonians/SkEstimator.cpp, src/QMCHamiltonians/SpaceGrid.cpp, src/QMCHamiltonians/SpeciesKineticEnergy.cpp, src/QMCHamiltonians/SpinDensity.cpp, src/QMCHamiltonians/StaticStructureFactor.cpp, src/QMCHamiltonians/tests/test_ObservableHelper.cpp
Following on from some experimenting to review #4332 which got merged prior to my review. OperatorHelper is looking better but it would be nice to remove some ugly.
Remove single group path term convenience constructor. Remove unnecessary and potentially problematic default constructor. Remove need for a bunch of explicit construction of temporary `std::vector<std::string>`
Stop using unique pointer vectors in a unnecessary way in `OperatorEstBase` simplify things further.
- Refactoring (no functional changes, no api changes)  Well at least not much.
- No
Leconte …
=> Drop special case constructor from Observable Helper

src/Utilities/ModernStringUtils.cpp, src/Utilities/ModernStringUtils.hpp, src/Utilities/for_testing/NativeInitializerPrint.hpp, src/Utilities/tests/test_ModernStringUtils.cpp
Adds a strip and split function that support `string-view`
Existing code does not use this but it is required for #4299 
- New feature
- No
Leconte
=> Extending modern string utils to include split and strip

src/Sandbox/restart.cpp
We plan to include the restart sandbox example in h5bench. For that, we need to be able to define a directory prefix in which the files are created. This PR includes that option by adding `-d` to the restart code.
- Other (please describe): Adds a new optional parameter for the restart sandbox example.
- No
MacOS and Linux
- **Yes**/No. This PR is up to date with current the current state of 'develop'
- **Yes**/No. Code added or changed in the PR has been clang-formatted
=> include option to specify a directory for the restart sandbox test

nexus/lib/machines.py
Allow use of template strings for job submission scripts.  This bypasses the generation of such scripts by Nexus and instead Nexus just writes the user provided submission script template.  This broadens the set of such scripts beyond what Nexus is capable of generating and also adds convenience.
- New feature
- No
Workstation
=> Nexus: enable use of templates for job submission scripts

CMakeLists.txt, README.md, src/QMCHamiltonians/SkEstimator.cpp, src/QMCWaveFunctions/PlaneWave/PWParameterSet.cpp, src/io/hdf/hdf_archive.h, src/io/hdf/hdf_stl.h, src/io/hdf/hdf_wrapper_functions.h
Move QMCPACK to use the HDF5 1.10 API, released in 2016. 1.10 is available starting in Ubuntu 18.04 and RHEL 8 The 1.8 and 1.12 branches have their final patch releases in January 2023, so 1.10 seems to be the sweet spot.
I think this flag in 1.8 will let us use a [longer `std::string` instead of `std::vector<std::string>` in ObservableHelper]( …
=> Use HDF5 1.10 API

src/Particle/tests/CMakeLists.txt, src/Particle/tests/test_distance_table.cpp
More unit tests.
- No
epyc-server
=> Expand distance table unit tests to cover more BC.

src/Particle/VirtualParticleSet.cpp, src/Particle/VirtualParticleSet.h, src/QMCHamiltonians/ECPotentialBuilder.cpp, src/QMCHamiltonians/NonLocalECPComponent.cpp, src/QMCHamiltonians/NonLocalECPotential.deriv.cpp, src/QMCHamiltonians/SOECPComponent.cpp, src/QMCHamiltonians/SOECPComponent.h, src/QMCHamiltonians/tests/test_ecp.cpp, src/QMCWaveFunctions/tests/test_DiracDeterminant.cpp, src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp, src/QMCWaveFunctions/tests/test_J2_bspline.cpp, src/QMCWaveFunctions/tests/test_MO.cpp, src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp, src/QMCWaveFunctions/tests/test_polynomial_eeI_jastrow.cpp, tests/solids/bccMo_2x1x1_SOREP/Mo-vmc-dmc-long.in.xml, tests/solids/bccMo_2x1x1_SOREP/Mo-vmc-dmc-short.in.xml, tests/solids/bccMo_2x1x1_SOREP/Mo-vmc-long.in.xml, tests/solids/bccMo_2x1x1_SOREP/Mo-vmc-short.in.xml, tests/solids/bccMo_2x1x1_SOREP/det_Mo-vmc-dmc.in.xml, tests/solids/bccMo_2x1x1_SOREP/det_Mo-vmc.in.xml
This PR adds VirtualParticleSets to SOECPs. This essentially makes it so that we no longer have to add an additional keyword to run with SOECPs since it can now use the default batched path with virtual particles. 
Note that while this is only implemented in the legacy APIs, this actually enables SOECPs to be used in the batched code since the default behavior of OperatorBase is to fallback to a loop over single walker APIs. So effectively, we have a path to run using the batched code, although it won't be as efficient as the mw implementation (coming soon). 
I did a little refactoring in SOECP, and had to change the makeMoves API in VirtualParticleSet so that we also store the current electron spin...otherwise the NonLocalECP part was failing when spinors were enabled. 
I also updated …
=> Add VPs to SOECP

src/Particle/VirtualParticleSet.cpp, src/Particle/VirtualParticleSet.h, src/QMCHamiltonians/NLPPJob.h, src/QMCHamiltonians/NonLocalECPComponent.cpp, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/NonLocalECPotential.deriv.cpp, src/QMCHamiltonians/SOECPComponent.cpp, src/QMCHamiltonians/tests/test_ecp.cpp, src/QMCWaveFunctions/BsplineFactory/HybridRepCenterOrbitals.h, src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.h, src/QMCWaveFunctions/Jastrow/J1Spin.h, src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h, src/QMCWaveFunctions/Jastrow/TwoBodyJastrow.cpp, src/QMCWaveFunctions/tests/test_DiracDeterminant.cpp, src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp, src/QMCWaveFunctions/tests/test_J1_bspline.cpp, src/QMCWaveFunctions/tests/test_J2_bspline.cpp, src/QMCWaveFunctions/tests/test_MO.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp, src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp, src/QMCWaveFunctions/tests/test_polynomial_eeI_jastrow.cpp
It is better to update the reference ParticleSet whenever makeMoves happen.
- Refactoring
- No
laptop
=> Update reference ParticleSet handling in VirtualParticleSet

src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h, src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h
Getting llvm-link error in real builds with icpx due to unprotected reduction on complex in offload regions. 
- Bugfix
- No
sunspot
=> Protect complex reduction in real builds.

src/Platforms/SYCL/SYCLDeviceManager.cpp
Using OpenMP interop to directly create SYCL queue has a lot of limitations. Revert to the old way exposing only the Level0 device and context object.
- No
sunspot
=> Restore old interop scheme using level_zero.

src/Platforms/SYCL/SYCLDeviceManager.cpp, src/Platforms/SYCL/SYCLDeviceManager.h, src/Platforms/SYCL/SYCLruntime.cpp, src/QMCWaveFunctions/Fermion/DelayedUpdateSYCL.h
SYCL queue copy constructor only does shallow copy. Underlying level 0 objects are shared and caused performance penalty due to undesired entanglement.
Make actual queue creation from device and context instead of copying.
- Bugfix
- No
sunspot
=> Sycl queue created instead of copy

src/Particle/VirtualParticleSet.cpp, src/Particle/VirtualParticleSet.h, src/QMCHamiltonians/HamiltonianFactory.cpp, src/QMCHamiltonians/HamiltonianFactory.h, src/QMCHamiltonians/NonLocalECPComponent.cpp, src/QMCHamiltonians/tests/test_ion_derivs.cpp, tests/molecules/FeCO6_b3lyp_pyscf/det_vmcbatch_noj.in.xml
The modified [tests/molecules/FeCO6_b3lyp_pyscf/det_vmcbatch_noj.in.xml](https://github.com/QMCPACK/qmcpack/compare/develop...ye-luo:reorder-nlpp-construction?expand=1#diff-885d05f95457a4ab71dc3836cc4ac4f995423d4c4a9fb88a7167f1a8565b03f5)
triggers a bug caused by mismatch distance table counts in the gold VPset and cloned VPsets.
When NLPP gets constructed, VP has only 1 DT based on the particle set at that moment.
However Coulomb adds e-e DT and the table counts is 2 and thus the cloned ones have two DTs based on later state of the particle set. This triggers shared resource issue.
This PR changes to create VP based …
=> Reorder nlpp construction to near beginning

.github/workflows/ci-github-actions-self-hosted.yaml
Node.js 12 actions [will be deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
Moving to the latest available versions
github-status-action might still need a new release
CI actions
- No
Must be merged and tested on sulfur/nitrogen CI
=> Bump github actions versions

config/build_nersc_perlmutter.sh
I've been looking at compiling the CPU version on Perlmutter since Cori will be retired soon. The added script compiles the real and complex versions for CPU-only nodes. Some dependencies, such as LibXml2, are handled via spack as this is not provided by default.
I didn't have luck with GNU compilers and/or the `cc`, `CC` wrappers provided by NERSC. However, the `mpicc`, `mpic++` MPI wrappers with cray compile without problems.
For the real build, all unit tests pass. 99% of deterministic tests pass, and there are 5 fails related to HEG (see attached).
For the complex build, 2 unit tests are failing. For the deterministic case, 84% is passing. The fails are related to HEG + Gaussian basis bulk systems (see attached).
I didn't explore the GPU build yet.
- Build script changes
- No …
=> Compile script for Perlmutter CPU

src/Particle/ParticleSet.cpp, src/Particle/ParticleSet.h, src/Particle/ParticleSetPool.cpp, src/QMCHamiltonians/QMCHamiltonian.cpp
Rename expand ParticleSet::get to print and support particle count limit.
When NaN is detected, print all particle coordinates.
Also `--verbosity=debug` now prints all particle coordinates.
- New feature
- No
laptop
=> Print coordinates when NaN is detected

src/QMCWaveFunctions/Jastrow/BsplineFunctor.cpp, src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.cpp, src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.h, src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp, src/QMCWaveFunctions/Jastrow/TwoBodyJastrow.cpp, src/QMCWaveFunctions/Jastrow/TwoBodyJastrow.h, src/QMCWaveFunctions/WaveFunctionComponent.h, tests/solids/NiO_a4_e48_pp/CMakeLists.txt, tests/solids/NiO_a4_e48_pp/det_NiO-batched-vmc-splitJ1.in.xml
Make J1 with partial elements to work and issue warnings when it happens.
- Bugfix
- No
epyc
=> Fix offload when partial J1 is specified

src/Platforms/CUDA/cuBLAS_missing_functions.cu, src/QMCWaveFunctions/BsplineFactory/SplineC2R.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2R.h, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h, src/QMCWaveFunctions/EinsplineSetBuilderESHDF.fft.cpp, src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h, src/QMCWaveFunctions/tests/CMakeLists.txt, src/QMCWaveFunctions/tests/test_einset.cpp, src/QMCWaveFunctions/tests/test_einset_NiO_a16.cpp
There is bug when using offload real build.
This caused writing to undesired memory locations and wrong numbers (crazy high variance/energy >>1)
- Bugfix
- No
epyc-server
=> Fix wrong output size in SplineC2ROMPTarget::mw_evaluateVGLandDetRatioGrads

CMakeLists.txt
Added check for when MPI is disabled but the parallel HDF5 library was found. This results in an error due to incompatibility, since the parallel HDF5 library cannot be used without MPI.
Closes #4370 
- No
Ubuntu 22.04
=> Add check for using parallel hdf5 in non-mpi build

src/einspline/multi_bspline_cuda_c_impl.h, src/einspline/multi_bspline_cuda_d_impl.h, src/einspline/multi_bspline_cuda_s_impl.h, src/einspline/multi_bspline_cuda_z_impl.h
This PR switches the GridDim.x and GridDim.y for eval_multi_multi_UBspline_3d_c_vgl_kernel to fix the issue that "num" can be larger than 65535, which is the maximum GridDim.y allowed in CUDA.
- Bugfix
- No
A100.
=> fix grid dim bug for eval_multi_multi_UBspline_3d_c_vgl_kernel

CMakeLists.txt
Added find_package call and meaningful error message.
Closes #4372 
- No
Ubuntu 22.04
=> Check for OpenMP compiler support

src/QMCWaveFunctions/tests/CMakeLists.txt
Per @rcclay 's request to use those classes outside the current testing folder.
Use `target_link_libraries(YOUR_TEST PUBLIC sposets_for_testing)` in intended locations.
- No
epyc-server
=> Add sposets_for_testing CMake target ConstantSPOSet FakeSPO

src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp, src/QMCWaveFunctions/RotatedSPOs.h, src/QMCWaveFunctions/SPOSet.h
These functions are specific to RotatedSPOs.  Use a dynamic_cast to get the right type and call buildOptVariables.
Requested in https://github.com/QMCPACK/qmcpack/pull/4426#discussion_r1091405773
- No
desktop
=> Remove buildOptVariables from SPOSet

src/QMCWaveFunctions/RotatedSPOs.cpp, tests/molecules/He_param/CMakeLists.txt, tests/molecules/He_param/He_orb_rot_param_grad_rhf.xml
Accumulate the derivatives in the case where multiple wavefunction pieces are controlled by the same variational parameter.
The fixes the single determinant case.  The multi-determinant case should work as it uses accumulation already.
The input file has no initial rotation (no "opt_vars" elements).  These don't work correctly in the RHF case, as the rotation ends up being applied twice.  (I don't think there's an easy way to fix this, and it doesn't seem like an important case to fix.  For normal usage, initial rotations will be read in from a VP file.)
Some of the other single-determinant derivative functions related to ECP's aren't changed, and I don't know if they need to be - will need to look into that separately.
- Bugfix
- No
desktop
_Update …
=> Fix orbital rotation RHF parameter derivatives

src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp, src/QMCDrivers/WFOpt/QMCCostFunctionBatched.h
For batched optimization, construct the crowd data in correlatedSampling in addition to checkConfigurations. The previous code would construct it in checkConfigurations and reuse the crowd data in correlatedSampling.
This simplifies changes to the variational parameters in the wavefunction, as the reset parameters call only needs to be performed on the gold copy.
Suggested in https://github.com/QMCPACK/qmcpack/pull/4426#discussion_r1095028360
- No
desktop …
=> Construct crowd data before each use in the batch optimizer

src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp
Affecting >512 splines. Caught by NiO a64 in complex build. 384 complex orbitals, 768 splines.
https://cdash.qmcpack.org/CDash/testDetails.php?test=25095055&build=396449
The error message is invalid memory access but the root cause was bad orbital values caused NaN in electron positions.
- Bugfix
- No
epyc-server
=> Fix spline block offset caused by #4439

src/Estimators/EstimatorManagerNew.cpp, src/Estimators/OneBodyDensityMatrices.h, src/QMCHamiltonians/OperatorBase.h, src/QMCWaveFunctions/SPOSet.h, src/QMCWaveFunctions/SPOSetBuilder.h, src/QMCWaveFunctions/SPOSetBuilderFactory.h, src/QMCWaveFunctions/SPOSetScanner.h, src/QMCWaveFunctions/TrialWaveFunction.h
While working on #4428, I got annoyed that SPOMap was defined all over the place if it needed changing.  While I don't think the definition will need to ultimately change, I wanted to consolidate all the definitions.
- No
desktop
- N/A Documentation has been added (if appropriate)
=> Make one definition of SPOMap

tests/performance/NiO/CMakeLists.txt
Add a single threaded version of the current 4 thread NiO performance tests when offload enabled. Help debug and monitor performance of mulithread offload compilers and runtimes.
- No
nitrogen2, amdclang, rocm 5.4.2
=> Add single thread offload NiO performance tests

src/QMCApp/QMCAppBase.cpp, src/QMCApp/QMCAppBase.h, src/QMCApp/QMCMain.cpp, src/QMCApp/QMCMain.h, src/QMCTools/QMCFiniteSize/QMCFiniteSize.cpp
Rename protected and private members
Eliminate one #ifdef QMC_COMPLEX in QMCMain class
Clean unused member in QMCMain
Related to #3411 #4099
- No
Ubuntu 22, must pass CI variants
=> Rename QMCAppBase and QMCMain members and one ifdef QMC_COMPLEX

src/QMCApp/QMCAppBase.h, src/QMCApp/QMCMain.h
clang 15 complains.
- Bugfix
- No
epyc-server
=> Fix clang warning about non-virtual destructor

src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp, src/QMCWaveFunctions/LCAO/LCAOrbitalSet.h, src/QMCWaveFunctions/SPOSetBuilder.cpp, src/QMCWaveFunctions/tests/test_RotatedSPOs_LCAO.cpp
A copy of the coefficient matrix is used for orbital rotation.
Change the copy to use a shared pointer.  This means the rotation only needs to be performed on one thread (and should be performed only on one thread).
The storage for the coefficient copy is used regardless of the setting of `use_stored_copy`. That means `storeParamsBeforeRotation` needs to be called once sometime before `applyRotation` is called.
The `use_stored_copy` flag changes which values get used - true uses the values in the copy and false uses the values in the existing coefficients.
- New feature
- No
desktop
simply a reminder of what we are going to look …
=> Used shared pointer for LCAO coefficient matrix copy

src/QMCWaveFunctions/BsplineFactory/SplineR2R.cpp, src/QMCWaveFunctions/BsplineFactory/SplineR2R.h, src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp, src/QMCWaveFunctions/tests/test_einset.cpp
This is the bspline version of #4468.
Bsplines did not previously keep a copy of the coefficients.   The copy of the coefficients performs two functions. First it allocates storage for the matrix multiplication in applyRotation (it replaces `new_coefs` for this purpose). Second, it allows using the global rotation method with bsplines.
- New feature
- No
desktop
- Yes. This PR adds tests to cover any new code, or to …
=> Store copy of bspline coefficients for orbital rotation

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp, src/QMCWaveFunctions/RotatedSPOs.cpp, src/QMCWaveFunctions/RotatedSPOs.h, src/QMCWaveFunctions/SPOSetBuilder.cpp, src/QMCWaveFunctions/tests/test_RotatedSPOs_LCAO.cpp
Change how rotation interacts with the optimizer to enable orbital rotation.
The method for tracking the rotation - history list versus global rotation - uses the "method" attribute on the "rotated_spo" tag.  The choices are "global" and "history", and the default is "global".
Note that the history method with the legacy driver and more than one thread does not work.  I couldn't figure out how to easily get all the information in one place to make the check and throw an error.  Given the default method is global rotation, and that does work with the legacy driver and multiple threads, this is going to take some effort to encounter.
* Batched driver
* With the changes in #4440, the batched driver only ever operates on one copy.
* Legacy driver
* global rotation - the state is kept in the …
=> Enable orbital rotation

examples/afqmc/01-neon_atom/README.rst
Correct the `.dat` filename in the first AFQMC tutorial from `qmc.scalar.s000.dat` to `qmc.s000.scalar.dat`.
- No
=> docs(): correct the wrong .dat filename in the afqmc tutorial

docs/methods.rst
Necessary info must be exposed to users.
- No
epyc
=> Document how the trial energy is updated.

docs/output_overview.rst, src/Particle/HDFWalkerInput_0_4.cpp, src/Particle/HDFWalkerOutput.cpp, src/Particle/HDFWalkerOutput.h, src/Particle/WalkerConfigurations.cpp, src/Particle/WalkerConfigurations.h, src/io/hdf/HDFVersion.h, tests/io/restart/qmc_short.restart.xml, tests/io/restart_batch/qmc_short_batch.restart.xml
Saves the walker weights following the same pattern used to save the particle positions.
This fixes #4157
- New feature
- No
simply a reminder of what we …
=> Save walker weights in HDF5 files

docs/analyzing.rst, nexus/bin/qdens-radial, nexus/lib/observables.py, nexus/sphinx_docs/user-scripts.rst
While I was trying to compare the charge densities obtained from `pwscf` versus `qmcpack`, I noticed that the charge density object in `qdens-radial`  uses `change_distance_units` to go from (e/Bohr^3) to (e/Ang^3) so that the overall integrated charge density is equal to N_e. Although the right density is obtained, I believe this is due to a double error, one in the definition of `change_distance_units` and one in the usage. In addition, the `change_distance_units` seems to be incorrectly transforming the grid points, thus `change_density_units` must be called instead (leaving the grid points untouched).
In addition to the above changes, `plot_radial_density` was modified to show the density units and a documentation section was added for `qdens-radial` thus closing #3590. The …
=> Fix units in qdens-radial and add documentation

src/QMCDrivers/SimpleFixedNodeBranch.cpp
Revert #4486 which was doing more than it should.
- Bugfix
- No
bora
=> Remove the error trap which blocks DMC->any QMC restart in classic drivers

src/Particle/MCWalkerConfiguration.cpp, src/Particle/SampleStack.cpp, src/Particle/SampleStack.h, src/Particle/tests/test_sample_stack.cpp, src/QMCDrivers/LMYEngineInterface/LMYE_QMCCostFunction.cpp, src/QMCDrivers/LMYEngineInterface/LMYE_QMCCostFunctionBatched.cpp, src/QMCDrivers/WFOpt/QMCCostFunction.h, src/QMCDrivers/WFOpt/QMCCostFunctionBatched.h, src/QMCDrivers/tests/QMCDriverNewTestWrapper.h, src/QMCDrivers/tests/test_QMCDriverNew.cpp
Refactoring SampleStack while working on #4493. I changed `sample_vector_` to hold values instead of pointers and deleted an unused member function. 
- No …
=> Remove raw owning pointers in SampleStack

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/config_ornl-nitrogen.sh, tests/test_automation/github-actions/ci/run_step.sh, tests/test_automation/github-actions/ci/run_step_ornl-nitrogen-1.sh
After system upgrades on nitrogen this PR reinstates ROCm jobs to CI
Starts refactoring CI for a cleaner separation of runner workflow steps
Move steps from run_step.sh to run_step_ornl-nitrogen-1.sh Update from Clang13 to Clang15
Add configuration file for LLVM and CMake deps
Tested locally
- No
ornl-nitrogen, must pass GitHub Actions workflows CI
- No. Code added …
=> Reinstate ornl-nitrogen-1 CI ROCm jobs

src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp, src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp
This PR fixes a bug I noticed as I was implementing the mw_XXXWithSpin APIs for MSD wave functions. It looks like when I initially did the unit tests for MultiSlaterDetFast, I forgot to add reference values for the spin gradients. Later on, there was renaming/refactoring from MultiSlaterDetFast into MultiSlaterDetTableMethod which introduced a bug into evalGradWithSpin (essentially returning 0 for the spin gradient). This bug was not caught by the unit tests because I seemingly overlooked adding the reference values for the spin gradient. 
This PR adds the correct values into the test for the spin gradient (coming from …
=> bugfix for MSD with spins and add mw_ tests

src/Particle/MCSample.h, src/QMCDrivers/MCPopulation.cpp, tests/io/CMakeLists.txt, tests/io/restart_dmc/C.BFD.xml, tests/io/restart_dmc/check.sh, tests/io/restart_dmc/det_qmc_vmcbatch_dmcbatch_tm.in.xml, tests/io/restart_dmc/det_qmc_vmcbatch_dmcbatch_tm.restart.xml, tests/io/restart_dmc/pwscf.pwscf.h5
This fixes #4493.
This add a dmc_batched restart test. "debug_disable_branching" is set to yes so that the walker weights are not all equal to 1.
To get this working, `weight` needed to be added to MCSample. In `MCPopulation::saveWalkerConfigurations(...)` I worked around `ParticleSet` not containing weights, but using both `walker_elec_particle_sets_` and `walkers_` …
=> Add restart_dmc test with nontrivial walker weights.

src/QMCTools/LCAOHDFParser.cpp, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.h, src/QMCWaveFunctions/LCAO/LCAOrbitalBuilder.cpp, src/QMCWaveFunctions/LCAO/RadialOrbitalSetBuilder.h
Hdf5 wrapper `read` has built-in error checking which is duplicated in other places if the lower level `readEntry` is used. This PR replaces some `readEntry` with `read`.
- No
Workstation 
=> Remove unnecessary hdf5 error checking

docs/conf.py, docs/developing.rst
A fix and a couple of updates to the development guide. 
First much of the C++ code was actually receiving generic python highlighting which looks just terrible.
In Restructured text, the format sphinx uses, with sphinx being the code what renders the manual now both locally and for `readthedocs` you actually need to specify the language you want syntax highlighting for in a block of code.  You can also set a default for a context.  Here I set the default for the `developing.rst` to be c++.
I've also revised some of the text around encapsulation. And removed reference to an exception being made for the use of c style casts.  I don't think there is or should be one.
- Bugfix
- No
mac laptop
_Update the following with a yes where …
=> fix code hightlighting default in devloping section. upd copyright

src/QMCHamiltonians/CoulombPBCAA.cpp
Fixes #4546.
- Bugfix
- No
epyc-server
=> Change coulomb safeguard printout to uniform error

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step_ornl-sulfur-2.sh
Current CI using oneAPI is unstable, these changes attempt to move CI to a green (all tests pass) status.
Remove ornl-nitrogen-2 (not used)
Switch oneAPI+CUDA12 (unstable) to GCC11+CUDA12 on ornl-sulfur-2
- No
=> Refactor ornl sulfur and nitrogen CI

CMake/ClangCompilers.cmake
We test compile `-fdisable-host-devmem` see https://github.com/ROCm-Developer-Tools/aomp/issues/526 for the reason.
AMDGPU_DISABLE_HOST_DEVMEM can be used to override the behavior.
- No
epyc
=> Introduce -fdisable-host-devmem option for upcoming AOMP/ROCm compilers

codecov.yaml
Try to avoid coverage failure reports until both real + complex builds have reported. Docs are at https://docs.codecov.com/docs/notifications#preventing-notifications-until-after-n-builds
- No
None.
None relevant
=> Update codecov configuration to notify after 2 builds

src/QMCWaveFunctions/RotatedSPOs.cpp, src/QMCWaveFunctions/RotatedSPOs.h, src/QMCWaveFunctions/SPOSet.h, src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp
Implement write/readVariationalParameters for orbital rotation.
The parameters associated with either global rotation or a history list are stored to the VP HDF file.
The parameters in myVars are also saved so the first call to resetParameters works correctly.  The first call occurs in WaveFunctionFactory::buildTWF after the VP file is read.   By "works correctly" , I mean the parameters set in myVars and the parameters in read into VariableSet match, so the change in parameters in RotatedSPOs::resetParametersExclusive is zero, and that causes no change to the carefully restored rotation matrices.
There are unit tests that do minimal testing of the code paths.  There will need to be more complete tests of this functionality.
- New feature
- No
desktop …
=> Read and write orbital rotation parameters

src/QMCWaveFunctions/RotatedSPOs.cpp, src/QMCWaveFunctions/tests/test_RotatedSPOs_LCAO.cpp
Disabled variational parameters will return -1 from a call to `myVars.where`, leading to an out-of-bounds array access.  This PR adds a check to avoid this situation.
Variational parameters can be disabled due to choosing a variational subset.  
Also in the case of a RHF wavefunction where there are different numbers of spin up/down electrons, there will be a different number of rotation parameters for each spin.  At a higher level of managing the parameters, this case is not being handled correctly, but this fix will stop it from segfaulting on invalid array access in the meantime.
- Bugfix
- No
desktop
simply a reminder of what …
=> Handle disabled variational parameters in rotation derivatives

.readthedocs.yaml
https://github.com/urllib3/urllib3/issues/2168#issuecomment-1536456946
It looks like a dependency finally reached EOL, comment in the thread suggests adding this config should resolve the readthedocs builds failing.
Bugfix #4587 
- No
-- needs to be tested on readthedocs build server --
- N/A. Code added or changed …
=> update runtime env to fix read the docs

tests/io/restart_batch/qmc_short_batch.in.xml, tests/io/restart_batch/qmc_short_batch.restart.xml
Restrict to total_walkers=16 which avoids memory pressure when running 8 ranks.
- No
epyc-server
=> Reduce restart_batch memory consumption when running 8r-2t.

.github/workflows/ci-github-actions-self-hosted.yaml
Remove current warnings in ornl CI e.g. bottom of [4911124265 log](https://github.com/QMCPACK/qmcpack/actions/runs/4911124265) 
Follow use of [env variable $GITHUB_OUTPUT](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
- No
N/A, must pass ornl CI after merge
=> Replace set-output in GitHub Actions

CMake/ClangCompilers.cmake
`-fopenmp-assume-no-nested-parallelism` and `-fopenmp-assume-no-thread-state` reduce shared memory and register usage. I don't see performance impact on NVIDIA but they do seem to get AMD a bit better.
- No
Summit
=> Automatically apply additional clang offload optimization flags.

nexus/.readthedocs.yaml, nexus/sphinx_docs/requirements.txt
Fix the Nexus configuration on rtd so that the Nexus documentation and not QMCPACK documentation is produced. https://nexus-workflows.readthedocs.io/en/latest/
rtd configuration updated online to read nexus/.readthedocs.yaml
- Bugfix
- No
None. Will need checking in CI, may require merge.
=> Fix Nexus rtd configuration

docs/installation.rst, src/QMCTools/ppconvert/CMakeLists.txt
CrayLinuxEnvironment is considered cross-compiling. Thus try_run requires user input and stop.
Consider ppconvert is not critical, simply turn it off by default.
QMC_ISNAN option can be used to override the detection.
- No
Frontier/Crusher
=> Introduce ENABLE_PPCONVERT option and skip ppconvert compilation when cross compiling.

src/Estimators/EstimatorManagerBase.cpp, src/QMCWaveFunctions/BsplineFactory/BsplineReaderBase.cpp, src/QMCWaveFunctions/Fermion/BackflowBuilder.cpp, src/Utilities/ProgressReportEngine.cpp, src/Utilities/ProgressReportEngine.h, src/Utilities/SimpleParser.cpp, src/Utilities/SimpleParser.h
Replace the unsafe function `sprintf` with `snprintf` or streams. 
This is part of #4438.
- No
my laptop, Ubuntu 20.04
_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask. …
=> Use snprintf or std::cout instead of sprintf.

external_codes/catch/Readme, external_codes/catch/catch.hpp
Update Catch2 to v2.13.9, the most recent before breaking changes in v3.0.1
This patch was applied to eliminate warnings from `sprintf`
https://github.com/catchorg/Catch2/commit/0e2895934cf778f3bd7e84b3df10dac81d4ef7e3
This is part of https://github.com/QMCPACK/qmcpack/issues/4438.
- Testing changes (e.g. new …
=> Update Catch2 to v2.13.9. Remove sprintf

src/Estimators/EstimatorManagerBase.cpp, src/Estimators/EstimatorManagerNew.cpp, src/Estimators/TraceManager.h, src/Particle/HDFWalkerInput_0_4.cpp, src/QMCApp/qmcapp.cpp, src/QMCHamiltonians/MPC.cpp, src/QMCTools/ppconvert/src/NLPPClass.cc, src/QMCWaveFunctions/BsplineFactory/BsplineReaderBase.cpp, src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp, src/QMCWaveFunctions/EinsplineSetBuilderESHDF.fft.cpp, src/QMCWaveFunctions/EinsplineSetBuilderOld.cpp, src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp, src/QMCWaveFunctions/Fermion/BackflowBuilder.cpp, src/Sandbox/ParticleIOUtility.cpp, src/Utilities/SimpleParser.cpp, src/Utilities/TimerManager.cpp, src/io/OhmmsData/Libxml2Doc.cpp
Cleaning up earlier attempts to use `std::snprintf` with lessons learned through completing #4438. Mostly using `std::array` instead of a c-style array and a separate size variable and checking the return value from the function. Also found a few places where `std::string_view` may avoid a call to `strlen`
- Code style update …
=> Cleanup snprintf calls with lessons learned

tests/molecules/Be_STO/CMakeLists.txt
Some fixes for #4619:
1. Check correct series number.
2. Skip test for mixed precision builds.
- Bugfix
- No
desktop
=> Fix Be orbital optimization test

src/QMCHamiltonians/OrbitalImages.cpp
A simpler alternative to https://github.com/QMCPACK/qmcpack/pull/4617
- Bugfix
- No
laptop
=> Fix sposet_indices missing construction in OrbitalImages.

nexus/lib/qmcpack_input.py, src/Particle/ParticleIO/XMLParticleIO.cpp
This PR should fix #4630. Nexus will no longer write the spin channels if they are empty.
- Bugfix
- No
NERSC/Perlmutter: All Nexus tests are passing.
=> Handle the special case of empty spin channels in Nexus

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp
Segfault occurs in RotatedSPOs when evaluating parameter derivatives for a wavefunction with multiple determinants.
- Bugfix
- No
=> Fix segfault with orbital rotation and multiple determinants

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.2.cpp, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.h
Fixes #4639
- Bugfix
- No
laptop
=> Fix MSD when there is only 1 det in a given spin channel.

docs/analyzing.rst, nexus/bin/qdens
The `spindensity` estimator can define arbitrary regions in space for density to be sampled. So far, `qdens` ignored these parameters if they were present in the qmcpack input, resulting in an incorrect `*.xsf` density output. This PR implements this missing feature in `qdens` and adds the documentation. This is currently handled for the `*.xsf` type file only, as I am unfamiliar with the `chgcar` format.
- Bugfix
- New feature
- No
NERSC/Perlmutter: All Nexus tests are passing.
- Yes. This PR is up to date with the current state of 'develop'
=> Allow the use of "cell" and "corner" parameters in spindensity qdens analysis

nexus/lib/pwscf_postprocessors.py
Small fix to properly read namelist input.  Previously failed if there was a dangling comma.
- Bugfix
- No
Workstation
=> Nexus: fix namelist read for Projwfc input

nexus/bin/qdens, nexus/lib/qmcpack_input.py
This PR updates the `qdens` tool to process density data produced by the batched code.  Updates were needed to handle the new style placement of estimators in the QMCPACK input file.
- Bugfix
- No
Workstation
=> Nexus: update qdens to handle batched driver input/output

docs/methods.rst, src/Particle/HDFWalkerOutput.h, src/QMCDrivers/CorrelatedSampling/CSVMC.cpp, src/QMCDrivers/DMC/DMC.h, src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/DMC/DMCDriverInput.h, src/QMCDrivers/QMCDriver.cpp, src/QMCDrivers/QMCDriver.h, src/QMCDrivers/QMCDriverInput.cpp, src/QMCDrivers/QMCDriverInput.h, src/QMCDrivers/QMCDriverNew.cpp, src/QMCDrivers/RMC/RMC.cpp, src/QMCDrivers/VMC/VMC.cpp, src/QMCDrivers/VMC/VMCBatched.cpp, src/QMCDrivers/tests/test_dmc_driver.cpp, src/QMCDrivers/tests/test_vmc_driver.cpp
This PR aims to simplify and improve the checkpointing process.
As mentioned in https://github.com/QMCPACK/qmcpack/issues/4633 the documented every N blocks checkpointing feature was not working as expected. In legacy, this required storeconfigs to also be specified to work (undocumented/unexpected).  Checkpointing was also not implemented in the batched drivers.
Here:
- checkpoint={-1,0,N} driver parameter option sufficient to control checkpointing
- Default changed to checkpoint=0. Configs will be written at the end of each QMC section by default. -1 disables. N sets write period in addition to end of section write.
- Removed storeconfigs option completely.
- Implemented checkpointing in batched code.
- Updated docs appropriately
Have verified by eye that the checkpoints look sensible …
=> Simplify checkpointing, change defaults, fix legacy, implement in batched

nexus/lib/qmcpack_input.py
Adds the crowds_serialize_walkers tag to the dmc input list in nexus.
- New feature
- No
macOS Monterey 12.6.3, Python 3.9.13
=> Nexus: Adding crowds_serialize_walkers tag to dmc input list

config/build_alcf_sunspot_icpx.sh, src/Platforms/SYCL/SYCLDeviceManager.cpp
It seems that matrix inversion in MKL fails when using default out-of-order queue. Switching to in-order queues makes `test_syclSolverInverter.cpp` to pass reliably. In-order queues add less burden on GPU runtime and should have lower latency. QMCPACK uses multiple queues and doesn't really need out-of-order queue to gain kernel parallelism.
- Bugfix
- No
sunspot
=> Use SYCL in-order queue.

src/QMCWaveFunctions/LCAO/CuspCorrectionConstruction.cpp, src/QMCWaveFunctions/LCAO/CuspCorrectionConstruction.h, src/QMCWaveFunctions/LCAO/LCAOrbitalBuilder.cpp, src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp, src/QMCWaveFunctions/LCAO/LCAOrbitalSet.h, src/QMCWaveFunctions/LCAO/LCAOrbitalSetWithCorrection.cpp, src/QMCWaveFunctions/LCAO/LCAOrbitalSetWithCorrection.h, src/QMCWaveFunctions/LCAO/SoaCuspCorrection.h, tests/molecules/H_positron/CMakeLists.txt
#4660 was caused by LCAOrbitalSet as base of LCAOrbitalSetWithCorrection.
SPOSet - > LCAOrbitalSet -> LCAOrbitalSetWithCorrection The 2 generation of inheritance is simply wrong. @PDoakORNL criticized a lot and I I agree. See all the overriding functions in LCAOrbitalSetWithCorrection that I removed in this PR. They are basically saying LCAOrbitalSetWithCorrection is not a LCAOrbitalSet.
SPOSet.cpp has a virtual mw_evaluateVGL. It also implements a fallback. LCAOrbitalSet has a specialization but LCAOrbitalSetWithCorrection doesn't. When running LCAOrbitalSet::mw_evaluateVGL gets used, and caused NaN.
Why NaN? All the 5 basis of the test case are S orbitals and S orbitals are removed by cusp correction. So orbitals evaluated by LCAOrbitalSet::mw_evaluateVGL was zero and caused NaN. In a …
=> Make LCAOrbitalSet a member of LCAOrbitalSetWithCorrection

nexus/lib/numerics.py
Closes #4670 
This looks to be a trivial fix ; vertices was removed in scipy 1.11.0 https://docs.scipy.org/doc/scipy/release/1.11.0-notes.html#expired-deprecations . However I did not yet find the version when simplices was introduced - is it old enough?
- Bugfix
- No
sulfur, nightly config
=> Nexus: Use simplices in convex_hull

CMakeLists.txt, src/Platforms/ROCm/cuda2hip.h, src/Platforms/tests/CUDA/test_CUDAallocator.cpp, src/config.h.cmake.in
Since rocm 5.6. hipHostRegister becomes terribly slow https://github.com/ye-luo/miniqmc/wiki/hip-hsa-issues.
Introduce QMC_DISABLE_HIP_HOST_REGISTER. which can be used to make hipHostRegister no-op.
I set it ON by default for now. Will go through a few nights of performance test runs.
My guess is that it makes runs slower because we lose more from not using pinned memory than slower hipHostRegister in close  to production benchmarks.
- No
epyc-server
=> Introduce QMC_DISABLE_HIP_HOST_REGISTER. ON by default.

CMake/IntelCompilers.cmake, src/Platforms/CPU/CMakeLists.txt, src/QMCTools/ppconvert/CMakeLists.txt
icpx has `-ffast-math` on by default. There's no harm adding it and it helps aligning behaviors with Clang and GNU.
- Bugfix
- No
sunspot
=> Make Intel LLVM compiler to pass qmcplusplus::isnan tests.

src/CMakeLists.txt, src/Estimators/CMakeLists.txt, src/Estimators/tests/CMakeLists.txt, src/Estimators/tests/test_EstimatorManagerCrowd.cpp, src/Estimators/tests/test_MomentumDistribution.cpp, src/Estimators/tests/test_PerParticleHamiltonianLogger.cpp, src/Estimators/tests/test_SpinDensityNew.cpp, src/Particle/ParticleBase/tests/CMakeLists.txt, src/QMCDrivers/CMakeLists.txt, src/QMCDrivers/DMC/DMC.cpp, src/QMCDrivers/DMC/DMC.h, src/QMCDrivers/DMC/DMCFactory.cpp, src/QMCDrivers/VMC/VMC.cpp, src/QMCDrivers/VMC/VMC.h, src/QMCDrivers/VMC/VMCFactory.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp, src/QMCDrivers/tests/CMakeLists.txt, src/QMCDrivers/tests/test_clone_manager.cpp, src/QMCDrivers/tests/test_dmc_driver.cpp, src/QMCDrivers/tests/test_vmc_driver.cpp, src/QMCHamiltonians/CMakeLists.txt, src/Utilities/RandomGenerator.h
A big thank to @quantumsteve 
No more redundant compilation of qmcham qmcdriver qmcestimators.
Closes #3700.
- No
epyc-server
=> Remove xxx_unit cmake targets

src/Concurrency/ParallelExecutorOPENMP.hpp, src/QMCApp/QMCMain.cpp, src/QMCHamiltonians/CoulombPotentialFactory.cpp, src/QMCHamiltonians/ECPComponentBuilder.1.cpp, src/QMCHamiltonians/ECPComponentBuilder.h, src/QMCHamiltonians/ECPComponentBuilder_L2.cpp, src/QMCHamiltonians/MPC.cpp, src/QMCHamiltonians/MPC.h
Address #4681 in a few places.
a) bug fix in Concurrency/ParallelExecutorOPENMP.hpp
b) clean up the MPC class
c) Remove dead ECPComponentBuilder::createVrWithData
- Bugfix
- No
epyc-server
=> Correct app_error usage

config/build_alcf_sunspot_icpx.sh, src/Platforms/SYCL/syclSolver.hpp, src/QMCWaveFunctions/Fermion/DelayedUpdateSYCL.h
If we don't proactively poking MKL, memory free() happens when unloading the dynamic library and causes segfault.
PS: Update sunspot recipe.
- Bugfix
- No
sunspot
=> Free MKL reserved memory before the SYCL queue destruction.

src/QMCWaveFunctions/tests/CMakeLists.txt, src/QMCWaveFunctions/tests/construct_rot.py, src/QMCWaveFunctions/tests/read_qmcpack.py, src/QMCWaveFunctions/tests/rot_Be_STO.wfnoj.xml, src/QMCWaveFunctions/tests/rot_be_sto_wf.py, src/QMCWaveFunctions/tests/rot_multi_1det_Be_STO.wfnoj.xml, src/QMCWaveFunctions/tests/rot_multi_2det_Be_STO.wfnoj.xml, src/QMCWaveFunctions/tests/rot_multi_be_sto_wf.py, src/QMCWaveFunctions/tests/slater_orbitals.py, src/QMCWaveFunctions/tests/test_RotatedSPOs_LCAO.cpp
Test case is a Be atom with an STO basis set.  Basis set and MO matrix are taken from https://github.com/QMCPACK/qmcpack/blob/develop/tests/molecules/Be_STO/partial_opt_Be_STO.wfnoj.xml
Python scripts compute reference values for the test cases:
1. single determinant
2. multi-determinant code path with one determinant (same values as 1)
3. multi-determinant code path with two determinants
For ease of using autodiff, the skew-symmetric matrix that goes into the rotation matrix is constructed by a separate script (construct_rot.py) and hard-coded into the wavefunction scripts.
- No
desktop …
=> Add tests for orbital rotation for Be

src/Platforms/CUDA/CMakeLists.txt, src/Platforms/CUDA/CUDADeviceManager.cpp, src/Platforms/CUDA/CUDADeviceManager.h, src/Platforms/MemoryUsage.cpp, src/Platforms/OMPTarget/CMakeLists.txt, src/Platforms/OMPTarget/OMPDeviceManager.cpp, src/Platforms/OMPTarget/OMPDeviceManager.h, src/Platforms/SYCL/CMakeLists.txt, src/Platforms/SYCL/SYCLDeviceManager.cpp, src/Platforms/SYCL/SYCLruntime.cpp, src/Platforms/SYCL/SYCLruntime.hpp
1) Break header files into h/cpp in OMPTarget and CUDA.
2) Enable SYCL free device memory reporting. There is a catch. Need to enable environment variable ZES_ENABLE_SYSMAN=1
- New feature
- No
sunspot
=> Update device manager

src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp, src/QMCDrivers/tests/test_QMCCostFunctionBatched.cpp
Situation can arise when walkers_per_rank is not commensurate with the number of processors and there are zero walkers on some ranks.
Fixes #4690
- Bugfix
- No
laptopt
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being …
=> Guard batch size computation against zero

src/QMCWaveFunctions/detail/CUDA/cuBLAS_LU.cu, src/QMCWaveFunctions/detail/CUDA/cuBLAS_LU.hpp, src/QMCWaveFunctions/tests/test_cuBLAS_LU.cpp
1. getrf_batched output errors of all the infos instead of the first one.
2. Check getri_batched infos.
- Bugfix
- No
epyc-server
=> Improve cublas getrf/getri_batched error handling.

src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h, src/QMCWaveFunctions/tests/test_polynomial_eeI_jastrow.cpp
Add the function `evaluateDerivativesWF` for the three-body Jastrow.  It's a copy of `evaluateDerivatives` with the code to compute `dhpsioverpsi` removed.
This function is needed for orbital rotation with psuedopotentials and J3.
- Bugfix
- New feature
- No
desktop
- No. This PR is up to date with current the current state of 'develop'
=> Add evaluateDerivativesWF for J3

src/QMCDrivers/GreenFunctionModifiers/DriftModifierUNR.cpp, src/QMCDrivers/QMCDriverNew.h, src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/TrialWaveFunction.h
Nan checks are better places where NaN is produced and hence better suited in TWF.
On frontier
```
NaN check in TWF::mw_calcRatioGrad found
particle 1484 grads[0] is NaN.
particle 1484 grads[1] is NaN.
particle 1484 grads[2] is NaN.
```
instead of
```
drift[0] is nan, vsq (-nan) sc (0.001)
```
- New feature
- No
Frontier
=> Move nan check from DriftModifierUNR to TWF

config/docker/dependencies/ubuntu22/openmpi/Dockerfile
This is updating the dockerfile for the changes I'm about to push for the `ubuntu22-openmpi:latest` image.
GCC9 tests have not been using gcc9, this should set gcc9 as the default and thus fix this.
In addition, I've also done this for clang just in case.
- Bugfix
- CI
- No
- Yes Code added or changed in the PR has …
=> pin clang and gcc versions for ubuntu22-openmpi

nexus/lib/machines.py
`OMP_PROC_BIND` and `OMP_PLACES` environment variables should not be set for GPU jobs. With this change, Nexus GPU jobs are running for me on Perlmutter.
- Bugfix
- No
NERSC/Perlmutter (Nexus tests are passing)
=> Fix Nexus GPU jobs for NERSC/Perlmutter

src/QMCWaveFunctions/RotatedSPOs.cpp, src/QMCWaveFunctions/RotatedSPOs.h, src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp
In the case where we go straight from an optimization into a VMC/DMC in the same run, or with WF evaluation during optimization we want to be able to utilize mw_ APIs and  offload when using RotatedSPOs. Currently, since RotatedSPOs inherits from SPOSet and doesn't have any mw_ APIs defined, it will just fall back to the single walker APIs. This PR adds the resource management and mw_ APIs to RotatedSPOs, which simply call its underlying SPOSet's resource and mw_ APIs. 
I made a unit test to check that these mw_ APIs have the correct behavior by introducing two "dummy" SPOSets, one that has mw_ APIs defined and one that doesn't. A RotatedSPO for the dummy SPO which doesn't have any mw_ specialization does RotatedSPOs::mw_XXX which calls underlying SPO::mw_XXX. Since it isn't defined, it …
=> add mw_ APIs to RotatedSPO

src/QMCWaveFunctions/RotatedSPOs.cpp, src/QMCWaveFunctions/RotatedSPOs.h
adding a timer to the Phi->apply_rotation calls. Useful as we are testing some of the performance of orbital optimization
- New feature
- No
macOS
- No. Documentation …
=> apply_rotation timer

src/Estimators/CMakeLists.txt
The 'test_estimators' binary is build independent of the setting of BUILD_UNIT_TESTS. This causes a linker error as 'sposets_for_testing' library is not available. Disable tests for Estimators if BUILD_UNIT_TESTS is OFF.
- No
=> Disable Estimator tests if BUILD_UNIT_TESTS is set to OFF.

nexus/lib/qmcpack_input.py
Add support for QMCPACK spinor inputs.  This is a small change.
- New feature
- No
Workstation
=> Nexus: support spinor inputs

nexus/lib/pyscf_input.py, nexus/lib/pyscf_sim.py, nexus/tests/unit/test_pyscf_input.py
Found on a Ubuntu 22.04 system where the 'python' executable doesn't exist, only 'python3'.
- Bugfix
- No
laptop
=> Use 'python3' as python exectable name when using pyscf from Nexus

src/AFQMC/Memory/device_pointers.hpp
This change is necessary for multi to be able to call `uninitialized_copy` generically from subarray -> array construction
- No
=> uninitcopy for device pointer

src/AFQMC/Memory/device_pointers.hpp
to fight ADL-unfriendly types used in AFQMC
This change is necessary for multi to be able to call `uninitialized_copy` generically from subarray -> array construction
- No
=> [AFQMC] Add customized uninitialized_copy for device_pointer

src/QMCWaveFunctions/tests/test_ConstantSPOSet.cpp, src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp, src/QMCWaveFunctions/tests/test_spline_applyrotation.cpp, src/Utilities/for_testing/checkMatrix.cpp, src/Utilities/for_testing/checkMatrix.hpp, src/Utilities/tests/for_testing/test_checkMatrix.cpp
While trying to get a new feature tested that I'm working on, I noticed that a few unit tests have incorrect usage of the "checkMatrix". Those tests were just calling checkMatrix(matA, matB) and not getting the result and checking to see if the matrices agree or not. 
This means that some of those features could actually be failing and we have been missing it since the checks weren't correct. I think I caught all instances here.
- Bugfix
- No
macOS
_Update the following with a yes where the items apply. If you're unsure …
=> Fix checkMatrix usage in some tests

src/Platforms/tests/SYCL/test_SYCLallocator.cpp, src/QMCWaveFunctions/Fermion/DelayedUpdateSYCL.h, src/QMCWaveFunctions/Fermion/syclSolverInverter.hpp, src/QMCWaveFunctions/detail/SYCL/sycl_determinant_helper.cpp, src/QMCWaveFunctions/detail/SYCL/sycl_determinant_helper.hpp
Since we use in-order queue, there is no need to use events for expressing dependency.
- No
sunspot
=> Remove sycl event usage

docs/intro_wavefunction.rst
Add documentation for orbital rotation.
- No
laptop
=> Add orbital rotation documentation

src/QMCWaveFunctions/EinsplineSetBuilderOld.cpp, tests/solids/diamondC_1x1x1_pp/CMakeLists.txt, tests/solids/diamondC_1x1x1_pp/det_qmc_input_check_bad_splineh5.in.xml, tests/solids/diamondC_1x1x1_pp/notapwscf.h5
Addresses https://github.com/QMCPACK/qmcpack/issues/4744#issuecomment-1735955308
the refined error for #4744 reproducer is
```
ERROR HDF5 read failure in hdf_archive::read /format
EinsplineSetBuilder::ReadOrbitalInfo h5 file format is too old or it is not a bspline orbital file!
EinsplineSetBuilder::set_metadata Error reading orbital info from HDF5 file.
```
- No
laptop
=> Refine EinsplineSetBuilder::ReadOrbitalInfo error handling.

src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilder_createSPOs.cpp, src/QMCWaveFunctions/CMakeLists.txt, src/QMCWaveFunctions/PlaneWave/PWBasis.cpp, src/QMCWaveFunctions/PlaneWave/PWOrbitalSetBuilder.cpp, src/QMCWaveFunctions/PlaneWave/PWOrbitalSetBuilder.h, src/QMCWaveFunctions/SPOSetBuilderFactory.cpp, src/QMCWaveFunctions/WaveFunctionFactory.cpp, src/QMCWaveFunctions/tests/test_pw.cpp
PWorbitalBuilder was based on WaveFunctionComponentBuilder
reworked PWorbitalSetBuilder is based on SPOSetBuilder and connected to the rest like other SPOSet builders.
- No
laptop
=> Rewrite planewave orbital set builder

src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
Addresses #4666.
mw_evaluate_notranspose and evaluate_notranspose don't produce bitwise identical results. 
The problem started by https://github.com/QMCPACK/qmcpack/pull/4407 which introduce a batched evaluation and caused bitwise matrix value checking failure. I printed diff and found the value is at the epsilon of float or double. So no concern.
The intention of the assertion was to catch any missing D2H transfer earlier and there is no need of recomputing. So the solution is removing the re-computation.
- Bugfix
- No
epyc-server
=> Fix assertion failure

src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/cuSolverInverter.hpp, src/QMCWaveFunctions/Fermion/rocSolverInverter.hpp, src/QMCWaveFunctions/Fermion/syclSolverInverter.hpp
One failure mode of 512 atom running on Summit.
cuSolver was showing non-deterministic failure. Re-doing inversion seems to rescue the run.
Add additional scanning of NaN.
- New feature
- No
Summit.
=> Rerun matrix inversion when failure happens (non-batched inversion case)

src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/TrialWaveFunction.h
When the ratio of calcRatioGrad returns 0, gradients can be NaN. The accept/reject algorithm naturally rejects such moves and thus the NaN check should be skipped. I updated the comment of calcRatioGrad to remind its caller checking the ratio value before accepting a move and fixed its use cases in NLPP T-move related routines.
- Bugfix
- No
Summit
=> Relax NaN check in TWF::calcRatioGrad

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/TrialWaveFunction.cpp
Found a severe bug in the batched DMC driver. It was introduced in 534fffc9d213935df04725305d89061a7aec1fd0
PhaseDiff is constantly 0 due to `std::imag(std::arg(ratios[iw]))`, the return of `std::arg` is always a real number. It doesn't affect complex build but breaks fixed node approximation in the real build. The insensitive `short-diamondC_2x1x1_pp-vmcbatch_dmcbatch` indicates lack of tests.
I would like to eventually remove TWF::PhaseDiff which is an unnecessary state to carry with. It can always be recomputed from ratio and the computation is cheap.
Also protect another source of NaN in DMCBatched.
- Bugfix
- No
epyc-server, frontier
=> [BUG] Fix wrong PhaseDiff and protect NaN for DMCBatched

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.2.cpp, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp
Loop index over nw must be 32 bits in size, otherwise the assignment following the reduction will miss the second item.
Bug affects offload with NVidia.
See https://github.com/QMCPACK/qmcpack/issues/4767
This PR represents the minimal changes needed to fix the real and complex offload builds for the multideterminant tests.
More changes could be made to make the type of `nw` consistent (A static analyzer would complain if run against the current code).
- Bugfix
- No
local server (A2000), JLSE A40
- Yes. This PR is up to date with current the current state …
=> Workaround for assignment-after-reduction offload bug

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.2.cpp, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp
preventing NaN by indirectly protecting zero.
- Bugfix
- No
epyc-server
=> Additional zero protection in MSD.

src/AFQMC/Numerics/detail/CUDA/Kernels/strided_2Drange.hpp, src/AFQMC/Numerics/detail/CUDA/Kernels/strided_range.hpp
Fix compilation error for CUDA 12.x. 11.x was fine.
- Bugfix
- No
epyc-server
=> Fix AFQMC compilation with CUDA 12.x

src/Platforms/OMPTarget/ompBLAS.cpp, src/QMCHamiltonians/CoulombPBCAA.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h, src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h, src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.2.cpp, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp
Close https://github.com/QMCPACK/qmcpack/issues/4774
Use int or uint32_t in offload loop indices.
- No
epyc-server
=> Use 32bit integer for loop indices in offload region.

src/Estimators/EstimatorManagerCrowd.cpp, src/Estimators/EstimatorManagerCrowd.h, src/Estimators/MagnetizationDensity.cpp, src/Estimators/MagnetizationDensity.h, src/Estimators/MomentumDistribution.cpp, src/Estimators/MomentumDistribution.h, src/Estimators/OneBodyDensityMatrices.cpp, src/Estimators/OneBodyDensityMatrices.h, src/Estimators/OperatorEstBase.h, src/Estimators/PerParticleHamiltonianLogger.cpp, src/Estimators/PerParticleHamiltonianLogger.h, src/Estimators/SpinDensityNew.cpp, src/Estimators/SpinDensityNew.h, src/Estimators/tests/FakeOperatorEstimator.h, src/Estimators/tests/test_EstimatorManagerCrowd.cpp, src/Estimators/tests/test_MagnetizationDensity.cpp, src/Estimators/tests/test_MomentumDistribution.cpp, src/Estimators/tests/test_PerParticleHamiltonianLogger.cpp, src/Estimators/tests/test_SpinDensityNew.cpp, src/QMCDrivers/Crowd.h
For zero variance, zero bias estimators, one needs access to the Hamiltonian, in addition to the trial wave function and particle set.  This change adds the crowd QMCHamiltonian lists to the accumulate() API's EstimatorManagerCrowd and OperatorEstBase.  This way the QMCHamiltonians will be in scope if needed, but otherwise can be ignored for observables that don't require access to it.  
- Refactoring (no functional changes)
- No
Intel xeon, RHEL 8
simply a …
=> Add Hamiltonian (lists) to Crowd Estimator accumulate() Calls.

src/Containers/OhmmsSoA/PosTransformer.h, src/Containers/OhmmsSoA/VectorSoaContainer.h
The member function `VectorSoaContainer::copyIn` has a template parameter  `T1` that in the current codebase is always equal to `T`. I see more risks than benefits to the additional functionality.   
Found while working on #4684.
- No …
=> Remove unused template parameter

CMakeLists.txt
Don't do cmake test for OpenMPtaskloop if QMC_OMP is not true.
- Bugfix
- No
OSX Ventura laptop and ubuntu X86 
=> only test for OMP_TASKLOOP if QMC_OMP is true

src/Platforms/OMPTarget/ompBLAS.cpp
**Describe the bug**
Missing header `<cstdint>` in `qmcpack/src/Platforms/OMPTarget/ompBLAS.cpp`  for compilation with GCC 13.2
https://gitlab.com/correaa/boost-multi/-/jobs/5346169350#L1644
**To Reproduce**
Steps to reproduce the behavior:
With debian:testing and GCC 13.2:
```bash
$ cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DBUILD_AFQMC=1 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=Debug -DMPIEXEC_PREFLAGS="--allow-run-as-root;--bind-to;none" ..
$ make
```
**Expected behavior**
Compilation should work
**System:**
Docker image with debian:testing
=> Fix missing header

src/Platforms/ROCm/cuda2hip.h, src/Platforms/tests/CUDA/test_CUDAallocator.cpp
`cudaPointerAttributes.memoryType` was renamed to `cudaPointerAttributes.type` in CUDA 10.
The same change is introduced in ROCm 6.
Adding a check of `HIP_VERSION_MAJOR` to use the correct name.
=> Change 'memoryType' to 'type' for ROCM >= 6

src/QMCWaveFunctions/BsplineFactory/EinsplineSpinorSetBuilder.cpp
This enables the writing of the einspline bandinfo files for spinors. It turns out these were actually being written as hidden files, because a string variable was empty in EinsplineSpinorSetBuilder. This now produces the expected behavior
Additionally, I noticed a difference between EinsplineSetBuilder and EinsplineSpinorSetBuilder in that a finalizeConstruction call was missing in the spinor code. This is needed when we have SplineX2XOMPTarget in order to map the coefficients onto the device. I added those calls as well. 
Closes #4770 
- Bugfix
- No
macOS
_Update the following with …
=> Improve EinsplineSpinorSetBuilder

src/Numerics/SoaCartesianTensor.h, src/Numerics/SoaSphericalTensor.h, src/Numerics/tests/test_soa_cartesian_tensor.cpp, src/QMCWaveFunctions/LCAO/AOBasisBuilder.cpp, src/QMCWaveFunctions/LCAO/MultiQuinticSpline1D.h, src/QMCWaveFunctions/LCAO/RadialOrbitalSetBuilder.h, src/QMCWaveFunctions/LCAO/SoaAtomicBasisSet.h, src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.cpp, src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.h
Avoid redundant data transfer and memory allocation and de-allocation.
- New feature
- No
epyc-server
=> LCAO offload optimization

src/Particle/CMakeLists.txt, src/QMCWaveFunctions/CMakeLists.txt, src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/TrialWaveFunction.h, src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp, src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp
The query function is introduced for refactoring better #4789.
When working on this, I noticed a linking headache caused by libqmcwfs and libqmcwfs_omptarget as two separate libraries with cyclic dependency. The solution is fairly simple. Just make qmcwfs_omptarget an object target and libqmcwfs contains all the object files of qmcwfs_omptarget. This restored the old library organization, there is only `libqmcwfs.a` at linking.
- New feature
- No
epyc-server
=> Add TrialWaveFunction::findMSD() query function

src/QMCHamiltonians/tests/test_QMCHamiltonian.cpp
Adds additional unit level testing to QMCHamiltonian with per particle listeners in the multiwalker case.
Fufills #4769
- No
OSX Laptoip
=> Add missing consistency test between per particle and per QMCHamiltonian energies

src/QMCWaveFunctions/Fermion/DelayedUpdateCUDA.h, src/QMCWaveFunctions/Fermion/cuSolverInverter.hpp, src/QMCWaveFunctions/Fermion/rocSolverInverter.hpp
Although no stream sync is needed when transferring data from/to pageable memory. Adding `cuda/hipStreamSynchronize` traps potential device side errors.
- Bugfix
- No
epyc-server
=> Add stream sync to detect errors on the device.

src/Platforms/CUDA/CUDADeviceManager.cpp
Fix the include conflict described in #4761
- Bugfix
- No
epyc-server
=> Resolve noinline definition conflict between CUDA headerfiles and GCC 12 libraries

src/Platforms/OMPTarget/CMakeLists.txt
Fix the issue raised in #4815. The consumer has been protected already https://github.com/QMCPACK/qmcpack/blob/252da5363755e987b1214d8d81c9ed422da84807/src/Platforms/DeviceManager.h#L22
- Bugfix
- No
epyc-server
=> Fix QMC_OMP=OFF compilation.

src/Optimize/OptimizeBase.h, src/QMCDrivers/WFOpt/QMCCostFunctionBase.cpp, src/QMCDrivers/WFOpt/QMCCostFunctionBase.h, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp, src/QMCDrivers/tests/test_DescentEngine.cpp, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp, src/QMCWaveFunctions/RotatedSPOs.cpp, src/QMCWaveFunctions/VariableSet.cpp, src/QMCWaveFunctions/VariableSet.h, src/QMCWaveFunctions/tests/test_variable_set.cpp
While working to enable complex orbital rotations, @rcclay, @jptowns and I realized there were some inconsistencies in how we deal with optimizable parameters and their types. 
The optimizer is hard coded deal with only real parameters since it takes the real part of the parameters stored in VariableSet.  Generally, to minimize a **complex analytic** function you only need to consider d/dz, but general functions that aren't complex analytic need to be formulated with d/dz and d/dz*.  For those types of functions, it is completely equivalent to work with just d/d(re(z)) and d/d(im(z)) though. The local energy and cost function that we minimize are not complex analytic, so we need to work with both d/d(re(z)) and d/d(im(z)). So, to make the optimizer properly deal with complex parameters, …
=> Convert VariableSet to RealType only

src/QMCWaveFunctions/LCAO/CuspCorrectionConstruction.cpp, src/QMCWaveFunctions/LCAO/LCAOSpinorBuilder.cpp, src/QMCWaveFunctions/LCAO/LCAOrbitalBuilder.cpp, src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp, src/QMCWaveFunctions/LCAO/LCAOrbitalSet.h, src/QMCWaveFunctions/LCAO/LCAOrbitalSetWithCorrection.cpp, src/QMCWaveFunctions/LCAO/LCAOrbitalSetWithCorrection.h, src/QMCWaveFunctions/LCAO/SoaCuspCorrection.cpp, src/QMCWaveFunctions/LCAO/SoaCuspCorrection.h, src/QMCWaveFunctions/tests/test_soa_cusp_corr.cpp
On the path to eventually remove SPOSet::setOrbitalSetSize. The size should be recorded in the constructor and not be allowed to change at a later point. Simplify the initialization logic.
- No
epyc-server
=> Move the role of LCAO::setOrbitalSetSize to constructors

src/QMCWaveFunctions/Jastrow/BsplineFunctor.cpp, src/QMCWaveFunctions/Jastrow/BsplineFunctor.h
Review after #4827
Fix https://cdash.qmcpack.org/CDash/testDetails.php?test=28505916&build=446393
It was caused by NaN due to out-of-bound access when accessing 1D spline coefficients in Jastrow.
- Bugfix
- No
bora
=> Fix spline jastrow

tests/molecules/LiH_ae_gms/vmc_noj_edens_vor_long.in.xml, tests/molecules/LiH_ae_gms/vmc_noj_edens_vor_short.in.xml
Fixes https://cdash.qmcpack.org/CDash/testDetails.php?test=28509968&build=446427
- Bugfix
- No
epyc-server
=> Fix test input file for LiH energy density estimator voronoi variant

src/type_traits/complex_help.hpp, src/type_traits/tests/CMakeLists.txt, src/type_traits/tests/test_complex_helper.cpp
Add a helper class for Value type reconstruction.
- New feature
- No
laptop
=> Add ValueAlias for ValueType reconstruction

CMakeLists.txt, tests/test_automation/github-actions/ci/run_step_ornl-sulfur-2.sh
Usually [findMPI failure](https://github.com/QMCPACK/qmcpack/actions/runs/6856906594/job/18647090392) is caused by compiler failure. Move the compilation ahead of findMPI.
- Bugfix
- No
epyc-server
=> Check compilers before handling MPI in CMake

.github/workflows/ci-github-actions-self-hosted.yaml, tests/test_automation/github-actions/ci/run_step_ornl-sulfur-1.sh, tests/test_automation/github-actions/ci/run_step_ornl-sulfur-2.sh
Use distinct build directories for the 2 classes of sulfur job. Fail fast so failing logs can be retrieved.
- No
None
=> Adjust sulfur CI for throughput and debuggability

src/AFQMC/Memory/SharedMemory/shm_ptr_with_raw_ptr_dispatch.hpp, src/AFQMC/Memory/device_pointers.hpp
declare stub for uninitialized_copy_n of shm_ptr in AFQMC
Implement missing algorithm reflecting changes in Multi
- No
=> [AFQMC] Implement uninit_copy for shm_ptr_with_raw_ptr_dispatch

src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/TrialWaveFunction.h, src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp, src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp
No more returns the first found one but all. More general.
- Bugfix
- No
epyc-server
=> Change findMSD return type to RefVector.

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/VMC/VMCBatched.cpp
directly calling timer start/stop functions doesn't work well with exceptions. Replace them with ScopedTimer.
Massive change shown in the diff is caused by indentation changes.
Please use `git show -w` to view actual changes.
- Bugfix
- No
epyc-server
=> Replace start/stop with scoped timers.

src/QMCWaveFunctions/BsplineFactory/BsplineReaderBase.cpp, src/QMCWaveFunctions/BsplineFactory/BsplineReaderBase.h, src/QMCWaveFunctions/BsplineFactory/BsplineSet.h, src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilder_createSPOs.cpp, src/QMCWaveFunctions/BsplineFactory/HybridRepCplx.h, src/QMCWaveFunctions/BsplineFactory/HybridRepReal.h, src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h, src/QMCWaveFunctions/BsplineFactory/SplineC2C.h, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h, src/QMCWaveFunctions/BsplineFactory/SplineC2R.h, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h, src/QMCWaveFunctions/BsplineFactory/SplineR2R.h, src/QMCWaveFunctions/BsplineFactory/SplineSetReader.h
Avoid multi level inheritance.  SplineSetReader is no more a base of HybridRepSetReader.
Make most functions const and kill as much state machines as possible.
- No
epyc-server
=> Refactor SplineSetReader and HybridRepSetReader

CMake/inspectCompiler.cmake, CMakeLists.txt, README.md, docs/installation.rst
3.21 (July 2021) is over 2 years old.
- No
epyc-server
=> Raise CMake minimum to 3.21

src/Utilities/ModernStringUtils.hpp, src/Utilities/for_testing/NativeInitializerPrint.hpp, src/Utilities/tests/test_ModernStringUtils.cpp
string2Int implementation used to parse int grid input in future PR for energy density estimator.
for stringview and using std::from_chars with modern stdlibc++
libc++ and older stdlibc++ revert to atoi.
- New feature
- Yes
- No
=> Expansion of ModernStringUtils with modern string2Int

nexus/lib/qmcpack_input.py, src/QMCDrivers/QMCDriver.cpp
This fixes driving spinor calculations that set the spin mass in the batched drivers. 
In the batched drivers, we used "spin_mass" for the xml tag whereas the legacy used "spinMass" for some reason.  I changed nexus to respect  the batched driver input tag. That would technically break backwards compatibility for legacy inputs since it used "spinMass", so I added both ways in legacy since that was a common theme in legacy. 
I caught this working on the tutorial
- Bugfix
- No
M1 mac …
=> nxs: fix nexus spin mass for batched drivers

nexus/lib/qmcpack_input.py
This PR adds or revises Nexus support for batched driver input generation.  There are three main additions: 1) add support for consolidated estimator input under `<estimators/>`, 2) forbid use of `samples` and enable passing of `walkers_per_rank` and `total_walkers` in optimization, and 3) enable switching batched determinant updates on/off (`slaterdeterminant.batch` attribute).
These updates are required for correct functioning of batched driver Nexus examples presented at the upcoming QMCPACK User's Workshop.
All Nexus tests pass locally.
- New feature
- No
Laptop
=> Nexus: updates for QMCPACK batched input generation

docs/spin_orbit.rst, nexus/lib/qmcpack.py, nexus/lib/qmcpack_input.py
Set correct cusp in two body jastrow when spinors are enabled so the user doesn't have to
- New feature
- No
M1 mac
- Yes. Documentation has been added (if …
=> Nexus: set correct cusp in SOC jastrow

src/Containers/OhmmsPETE/TinyVector.h, src/Containers/OhmmsPETE/tests/test_TinyVector.cpp, src/type_traits/complex_help.hpp
This changes the string output of `TinyVector` so that all values that std::fpclassify recognizes as FP_ZERO are output as 0.  Importantly for #4857 -0.0 is output as 0.0. This should remove another potential divergence for comparing the output of NEReferencePoints description output.
- Bugfix
- New feature
- No
x86 v100 cloud instance
- Yes Documentation has been added (if …
=> [WIP] ReferencePoints report -0.0 is equivalent to 0.0 output either as 0.

src/Platforms/tests/CMakeLists.txt
Should fix missing coverage in #4847.
- No
epyc-server
=> Run omptarget tests unconditionally as the omptarget runtime

src/Estimators/CMakeLists.txt, src/Estimators/ParseGridInput.cpp, src/Estimators/ParseGridInput.hpp, src/Estimators/tests/CMakeLists.txt, src/Estimators/tests/test_ParseGridInput.cpp
Add a class to handle parsing the grid input format introducted in the legacy EnergyDensityEstimator.  See manual for a description of this.
- New feature
- No
x86 v100
- …
=> Introducing ParseGridInput

src/Utilities/ModernStringUtils.hpp, src/Utilities/tests/test_ModernStringUtils.cpp
Fixes dangling else warning seen by clang.
Also extends unit test to the non number exception.
- Bugfix
- No
osx clang 16
gcc 11.3.0 x86 v100
- Yes  Code added or changed in the PR has been clang-formatted
- Yes  This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes  Documentation has been added (if appropriate)
=> Fix dangling else warning on clang

src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp
Reduce unnecessary memory use in SplineC2COMPTarget.
spline_padded_size >> sposet_padded_size
- Bugfix
- No
Summit
=> Differentiate spline and sposet padded size in SplineC2COMPTarget

src/Particle/SoaDistanceTableAAOMPTarget.h, src/Particle/SoaDistanceTableABOMPTarget.h
Using async target tasks causes unintended congestion. A task launched by crowd A (thread A) may run on thread B and slows down the execution of crowd B and amplify thread imbalance. Before we have a better understanding of target tasks, disable them and rely on multi-threaded offload for performance.
- Other (please describe): Performance tuning.
- No
Polaris
=> Disable target tasks in DTs.

src/AFQMC/Memory/SharedMemory/shm_ptr_with_raw_ptr_dispatch.hpp
uninitialized_copy_n for shmem was implemented in the wrong way preventing an update of Multi
- Bugfix (silent bug)
- No
Ubuntu 22.04
=> [AFQMC] correct implementation of uninitialized_copy_n for shmem

src/QMCHamiltonians/NonLocalECPotential.cpp
Fix #4889. I'm still not satisfied with the current handling of shared resource of VP. Will explore a cleaner solution when I refactor the code.
- Bugfix
- No
Bora
=> Fix #4889 by protecting nullptr.

src/QMCHamiltonians/tests/test_ewald2d.cpp
Issue reported by Intel but the cause was Clang tightening precision handling https://cdash.qmcpack.org/CDash/viewBuildError.php?buildid=457608
- Bugfix
- No
epyc-server
=> Fix MP compilation with Clang.

.github/workflows/ci-github-actions-self-hosted.yaml
Current GitHub Action for self-hosted runners doesn't work with node.js 12 triggering a spurious message on ornl CI. 
Node.js 12 support was deprecated [last year](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/). 
This is PR upgrade the problem with a compatible action with the same functionality. 
It needs to be merged first in order to be tested.
- No
N/A
- No. Documentation has been added (if …
=> Switch to Node.js 16 compatible action

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/DMC/DMCBatched.h, src/QMCDrivers/QMCDriverNew.cpp, src/QMCDrivers/QMCDriverNew.h
T-move info was only set to all the existing walkers (both live and dead) at the beginning of the DMC driver. If branching creates new walkers, these walkers will be running as locality approximation. The fix is to set the handler before each DMC step. A better solution will be moving such meta data out of each walker and keeping them to the driver. This will be done once I get around tho restructure T-move related codes.
- Bugfix
- No
bora
=> Fix T-move in batched DMC driver.

.github/workflows/ci-github-actions.yaml, tests/test_automation/github-actions/ci/run_step.sh
Move to supported macos-13 and gcc-12 on macos CI
Attempt to Address current failure in HDF 1.14 in current CI e.g. #4905 
Fixes #4907 
- No
N/A. Must pass CI
=> Update macos CI to latest version

src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/WaveFunctionComponent.cpp, src/QMCWaveFunctions/tests/MinimalWaveFunctionPool.h, src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp
This PR fixes a bug I found when doing some testing of the spinor code using the batched drivers. Essentially, I saw errors in the energy and kinetic energy relative to legacy only if there is a jastrow present and only if drift was on. Ended up tracking it down to the fact that WaveFunctionComponents that do not use the spins do not touch the spin gradient component, which they shouldn't. However,  the problem was that in the TWF::mw_evalGrad function, it was passing in the previous wave function components TWFGrad type. Since the Jastrow mw_evalGrad wasn't setting the spin component to zero, then the grads += grads_z …
=> Fix bug in TrialWaveFunction mw_evalGrad for spinor wave functions

src/AFQMC/Memory/multi_memory/block.hpp
Undeprecate memory block class that can be used with the last release of Multi.
- No
Ubuntu 23.10
=> [AFQMC] undeprecate memory block class

src/Estimators/OneBodyDensityMatrices.cpp
The OneBodyDensityMatrix only has been implemented for spinors if you're using the density integrator. This PR adds a guard to prevent other integrators being used. 
- New feature
- No
m1 mac
- No. This PR adds tests to cover any new code, or to catch …
=> add guard to prevent incorrect usage of 1rdm for spinor

src/QMCWaveFunctions/Fermion/SlaterDet.cpp, src/QMCWaveFunctions/Fermion/SlaterDet.h, src/QMCWaveFunctions/WaveFunctionComponent.h, src/QMCWaveFunctions/tests/CMakeLists.txt, src/QMCWaveFunctions/tests/test_SlaterDet.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp
While I was profiling some runs on spinor calcualtions, I noticed that a few spinor calculations were going through single walker APIs where I expected they would use mw_. Turns out I forgot to add mw_ WithSpin APIs to both SlaterDet as well as DiracDeterminant so everuthing was always falling back to single walker. They were only added to DiracDeterminantBatched, which isn't being used in CPU builds since I am not building with ENABLE_OFFLOAD. 
This PR adds the appropriate APIs to SlaterDet first. Will add something to DiracDeterminant in the future, but falling back to the single walker should be fine for now. …
=> Add mw_ WithSpin APIs to SlaterDet

src/QMCWaveFunctions/RotatedSPOs.h, src/QMCWaveFunctions/SpinorSet.cpp, src/QMCWaveFunctions/tests/test_MO_spinor.cpp, src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp
Orbital optimization with spinors had a few issues. First, RotatedSPOs were missing a few spin APIs. Second, once the appropriate APIs were added, there were some sizing issues when spinors were used with DiracDeterminants. This is because DD always passes in data structues sized nelec x nelec, whereas in the case of orb opt the spinorset has OrbitalSetSize > nelec. This is now fixed, and orb opt with spinors should be working
Unit tests were modified or added to in order to check both the missing spin APIs in RotatedSPOs as well as the sizing issues in SpinorSet. 
- Bugfix
- No
M1 …
=> Fix spinors for orb opt

tests/test_automation/github-actions/ci/run_step.sh
Closes https://github.com/QMCPACK/qmcpack/issues/4924
Xcode 15 introduced a new linker which was not robust and caused sporadic crash.
Switch to the classic linker.
- No
None
=> Change macOS CI to use the classic linker

tests/test_automation/github-actions/ci/run_step_ornl-nitrogen-1.sh
CI tests may hang on AMD GPU runs. Add a 180sec timeout and allow repeat at most twice. Better than current 1h limit.
- Other (please describe): CI settings
- No
None
=> Shorten timeout on AMD CI runs.

tests/test_automation/github-actions/ci/run_step.sh
GitHub Actions now provides 4 cores in free runners on [Linux and macOS 13](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
This PR adds more test concurrency from 2 to 4
- No
N/A, must pass CI
- No. This PR adds tests to cover any …
=> Update 2 to 4 cores used in tests on GitHub Actions runners

src/QMCWaveFunctions/BsplineFactory/HybridRepCenterOrbitals.h, src/QMCWaveFunctions/BsplineFactory/HybridRepCplx.h, src/QMCWaveFunctions/BsplineFactory/HybridRepReal.h, src/QMCWaveFunctions/Fermion/SlaterDet.h
Noticed a missing safety check in the complex code path of hybridrep.
- Bugfix
- No
Polaris
=> Fix hybridrep complex

tests/converter/converter_test.py, tests/converter/gpaw/gpaw4qmcpack_test.py, tests/converter/pwconverter_test.py
Robust against miscellaneous warning printout.
The return code checks before stderr checks are supposed to do the actual work.
- No
epyc-server
=> Do not error out with non-empty stderr in converter test scripts.

src/QMCWaveFunctions/tests/test_hybridrep.cpp, tests/solids/diamondC_2x1x1-Gaussian_pp_MSD/CMakeLists.txt, tests/test_automation/github-actions/ci/run_step_ornl-sulfur-2.sh
Bump from LLVM 16 to 18 in sulfur CI for CUDA+AFQMC+Offload configurations
- No
=> Bump to llvm 18 in sulfur CI

CMakeLists.txt, config/build_alcf_sunspot_icpx.sh
The explicit setting of CMP0144 only suppresses warning. We always have the new behavior.
- No
sunspot
=> Update sunspot recipe and suppress CMake warning.

src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h
Review after #4961
Updated timer reporting at medium level
```
QMCLinearOptimizeBatched                                       0.0131     0.0055              2       0.006525866
QMCCostFunctionBatched::correlatedSampling                   0.0007     0.0007              2       0.000333037
Hamiltonian:h_free::evaluate                               0.0000     0.0000              2       0.000001550
ParticleSet:none::update                                   0.0000     0.0000              2       0.000001915
WaveFunction:psi0::recompute                               0.0000     0.0000              2       0.000002405
QMCLinearOptimizeBatched::Eigenvalue                         0.0005     0.0004              2       0.000225491
QMCLinearOptimizedBatched::invert_ovlMat                   0.0000 …
```
=> Refine WFOpt batched driver timer reporting

nexus/lib/machines.py
Replace the deprecated and recently removed load_source function using the recommended replacement https://github.com/python/cpython/blob/main/Doc/whatsnew/3.12.rst
The undocumented ability to use a ~/.nexus/local_machines.py would be useful e.g. for central installations of nexus where the user doesn't have write access to the machines.py file
CI needs to run to see if this closes #4949
- Bugfix
- New feature
- No
nitrogen2 with and without ~/.nexus/local_machines.py and python 3.11.7. (CI on mac has 3.12)
- NA. …
=> Nexus: Replace deprecated load_source

src/Platforms/CUDA/CUDAallocator.hpp, src/Platforms/DualAllocatorAliases.hpp, src/Platforms/OMPTarget/OMPallocator.hpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h, src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h
Introduce OMPTargetAllocator. Having OpenMP offload consistently manages all the device memory.
- New feature
- No
epyc-server
=> Introduce OMPTargetAllocator device-only allocator

src/Estimators/OneBodyDensityMatrices.cpp, src/io/OhmmsData/Libxml2Doc.cpp
With our default compilation options GCC14 usefully flags a couple of new routes to uninitialized variable use. Fixed.
There is still a large but not-new warning coming from ppconvert IO handling that I did not fix.
- Bugfix
- No
nitrogen2, nightly config with trial installation of gcc 14.1
=> Fix GCC14-flagged uninitialized use warnings

src/io/hdf/hdf_stl.h, src/io/hdf/tests/test_hdf_archive.cpp
std::vector<bool> is an exception case so it needs it own h5dataproxy.  There isn't a matching h5 data type so I convert it to/from char type. This is used by the energy density estimator to avoid adhoc kludging there.
- New feature
- No
osx laptop
- Yes Documentation has …
=> extend h5 data proxy for std::vector<bool> needed for EDE

nexus/lib/pwscf.py
When a new NSCF is located on a different path than SCF, Nexus will rsync the SCF results into the new path. This is a great feature for submitting multiple NSCF calculations with various k-points. However, this can take quite a while and can give the false sense that Nexus is hanging when, in fact, it is silently rsync'ing the results. This has confused me a few times.
I simply put two print statements warning the user that this is happening. It only executes the first time when the directory does not exist. There is probably a better way to output this - let me know if there is and I will be happy to update.
- No
All Nexus tests pass on my laptop (Linux Mint 21.3), except for 61/69 qdens_radial. 
=> Nexus: Print warning for the Nexus user before pwscf rsync

nexus/lib/machines.py
This PR updates the PBS scheduler available job states. Most important change from the older version PBS is the change of `completed` to `finished`. May 2020 version is installed in Polaris and it uses the new job state definitions. Without this update, it is not possible to use Nexus to submit jobs in Polaris because the state finished (F) is not defined. For compatibility in other computers still using the older version PBS, I have kept both completed and finished state tags. 
For reference, please see page RG-199 at https://2021.help.altair.com/2021.1/PBSProfessional/PBSReferenceGuide2021.1.pdf.
Here is the information from `man qstat` in Polaris which has the matching information (select '1B' after man qstat): 
```
The job's state:
B  Array job has at least one subjob
running
E  Job …
```
=> Nexus: Updated PBS job states for Polaris

nexus/bin/qdens-radial, nexus/tests/unit/test_qdens_radial.py
The Nexus `qdens-radial` test is passing for me when running on a NERSC machine, but it's failing on my Linux laptop. Upon inspection, the test is failing due to float comparison with many significant digits, which is a problematic thing to do:
Laptop:
```
Cumulative Value of C Species at Cutoff 0.6 is: 1.1078267486386277+/-0.0016066467832022906
```
NERSC:
```
Cumulative Value of C Species at Cutoff 0.6 is: 1.1078267486386275+/-0.0016066467833404942
```
In practice, we don't need 16 digits after decimal for charge densities. So I changed the `qdens-radial` output to have 8 digits after decimal and updated the reference data for the tests. After this change, all tests are passing for me locally and on NERSC.
- No
NERSC, Laptop …
=> Nexus: Fix the qdens-radial test

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp
Fixes https://github.com/QMCPACK/qmcpack/issues/4992 when the determinant with the largest coefficient is not the first one after the cutoff filtering.
- Bugfix
- No
epyc-server
=> ReferenceDeterminant should only be used at evaluation not preparation.

src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h, src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h, src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h, src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp
Make delayed update engines holding less data.
- No
epyc-server
=> Move psiMinv out of delayed update engines to DiracDeterminantBatched

src/QMCDrivers/WFOpt/LinearMethod.cpp, src/QMCDrivers/WFOpt/LinearMethod.h, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h, src/QMCDrivers/tests/test_LinearMethod.cpp
Move the eigenvalue selection code to a separate function, so it can be re-used with different solvers.
Add an "ev_solver" parameter to allow switching between the two implemented solution methods.
The choice of eigenvalue solvers is only implemented for the "one shift only" optimizer in the batched driver.
Prior to this PR, the code using the generalized eigensolver existed in the code, but was not connected.   More importantly, these changes are paving the way for a larger selection of eigenvalue solvers.
One change in logic is the eigenvalue problem is solved on one rank and the resulting change in parameters is broadcast to the other ranks. Previously, the eigenvalue problem was solved on each rank separately.  This is looking forward to different solvers which may not produce exactly …
=> Split eigenvalue solve from eigenvalue selection and add choice of solvers

src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h, src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h
Not fully done. Make resource consumed by delayed update engines explicit. Ownership goes to DiracDeterminantBatched.
- No
epyc
=> Move resource out of delayed update engines into DiracDeterminantBatched

src/Estimators/SelfHealingOverlap.cpp, src/QMCHamiltonians/SelfHealingOverlapLegacy.cpp, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.h, src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp
Will rebase after #4991
1) renamed detRatios to calcIndividualDetRatios, added unit tests and simplified its implementation
2) Cleaned up evaluateDerivativesMSD optional arguments handling.
- Refactoring (no functional changes)
- No
laptop
=> Adjust MSD functions

src/Particle/Lattice/LatticeAnalyzer.h
Closes #4975 
For the reported supercell, the basis mapping was failing after 10K attempts due to numerical tolerance issues when Intel 2021.1 was used on the old CADES system . Tolerance was increased conservatively. Was unable to reproduce the problem with recent GCC, Clang etc. on other systems. Fix was verified with a generic (vs AVX512) build since I was using different nodes.
I will PR an updated build script when an updated cmake is installed by the admins.
- Bugfix
- No
ORNL CADES SHPC Condo. https://docs.cades.ornl.gov/#condos/overview/ …
=> Fix 4975 via increased tolerance

docs/running.rst, src/QMCApp/QMCMain.cpp, src/Utilities/qmc_common.cpp
dryrun will exit cleanly (zero error code) rather than QMCPACK aborting. Small edits to docs and comments.
```
Hamiltonian h0
Kinetic         Kinetic energy
LocalECP        CoulombPBCAB potential source: ion0
NonLocalECP     NonLocalECPotential: ion0
ElecElec        CoulombPBCAA potential: e_e
IonIon          CoulombPBCAA potential: ion0_ion0
dryrun == 1 : Skipping all QMC and loop elements 
Use --enable-timers=<value> command line option to increase or decrease level of timing information
Stack timer profile
Timer      Inclusive_time  Exclusive_time  Calls       Time_per_call
Startup    54.0524    54.0524              1      54.052436786
QMCPACK execution completed successfully
```
- Bugfix
- New feature
- No
Ubuntu 22.04 gcc 11.4.0
- Yes. This PR …
=> Improve dryrun capabilty

config/build_ornl_cades_baseline.sh
Functional but likely suboptimal build script for ORNL Baseline (Dual AMD EPYC 7713 64-Core Processor nodes, HT disabled, slurm).
- No
Baseline. Test runtimes are reasonable when compared to our Zen3 nightlies.
=> Add config build script for ORNL Baseline

src/AFQMC/Matrix/matrix_emplace_wrapper.hpp
clang development seems tightening source code validation.
There is an unused constructor causing error
```
In file included from /scratch2/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack-develop/src/AFQMC/Matrix/csr_hdf5_readers.hpp:34:
/scratch2/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack-develop/src/AFQMC/Matrix/matrix_emplace_wrapper.hpp:51:56: error: 'scomm_' is a private member of 'boost::mpi3::shm::mutex'
51 |     m = std::move(std::make_unique<shm_mutex>(other.m->scomm_));
|                                                        ^
[CTest: warning matched] /scratch2/QMCPACK_CI_BUILDS_DO_NOT_REMOVE/qmcpack-develop/external_codes/mpi_wrapper/mpi3/include/mpi3/shm/mutex.hpp:14:29: note: implicitly declared private here
14 |         mpi3::shared_communicator& scomm_;  // …
```
=> Fix AFQMC compilation.

src/AFQMC/Memory/device_pointers.hpp
(e.g. A is not a fancy pointer -- in continuous memory); and if not, there will be other candidates, possibly provided by Multi itself (e.g. through ADL priority)
AFQMC used to provide its own fancy memory specializations.
Some of these function do not work for iterators that are not fancy pointers themselves, giving a hard error.
Use decltype to remove the overload if not semantically correct
- No
Ubuntu 22.04 and CUDA 12
=> [AFQMC] only use afqmc-device copy overload if semantically correct

src/Platforms/OMPTarget/QueueOMPTarget.hpp, src/Platforms/OMPTarget/ompBLAS.cpp, src/Platforms/OMPTarget/ompBLAS.hpp, src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp
I noticed that ompBLAS are all blocking calls and may cause issue with asynchronous transfers is used. For the moment, make all the QueueOMPTarget calls synchronous. More asynchronous experiment can be done at a later point if needed.
Use template to reduce the number of lines in ompBLAS.hpp.
- No
epyc-server
=> Disable the asynchronous behavior of QueueOMPTarget queue and simplify ompBLAS.hpp

src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp
Review after #5020
This helps calcaulations heavy on "LCAOrbitalSet::MO" timer.
In a test case I got from @anbenali.
Compared to our vanilla ompBLAS, timing reported by "LCAOrbitalSet::MO" drops from `60.9992` to `0.4079` seconds.
Note that: our ompBLAS gemm was not properly parallelized. I will address this issue when I PR the batched version.
- Other (please describe): Performance optimization.
- No
JLSE
=> Connect LCAO to cublas gemm

src/Message/CMakeLists.txt, src/Message/catch_main.cpp, src/Platforms/tests/CMakeLists.txt, src/QMCApp/QMCMain.h, src/QMCTools/convert4qmc.cpp, src/QMCTools/convertpw4qmc.cpp, src/QMCTools/qmc-extract-eshdf-kvectors.cpp, src/QMCTools/qmcfinitesize.cpp, src/Sandbox/restart.cpp, src/io/hdf/hdf_archive.cpp, src/io/hdf/hdf_archive.h
No need to add it to the "main" of every executable and simplify linking. A unit test that doesn't use hdf5 doesn't need to link hdf5.
- No
epyc-server
=> Move hdf5 suppressor into file scope.

docs/intro_wavefunction.rst, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
Somehow this change should have been introduced when DiracDeterminantBatched was added.
`<slaterdeterminant gpu="omptarget">` can be used to hit the offload code path in a CUDA+OpenMP offload build. The CUDA one is default.
- New feature
- No
Polaris
=> Allow directly select openmp offload code path.

CMakeLists.txt
Better guard workaround.
- No
epyc-server
=> Restrict memory association workaround to hip<5.5

src/Platforms/SYCL/AccelBLAS_SYCL.hpp, src/Platforms/SYCL/syclBLAS.cpp, src/Platforms/SYCL/syclBLAS.hpp, src/Platforms/tests/test_AccelBLAS.cpp
The gemv_batch of oneMKL doesn't meet our requirement that alpha and beta are vectors. Add our version like cuBLAS_missing_functions.
These are makeshift versions lacking tuning.
- New feature
- No
sunspot
=> Add syclBLAS gemv_batch and ger_batch

.github/workflows/ci-github-actions.yaml
Workaround macos CI failure due to numpy v2 incompatibility (#5050) by requesting v1.26.4
- Bugfix
- No
None. CI needs to run and pass.
=> Request numpy v1.26.4 for macos CI

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/SFNBranch.cpp, src/QMCDrivers/VMC/VMCBatched.cpp, src/Utilities/RunTimeManager.cpp, src/Utilities/RunTimeManager.h
Improve progress monitoring by printing timings for warmup and blocks. Block timing and elapsed time given for first, last, and every ~25% progress. Max 5 timing lines printed.
Also changed output "End of a QMC block" to "End of a QMC section" for clarity.
Sample output:
```
658: VMC Warmup completed in 2.3138e-02 secs
658: =====================================================
658: --- Memory usage report : VMCBatched after Warmup ---
658: =====================================================
658: Available memory on node 0, free + buffers :   27749 MiB
658: Memory footprint by rank 0 on node 0       :     122 MiB
658: =====================================================
658: Completed block    1 of 100 average 0.01264 secs/block after 19.97 secs
658: Completed block   26 of 100 average …
```
=> Print block and warmup timings

src/QMCWaveFunctions/Fermion/DelayedUpdateBatched.h, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/DiracMatrixComputeCUDA.hpp, src/QMCWaveFunctions/Fermion/DiracMatrixComputeOMPTarget.hpp, src/QMCWaveFunctions/tests/benchmark_DiracMatrixComputeCUDA.cpp, src/QMCWaveFunctions/tests/test_DiracMatrixComputeCUDA.cpp, src/QMCWaveFunctions/tests/test_DiracMatrixComputeOMPTarget.cpp
Part 1 of #5061
Previously, all the dirac matrix batched inverters borrow the blas handle from DelayedUpdateBatched resource.
This PR make inverters owing their own blas handles although the compute::Queue remains being shared.
Much less entangled code.
- No
epyc-server
=> Decouple inverter blas handle with DelayedUpdateBatched

CMake/IntelCompilers.cmake, CMake/IntelDPCPPConfig-modified.cmake, CMakeLists.txt, config/build_alcf_aurora_icpx.sh, config/build_alcf_sunspot_icpx.sh
Enable ahead-of-time reduces initialization time by skipping the JIT compilation.
- No
Aurora
=> Enable ahead-of-time compilation when using oneapi

nexus/lib/qmcpack_input.py
One line fix for 1RDM input generation.  Fixes the case when "reuse" is not specified.
Issue reported by @annette-lopez.
- Bugfix
- No
Laptop
=> Nexus: small fix for  1RDM input generation

src/Particle/Walker.h, src/QMCDrivers/MCPopulation.cpp, src/QMCDrivers/MCPopulation.h, src/QMCDrivers/tests/test_MCPopulation.cpp
segment of #5010
`Walker`
* Fix bug with Walker constructor that ignored walker_id, parent_id arguments.
* Add useful documentation to Walker.h
`MCPopulation`
* Refactor into MCPopulation the fission of high multiplicity walkers into 2 or more walkers.
* Generate walker_ids for walkers for each trajectory they start. (i.e. a life)
* Assign parent id of new walkers in useful way.
* Expand in code documentation.
- Bugfix
- New feature
There is should be no user observable change except due to #5019 where walker_id's will be different but still undependable.
- No
OSX laptop
linux x86 vm
_Update the following with a yes where the items …
=> MCPopulation now gives walkers useful walker and parent ids

src/Platforms/CUDA/QueueCUDA.hpp, src/Platforms/OMPTarget/QueueOMPTarget.hpp, src/Platforms/Queue.hpp, src/Platforms/SYCL/QueueSYCL.hpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h, src/QMCWaveFunctions/Fermion/DiracMatrixComputeCUDA.hpp, src/QMCWaveFunctions/Fermion/DiracMatrixComputeOMPTarget.hpp, src/QMCWaveFunctions/Fermion/DiracMatrixInverter.hpp, src/QMCWaveFunctions/tests/test_DiracMatrixComputeOMPTarget.cpp
Introduce DiracMatrixInverter base class to avoid exposing all the inverters via DiracDeteriminantBatched.h
- New feature
- No
epyc-server
=> Introduce DiracMatrixInverter abstraction

src/QMCWaveFunctions/CMakeLists.txt, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/DiracMatrixComputeCUDA.cpp, src/QMCWaveFunctions/Fermion/DiracMatrixComputeCUDA.hpp, src/QMCWaveFunctions/Fermion/DiracMatrixComputeOMPTarget.cpp, src/QMCWaveFunctions/Fermion/DiracMatrixComputeOMPTarget.hpp, src/QMCWaveFunctions/Fermion/DiracMatrixInverter.hpp
This is the last part of https://github.com/QMCPACK/qmcpack/pull/5061
All the template variants are explicitly compiled. This is now prepared for the final (long term) target with all the build variants fused.
Explicit template exposed that a few functions of DiracMatrixComputeOMPTarget cannot be compiled and hence I tried to keep a minimal DiracMatrixComputeOMPTarget.
Since DiracMatrixComputeOMPTarget is indeed a fallback running on host, I simplified the code in  `DiracDeterminantBatched::mw_invertPsiM`
- No
epyc-server
=> Using explicit template for inverter implementation classes

.github/workflows/ci-github-actions.yaml, tests/test_automation/github-actions/ci/run_step.sh
Try GCC 14 to avoid macOS CI failure
- No
None. CI needs to run.
=> Use GCC14 and macos-14 in macOS CI

src/QMCDrivers/MCPopulation.cpp, src/QMCDrivers/VMC/VMCBatched.cpp
MCpopulation::saveWalkerConfigurations should only save data from internal walker configurations not particlesets.
It affects DMC restart.
- Bugfix
- No
epyc-server
=> Fixes  #5069

src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilder.h, src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderCommon.cpp, src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderESHDF.fft.cpp, src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilder_createSPOs.cpp, src/QMCWaveFunctions/BsplineFactory/EinsplineSpinorSetBuilder.cpp
1. ReadOrbitalInfo and ReadOrbitalInfo returning bool removed. Use exception
2. Remove codes related to `Format != ESHDF` already inaccessible.
3. Concentrate bcastBandInfoSet calls
4. Fix OccupyBands_ESHDF hang when error occurs and make it const.
- Bugfix
- No
epyc-server
=> Tidy EinsplineSetBuilder

src/QMCHamiltonians/ACForce.cpp, src/QMCHamiltonians/BareKineticEnergy.cpp, src/QMCHamiltonians/BareKineticEnergy.h, src/QMCHamiltonians/CoulombPBCAA.cpp, src/QMCHamiltonians/CoulombPBCAA.h, src/QMCHamiltonians/CoulombPBCAB.cpp, src/QMCHamiltonians/CoulombPBCAB.h, src/QMCHamiltonians/CoulombPotential.h, src/QMCHamiltonians/LocalECPotential.cpp, src/QMCHamiltonians/LocalECPotential.h, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/NonLocalECPotential.h, src/QMCHamiltonians/OperatorBase.cpp, src/QMCHamiltonians/OperatorBase.h, src/QMCHamiltonians/QMCHamiltonian.cpp, src/QMCHamiltonians/QMCHamiltonian.h, src/QMCHamiltonians/tests/test_bare_kinetic.cpp, src/QMCHamiltonians/tests/test_force.cpp, src/QMCHamiltonians/tests/test_ion_derivs.cpp
Under the assumption that the force is evaluated after energy.
1. There is no need to recompute/return energy during a derivative calculation. Thus name `H::evaluateWithIonDerivs` to `H::evaluateIonDerivs` with the return value removed.
2. No need to keep versions that randomize quadrature grid. Thus remove the non-deterministic variants and remove `Deterministic` in the function names, all the APIs are deterministic.
- Other (please describe): remove unused and simplify existing code paths. 
- No
bora
=> Simplify evaluateIonDerivs used by force calculation.

src/QMCHamiltonians/NonLocalECPComponent.cpp, src/QMCHamiltonians/NonLocalECPComponent.h, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/NonLocalECPotential.h, src/QMCHamiltonians/tests/test_ecp.cpp
I'm only touching the single walker API in this PR. The batched API will be modified in a later PR.
NonLocalECPComponent::tmove_xy_ is renamed to tmove_xy_all_ because it is intended for all the electrons not one. I tried to reduce direct access to tmove_xy_all_ but more relying on passing via function argument.
old code does
```
PP[iat]->evaluateOne(P, iat, Psi, ref_elec, dist[iat], -displ[iat], use_DLA);
if(Tmove)
PP[iat]->contributeTxy(ref_elec, tmove_xy_);
```
two steps. The new code uses a single function and handles the tmove logic inside evaluateOne.
```
PP[iat]->evaluateOne(P, iat, Psi, ref_elec, dist[iat], -displ[iat], tmove_xy_, use_DLA);
```
This facilitates DLTM implementation.
- No
laptop
- Yes. This PR is up to date with …
=> explicitly passing Tmove data as an argument to NonLocalECPComponent::evaluateOne

src/QMCHamiltonians/ECPotentialBuilder.cpp, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/NonLocalECPotential.h, src/QMCHamiltonians/OperatorBase.cpp, src/QMCHamiltonians/OperatorBase.h, src/QMCHamiltonians/tests/test_NonLocalECPotential.cpp
Phasing out `ComputeForces` flag in Hamiltonian member classes. It was used to control force related calculation during Hamiltonian evaluation which is no longer needed. ACForce estimator calls evaluateIonDerivs explicitly for the force calculation. Similar change will be made in Coulomb classes with `ComputeForce`.
- No
laptop
=> Remove ComputeForces flag in NLPP

src/QMCHamiltonians/NonLocalECPComponent.cpp, src/QMCHamiltonians/NonLocalECPComponent.h, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/NonLocalECPotential.h
Similarly to https://github.com/QMCPACK/qmcpack/pull/5091, updated batched APIs.
- New feature
- No
laptop
=> explicitly passing Tmove data as an argument to NonLocalECPComponent::mw_evaluateOne

src/QMCDrivers/MCPopulation.cpp
Address https://github.com/QMCPACK/qmcpack/issues/5106
Should be less confusing to users and can still be visible upon request.
- Bugfix
- No
epyc-server
=> Report walker allocation as debug info not warning.

src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.h
Fixes a bug pointed out by @bkincaid256, which has to do with using SOECPs with multi slater determinants and getting the wrong total energies.  The exact spin integration method was only implemented for single determinants.  This PR prevents that code path. 
- Bugfix
- No
mac
- Yes. Code added or changed in the PR …
=> Prevent SOECP exact spin evaluation with multi slater determinant wave functions due to incomplete code paths

nexus/bin/qmc-fit
A minor fix that autogenerates the valid keys for `qmc-fit`.
```
-f FIT_FUNCTION, --fit FIT_FUNCTION
Fitting function, options are []. (default: linear)
-f FIT_FUNCTION, --fit FIT_FUNCTION
Fitting function, options are ['birch', 'cubic',
'linear', 'morse', 'murnaghan', 'quadratic',
'quartic', 'sqrt', 'vinet']. (default: linear)
```
- Bugfix
- No
local workstation
=> qmc-fit help keys are auto-populated correctly

src/QMCDrivers/CorrelatedSampling/CSVMC.h, src/QMCDrivers/DMC/DMC.cpp, src/QMCDrivers/DMC/DMC.h, src/QMCDrivers/DMC/DMCFactory.cpp, src/QMCDrivers/QMCDriver.h, src/QMCDrivers/QMCDriverInterface.h, src/QMCDrivers/QMCDriverNew.h, src/QMCDrivers/RMC/RMC.h, src/QMCDrivers/VMC/VMC.cpp, src/QMCDrivers/VMC/VMC.h, src/QMCDrivers/VMC/VMCFactory.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.h, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h, src/QMCDrivers/WaveFunctionTester.cpp
Individual derived class should carry the know whether and how many RNGs to carry with.
I'm refactoring legacy drivers here and will later touch the batched drivers.
- No
laptop
=> Move Rng out of QMCDriver base class.

CMake/ClangCompilers.cmake, CMakeLists.txt, src/Particle/CMakeLists.txt, src/Platforms/OMPTarget/CMakeLists.txt, src/QMCWaveFunctions/CMakeLists.txt
I got nvlink failure when using llvm 15 but 16 was OK. So raise the minimal version to 16 when using offload.
Closes #5127. Debug build works fine with clang 16 without -O3.
- No
epyc-server
=> Remove ENABLE_OFFLOAD_CLANG_DEBUG_O3 option in CMake and raise Clang minimal version to 16 when using offload

src/QMCHamiltonians/CMakeLists.txt, src/QMCHamiltonians/Listener.cpp, src/QMCHamiltonians/Listener.hpp, src/QMCHamiltonians/tests/test_Listener.cpp
Provide support functions to work with Listener CrowdEnergyValues that will be used by EnergyDensityEstimator.
TraceManager provided some elaborate ways to combine energy values from a named list of hamiltonian components. I've found we really just need to be able to combine all the different hamiltonian components per particle.  This provides support for that via some helper functions and tests it.
- New feature
- or Refactoring (no functional changes, no api changes)
- No
ubuntu x86 v100
simply a reminder of what we are going to look for …
=> Provide the minimum combined Listener values support EnergyDensityEstimator requires

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/DMC/DMCBatched.h, src/QMCDrivers/QMCDriverNew.cpp, src/QMCDrivers/QMCDriverNew.h, src/QMCDrivers/VMC/VMCBatched.cpp, src/QMCDrivers/VMC/VMCBatched.h, src/QMCDrivers/tests/QMCDriverNewTestWrapper.h
`QMCDriverNew::initializeQMC` creates Crowds and StepContexts. Consider the StepContexts is driver specific. I need to move them out of the base class and create driver-specific variants. For this reason, split `initializeQMC`
- New feature
- No
laptop
=> Split QMCDriverNew::initializeQMC

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/DMC/DMCBatched.h, src/QMCDrivers/QMCDriverFactory.cpp, src/QMCDrivers/QMCDriverNew.cpp, src/QMCDrivers/QMCDriverNew.h, src/QMCDrivers/VMC/VMCBatched.cpp, src/QMCDrivers/VMC/VMCBatched.h, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h, src/QMCDrivers/tests/QMCDriverNewTestWrapper.h, src/QMCDrivers/tests/SetupDMCTest.h, src/QMCDrivers/tests/SetupPools.cpp, src/QMCDrivers/tests/SetupPools.h, src/QMCDrivers/tests/test_DMCBatched.cpp, src/QMCDrivers/tests/test_QMCDriverNew.cpp, src/Utilities/RandomNumberControl.cpp, src/Utilities/RandomNumberControl.h
A step closer to clean up RNG handling in drivers.
1. Capture RNG resource via batched driver constructor. No longer directly access `RandomNumberControl::Children`.
2. Add a RandomNumberGeneratorPool helper class for unit test need of fake RNGs.
3. There are small changes moving step_contexts_ to VMC and DMC drivers that are unrelated to this topic but I was unable to take them out of this PR.
- New feature
- No
laptop
=> Capture RNG resource via batched driver constructor

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/QMCDriverNew.cpp, src/QMCDrivers/QMCDriverNew.h, src/QMCDrivers/VMC/VMCBatched.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp, src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h, src/QMCDrivers/tests/QMCDriverNewTestWrapper.h, src/QMCDrivers/tests/test_QMCDriverNew.cpp
Previously we requires `num_crowds <= num_threads`. There is a bad entanglement between drivers and threads.
1) With this PR, the nature RNGs being part of parallel context gets directly reflected. We check the count of RNGs rather than `num_threads`.
2) When `num_crowds > num_rngs` previously `num_crowds > num_threads`, we just override `num_crowds` to `num_rngs` with a warning instead of a hard stop. It should be more user-friendly.
3) unit tests also benefit from this change. Many test setups become thread independent. With #5133 unit test can pick any number of RNGs.
- No
laptop …
=> Change num_crowds > num_threads handling and also decouple num_crowds from num_threads

src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
closes https://github.com/QMCPACK/qmcpack/issues/5140
assertions are not robust against numerical round error. When evaluating LCAO, the batched and non-batched evaluation may differ slightly due to using gemm and gemv.
- Bugfix
- No
jlse
=> Remove value assertion that caused false positive faiure

src/QMCDrivers/DMC/DMCBatched.cpp, src/QMCDrivers/DMC/DMCDriverInput.cpp, src/QMCDrivers/DMC/DMCDriverInput.h, src/QMCHamiltonians/NonLocalTOperator.cpp, src/QMCHamiltonians/NonLocalTOperator.h, src/QMCHamiltonians/TmoveKind.h, src/QMCHamiltonians/tests/test_NonLocalTOperator.cpp
Clean up the function `thingsThatShouldBeInMyConstructor`. Move the string to enum conversion into the input class.
- No
laptop
=> Cleanup NonLocalTOperator constructor.

src/Containers/OhmmsPETE/OhmmsMatrix.h, src/Containers/OhmmsPETE/tests/test_Matrix.cpp
Right now the Matrix class can only do a widening or narrowing assignment if the Matrices involved have the same dimensions. I don't think this makes much sense and its quite problematic for how I want to write the hdf5 output from the new estimators.  To do that hdf5 output only widening assignments are made i.e. a Matrix<float> is assigned to a Matrix<double>.
#5139 depends on this PR to fix its CI failures.
However there are number of narrowing assigments in the mixed precision all adhere to this matching size rule. Maybe that's an important constraint?  So I have left this behavior. But I do think that probably it should be changed so all Matrix Matrix assignments have the same semantics.
Important to note that through the magic of PETE all the non matching assignments were going …
=> Ohmms matrix assignment operator should be able to do a widening assigment

codecov.yml
Specifically including the test files in the search pattern works. Based on https://docs.codecov.com/docs/ignoring-paths
- No
None
=> codecov configuration: specifically ignore test files

docs/methods.rst
Clarify how to choose and adjust `minwalkers`
- No
epyc-server
=> Update OneShiftOnly doc

src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
Fix test failures in gcc13/14 debug mixed precision builds with added or increased tolerances
https://cdash.qmcpack.org/viewTest.php?onlyfailed&buildid=11547
Closes #4921 
Verified that complex mixed debug builds are also OK.
- No
Ubuntu 24 with gcc13
=> Fix diamond 2x1x1 unit test with mixed precision debug

src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp, src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/TrialWaveFunction.h
SR doesn't need derivatives from KE. so introduce and call `TrialWaveFunction::mw_evaluateParameterDerivativesWF`.
`WFC::mw_evaluateParameterDerivativesWF` exists, I just need to expose it at the TWF level.
- New feature
- No
laptop
=> Call cheaper TrialWaveFunction::mw_evaluateParameterDerivativesWF in SR

src/Particle/DTModes.h, src/QMCWaveFunctions/Jastrow/BsplineFunctor.h, src/QMCWaveFunctions/Jastrow/FakeFunctor.h, src/QMCWaveFunctions/Jastrow/PadeFunctors.h, src/QMCWaveFunctions/Jastrow/TwoBodyJastrow.cpp, src/QMCWaveFunctions/Jastrow/UserFunctor.h
The enum value was incorrect. 0x10 is actually 16 in decimal.
- Bugfix
- No
epyc-server
=> Fix DTmode and its operation in J2

docs/running.rst, src/QMCApp/qmcapp.cpp, tests/solids/diamondC_1x1x1_pp/CMakeLists.txt
Closes #3124 
Enforce QMCPACK input files end in .xml vs have xml string in them
Accurate more verbose message when no valid input specified 
(Could still be nicer for new users, e.g. print list of valid options,  print QMCPACK title and version)
Also: Remove long hidden/untested/undocumented clone feature. There are other ways to do what it does, so simplify by removing.
- Bugfix
- No
All deterministic tests including ensemble tests, gcc14 mpi,
=> Improve input file argument handling

src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
Check gradient element by element instead of using the norm.
Fixes failing gradient asserts in e.g. short-Be_STO-vmc-1-16 runs built with debug, where the gradient is wrongly asserted as zero. https://cdash.qmcpack.org/tests/4052499 . 
```
evalGrad gradient is -8.62777e-06 4.98444e-06 -4.77582e-06
gradient of zeroUnexpected exception thrown in threaded section
Fatal Error. Aborting at Unhandled Exception
```
- Bugfix
- No
sulfur, gcc14 debug builds
=> Remove erroneous gradient check

tests/solids/LiH_solid_1x1x1_pp/CMakeLists.txt
https://cdash.qmcpack.org/tests/4363490
Address rare failure in short-LiH_solid_1x1x1_pp-x-dmc-hf_noj-1-16-totenergy
```
Tests for series 1
Testing quantity: LocalEnergy
reference mean value     :  -8.31413000
reference error bar      :   0.00400000
computed  mean value     :  -8.30212434
computed  error bar      :   0.00462636
pass tolerance           :   0.01200000  (  3.00000000 sigma)
deviation from reference :   0.01200566  (  3.00141515 sigma)
error bar of deviation   :   0.00611581
significance probability :   0.99731258  (gaussian statistics)
status of this test      :   fail
Test status: fail
```
- No
None
_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to …
=> Increase short-LiH_solid_1x1x1_pp-x-dmc-hf_noj-1-16-totenergy error

tests/solids/bccH_1x1x1_ae/CMakeLists.txt
https://cdash.qmcpack.org/tests/4363516
Address rare statistical failure in short-bccH_1x1x1_ae-vmc-all-nodrift_sdj-1-16-totenergy with increased error bar
e.g. Clang18 build gave:
```
Tests for series 0
Testing quantity: LocalEnergy
reference mean value     :  -1.83403200
reference error bar      :   0.00030000
computed  mean value     :  -1.83527856
computed  error bar      :   0.00052208
pass tolerance           :   0.00090000  (  3.00000000 sigma)
deviation from reference :  -0.00124656  ( -4.15519995 sigma)
error bar of deviation   :   0.00060214
significance probability :   0.99996748  (gaussian statistics)
status of this test      :   fail
Test status: fail
```
- No
None …
=> Increase  short-bccH_1x1x1_ae-vmc-all-nodrift_sdj-1-16-totenergy error

src/Estimators/tests/test_OneBodyDensityMatrices.cpp, src/Platforms/CUDA/CUDAallocator.hpp, src/Platforms/DualAllocator.hpp, src/Platforms/OMPTarget/OMPallocator.hpp, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h, src/spline2/BsplineAllocator.hpp, src/spline2/MultiBspline.hpp
1. Simplify template parameters of BsplineAllocator
2. Resolve the last warning about "&input"
https://cdash.qmcpack.org/viewBuildError.php?type=1&buildid=12897
- No
epyc-server
=> Simplify template parameters of BsplineAllocator and remove an unused variable in a unit test

src/QMCWaveFunctions/BsplineFactory/SplineC2C.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2C.h, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h, src/QMCWaveFunctions/BsplineFactory/SplineC2R.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2R.h, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h, src/QMCWaveFunctions/BsplineFactory/SplineR2R.cpp, src/QMCWaveFunctions/BsplineFactory/SplineR2R.h, src/Sandbox/einspline_spo.hpp, src/spline2/BsplineAllocator.hpp, src/spline2/MultiBspline.hpp, src/spline2/tests/test_multi_spline.cpp
1) reduce MultiSpline::create_spline template parameters
2) Make MultiSpline::copy_spline a free function.
- Other (please describe): code refactoring.
- No
epyc-server
=> Clean up around BsplineAllocator.hpp and MultiSpline.hpp

src/QMCTools/DiracParser.cpp
Updates converter to be compatible with DIRAC versions > 22. 
- New feature
- No
mac
=> make convert4qmc compatible with DIRAC versions > 22

src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h, src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h, src/spline2/BsplineAllocator.hpp, src/spline2/MultiBspline.hpp, src/spline2/MultiBsplineBase.hpp, src/spline2/MultiBsplineOffload.hpp
Review after #5195
Introduce MultiSplineBase as the base class for MultiSpline and MultiSplineOffload.
When implementing R2R offload, I'm trying to prevent creating an offload class by copying the whole R2R class. As a preparation step, I need to make MultiSpline abstracted.
- New feature
- No
epyc-server
=> Introduce MultiSplineBase and MultiSplineOffload classes

CMakeLists.txt, src/Platforms/ROCm/cuda2hip.h, src/Utilities/NewTimer.h
When `USE_NVTX_API=ON` and `QMC_CUDA2HIP=ON` rocTX markers are used.
=> Add rocTX support

nexus/bin/qdens
This PR temporarily blocks the `density_cell` and `density_corner` keywords in qdens due to bug #5201. It can go unnoticed easily so it is better to block it until the bug is resolved.
I also slightly organized those keywords to better align with the other options.
- Bug prevention (but not a fix)
- No
NERSC.
- Yes. This PR is up to date with the current state of 'develop'
=> Block the density cell and corner keywords in qdens

nexus/lib/qmcpack.py
In #5184, I introduced the handling of J3 terms in Nexus for SOC calculations. At the time I tested it in CrI3, which has two species. For single-element systems such as Ir, the data structure of J3 terms changes (reported by @rcclay). In this edge case, nothing needs to be done when incorporating the previous Jastrow, since there will be only a single 'uu' term in J3.
- Bugfix
- No
NERSC. Nexus tests are passing.
=> Nexus: Bugfix for SOC J3 terms

src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp
The transferred values are used in ST anyway. There is no need to transfer with a higher precision TT.
I made the change when implementing C2C but forgot to update C2R.
- No
epyc-server
=> Transfer using ST type in C2R

src/Particle/ParticleIO/XMLParticleIO.cpp, src/Particle/ParticleIO/tests/test_xml_io.cpp
No deterministic tests got flagged.
- New feature
- No
laptop
=> Add an input consistency check.

src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderESHDF.fft.cpp
#5078 removed setting `NumDistinctOrbitals` inside `EinsplineSetBuilder::OccupyBands_ESHDF` thus, the printing should also be updated.
- Bugfix
- No
epyc-server
=> Fix printing 0 caused by #5078

nexus/lib/fileio.py
A common way to analyze charge/spin densities in qmcpack is to generate the `*.xsf` data files via `qdens` that reads the data from the native `stat.h5` files. The xsf files can then be further analyzed via `qdens-radial` or other tools. Currently, the data (such as charge density) in the xsf files are written as floats with 8 significant digits (`12.8f`). I think scientific notation is better for this type of data. For example, QE (v7.0) uses scientific notation with 6 significant digits (`12.6E`). In a simple test I did, the integrated charge (norm) has improved significantly using the `12.6E` style for CH4 molecules in a 16^3 Ang box. Here the correct norm is 5.
Old code:
```
Max Density: 0.00069445
Norm: 4.999454429999994
File Size: 111 MB
```
New code:
```
Max Density: 0.0006944463 …
```
=> Improve the xsf format data precision

src/QMCWaveFunctions/Fermion/SlaterDet.cpp, src/QMCWaveFunctions/Fermion/SlaterDet.h, src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h, src/QMCWaveFunctions/Jastrow/TwoBodyJastrow.h, src/QMCWaveFunctions/OptimizableFunctorBase.h, src/QMCWaveFunctions/OptimizableObject.h, src/QMCWaveFunctions/RotatedSPOs.h, src/QMCWaveFunctions/SPOSet.h, src/QMCWaveFunctions/WaveFunctionComponent.h, src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp
myVars are intended for routines of optimizable components interacting with WFOpt. Thus it is cleaner to pull them out of SPOSet/WFC based classes and place it in OptimizableObject class. Namely myVars disappears in derived classes without immediate optimizable contents.
`JeeIOrbitalSoA` and `TwoBodyJastrow` only contain optimizable parameters in their functors but keeps a local myVars for parameter filtering. For now, add local myVars variables. but I'd like to have them eventually going away.
The use of myVars `SlaterDet` is currently no-op and thus removed.
- No
epyc-server
=> Relocate myVars in SPOSet/WFC base classes to OptimizableObject

src/QMCDrivers/QMCDriverInput.h
Missed in #4109 . Set batched full precision recomputation frequency consistent with documentation. Credit to Ye for noticing.
- Bugfix
- No
Sulfur, GCC14 nightly config, via grep.
-No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
=> Set full precision batched recomputation default

src/config.h.cmake.in, src/io/hdf/hdf_archive.cpp
I've encountered two small typos:
- The CMake release variable was spelled `QMCAPCK` instead of `QMCPACK`  
- This doesn't seem to be set anywhere though
- The hdf5 `create` ignores `flags` input
- any created archive would be done with `H5F_ACC_TRUNC` mode only
- There are only a few instances of the alternative `H5F_ACC_EXCL` being used 
```
AFQMC/Wavefunctions/WavefunctionFactory.cpp
1191:        if (!restart.create(restart_file, H5F_ACC_EXCL))
AFQMC/Walkers/tests/test_sharedwset.cpp
252:  if (!dump.create("dummy_walkers.h5", H5F_ACC_EXCL))
317:  if (!dump.create("dummy_walkers.h5", H5F_ACC_EXCL))
458:    if (!dump.create("dummy_walkers.h5", H5F_ACC_EXCL))
```
- Bugfix
- No …
=> Fix two small typos

nexus/requirements.txt, nexus/requirements_minimal.txt, nexus/sphinx_docs/installation.rst
This PR should close #5253. A `requirements.txt` file was added in `qmcpack/nexus/`. I did not add `requirements_minimal.txt` as only numpy is needed for core functionality and adding a file for just a single package seems redundant to me.
Appropriate description has been added to the Nexus documentation. Other smaller issues were also fixed in the docs: python3 support, and `--user` instead of `-user`.
- No
Local Linux Machine
=> Nexus: Add dependency versions file + update docs

src/QMCHamiltonians/EnergyDensityEstimator.cpp, src/QMCHamiltonians/ReferencePoints.cpp, src/QMCHamiltonians/ReferencePoints.h, src/QMCHamiltonians/SpaceGrid.cpp, src/QMCHamiltonians/SpaceGrid.h
- Bugfix
At least on my system check_stat.py cannot successfully read the output of the legacy energy density estimator anymore.  This fixes that.
Consequently the
short-diamondC_1x1x1_pp-vmc-estimator-energydensity-cell-4-4-check
short-diamondC_1x1x1_pp-dmc-estimator-energydensity-cell-4-4-check 
tests pass
- No
dgx workstation.
- Yes Documentation has been added (if …
=> Put some legacy energy density variables back into the correct hdf5 group.

CMake/DetermineDeviceArchitectures.cmake, CMakeLists.txt
Noticed that the value "none" is unnecessary. Just leave ENABLE_SANITIZER empty or unset.
- No
=> Remove "none" option in ENABLE_SANITIZER

config/build_alcf_aurora_icpx.sh, config/build_alcf_polaris_Clang.sh
As CMake option is updated on #5267, Build recipes for Polaris and Aurora need to be updated with removing unnecessary options and simplifying their build names.  
- No
Polaris, Aurora
- No. This PR adds tests to cover any new code, or to catch a bug …
=> Update build recipe for polaris and aurora

docs/installation.rst
Update user guide. Removed ALCF Theta, OLCF Summit and Nersc Cori and added ALCF Aurora.
- No
None
=> Remove manual sections for obsolete machines and add ALCF Aurora

config/build_nersc_perlmutter_Clang.sh
Update build recipe
- No
Perlmutter
=> Update NERSC perlmutter recipe

src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.cpp
Hybridrep spinor wave functions wasn't working because the orbital norm check was still being used in the hybridrep splines. This needs to be disabled since individual up/down components aren't normalized, only the total spinor is. This is now fixed, and enables hybridrep with spinors. 
- Bugfix
- No
mac 
- Yes. …
=> disable norm check for hybridrep on spinor WFs

src/Estimators/tests/test_EnergyDensityInput.cpp, src/Estimators/tests/test_PerParticleHamiltonianLogger.cpp, src/QMCDrivers/WFOpt/QMCCostFunctionBase.cpp, src/QMCDrivers/WFOpt/QMCCostFunctionBase.h, src/QMCDrivers/tests/test_QMCCostFunctionBase.cpp, src/QMCHamiltonians/tests/test_SOECPotential.cpp, src/QMCWaveFunctions/LCAO/CuspCorrectionConstruction.cpp, src/QMCWaveFunctions/tests/test_J1OrbitalSoA.cpp, src/QMCWaveFunctions/tests/test_J1Spin.cpp, src/QMCWaveFunctions/tests/test_LCAOrbitalBuilder.cpp, src/QMCWaveFunctions/tests/test_MO.cpp, src/QMCWaveFunctions/tests/test_MO_spinor.cpp, src/QMCWaveFunctions/tests/test_cartesian_ao.cpp, src/QMCWaveFunctions/tests/test_pyscf_complex_MO.cpp, src/QMCWaveFunctions/tests/test_soa_cusp_corr.cpp, src/Sandbox/restart.cpp, src/Utilities/TimerManager.cpp, src/Utilities/TimerManager.h, src/Utilities/tests/test_timer.cpp
Less entanglement and allow easy use of timers.
- No
frontier
=> Reduce OhmmsData/Libxml2Doc.h propagation via TimerManager.h

src/Utilities/for_testing/ApproximateEquality.cpp, src/Utilities/for_testing/ApproximateEquality.hpp, src/Utilities/for_testing/CMakeLists.txt, src/Utilities/for_testing/MatrixAccessor.hpp, src/Utilities/for_testing/NativeInitializerPrint.hpp, src/Utilities/for_testing/checkMatrix.hpp, src/Utilities/for_testing/checkVector.hpp, src/Utilities/tests/for_testing/CMakeLists.txt, src/Utilities/tests/for_testing/test_NativeInitializerPrint.cpp, src/Utilities/tests/for_testing/test_checkVector.cpp
Expanded Utilities/for_testing.
See title
Incoming PR's will have tests that use these and provide coverage.
- New feature
- No
=> Add checkVector test helper equivalent to checkMatrix, NativePrint for std::unordered_map and std::array

tests/molecules/He_param/CMakeLists.txt
Fix failure found in https://github.com/QMCPACK/qmcpack/pull/5298#issuecomment-2637259140
- Bugfix
- No
epyc-server
=> Fix short-He_orb_rot_param_grad parameter checking.

src/QMCHamiltonians/CMakeLists.txt, src/QMCHamiltonians/CoulombPBCAA.cpp, src/QMCHamiltonians/CoulombPBCAA.h, src/QMCHamiltonians/CoulombPBCAB.cpp, src/QMCHamiltonians/CoulombPBCAB.h, src/QMCHamiltonians/CoulombPotential.cpp, src/QMCHamiltonians/CoulombPotential.h, src/QMCHamiltonians/CoulombPotentialFactory.cpp, src/QMCHamiltonians/LocalECPotential.cpp, src/QMCHamiltonians/LocalECPotential.h, src/QMCHamiltonians/NonLocalECPotential.cpp, src/QMCHamiltonians/tests/test_force.cpp
The default decay behavior for `::mw_evaluatePerParticleWithToperator` breaks any estimator needing per particle Hamiltonian values reported when tmoves were turned on.  See #5245. Here we explicity declare and define  `::mw_evaluatePerParticleWithToperator` to `::mw_evaluatePerParticle` instead of `::mw_evaluateWithToperator` for  
`CoulombPotential`, `CoulombPBCAA`, and `CoulombPBCAB` so that these energies are not omitted from the Batched EnergyDensityEstimator port.
We remove the unnecessary templating on real type from CoulombPotential and split its header into implementation and header to reduce unnecessary recompilation.
- Bugfix
- New feature
- Testing changes, in this PR no …
=> Hamiltonian updates for batched estimators

tests/test_automation/github-actions/ci/run_step.sh
deterministic-unit_test_estimators has a 100% fail rate on mac ci
As far as I know there is no hint of either a full diagnosis or a solution; the problem is not seen elsewhere including other arm systems.
After such a long time I think the merit of having a passing CI exceeds the merit of having the mac ci fail, which results in a red check mark for every PR. If we merge this PR, I'll add a fresh issue on the mac problem.
- No
None. Check for scripting errors.
- Yes/No. Documentation has been added (if …
=> Skip deterministic-unit_test_estimators on mac in ci

src/QMCWaveFunctions/BsplineFactory/SplineC2C.cpp, src/QMCWaveFunctions/BsplineFactory/SplineR2R.cpp
Align datatype.
- Bugfix
- No
laptop
=> Align applyRotation reduction datatype in the mixed precision case.

src/Platforms/SYCL/SYCLDeviceManager.cpp
Reduce sycl implementation leaking. Works also for oneapi 2025.
- Bugfix
- No
Aurora (PVC) and epyc-server (Arc B580)
=> Make openmp/SYCL interop portable across oneapi 2024/2025

src/QMCDrivers/WalkerLogCollector.cpp, src/QMCDrivers/WalkerLogManager.cpp
Don't activate timer when features are inactive.
- Bugfix
- No
laptop
=> Move timers after no-op early return in WalkerLog classes

src/QMCWaveFunctions/tests/FakeSPO.cpp, src/QMCWaveFunctions/tests/FakeSPO.h, src/QMCWaveFunctions/tests/test_DiracDeterminant.cpp, src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp, src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp
This PR ports `FakeSPO` to the templatized version of `SPOSet`, namely `SPOSetT<T>`, which is introduced in #5306. 
- No
Linux with GCC and Open MPI.
- Yes. This PR is up to date with the current state of 'develop'
=> Porting `FakeSPO` to `SPOSetT<T>`

tests/solids/diamondC_2x1x1-Gaussian_pp_MSD/CMakeLists.txt
Address 3 statistical failures https://cdash.qmcpack.org/testSummary.php?project=1&name=short-diamondC_2x1x1-Gaussian_pp_MSD-1-16-localecp&date=2025-02-20
- No
None
=> Increase diamondC_2x1x1-Gaussian_pp localecp tol

tests/test_automation/nightly_test_scripts/nightly_ornl.sh, tests/test_automation/nightly_test_scripts/ornl_setup.sh, tests/test_automation/nightly_test_scripts/ornl_setup_environments.sh, tests/test_automation/nightly_test_scripts/ornl_versions.sh
Current spack-based recipe for nightly tests. numpy2 is forced and works for testing, including PySCF. Still missing for science use or running the full set of tutorials - py-spglib (currently outdated, forces numpy <2) and PySCF optional packages such as geomeTRIC and pyscf-dispersion (not yet in spack).
- No
nitrogen*, sulfur.
=> Update nightly test configurations with numpy2

CMakeLists.txt, docs/installation.rst
QMC_DISABLE_HIP_HOST_REGISTER default to OFF
QMC_OFFLOAD_MEM_ASSOCIATED default ON.
QMC_OFFLOAD_MEM_ASSOCIATED is clearly required. Otherwise hipMemcpyAsyc 10x slower.
In the following study, I investigated our cmake option QMC_DISABLE_HIP_HOST_REGISTER
and a libomptarget environment variable LIBOMPTARGET_AMDGPU_MAX_ASYNC_COPY_BYTES=0. This option doesn't behave exactly as its name indicates. For transfer smaller than specified size, the runtime uses a staging buffer for transfer which needs an extra copy from the source to the staging buffer. I don't see benefit of this "optimizatoin". setting 0 stops this code path.
```
cat timing.out 
w1792    DMC  Particle  Jastrow  Det  SPO  Prod
input                a8      10.1874 1.5654 0.5169 2.8677 1.3319 9.626
input-hostreg        a8 …
```
=> Revise cmake option default values for AMD GPUs

src/Particle/CMakeLists.txt, src/Particle/Lattice/CrystalLattice.cpp, src/Particle/Lattice/CrystalLattice.h, src/Particle/Lattice/LatticeAnalyzer.h, src/Particle/Lattice/ParticleBConds3D.h, src/Particle/Lattice/tests/CMakeLists.txt, src/Particle/Lattice/tests/test_CrystalLattice.cpp
@ye-luo suggestion this works as a separate PR.
Build and link CrystalLattice once as opposed to repeatedly due to including implementation into header.
Add accessors to facilitate encapsulation and full precision lattices.
this supports #5327 
- New feature
- No
sdgx server
- Yes Code …
=> explicitly instantiate CrystalLattice simplify initialization

src/Particle/Lattice/CrystalLattice.h, src/Particle/Lattice/ParticleBConds.h, src/Particle/Lattice/ParticleBConds3DSoa.h
Make functions as templates to support precision mix.
- New feature
- No
epyc-server
=> Make DTD_BConds constructor support flexible precision of CrystalLattice

docs/hamiltonianobservable.rst
Fix simple typos
- Bugfix
- No
None
=> Fix typos in Hamiltonian Observable docs

tests/solids/diamondC_1x1x1_pp/CMakeLists.txt, tests/solids/diamondC_1x1x1_pp/qmc_short_vmcbatch_kspace.in.xml
Add batched version of existing short test.
Also, remove offload checks in CMakeLists.txt
In part motivated by #5348 . The new test passes on CPUs.
- No
Ubuntu24, AOCC+AOCL
=> Add kspace jastrow batched test

src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminant.h, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.h, src/QMCWaveFunctions/WaveFunctionComponent.cpp, src/QMCWaveFunctions/tests/test_SlaterDet.cpp
Fixes #5358 and maybe #5283?
WFC::mw_eval/ratioGradWithSpin falling back to WFC::eval/ratioGradWithSpin causes mixing batched and non-batched API calls. proposed the move using non-batched API and then crash in the mw_accept. To prevent this, default fallback should be WFC::mw_eval/ratioGrad.
With this change, spinor aware classes should implement both WFC::mw_eval/ratioGradWithSpin and WFC::eval/ratioGradWithSpin although the batched implementation can be just a loop.
DummyDiracDetWithoutMW class in the unit test is removed due to not satisfying the above requirement.
- Bugfix
- No
epyc-server
- Yes. Code added or changed in the PR has been …
=> Fix mw_evalGradWithSpin/mw_ratioGradWithSpin fallback.

nexus/lib/machines.py, nexus/tests/unit/test_machines.py
This slurm-based largely CPU machine ( https://docs.cades.olcf.ornl.gov/baseline_user_guide/baseline_user_guide.html#baseline-user-guide ) has a few different accessible maximum node counts and memory sizes depending on the user's project. I will evolve the machine definition as I gain access to other projects. Current version should be enough for <20 node & low memory runs in all queues, which is likely the majority of usage.
- New feature
- No
Baseline. No issues found using in full production (PySCF->DMC).
=> Nexus: Add ORNL baseline machine

src/Particle/ParticleSet.cpp, src/QMCHamiltonians/tests/test_ecp.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminant.h, src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.h, src/QMCWaveFunctions/Fermion/SlaterDet.h, src/QMCWaveFunctions/TrialWaveFunction.cpp, src/QMCWaveFunctions/WaveFunctionComponent.cpp, src/QMCWaveFunctions/WaveFunctionComponent.h, src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp, src/Utilities/tests/for_testing/test_NativeInitializerPrint.cpp, tests/solids/bccMo_2x1x1_SOREP/CMakeLists.txt, tests/solids/bccMo_2x1x1_SOREP/det_Mo-vmcbatch-dmcbatch.in.xml, tests/solids/bccMo_2x1x1_SOREP/det_Mo-vmcbatch.in.xml
There is a bug introduced in #5360 and discovered when adding unit test coverage.
`WaveFunctionComponent::mw_ratioGradWithSpin` should not overwrite `spingrad_new` which should be accumulative.
I also fixed `ParticleSet::mw_makeMove` to align with `ParticleSet::makeMove` behavior, it affects unit tests but not actual simulation.
- Bugfix
- No
epyc-server
=> Fix a few spinor related batched API bugs

nexus/bin/qdens
Allow qdens to run without warnings
- Bugfix
- No
nitrogen2, nightly python config
=> Fix Angstrom escape in qdens

src/Estimators/OneBodyDensityMatrices.h, src/Estimators/tests/test_MagnetizationDensity.cpp, src/QMCHamiltonians/DensityMatrices1B.h, src/QMCWaveFunctions/CompositeSPOSet.cpp, src/QMCWaveFunctions/CompositeSPOSet.h, src/QMCWaveFunctions/tests/ConstantSPOSet.cpp, src/QMCWaveFunctions/tests/ConstantSPOSet.h, src/QMCWaveFunctions/tests/test_CompositeSPOSet.cpp, src/QMCWaveFunctions/tests/test_ConstantSPOSet.cpp, src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp, src/QMCWaveFunctions/tests/test_SlaterDet.cpp
Introducing templates for the classes derived from `SPOSetT<T>`. This is the following change towards a unified build for real, complex, and mixed-precision, started from #5306, and separated from #5355.
- No
Linux with GCC
=> More template classes derived from `SPOSetT<T>`

src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.cpp, src/QMCWaveFunctions/BsplineFactory/SplineSetReader.cpp
Fixed a bug introduced in https://github.com/QMCPACK/qmcpack/pull/4849/files
It caused reading the same dump file from every MPI rank.
- Bugfix
- No
Aurora
=> Spline dump should only be read by rank 0.

nexus/lib/qmcpack_input.py, nexus/tests/unit/test_qmcpack_analyzer.py, nexus/tests/unit/test_qmcpack_input.py
Add support for features Cody's project needs:
- stochastic reconfiguration optimizer inputs
- `<rotate_spo>` wrapper around `<sposet>`
- improved k-space jastrow generation
- New feature
- No
Laptop
=> Nexus: support for stochastic reconfiguration and basic orbital rotation

tests/test_automation/nightly_test_scripts/nightly_ornl.sh, tests/test_automation/nightly_test_scripts/ornl_setup.sh, tests/test_automation/nightly_test_scripts/ornl_setup_environments.sh, tests/test_automation/nightly_test_scripts/ornl_versions.sh
Latest version of nightlies.
Add a asan build. Will adjust over time, but the intent is to run at least all the short tests in at least one build configuration.
The RMGDFT spack package is modified to allow recent boost.
- No
sulfur
=> Update nightlies: add asan build, rmgdft develop version

src/Utilities/SimpleParser.cpp, src/Utilities/SimpleParser.h, src/Utilities/for_testing/CMakeLists.txt, src/Utilities/for_testing/checkVector.hpp, src/Utilities/tests/for_testing/test_checkVector.cpp, src/Utilities/tests/test_parser.cpp
Utilities checkVector for vector of TinyVector, more strict C++ for simple parser.  NULL and nullptr aren't the same thing even if they are often represent as such, some compilers/runtimes can call foul.  Get won't put anything in char if stream is empty so that also can be bad. 
- Bugfix
- New feature
- No
simply a reminder of what we are going to …
=> Utilities checkVector for vector of TinyVector, more strict C++ for simple parser

src/QMCDrivers/QMCDriverNew.cpp
Help the user by suggesting a walker count that would be load balanced when imbalance is detected.
- New feature
- No
sulfur, gcc14. A few by-hand MPI task and OpenMP thread count settings.
=> Suggest walker totals to achieve VMC load balance

src/Platforms/DeviceAllocator.hpp, src/Platforms/DualAllocator.hpp, src/Platforms/DualAllocatorAliases.hpp
Separating `DeviceAllocator` in a dedicated header from `DualAllocatorAlises.hpp` allows the other objects or files to include `DeviceAllocator` specifically.
- No
=> Separate `DeviceAllocator`

CMake/IntelDPCPPConfig-modified.cmake
CL/sycl.hpp has been deprecated long time ago.
A fix for oneapi 2025.1
- No
epyc-server
=> Update CMake/IntelDPCPPConfig-modified.cmake for oneapi 2025.1

src/Containers/tests/test_dual_allocators_ohmms_containers.cpp, src/Particle/RealSpacePositionsOMPTarget.h, src/Particle/SoaDistanceTableAAOMPTarget.h, src/Particle/SoaDistanceTableABOMPTarget.h, src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.h, src/QMCWaveFunctions/tests/test_DiracMatrixInverterOMPTarget.cpp
Only use `OMPTarget/OffloadAlignedAllocators.hpp` outside platforms.
- No
laptop
=> Consolidate header file inclusion

nexus/lib/pwscf.py
When QE is installed with HDF5 support(default to compile pw2qmcpack.x), instead of the charge-density.dat and spin-polarization.dat files, a single charge_density.hdf5 file is produced. Currently Nexus does not support transferring results between simulation objects with hdf5 extensions. 
I have noticed that while creating these softlinks, Nexus does not actually check if the .dat file exists in the reference directory. I initially tried implementing these checks, but it broke several tests. New code checks if there is a charge-density.hdf5 file in the reference directory, if not then assumes there is a .dat file (which is the current behavior). 
- New feature
- No. Passes all tests in nxs-test.
Python 3.12.8
- No. …
=> Nexus: QE HDF5 charge density results support

nexus/lib/structure.py
Starting with v2.5.0 SPGLIB returns using SpglibDataset type from get_symmetry_dataset function, rather than using native dictionary. Current PR does type checking to transfer that information to Nexus and preserves compatibility. 
- Bugfix
- No: All tests in nxs-test pass. I downgraded spglib to 2.4.0 and upgraded to 2.6.0 then ran the tests after each case. 
Python 3.12.8
=> Nexus: Fix spglib compatibility

tests/molecules/CHN_ae/CMakeLists.txt
Fix a few statistical failures https://cdash.qmcpack.org/testSummary.php?project=1&name=short-chn_ae_cuspCorrection-vmc-1-16-kinetic&date=2025-04-11
- No
None
=> Address statistical failures in short-chn_ae_cuspCorrection-vmc-1-16-kinetic 

.github/pull_request_template.md
Attempt to avoid tasklist feature that shows "N of 5" tasks complete for items that are not a list of tasks to be completed
Preview on GitHub shows bulleted list with check boxes
- Bugfix
- No
None.
=> Bypass tasklist feature in PR template

src/Utilities/FakeRandom.cpp, src/Utilities/FakeRandom.h, src/Utilities/RandomBase.h, src/Utilities/StdRandom.cpp, src/Utilities/StdRandom.h, src/Utilities/tests/test_FakeRandom.cpp, src/Utilities/tests/test_StdRandom.cpp
In https://github.com/QMCPACK/qmcpack/pull/4650, the copy assign operator wasn't implemented properly.
It caused misbehaving https://github.com/QMCPACK/qmcpack/blob/a5ad8e09d8d38d506cb2f806ffd89690d9ed6fa1/src/QMCDrivers/WFOpt/QMCCostFunction.cpp#L520
when invoked via base classes.
Only legacy driver got affected, batched driver didn't due to not using `MoverRng` but its full clones.
This issue got surfaced when investigating the failure of #5435.
- Bugfix
- No
laptop
* * [x] This PR adds tests to cover any new code, or to catch a bug that is being fixed
* * [ ] Documentation has been added …
=> Fix RNG copy assign operator

src/QMCDrivers/WFOpt/QMCCostFunction.cpp, src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp
Should make GradientTest faster.
- No
laptop
=> Bypass calls to Cost() in wavefunction optimization. Avoid derivative computation and excessive printout in finite difference

docs/developing.rst
Move contents of wiki page to manual. A few minor edits + also change copyright date in example.
Once merged I will remove it from https://github.com/QMCPACK/qmcpack/wiki/Release-process
- No
None
* * [X] This PR is up to date with current the current state of 'develop'
* * [X] Documentation has been added (if appropriate)
=> Add release process to development section of manual

src/Containers/OhmmsPETE/OhmmsMatrix.h, src/Containers/OhmmsPETE/OhmmsVector.h, src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp
https://github.com/QMCPACK/qmcpack/pull/5449 exposed some allowed risky behaviors of OhmmsMatrix and I decided to eliminate all of them. So doing the following.
1. get ride of `OhmmsMatrix::attachReference(*ptr)`, matrix dimensions mush be provided.
2. OhmmsMatrix no longer keeps TotSize, fully relies on the underlying container.
3. OhmmsMatrix::free set D1 and D2 to 0.
4. Forbid calling `attachReference` when containers do own memory effectively blocking lazy free.
- Bugfix
- No
epyc-server
=> Enhance OhmmsVector/Matrix safety

src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.h, src/QMCWaveFunctions/tests/test_spo_collection_input_LCAO_xml.cpp, src/QMCWaveFunctions/tests/test_spo_collection_input_spline.cpp
This PR changed how the legacy input was consumed. No change to the input.
I moved spsoet creation outside the determinant parsing/creation.
I also noticed that input tests were not exactly mimicking legacy. So I adjusted them. 
There is one benefit. There was a bug that code crash if a requested sposet name cannot be found.
This PR will report a clean user error message.
- Bugfix
- No
epyc-server
=> Adjust parsing legacy input when sposets are implicitly inside determiants

src/Estimators/tests/test_MagnetizationDensity.cpp, src/QMCDrivers/WaveFunctionTester.cpp, src/QMCHamiltonians/tests/test_SOECPotential.cpp, src/QMCHamiltonians/tests/test_ecp.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminant.h, src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h, src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.cpp, src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.h, src/QMCWaveFunctions/Fermion/SlaterDet.cpp, src/QMCWaveFunctions/Fermion/SlaterDet.h, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp, src/QMCWaveFunctions/Fermion/SlaterDetBuilder.h, src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.cpp, src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.h, src/QMCWaveFunctions/WaveFunctionComponent.h, src/QMCWaveFunctions/tests/test_DiracDeterminant.cpp, src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp, src/QMCWaveFunctions/tests/test_RotatedSPOs_LCAO.cpp, src/QMCWaveFunctions/tests/test_SlaterDet.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp, src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
Depends on #5461
This PR move sposet ownership from DiracDeterminant to SlaterDet.
SlaterDet has the proper knowledge how many unique sposets are actually used by the deterimants.
This is a necessary step to have clean handling of optimization in the case of restricted HF.
- Bugfix. More of a conceptual bug.
- No
epyc-server
=> Move sposet ownership from DiracDeterminant to SlaterDet

CMakeLists.txt, config/build_olcf_frontier_ROCm.sh, docs/installation.rst
HPE/Cray has discontinued CrayLinuxEnvironment for a very long time. The last machine I had access was Theta.
Using this setting is harmful on modern Cray machines. This PR removes the requirement of using `-DDCMAKE_SYSTEM_NAME=CrayLinuxEnvironmen`. In case a user still has access to old machines, this setting can still be activated as supported by CMake.
- Yes
- No
Frontier
=> Remove CrayLinuxEnvironment related setting.

tests/solids/diamondC_1x1x1_pp/CMakeLists.txt, tests/solids/diamondC_1x1x1_pp/det_qmc_short_edens_cell.in.xml, tests/solids/diamondC_1x1x1_pp/det_qmc_short_edens_voronoi.in.xml, tests/solids/diamondC_1x1x1_pp/det_qmc_short_vmcbatch_edens_cell.in.xml, tests/solids/diamondC_1x1x1_pp/det_qmc_short_vmcbatch_edens_voronoi.in.xml
As part of investigating #5468 , add some single core deterministic tests. There are no existing deterministic energy density estimator tests. The new tests currently only verify that the underlying VMC run is not changed by the estimators; the existing proven check data for the VMC only runs is used. Legacy passes. Batched changes the result but I am uncertain if this estimator was fully plumbed or if it is reasonable to keep the old behavior; to be revisited once @PDoakORNL is back. 
Once we understand the issue with the existing tests &/or implementation, these new tests should be updated with a check on the estimator results following the existing pattern for the short tests defined in the same file.
- Testing changes (e.g. new …
=> Add partial deterministic energy density estimator tests

src/QMCWaveFunctions/Fermion/DelayedUpdateAccel.h, src/QMCWaveFunctions/Fermion/DiracDeterminant.h
After #5442, `DelayedUpdateCUDA` can handle both CUDA and SYCL cases. This PR renames it to `DelayedUpdateAccel`.
- No
=> Renaming `DelayedUpdateCUDA` -> `DelayedUpdateAccel`

src/QMCWaveFunctions/tests/CMakeLists.txt, src/QMCWaveFunctions/tests/benchmark_SolverInverters.cpp
- Now `benchmark_SolverInverters` takes normal precision value, alongside the full precision.
- Add benchmark test for `SolverInverters` with SYCL case. Related to #5485
- No
Aurora
=> Add SYCL benchmark for `SolverInverters`

docs/developing.rst
Add the note on clang-format off from the wiki, make a bit more accessible. Will remove https://github.com/QMCPACK/qmcpack/wiki/Source-formatting after merge.
- No
None. Check rtd build
* * [X] Documentation has been added (if appropriate)
=> Update formatting docs

src/Numerics/OneDimQuinticSpline.h
Minor fix. Avoid since not allowed in C++20.
(Noticed while enabling all warnings for a test build. Blitz, used by ppconvert, is also guilty)
- Bugfix
- No
gcc14.2 mpi, nightly config
=> Avoid tempate id in quintic spline constructor

src/Concurrency/ParallelExecutorOPENMP.hpp
sycl::exception is based on std::exception not std::runtime_error. The current code swallows it without printing out the what() string.
- Bugfix
- No
laptop
=> Fix error handling in ParallelExecutorOPENMP.hpp

src/Utilities/string_utils.h
Avoid thousands of sign-comparison warnings when QMCPACK is built with -Wsign-compare
Also removed some commented code
- Bugfix
- No
GCC13, Ubuntu 24 LTS
=> Fix size types in string_utils

src/Containers/OhmmsPETE/OhmmsArray.h, src/Containers/OhmmsPETE/OhmmsVector.h, src/Estimators/TraceManager.h, src/Platforms/MemoryUsage.cpp, src/io/hdf/hdf_stl.h
Sign comparison fixes to fully clean TraceManager, OhmmsArray, OhmmsVector. Couple of fixes to hdf_stl and MemoryUsage but they need more work.
This gets us below 10^4 sign comparison warnings (!) when compiled with gcc13 and -Wsign-compare 
- Bugfix
- No
GCC13, Ubuntu 24 LTS
* * [ ] This PR adds tests to …
=> Sign comparison fixes: TraceManager, OhmmsArray, OhmmsVector, hdf_stl, MemoryUsage

src/QMCWaveFunctions/Fermion/cuSolverInverter.hpp, src/QMCWaveFunctions/Fermion/rocSolverInverter.hpp
After #5442, the `hstream_` data member is not required in `[cu/roc]SolverInverter`. This PR deletes it.
- No
Linux with CUDA.
=> Delete `hstream_` data member from `[cu/roc]SolverInverter`

CMake/macros.cmake, tests/io/CMakeLists.txt, tests/performance/C-graphite/CMakeLists.txt, tests/performance/C-molecule/CMakeLists.txt, tests/performance/NiO/CMakeLists.txt
`r` MPI rank, `t` thread, `s` series
The new nomenclature allows accurate filtering.
- No
epyc-server
=> More verbose test name r1-t16-s2 instead of 1-16-2

src/Estimators/EstimatorManagerNew.cpp, src/Estimators/EstimatorManagerNew.h, src/Estimators/OperatorEstBase.cpp, src/Estimators/OperatorEstBase.h, src/Estimators/tests/test_manager_mpi.cpp
`OperatorEstBase::zero` becomes a virtual method, more complex estimators are better off not packing all their data into the share `data_` buffer so overriding to customize zeroing is necessary.
`OperatorEstBase::collect`
no longer has the side effect of zeroing the `OperatorEstBase` objects passed to it.
refactor split of collect `OperatorEstBase::makeBlockAverages` otherwise unchanged.
typo in test program.
- New feature
- No
sdgx2
* * [x] I have read the …
=> fixes for more complex estimators

src/Estimators/EnergyDensityEstimator.cpp, src/Estimators/NEReferencePoints.cpp, src/Estimators/StructureFactorEstimator.cpp, src/io/hdf/hdf_archive.h
Fix hdf_archive::write const correctness.
- Bugfix
- No
epyc-server
=> Use const ref in hdf_archive::write APIs

src/.clang-tidy
The .clang-tidy for the project contained an option no longer supported and when used with clangd 20.1.4 integrated with clang-tidy this causes an error.  With the tooling I'm using this causes a popup everytime a file is saved and clangd rechecks it. From the documentation I can find this check has been deprecated for a very long time.
I turned on some other checks that were useful to me.
- Bugfix
- No
sdgx2
* * [x] This PR is …
=> Update clang tidy

nexus/lib/machines.py, nexus/tests/unit/test_machines.py
Adds Frontier to machine.py. The added tests only cover the CPU-only submissions. I think the tests have a special way to treat gpu runs only for Summit. I think gpu runs are also not tested for other supercomputers. 
- New feature
- No
MacOS, python 3.11
* * [ ] I have read the pull request guidance and develop docs
=> Nexus: Frontier added in machines.py

src/io/hdf/hdf_archive.cpp, src/io/hdf/hdf_archive.h, src/io/hdf/hdf_dataproxy.h, src/io/hdf/hdf_pete.h, src/io/hdf/hdf_wrapper_functions.h, src/io/hdf/tests/test_hdf_archive.cpp
hdf5 archive lacks support for appending to hdf5 datasets which is present in the hdf_wrappers.  This PR extends this functionality to the hdf_archive level allowing new modules to append to hdf5 datasets without resorting to using Observable helper.  New estimators should use this functionality instread of observable helper. Revives some code from #4540.
- New feature
- No
sdgx2
* * [x] I have read the pull …
=> Add append support to Hdf archive

docs/developing.rst
Mantion the gh line used the last couple of releases. The old changelog tools tend not to be usable due to rate limits.
- No
None
* * [X] Documentation has been added (if appropriate)
=> Mention gh tool in release docs

src/AFQMC/Memory/CUDA/cuda_arch.cpp, src/AFQMC/Memory/HIP/hip_arch.cpp, src/AFQMC/Numerics/tests/test_dense_numerics.cpp, tests/test_automation/github-actions/ci/run_step_ornl-sulfur-2.sh
Due to recent change on sulfur, CUDA version on the offload CI case needs to be updated.
Fix a wrong stride used in test_afqmc_numerics.
- Bugfix
- No
epyc-server
=> Bump up CUDA version in CI and fix test_afqmc_numerics

src/QMCWaveFunctions/BsplineFactory/EinsplineSpinorSetBuilder.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2C.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp, src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h, src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp, src/QMCWaveFunctions/tests/test_einset_spinor.cpp, src/QMCWaveFunctions/tests/test_spline_applyrotation.cpp
Please also follow the [GitHub Pull Request guidance](https://qmcpack.readthedocs.io/en/develop/developing.html#github-pull-request-guidance). As much as possible, try to avoid the ["Don't"s](https://qmcpack.readthedocs.io/en/develop/developing.html#don-t) to help maintain a high development velocity.
Implements orbital rotations for SplineC2COMPTarget. Basically, it keeps a copy of the spline coeffs on the host, and whenever the splines are rotated, it does the rotation on the CPU and offloads the new spline coeffs to the GPU for later use. This is the simplest approach, and should be fine for production calcualtions. …
=> Orbital Rotation for SplineC2COMPTarget

CMakeLists.txt, external_codes/boost_multi/multi/include/boost/multi/adaptors/cuda/cublas/context.hpp, src/AFQMC/Numerics/detail/HIP/hipblas_wrapper.hpp, src/Platforms/ROCm/CMakeLists.txt, src/Platforms/ROCm/cuda2hip.h, src/Platforms/ROCm/hipBLAS.cpp, src/Platforms/ROCm/hipBLAS.hpp, src/Platforms/ROCm/hipblasTypeMapping.hpp
- Replaced `hipblasComplex` with `hipFloatComplex` and `hipblasDoubleComplex` with
`hipDoubleComplex` to reflect changes in ROCm 6.0+ and support ROCm 7.0,
where the old types have been removed.
- Added support for building with ROCm 6.x by using `-DHIPBLAS_V2`.
Verified builds with both ROCm 6.0 and 7.0.
=> Replace deprecated hipBLAS complex types for ROCm 6.0+ and 7.0

src/QMCApp/QMCMain.cpp
When using a script or mpi launcher exposing one GPU per MPI rank, the code prints out
```
Accelerators per node = 1
```
which caused confusion on multi-GPU nodes.
What the code print is actually the number of visible GPUs by rank 0.
Thus change the printout to
```
Accelerators per rank = 1
```
- Bugfix
- No
Aurora
=> Printout correction "Accelerators per rank"

CMake/macros.cmake, CMake/unit_test.cmake, CMakeLists.txt, config/sanitizers/lsan.supp
In my development environment every unit test fails asan for a mpi build. This fixes that. It also makes it possible to use the lsan suppression file at all with ctest.
- Bugfix
- New feature
- No
sdgx2
* * [x] …
=> running unit tests with asan on broken for openmpi

src/QMCDrivers/WalkerLogBuffer.h, src/QMCDrivers/WalkerLogCollector.h, src/QMCDrivers/WalkerLogManager.cpp, src/QMCDrivers/WalkerLogManager.h, src/QMCDrivers/tests/CMakeLists.txt, src/QMCDrivers/tests/ValidWalkerLogInput.h, src/QMCDrivers/tests/test_WalkerLogManager.cpp
I see no documented reason for why move constructors or the rule of five in general should be broken for `WalkerLog*` classes.  And it became a subtle use after return asan issue when refactoring batched drivers. I have addressed this sufficiently to address work needed for testing of variable estimator measurements to be sound and testable. I have also added the the beginning of actual unit testing for WalkerLogManager and a testing data class for WalkerLogInput.
There was a nasty shared state reference which so far looks to have been unused.  This will all get more coverage int he variable esimator measurement period PR.
- Bugfix
- New feature
- No
_Update the following with an [x] …
=> WalkerLogXXX should provide move constructors

CMakeLists.txt, config/sanitizers/lsan.supp, config/sanitizers/lsan_mpi.supp
a https://github.com/QMCPACK/qmcpack/pull/5566 follow-up
- No
epyc-server
=> Restrict asan suppression to only the MPI case.

nexus/lib/machines.py
Some supercomputers supported by Nexus have the ability to include an email in the job's `sbatch` file, however this feature was lacking for Perlmutter. This PR adds in the code required to both add the email into the job header, and also set `--mail-type=ALL` to make sure the user receives emails regarding their job. This is consistent with the other supercomputers that already have support for job emails.
- New feature
- No
This has been tested on Perlmutter using a simple python script to call Nexus and create a job for a Quantum ESPRESSO calculation.
* * [ ] This PR adds tests to cover any new …
=> Add email support to Perlmutter Jobs through Nexus

src/Estimators/EstimatorManagerCrowd.cpp, src/Estimators/EstimatorManagerNew.cpp, src/Estimators/OperatorEstBase.h, src/Estimators/SpinDensityNew.cpp, src/QMCDrivers/DMC/DMCContextForSteps.h
Consistently call startBlock and stopBlock for all estimators.
While these "hooks" are not much used at the moment by estimators they are needed for to implement various memory reduction and testing strategies and currently are called inconsistently.  startBlock gets called crowd scope estimators and stopBlock for rank scope estimators.  This PR connects the missing calls.
Currently I believe SpinDensityNew with memory saving in the actual application will have less than optimal performance due to crowd scope estimators reserving only 10 particle steps worth of memory.
With this fix SpinDensityNew::startBlock also needs a fix.
- Bugfix
- No
sdgx2
_Update the following with an [x] where …
=> Start stop block consistency

nexus/lib/qmcpack_input.py, src/QMCDrivers/QMCDriverInput.cpp
Changes input keyword "estimator_measurement_period" to "estimator_period" as discussed in #5576.  Also add support for the new keyword in Nexus.
- No
Laptop
=> Switch to "estimator_period" keyword and add Nexus support

src/Platforms/SYCL/syclBLAS.cpp
Align SYCL `batched_gemv[NT]` kernels to the CUDA variants. Resulted in ~3x faster performance overall in benchmark testing: `src/Platforms/tests/benchmark_accelBLAS "AccelBLAS gemv_batched benchmark"` on Aurora.
- Before:
```
-------------------------------------------------------------------------------
AccelBLAS gemv_batched benchmark
gemv_batched<PlatformKind::SYCL>
-------------------------------------------------------------------------------
/home/leey/project/qmcpack/src/Platforms/tests/benchmark_AccelBLAS.cpp:407
...............................................................................
benchmark name                       samples       iterations    estimated
mean          low mean      high mean
std dev       low std dev   high std dev …
```
=> Align SYCL `batched_gemv` to CUDA's

src/QMCTools/getSupercell.cpp, src/QMCTools/tests/CMakeLists.txt
qmc-get-supercell tool is to get the best tiling matrix possessing the largest Wigner-Seitz radius within the given cell size, but it is not easy to guess the tiling matrix of 2D system for the large cell. This PR is to add option --2dxy where only xy component is allowed to expand.
- New feature
- No
Polaris, Aurora
* * [ ] I have read the pull request guidance and develop docs
* * [ ] This PR is up to date with the …
=> Add 2dxy option on qmc-get-supercell tool

nexus/lib/rmg_input.py, nexus/lib/testing.py, nexus/tests/unit/test_qmcpack_input.py, nexus/tests/unit/test_quantum_package_input.py, nexus/tests/unit/test_vasp_input.py
The NumPy aliases `numpy.string_` and `numpy.float_` were removed in NumPy 2.0.0. The correct aliases `numpy.bytes_` and `numpy.float64` have been available since at least NumPy 1.13, and therefore can replace the deprecated aliases. 
Further, the function for NumPy compatibility in `testing.py` was removed and the command for altering print settings was placed in the try-except statement to retain desired print formatting but remove the unnecessary function. 
All instances where `numpy.bytes_` were added to strings were altered so the `numpy.bytes_` object was first converted to string to ensure compatibility.
- Bugfix
- No
Checked compatibility with default python environment on Perlmutter, Python 3.6.15, NumPy 1.17.3, as well as the most recent python environment on Perlmutter, Python …
=> [Nexus] Remove Deprecated NumPy Aliases `numpy.string_` and `numpy.float_`

labs/lab5_excited_states/band.py, labs/lab5_excited_states/optical.py
This PR updates the Lab5 excited states tutorial (labs/lab5_excited_states/optical.py and band.py) to be compatible with Python 3 and adds helpful documentation comments to clarify the usage of different determinant formats.
- No
=> Update Lab5 Excited States Tutorial for Python 3 Compatibility

nexus/lib/plotting.py, nexus/lib/pwscf_analyzer.py
The module `plotting.py` contained a series of `try... except` statements to test for matplotlib, however in the innermost nested `try... except` the command `matplotlib.use()` was invoked with a keyword `warn=False` that has been deprecated since at least the release of matplotlib 3.3, and has been defaulted to `False` since matplotlib 3.0. Given that matplotlib <3.0 is for Python 2 mostly, and since Nexus does not support Python 2 anymore, this should be removed.
Previously, this was throwing an exception that was not caught because of the `try... except` statement it was contained in that caught all exceptions, in this case a `TypeError`, even though it should only be catching the correct exception of `ValueError`.
- Bugfix
- No
Perlmutter with Python 3.9.18 using Matplotlib 3.8.2, and …
=> [Nexus] Remove deprecated Matplotlib keyword `warn` from `plotting.py`
