src/QMCDrivers/DummyQMC.h

Add single comment to DummyQMC.h for PR test

---

tests/test_automation/nightly_ornl_oxygen.sh
tests/test_automation/weekly_ornl_oxygen.sh

Scripts now clone/pull from GitHub. Updated Intel compiler to 2017. Adjusted build/test order to prioritize faster/more interesting/revealing configurations.

Updated oxygen scripts for ctest/cdash using QMCPACK GitHub repository

---

tests/test_automation/nightly_ornl_oxygen.sh

Use older Intel compiler later

Tweak build order

---

tests/test_automation/nightly_ornl_olcf_eos.job
tests/test_automation/nightly_ornl_olcf_titan_cpu.job
tests/test_automation/nightly_ornl_olcf_titan_gpu.job

Updated scripts for OLCF machines. They now pull from GitHub. Same script recipe as for oxygen.

OLCF script update

---

tests/test_automation/nightly_alcf_hyperion.sh

Update nightly regression test script on KNL box at ALCF (hyperion). Changes based on Paul Kent's oxygen script.
@prckent I think this blasted thing is finally working.

Update hyperion nightly regression test script for github

---

nexus/library/pwscf.py
nexus/library/simulation.py

use restartable=True in generate_pwscf to enable
will automatically restart if prior run has finished and either a time limit is reached or non-convergence is evident

nexus: enable automatic pwscf restarts

---

nexus/library/pwscf_input.py

Variables like 'U_projection_type' were being incorrectly rendered in lowercase.

nexus: bugfix for case sensitivity issues in pwscf input

---

CHANGELOG.md
CMakeLists.txt

This updates develop to be current with the 3.0.0 release on master.

Rc 3.0.0 integration back into develop

---

manual/simulationcell.tex

Added section detailing simulationcell to the manual, and updated qmcpack_manual.pdf.

Added section on simulationcell to the manual.

---

nexus/library/machines.py

These commits add some functionality that may be useful if Loadleveler is encountered again in the future.
Modularity of class member functions has been somewhat improved to allow easier testing of new machines given only expected command line output for job submission and queue querying.

Nexus: add machine SuperMUC at Leibniz Supercomputing Center

---

src/QMCWaveFunctions/EinsplineSetBuilderOld.cpp

Open spline HDF5 file read only. Closes #122

---

tests/performance/NiO/process_perf.py

Add more tests and error messages for the performance timers post-processing script.
Hopefully this will give more insight into the nightly performance test failures.

More debug output from performance tests

---

manual/output_overview.tex
manual/qmcpack_manual.tex
manual/running.tex

Created a new PR as per PRK's suggestion.
Added a chapter "Output Overview" to the manual which gives some details on output files.
This PR includes the suggestions made on the original PR by MD, and YL.

Manual updates

---

src/AFQMC/Drivers/AFQMCDriver.cpp
src/AFQMC/Drivers/AFQMCDriver.h
src/AFQMC/Estimators/BasicEstimator.h
src/AFQMC/Walkers/DistWalkerHandler.cpp
src/AFQMC/Walkers/DistWalkerHandler.h
src/Utilities/NewTimer.h
src/Utilities/tests/test_timer.cpp

Create helper types and functions to create a list of timers and index it by an enum.
The old AFQMC timers were not removed.  That is for a future commit.

Add timers to AFQMC.

---

src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp
src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp

Clean code abort with invalid spin requested.

---

src/QMCWaveFunctions/Jastrow/PolynomialFunctor3D.h
src/QMCWaveFunctions/tests/CMakeLists.txt
src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp
src/QMCWaveFunctions/tests/test_polynomial_eeI_jastrow.cpp

Tested with Intel 17 u2. The workaround is still needed.

Add Jastrow eeI unit test

---

src/QMCWaveFunctions/Jastrow/TwoBodyJastrowOrbitalBspline.cpp

To address the failing in the nightly.

Fix CUDA J2 in 1 up + 1 down electron case.

---

src/QMCDrivers/QMCUpdateBase.h
tests/solids/bccH_1x1x1_ae/qmc_short_vmc_all.in.xml
tests/solids/bccH_1x1x1_ae/qmc_short_vmc_all_nodrift.in.xml
tests/solids/bccH_1x1x1_ae/qmc_short_vmc_dmc_all.in.xml
tests/system/CMakeLists.txt

corrected handling of species with different mass in update-all driver
added tests for update-all driver on bcc hydrogen
added more observables to bcc test

fixed update-all driver (ae)

---

nexus/library/bundle.py
nexus/library/developer.py
nexus/library/generic.py
nexus/library/nexus.py
nexus/library/project_manager.py
nexus/library/pwscf.py
nexus/library/pwscf_input.py
nexus/library/qmcpack_input.py
nexus/library/qmcpack_workflows.py

Fix parallel pw2qmcpack workflow and add/update jastrow and estimator elements as requested by SNL.
Add ability to serialize objects in preparation for object differences needed for eventual unit tests.

fix for parallel pw2qmcpack workflow, other small updates

---

src/QMCDrivers/DMC/DMCOMP.cpp
src/QMCDrivers/DMC/DMC_CUDA.cpp

Revert "Add output to DMC CPU driver.  Indicates status of t-moves"

---

tests/test_automation/jenkins_rhea_cpu.sh
tests/test_automation/jenkins_rhea_gpu.sh

These scripts will be called by Jenkins at OLCF to run CI on Rhea

Jenkins on Rhea

---

src/QMCWaveFunctions/Jastrow/BsplineFunctor.h
src/QMCWaveFunctions/Jastrow/BsplineJastrowBuilder.cpp
src/QMCWaveFunctions/Jastrow/eeI_JastrowBuilder.cpp

Protect user mistake as discussed in issue #34

Print error when Rcut > WS radius in Jastrow.

---

tests/estimator/latdev/latdev_check.py
tests/estimator/skinetic/skinetic_check.py

Print some information about estimator failures - see if it's a tolerance issue, or something more serious.

Output more information for estimator failures

---

tests/pw2qmcpack/CMakeLists.txt

Remove unreliable flux from this shorter test with QE wavefunctions

---

tests/io/restart/check.sh

Printout is more verbose.
Check up to 7th digit after the decimal.
Issue #258
Because I was not able to reproduce the failure on my platforms, I only simulated the case for checking the fix.

Increase restart check tolerance

---

CHANGELOG.md

Note that my NEXUS description is lacking.
Please update with whatever I missed that is considered important.
Note that it should be possible to edit this update directly on GitHub.

Human readable list of notable updates since last release. 

---

nexus/library/machines.py

Add support for Cori at NERSC.  Differentiate between KNL and Haswell partitions.  Leave finer details, e.g. "OMP_PROC_BIND=spread", to user input.

nexus: add Cori at NERSC

---

nexus/library/machines.py
nexus/library/simulation.py

"exit_call = exit" does not work in ipython. Make it become sys,exit
Add an option for not modifying the code while adding new machine to nexus.

compatiple with ipython & local machine setting

---

src/OhmmsPETE/tests/test_matrix.cpp
src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h

1) add a unit test for OhmmsMatrix row/col swap.
2) allow eeI Jastrow defined only on partial atoms.

Minor changes related to JeeI.

---

manual/installation.tex

Update NERSC docs

---

src/einspline/tests/test_one.cpp

Addresses failure of unit tests on some systems.

Add tolerance to einspline 1D unit tests.

---

src/QMCHamiltonians/LocalECPotential.cpp

The PP local channel computation was not correct with SoA. Reported by H. Shin.

Fix OpenBC PP with SoA.

---

CMake/ClangCompilers.cmake
CMake/GNUCompilers.cmake
CMake/IntelCompilers.cmake
CMakeLists.txt

Closes #298 
Breaking change for users with outdated compilers

Require C++11 and increase minimum compiler versions

---

manual/installation.tex

Manual edits: cdash is public, version fixes

---

tests/test_automation/jenkins_rhea_cpu.sh
tests/test_automation/jenkins_rhea_cpu_mixed.sh
tests/test_automation/jenkins_rhea_gpu.sh

This pull requests closes
issue #323 by adding a new jenkins script to tests/test_automation (and a new jenkins job on the server)
issue #340 by explicitly checking the output of cmake for the expected versions of the compiler

Ci issues 323 340

---

manual/backflow.tex

Incorporate optimization tips into Backflow section from document found on Assembla.

Include optimization tips in Backflow wavefunction section.

---

src/Platforms/devices.h

Reduces scope for error on multi/mixed GPU machines

Print GPU device names

---

CHANGELOG.md

In partial preparation for new release.

Update changelog with major changes since last release

---

config/build_olcf_eos.sh
config/build_olcf_titan.sh

Add parallel hdf5, include double cmake call for titan gpu builds.

update build_olcf scripts

---

src/QMCHamiltonians/PairCorrEstimator.cpp
src/QMCWaveFunctions/Jastrow/TwoBodyJastrowOrbital.h

Closes #392
AoS tests all pass. SoA needs to fix backflow.
AoS:
```
ctest -R short-heg
Test project /sandbox/opt/qmcpack/build_Intel_real
Start 24: short-heg_14_gamma-ni-16-1
1/27 Test #24: short-heg_14_gamma-ni-16-1 .................   Passed    1.06 sec
Start 25: short-heg_14_gamma-ni-16-1-totenergy
2/27 Test #25: short-heg_14_gamma-ni-16-1-totenergy .......   Passed    0.03 sec
Start 26: short-heg_14_gamma-ni-16-1-variance
3/27 Test #26: short-heg_14_gamma-ni-16-1-variance ........   Passed    0.02 sec
Start 27: short-heg_14_gamma-ni_dmc-16-1
4/27 Test #27: short-heg_14_gamma-ni_dmc-16-1 .............   Passed    1.79 sec
Start 28: short-heg_14_gamma-ni_dmc-16-1-totenergy
5/27 Test #28: short-heg_14_gamma-ni_dmc-16-1-totenergy ...   Passed    0.03 sec
Start 29: …
```

Fix heg aos

---

src/QMCHamiltonians/PairCorrEstimator.cpp

No more crash in short-heg_14_gamma-hf-1-16

Fix a bug in PairCorrEstimator.

---

src/QMCApp/QMCMain.cpp

With this fix, processPWH return true properly.

Fix double free pointer crashing in heg test input.

---

src/OhmmsPETE/TinyVector.h
src/OhmmsSoA/VectorSoaContainer.h

Eliminate unroll warning from Intel compilers.

---

src/QMCDrivers/DMC/DMCUpdateAll.cpp
src/QMCDrivers/VMC/VMCUpdateAll.cpp

also enabled substep in all-particle VMC

fixed hdf5 observables in all-particle driver

---

src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp

Bug is from PR #373 
Nightly tests exposed this issue.

Fix CPU code path when gpu=yes is present.

---

src/Message/MPIObjectBase.h
src/QMCApp/tests/test_project_data.cpp
src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h
src/QMCWaveFunctions/Jastrow/eeI_JastrowOrbital.h
src/Utilities/OhmmsInform.h
src/Utilities/SimpleParser.h

Replace with stringstream (from the sstream include).
Also remove the check for gcc version 2.

Remove deprecated strstream.

---

manual/opt.tex
src/QMCDrivers/QMCCostFunctionBase.cpp
src/QMCDrivers/QMCFixedSampleLinearOptimize.cpp

Manual is updated as well.
closes #19

Update default optimizer to OneShiftOnly.

---

src/QMCDrivers/QMCDriver.cpp
src/QMCDrivers/QMCDriver.h

Add checkpoint timer

---

nexus/library/pwscf_postprocessors.py
nexus/library/qmcpack_workflows.py

Allows pp.x to be part of the workflows generated by qmcpack_workflows.

Add QE postprocessing support in qmcpack_workflows

---

src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp

Protect complex build.

---

CMake/python.cmake
nexus/examples/CMakeLists.txt

Skip Nexus example tests if numpy is not present

---

src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h

Workaround issue with Intel compiler <= 17u1.

---

manual/opt.tex

Slightly more detailed guidance. Remove brick wall reference.

Improve optimization text

---

src/QMCTools/ppconvert/src/common/Fitting.h

Permits doxygen to run to completion in old_docs

Correct doxygen LaTeX formula

---

src/Particle/ParticleSet.cpp
src/QMCWaveFunctions/Fermion/DiracDeterminantBase.cpp
src/QMCWaveFunctions/Jastrow/eeI_JastrowBuilder.cpp

Add more in ParticleSet.
Remove ratio timer in evaluateLog.
Change JeeI timer name from eeI to JeeI.

Refine timers.

---

README.md

This is a test PR to see if I can reduce the new found chattiness of the robot.

removed trailing whitespace from README.md

---

src/QMCWaveFunctions/Experimental/LCOrbitalSetWithCorrection.cpp
src/QMCWaveFunctions/Jastrow/ThreeBodyGeminal.cpp

Replace fixed length char array with std::string.

Fix GNU 7.2 warning about char array fixed length.

---

src/Particle/ParticleSet.cpp
src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.h
src/QMCWaveFunctions/MolecularOrbitals/AtomicBasisBuilder.h

minor changes, missed in earlier PRs GNU fix and timer.

Minor changes

---

doxygen/DoxygenLayout.xml
doxygen/Makefile
doxygen/index.doc
doxygen/qmcpack.cfg

Disables outdated developer section, updates code description. Did not delete files yet (#530)
I intend to rebuild these documents at least nightly, as we do for the manual PDF.

Ready doxygen files for publishing again

---

src/QMCWaveFunctions/EinsplineSet.cpp

MNC stands for Minimum Necessary Change
all backflow tests now pass when QMC_COMPLEX=1
partially address #442

MNC to fix backflow optimization for QMC_COMPLEX

---

src/QMCWaveFunctions/Jastrow/OneBodyJastrowOrbital.h
src/QMCWaveFunctions/tests/gen_bspline_jastrow.py
src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp

Mostly just tests the underlying Bspline functor. 
Checks at the level of calling 'evaluate' need to be added.

Unit test for Bspline one-body Jastrow

---

manual/installation.tex

Update performance test names

---

CHANGELOG.md

Additional updates are expected before the next release

Updating CHANGELOG.md since last release

---

manual/installation.tex

Rechecked/updated Apple OS X brew recipe.

Update brew recipe

---

src/Utilities/InfoStream.cpp

Match changes made to code in miniqmc.

Delete nullStream in the stream destructor.

---

manual/ionwf.tex
manual/qmcpack_manual.tex
src/QMCWaveFunctions/IonOrbital.cpp
src/QMCWaveFunctions/IonOrbital.h
src/QMCWaveFunctions/IonOrbitalBuilder.cpp
tests/CMakeLists.txt
tests/models/CMakeLists.txt
tests/models/sho/grad_lap.xml
tests/models/sho/vmc_sho.xml

Ratio test is broken at the current commit a7047891a7191ffa3b772905d5043862748d167f
However ratio test passes as of Dec. 23 commit 8194d94148ec6a2bb60e44c349b9b1e6ca152c09
update: Ratio test is still broken at commit 8194d94148ec6a2bb60e44c349b9b1e6ca152c09

Resurrect Ionwf

---

src/Numerics/SlaterBasisSet.h
src/QMCWaveFunctions/lcao/AOBasisBuilder.h
src/QMCWaveFunctions/lcao/LCAOrbitalBuilder.cpp
src/QMCWaveFunctions/lcao/LCAOrbitalBuilder.h
src/QMCWaveFunctions/lcao/MultiFunctorBuilder.h
src/QMCWaveFunctions/lcao/RadialOrbitalSetBuilder.h

HDF5 Reader for SOA code

---

src/CMakeLists.txt

Taken from miniqmc: https://github.com/QMCPACK/miniqmc/pull/84

Escape quotes in git subject lines

---

tests/test_automation/nightly_anl_cetus.sub

Write a more general script.
Found the following useful when there is a wall limit.
```
ctest --stop-time `date --date=now+55mins +%H:%M:%S`
```

Update the nightly test script for Mira/Cetus.

---

external_codes/quantum_espresso/README
external_codes/quantum_espresso/add_pw2qmcpack_to_qe-6.2.1.diff
external_codes/quantum_espresso/download_and_patch_qe6.2.1.sh

Yes. It finally arrives.
The patched reference code is hosted on [github](https://github.com/ye-luo/q-e/releases/tag/v6.2.1%2Bpw2qmcpack).
I know little about autotools. So I rely on QE to handle HDF5 search. This is different from the past.
close #266

Add QE 6.2.1 pw2qmcpack converter.

---

src/Lattice/tests/test_bconds.cpp

Add tests for the isValid and outOfBound methods.

Add a few more unit tests for CrystalLattice.

---

src/OhmmsData/tests/test_xml.cpp

Tests for the OhmmsXPathObject class.

Add more tests to XML-handling objects

---

tests/test_automation/jenkins_rhea_cpu.sh
tests/test_automation/jenkins_rhea_gpu.sh

This updates our current scripts for OLCF CI to use the new infrastructure.

updating scripts for new ci

---

src/QMCDrivers/CloneManager.cpp
src/QMCDrivers/CloneManager.h
src/QMCDrivers/CorrelatedSampling/CSVMC.cpp
src/QMCDrivers/CorrelatedSampling/CSVMC.h
src/QMCDrivers/DMC/DMCFactory.cpp
src/QMCDrivers/DMC/DMCOMP.cpp
src/QMCDrivers/DMC/DMCOMP.h
src/QMCDrivers/QMCCSLinearOptimizeWFmanagerOMP.cpp
src/QMCDrivers/QMCCSLinearOptimizeWFmanagerOMP.h
src/QMCDrivers/QMCCorrelatedSamplingLinearOptimize.cpp
src/QMCDrivers/QMCCostFunctionCUDA.cpp
src/QMCDrivers/QMCCostFunctionCUDA.h
src/QMCDrivers/QMCCostFunctionOMP.cpp
src/QMCDrivers/QMCCostFunctionOMP.h
src/QMCDrivers/QMCFixedSampleLinearOptimize.cpp
src/QMCDrivers/QMCLinearOptimize.cpp
src/QMCDrivers/QMCOptimize.cpp
src/QMCDrivers/RMC/RMCFactory.cpp
src/QMCDrivers/RMC/RMCSingleOMP.cpp
src/QMCDrivers/RMC/RMCSingleOMP.h
src/QMCDrivers/VMC/VMCFactory.cpp
src/QMCDrivers/VMC/VMCLinearOptOMP.cpp
src/QMCDrivers/VMC/VMCSingleOMP.cpp
src/QMCDrivers/VMC/VMCSingleOMP.h
src/QMCDrivers/tests/test_clone_manager.cpp
src/QMCDrivers/tests/test_dmc_omp.cpp
src/QMCDrivers/tests/test_vmc_omp.cpp

Simplify its constructor and all the dependent OMP drivers.

Cleanup CloneManager

---

src/QMCDrivers/WalkerControlBase.cpp

Delete unused code.

---

manual/qmcpack_papers.bib

CMS published papers and others mainly from the last 3 years.

Add recent QMCPACK papers to manual

---

config/blue_waters.sh

based on build_olcf_titan.sh
I made sure that cmake variables were set properly in CMakeCache.txt for each build and that they all compiled.

add Blue Waters configuration script

---

tests/test_automation/nightly_ornl_oxygen.sh
tests/test_automation/weekly_ornl_oxygen.sh

Includes Intel2017 compilation of QE 6.2.1, Kepler and Volta GPU builds.

Update oxygen test scripts

---

manual/lab_advanced_molecules.tex
manual/lab_condensed_matter.tex
manual/lab_qmc_basics.tex
manual/selected_ci.tex

Remove non-ascii characters in manual

---

src/QMCWaveFunctions/BsplineFactory/SplineC2RAdoptor.h

Fix GPU C2R spline communication

---

manual/bibliography.bib
manual/jastrow.tex

A brife intro + an example. More complicated guidelines will be added in the near future.
Closes #415

Update three body Jastrow manual section

---

manual/qmcpack_manual.tex

So is this what we want?
Fixes #921

Restore the header of bibliography in the manual

---

src/QMCWaveFunctions/lcao/MultiQuinticSpline1D.h
src/QMCWaveFunctions/tests/CMakeLists.txt
src/QMCWaveFunctions/tests/test_multiquintic_spline.cpp

Also fix a small bug in the 3rd derivative routine.

Add unit test for MultiQuinticSpline1D

---

tests/test_automation/nightly_ornl_oxygen.sh
tests/test_automation/weekly_ornl_oxygen.sh

Closes #928 
These ran last night e.g. https://cdash.qmcpack.org/CDash/testDetails.php?test=2718884&build=25682

Update oxygen scripts to QE6.3

---

src/Utilities/tests/test_rng.cpp

Add deterministic test of mt19937 random generator

---

README.md
manual/installation.tex
manual/qmcpack_manual.tex

Adding documentation for ENABLE_MKL.
Closes #750

Enable mkl docs

---

src/simd/algorithm.hpp

Remove unsafe alignment assumption in simd::copy_n

---

src/LongRange/EwaldHandler3D.cpp
src/LongRange/EwaldHandler3D.h

Addresses #964, unit test failures from #956

Ensure MaxKshell is initialized.

---

src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h

The cost of updating the neighbour list was N^2, now N.

Improve JeeI::acceptMove algorithm.

---

src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h
src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.h
src/QMCWaveFunctions/Fermion/MultiDiracDeterminantBase.h
src/QMCWaveFunctions/Fermion/SlaterDet.h
src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.h
src/QMCWaveFunctions/TrialWaveFunction.cpp
src/QMCWaveFunctions/TrialWaveFunction.h
src/QMCWaveFunctions/WaveFunctionComponent.h

I didn't see any actual implementation in a derived WaveFunctionComponent.

Remove legacy alternateXXX in TrialWaveFunction and WaveFunctionComponent.

---

manual/bibliography.bib
manual/qmcpack_papers.bib
manual/running.tex
manual/spo_hybrid.tex
src/QMCApp/qmcapp.cpp

Documents more command line options and updates paper info
Replace disable-timers with enable-timers=none

Update command line options, papers, timers in manual

---

src/Optimize/NRCOptimization.h
src/QMCWaveFunctions/Jastrow/kSpaceJastrow.cpp

Minor correction to the types.

---

src/Utilities/OutputManager.h

The compiler warning of missing a return points me to this class.
I feel this is a bit over provisioning.

Remove the switch in OutputManager.

---

src/AFQMC/Matrix/tests/CMakeLists.txt
src/AFQMC/Numerics/tests/CMakeLists.txt
src/Estimators/tests/CMakeLists.txt
src/Lattice/tests/CMakeLists.txt
src/Numerics/tests/CMakeLists.txt
src/OhmmsData/tests/CMakeLists.txt
src/OhmmsPETE/tests/CMakeLists.txt
src/Particle/tests/CMakeLists.txt
src/ParticleBase/tests/CMakeLists.txt
src/ParticleIO/tests/CMakeLists.txt
src/QMCApp/tests/CMakeLists.txt
src/QMCDrivers/tests/CMakeLists.txt
src/QMCHamiltonians/tests/CMakeLists.txt
src/QMCWaveFunctions/tests/CMakeLists.txt
src/Utilities/tests/CMakeLists.txt
src/einspline/tests/CMakeLists.txt
src/io/tests/CMakeLists.txt
src/spline2/tests/CMakeLists.txt

Use - between fields.
Use _ for many words within a field.

Change _ to - and add spline2.

---

nexus/library/machines.py

Add support for Theta at ALCF.  Jobs now accept a hyperthreads option.

Nexus: add ALCF machine Theta

---

src/AFQMC/Matrix/SMSparseMatrix.h
src/AFQMC/Matrix/array_partition.hpp
src/AFQMC/Matrix/hdf5_readers.hpp
src/AFQMC/Propagators/phaseless_ImpSamp_ForceBias.cpp
src/AFQMC/Walkers/WalkerControl.hpp
src/AFQMC/Walkers/WalkerUtilities.hpp
src/Message/Communicate.cpp
src/QMCDrivers/DMC/WalkerControlMPI.cpp
src/QMCDrivers/DMC/WalkerReconfiguration.cpp
src/QMCDrivers/DMC/WalkerReconfigurationMPI.cpp
src/QMCWaveFunctions/BsplineFactory/SplineC2CAdoptor.h
src/QMCWaveFunctions/BsplineFactory/SplineC2RAdoptor.h
src/Utilities/DistributedIndex.h
src/Utilities/FairDivide.h
src/Utilities/tests/test_partition.cpp

Rename UtilityFunctions.h to FairDivide.h

---

nexus/library/nexus.py
nexus/library/nexus_base.py
nexus/library/simulation.py
nexus/library/structure.py

A few updates to get graph_sims feature working well from the user side.

Nexus: Update for Nexus Monthly Meeting (Oct)

---

CMake/FindVectorMath.cmake

Also need to protect glibc 2.22

---

src/QMCDrivers/DMC/DMCOMP.cpp
src/QMCDrivers/DMC/DMCOMP.h
src/QMCDrivers/QMCUpdateBase.cpp
src/QMCDrivers/QMCUpdateBase.h
src/QMCDrivers/VMC/VMCSingleOMP.cpp

Remove legacy benchmark functions

---

manual/external_tools.tex

Configuration note about this tool

Configuration docs for Scitools Understand

---

src/QMCDrivers/CMakeLists.txt
src/QMCDrivers/DMC/DMC.cpp
src/QMCDrivers/DMC/DMC.h
src/QMCDrivers/DMC/DMCFactory.cpp
src/QMCDrivers/LMYEngineInterface/LMYE_QMCCostFunction.cpp
src/QMCDrivers/QMCCorrelatedSamplingLinearOptimize.cpp
src/QMCDrivers/QMCCorrelatedSamplingLinearOptimize.h
src/QMCDrivers/QMCCostFunction.cpp
src/QMCDrivers/QMCCostFunction.h
src/QMCDrivers/QMCFixedSampleLinearOptimize.cpp
src/QMCDrivers/QMCLinearOptimize.cpp
src/QMCDrivers/QMCOptimize.cpp
src/QMCDrivers/QMCUpdateBase.cpp
src/QMCDrivers/RMC/RMC.cpp
src/QMCDrivers/RMC/RMC.h
src/QMCDrivers/RMC/RMCFactory.cpp
src/QMCDrivers/VMC/VMC.cpp
src/QMCDrivers/VMC/VMC.h
src/QMCDrivers/VMC/VMCFactory.cpp
src/QMCDrivers/VMC/VMCLinearOpt.cpp
src/QMCDrivers/VMC/VMCLinearOpt.h
src/QMCDrivers/tests/CMakeLists.txt
src/QMCDrivers/tests/test_dmc_driver.cpp
src/QMCDrivers/tests/test_vmc_driver.cpp

Closes #692 
(shouldn't clash with #1170 )

Remove and cleanup OMP naming

---

manual/afqmc.tex
manual/backflow.tex
manual/convert4qmc.tex
manual/dmc.tex
manual/estimator_implementation.tex
manual/fdlr.tex
manual/gaussian_orbitals_solids.tex
manual/hamiltonianobservable.tex
manual/jastrow.tex
manual/jastrow_one_body_pade.tex
manual/jastrow_one_body_spline.tex
manual/jastrow_two_body_spline.tex
manual/lab_qmc_basics.tex
manual/methods.tex
manual/opt.tex
manual/particleset.tex
manual/pseudopotentials.tex
manual/qmcpack_manual.tex
manual/simulationcell.tex
manual/singledeterminant.tex
manual/spo_gaussian.tex
manual/spo_heg.tex
manual/spo_hybrid.tex
manual/spo_spline.tex
manual/vmc.tex

this addresses #1167
XML is now not unreadable.
I wouldn't go so far as to say it closes all listing issues but we need to collect more detail on those.

xml listings are now nice for pdf, readable for html

---

src/Numerics/Blasf.h
src/Numerics/OhmmsBlas.h

Extracted from #1194 to ease the review burden.

Add additional BLAS/LAPACK routines for AFQMC.

---

src/Numerics/OhmmsBlas.h
src/QMCWaveFunctions/MolecularOrbitals/LCOrbitalSetOpt.h

Fix double definition of sscal

---

CHANGELOG.md

Minimize surprise for anyone running develop

Mention renaming of utilties

---

src/QMCWaveFunctions/Fermion/DelayedUpdate.h

I didn't see it causing problem but I feel it more safe to add this guard. It costs nothing.

Add a safe guard to updateInvMat

---

src/QMCTools/LCAOH5Parser.cpp
src/QMCTools/QMCGaussianParserBase.cpp
src/io/hdf_archive.cpp
src/io/hdf_archive.h
src/io/hdf_dataproxy.h
src/io/hdf_double_hyperslab.h
src/io/hdf_ma.h
src/io/tests/CMakeLists.txt
src/io/tests/test_hdf_multiarray.cpp
src/io/tests/test_hdf_parallel.cpp
src/type_traits/container_proxy.h

Extracted from #1194 
Also adds a small number of new unit tests.

Add HDF data type proxies for AFQMC

---

nexus/bin/nxs-test

Left the door open on one of the last commits.  Instead of commenting/uncommenting bits of code, add a flag to nxs-test when job/machine reference data needs to be updated.

Nexus: add job_ref_table option to nxs-test

---

manual/build_manual.sh
manual/installation.tex
manual/running.tex

1. Mention delayed update in performance tests
2. Add description to nested threading.

Nested threading and improved delayed update documentation

---

src/type_traits/container_proxy.h

Add some container proxies for ALF multi. @mmorale3 . Once this is merged I'll consolidate the self contained AFQMC branches.

Additional container proxies for ALF multi.

---

tests/test_automation/jenkins_rhea_cpu.sh
tests/test_automation/jenkins_rhea_gpu.sh

attempting to bring back jenkins

resurrect CI

---

tests/solids/NiO_a4_e48_pp/CMakeLists.txt
tests/solids/NiO_a4_e48_pp/NiO-delayedupdate-vmc-dmc-TMv1v3-short.in.xml
tests/solids/NiO_a4_e48_pp/NiO-vmc-dmc-TMv1v3-short.in.xml
tests/solids/NiO_a4_e48_pp/NiO-vmc-dmc-short.in.xml

Split t-move tests

---

manual/installation.tex

A few minor updates:
- Include a section on known limitations.
- Add phdf5 variants.
- Minor clean-up.

Minor update to the Spack package section of the QMCPACK manual

---

manual/running.tex
manual/spo_spline.tex
src/QMCWaveFunctions/BsplineFactory/BsplineReaderBase.cpp
src/QMCWaveFunctions/BsplineFactory/BsplineReaderBase.h
src/QMCWaveFunctions/BsplineFactory/HybridAdoptorBase.h
src/QMCWaveFunctions/BsplineFactory/SplineAdoptorReaderP.h
src/QMCWaveFunctions/BsplineFactory/SplineC2CAdoptor.h
src/QMCWaveFunctions/BsplineFactory/SplineC2RAdoptor.h
src/QMCWaveFunctions/BsplineFactory/SplineR2RAdoptor.h
src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp
src/QMCWaveFunctions/BsplineFactory/createComplexSingle.cpp
src/QMCWaveFunctions/BsplineFactory/createRealDouble.cpp
src/QMCWaveFunctions/BsplineFactory/createRealSingle.cpp
src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp
src/qmc_common.cpp
tests/io/CMakeLists.txt
tests/io/save_coefs/C.BFD.xml
tests/io/save_coefs/check.sh
tests/io/save_coefs/pwscf.pwscf.h5
tests/io/save_coefs/qmc_short.in.xml
tests/io/save_coefs/qmc_short.restart.xml

Manual updated.
Test added but it doesn't test seriously.
Solve part of #146
Close #1259

Relocate command line save_wfs as XML input tag save_ceofs

---

src/QMCWaveFunctions/lcao/LCAOrbitalSet.cpp

When you are developing first build debug, test, then build release and test, then push.  
All the assert's and what not do nothing otherwise.

Debug build was broken.  Check the debug build

---

src/QMCWaveFunctions/BsplineFactory/BsplineSet.h
src/QMCWaveFunctions/BsplineFactory/SplineAdoptorBase.h
src/QMCWaveFunctions/EinsplineSet.h
src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp
src/QMCWaveFunctions/EinsplineSetCuda.cpp
src/QMCWaveFunctions/SPOSet.h

This is needed for my OpenMP offload.
Hooks finalizeConstruction in BsplineSet.h
PR separately for easy review.

Rename initGPU to finalizeConstruction for more general use

---

config/BGQ_Clang_ToolChain.cmake

This reduces a lot of warning.

Raise boost version on BG/Q

---

external_codes/mpi_wrapper/mpi3/communicator.hpp

Also move the operator/ out of the class because clang complains about member access into incomplete type.
Same fix is also a PR into the mpi wrapper repository.

Reorder gather_n calls to satisfy clang

---

src/AFQMC/Hamiltonians/rotateHamiltonian.hpp
src/AFQMC/Memory/SharedMemory/shm_ptr_with_raw_ptr_dispatch.hpp
src/AFQMC/Wavefunctions/tests/test_wfn_factory.cpp

Fixes an issue when running on more than one node.

Fix bug with half rotated integrals

---

tests/test_automation/jenkins_rhea_cpu.sh
tests/test_automation/jenkins_rhea_gpu.sh

After the rhea rhel7 upgrade, a new software stack was installed among other changes.

update rhea scripts with new modules

---

tests/test_automation/jenkins_rhea_cpu.sh
tests/test_automation/jenkins_rhea_gpu.sh

Force the correct libstdc++ via LD_PRELOAD

Workaround rhea issue

---

src/spline/einspline_util.hpp

closes #1343 
Although IBM should fix the spectrum MPI, at least we have a working code.

Solve Summit MPI message size limit issue

---

tests/test_automation/README
tests/test_automation/nightly_ornl_oxygen.sh
tests/test_automation/weekly_ornl_oxygen.sh

Closes #1477 
Run by hand to verify. Build recipe for 6.3 works unchanged.

Update oxygen scripts for QE 6.4

---

CMakeLists.txt
tests/test_automation/jenkins_rhea_cpu.sh
tests/test_automation/jenkins_rhea_gpu.sh

Documentation to be updated #1488

Make SOA build the default

---

nexus/lib/nexus.py

Update Nexus version to 1.7.0 ahead of QMCPACK v3.7.0 release.

Nexus: update version to 1.7.0

---

src/OpenMP/OMPallocator.hpp
src/OpenMP/tests/CMakeLists.txt
src/OpenMP/tests/test_deep_copy.cpp

Fixed some bug in openmp unit test for offload

Fix test_openmp

---

src/QMCHamiltonians/ECPComponentBuilder.2.cpp

Fix parseCasino

---

src/AFQMC/Hamiltonians/KPFactorizedHamiltonian.cpp

Fixes an issue with different number of MOs per kpoint.

Fix bug in kpoint AFQMC code

---

external_codes/mpi_wrapper/mpi3/communicator.hpp
external_codes/mpi_wrapper/mpi3/test/communicator_split.cpp

Manual copy of commit 73b8a31966f3687c89f8c29c5dca337fca532d32 from mpi3 gitlab.
https://gitlab.com/correaa/boost-mpi3/commit/73b8a31966f3687c89f8c29c5dca337fca532d32
Prerequisite for finishing #1448, which is a prerequisite for removing OOMPI.

Solve leaking MPI_Group

---

manual/bibliography.bib
manual/features.tex
manual/installation.tex
manual/introduction.tex
manual/running.tex
manual/unit_testing.tex
manual/units.tex

Edits from Charlie Horak (ORNL) for style and consistency plus bibliography fix.

Editing pass on Sections 1-5 of manual

---

tests/scripts/jsrunhelper.sh

Forgot to include this script in #1567

Add a jsrun helper script.

---

nexus/bin/qmca

The headers of the AFQMC scalar output files have changed.

Update qmca AFQMC local energy translation.

---

utils/afqmctools/afqmctools/analysis/rdm.py
utils/afqmctools/afqmctools/hamiltonian/kpoint.py
utils/afqmctools/afqmctools/hamiltonian/mol.py
utils/afqmctools/afqmctools/utils/qmcpack_utils.py
utils/afqmctools/afqmctools/wavefunction/mol.py
utils/afqmctools/afqmctools/wavefunction/pbc.py

Update wavefunction helper routines. Necessary for workshop.

Update wavefunction write and RDM extraction.

---

CMake/GNUCompilers.cmake

Put correct CXX flag for vla

---

nexus/lib/structure.py

Fix small bug in skew function.

Nexus: fix structure skew function

---

src/QMCDrivers/QMCCostFunctionBase.cpp
src/QMCHamiltonians/LocalMomentEstimator.cpp

In src/QMCDrivers/QMCCostFunctionBase.cpp, I only add parenthesis in line 274 and 279 but the formatting showed a lot of change.

Fix Clang warning and LocalMomentEstimator crash

---

src/QMCTools/CMakeLists.txt
src/QMCTools/LCAOHDFParser.cpp
src/QMCTools/LCAOHDFParser.h
src/QMCTools/convert4qmc.cpp

Rename class and file to LCAOHDFParser

---

src/QMCTools/PyscfToQmcpack.py

make PyscfToQmcpack python3 compatible

Make PyscfToQmcpack.py python3 compatible

---

manual/gaussian_orbitals_solids.tex

More edits from Charlie Horak.
Confirmed manual LaTeX still builds

Update GTO chapter

---

CMakeLists.txt

Should have thought of this.  Policy was added in 3.9.0.

Protected cmake_policy(set CMP0074 new)

---

manual/selected_ci.tex

Updated selected-ci chapter

---

nexus/docs/nexus_user_guide.tex
nexus/install

Update to version 1.8.0 ahead of the release.

Nexus: update version number to 1.8.0

---

external_codes/quantum_espresso/README
external_codes/quantum_espresso/add_pw2qmcpack_to_qe-6.4.1.diff
external_codes/quantum_espresso/download_and_patch_qe6.4.1.sh

Add QE 6.4.1 patch

---

src/AFQMC/Wavefunctions/WavefunctionFactory.cpp

Fixes an issue with reading initial wavefunction from hdf5. Only affects systems where nalpha != nbeta

Fix reading of initial wavefunction from hdf5.

---

src/QMCDrivers/QMCFixedSampleLinearOptimize.cpp

@ye-luo This PR fixes a bug that affects the correctness of correlated sampling in the adaptive_three_shift method.

Fix a bug in Adaptive_Three_Shift

---

nexus/lib/pwscf_analyzer.py

For calculations of 'nscf' type, the needed quantities for the MD analysis are not present in the output file.

Temporary fix for MD analysis when calculation is 'nscf' type.

---

nexus/lib/pwscf_analyzer.py

This will include the fermi energy of pwscf into the analyzer image.

Adding scrape of fermi energy to pwscf_analyzer.py

---

tests/test_automation/nightly_ornl_oxygen.sh
tests/test_automation/ornl_oxygen_setup.sh
tests/test_automation/weekly_ornl_oxygen.sh

Spack python updates and PYTHONPATH fix
To free up time on oxygen the combination of builds tested will be updated in a later PR.

Update oxygen nightlies scripts

---

tests/test_automation/jenkins_oxygen_cpu.sh
tests/test_automation/jenkins_oxygen_cuda.sh
tests/test_automation/jenkins_oxygen_gpu.sh

this is to get initial CI set up on oxygen.

Jenkins CI scripts for oxygen

---

nexus/lib/structure.py

Addresses #1864.  Impact of gcd use is localized to the `get_band_tiling` function.

Nexus: localize gcd

---

manual/developing.tex
manual/distance_tables.tex

Some development documentation on how to program ParticleSets, distance tables, and particle groups.

Add docs on distances and particles to the manual

---

src/QMCHamiltonians/OperatorBase.h
src/QMCHamiltonians/QMCHamiltonian.cpp
src/QMCHamiltonians/QMCHamiltonian.h

Added in `OperatorBase.h` and `QMCHamiltonian.h`.

Batched interface in Hamiltonian

---

external_codes/mpi_wrapper/mpi3/communicator.hpp
external_codes/mpi_wrapper/mpi3/environment.hpp
external_codes/mpi_wrapper/mpi3/error.hpp

These compile okay, and the unit and deterministic tests pass.  This should be a safe update.
Continues #1900

More updates from gitlab mpi_wrapper

---

nexus/bin/nxs-test
nexus/lib/execute.py
nexus/lib/superstring.py
nexus/lib/unit_converter.py
nexus/tests/unit/test_execute.py
nexus/tests/unit/test_memory.py
nexus/tests/unit/test_plotting.py
nexus/tests/unit/test_superstring.py
nexus/tests/unit/test_unit_converter.py

This PR adds tests for modules that perform simple utility functions.

Nexus: tests for simple utilities

---

nexus/bin/nxs-test
nexus/lib/testing.py
nexus/tests/unit/test_structure.py
nexus/tests/unit/test_testing.py

Harden functions used for testing and add explicit tests for these functions.  This PR depends on #1907.

Nexus: tests of testing module

---

src/QMCDrivers/ContextForSteps.h
src/QMCDrivers/Crowd.cpp
src/QMCDrivers/Crowd.h
src/QMCDrivers/VMC/VMCBatched.cpp
src/QMCDrivers/VMC/VMCBatched.h
src/QMCDrivers/tests/test_Crowd.cpp

Accept rate now reported and warmup steps actually done.

Unified driver acceptance rate and Warmup steps

---

nexus/lib/physical_system.py
nexus/tests/unit/test_physical_system.py
nexus/tests/unit/test_structure.py

Expand existing set of tests for the `physical_system` module.  Also add a missing test for the `Structure` class.

Nexus: expand tests for physical system module

---

nexus/bin/nxs-test
nexus/lib/testing.py
nexus/tests/unit/test_nexus_base.py

Add tests for the `nexus_base` module.  This PR depends on #1939.

Nexus: add tests for nexus_base module

---

nexus/bin/nxs-test
nexus/lib/nexus.py
nexus/tests/unit/test_nexus_imports.py

Be more explicit with the test for user facing imports from the `nexus` module.  This PR depends on #1940.

Nexus: update test for nexus imports

---

src/type_traits/tests/test_template_types.cpp

Here is the missing test file.
**Until #1949 is resolved we should not merge based on Oxygen CI success**

Build fixed but #1949 still serious Oxygen CI suspect

---

tests/test_automation/jenkins_oxygen_cpu.sh
tests/test_automation/jenkins_oxygen_cuda.sh
tests/test_automation/jenkins_oxygen_gpu.sh

This should prevent the false-positive like we got with #1947

oxygen jenkins exits on configure/build failure

---

external_codes/mpi_wrapper/mpi3/communicator.hpp
external_codes/mpi_wrapper/mpi3/shared_communicator.hpp

Update communicator.hpp and shared_communicator.hpp
The shared_window.hpp file needs to be updated, but that requires resolving an issue with the AFQMC code.

Sync communicator from gitlab repo

---

src/QMCWaveFunctions/tests/CMakeLists.txt
src/QMCWaveFunctions/tests/test_kspace_jastrow.cpp

closes #1845 , I checked that the unit test passes in AOS and SOA on the CPU.

add regression unit tests to kspace jastrows

---

src/AFQMC/Hamiltonians/HamiltonianFactory.cpp
src/AFQMC/SlaterDeterminantOperations/rotate.hpp
src/AFQMC/Walkers/WalkerControl.hpp
src/AFQMC/Wavefunctions/WavefunctionFactory.cpp
src/Estimators/TraceManager.h
src/Numerics/CartesianTensor.h
src/Numerics/OptimizableFunctorBase.h
src/Numerics/Ylm.h
src/Particle/HDFWalkerInput_0_4.cpp
src/QMCDrivers/GreenFunctionModifiers/DriftModifierBuilder.cpp
src/QMCDrivers/QMCFixedSampleLinearOptimize.cpp
src/QMCDrivers/QMCLinearOptimize.cpp
src/QMCHamiltonians/HamiltonianFactory.cpp
src/QMCHamiltonians/NonLocalECPotential.cpp
src/QMCHamiltonians/OrbitalImages.cpp
src/QMCHamiltonians/SpaceGrid.cpp
src/QMCTools/GamesFMOParser.cpp
src/QMCTools/getSupercell.cpp
src/QMCWaveFunctions/BsplineFactory/HybridAdoptorBase.h
src/QMCWaveFunctions/EinsplineSet.cpp
src/QMCWaveFunctions/ElectronGas/ElectronGasOrbitalBuilder.cpp
src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
src/QMCWaveFunctions/Jastrow/RPAJastrow.cpp
src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp
src/QMCWaveFunctions/lcao/SoaCartesianTensor.h
src/QMCWaveFunctions/tests/test_multiquintic_spline.cpp
src/Utilities/unit_conversion.cpp
src/formic/utils/lmyengine/davidson_solver.cpp
src/formic/utils/lmyengine/spam_solver.cpp

Ideally, these fixes would rework the logic to better use scoping and RAII for added safety, instead of depending on all cases being handled correctly by several `if` - `else if` - `else` blocks. I did make some simple changes like this, but when things got too complex or it seemed reasonable to do so, I applied the band-aid and moved on. I also didn't spend a lot of time in sections of the code that need larger consideration anyway (e.g. xml/builders).

compiler warnings 2 of N: -Wmaybe-uninitialized

---

examples/afqmc/01-neon_atom/README.rst
examples/afqmc/02-neon_frozen_core/README.rst
examples/afqmc/03-carbon_triplet_uhf/README.rst
examples/afqmc/05-N2_phmsd/README.rst
examples/afqmc/06-methane_converge_back_prop/README.rst
examples/afqmc/06-methane_converge_back_prop/scf.py
examples/afqmc/07-diamond_2x2x2_supercell/README.rst
examples/afqmc/08-diamond_2x2x2_kpoint_sym/README.rst

Fixes for issues raised in #1964 .

Fix afqmc examples

---

src/QMCDrivers/Optimizers/DescentEngine.cpp
src/QMCDrivers/Optimizers/HybridEngine.cpp

Fix BGClang MP complex build.
Fix Intel and PGI no MPI build.

Fix compilation

---

examples/afqmc/06-methane_converge_back_prop/check_h1e_conv.py
src/AFQMC/Estimators/EstimatorHandler.h

Performs scalar.h5 -> stat.h5 change requested in #1979.

Update HDF5 filename for heavy observables.

---

src/QMCDrivers/Optimizers/OptimizerTypes.h
tests/molecules/H4_msd_ae/CMakeLists.txt

Make most WF optimization error away.
https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=85621

Fix opt tests

---

manual/gaussian_orbitals_solids.tex
manual/singledeterminant.tex
src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp

Default delay_rank to 32 when >=192 electrons in a determinant

---

src/QMCDrivers/BranchIO.cpp
src/QMCDrivers/BranchIO.h
src/QMCDrivers/DMC/DMCBatched.cpp
src/QMCDrivers/DMC/DMCBatched.h
src/QMCDrivers/SimpleFixedNodeBranch.cpp
src/QMCDrivers/SimpleFixedNodeBranch.h

Made VParam enum scoped, Changed VParamType to std::array subtype.

Cleaning up SimpleFixedNodeBranch

---

utils/afqmctools/README.md
utils/afqmctools/afqmctools/hamiltonian/kpoint.py
utils/afqmctools/afqmctools/inputs/from_pyscf.py
utils/afqmctools/bin/pyscf_to_afqmc.py

Removes dependency on parallel hdf5 for kpoint Cholesky generation by implementing serial writing.
Serial write is now the default.

Serial hdf5 afqmc kp.

---

nexus/bin/nxs-test
nexus/lib/project_manager.py
nexus/lib/testing.py
nexus/tests/unit/test_project_manager.py
nexus/tests/unit/test_simulation.py

Add tests for the `project_manager` module.  This includes actual execution of full workflows composed of simple test runs (in which each run just calls "echo run" instead of performing an actual simulation).

Nexus: tests for project manager module

---

utils/afqmctools/afqmctools/inputs/from_pyscf.py
utils/afqmctools/afqmctools/wavefunction/pbc.py
utils/afqmctools/bin/pyscf_to_afqmc.py

Add user controllable occupancy threshold parameter for wavefunctions generated from mean field calculations with non integer occupancies.

Afqmc occupancy threshold

---

nexus/lib/qmcpack_result_analyzers.py

@tiihonej will test if this adjustment is correct.

Nexus: fix opt selection

---

src/formic/utils/lmyengine/engine.cpp
src/formic/utils/lmyengine/engine.h

Fix Clang compilation and save compilation time.

---

utils/code_tools/qmcpack-style.el
utils/code_tools/walker_property_print.py

couple of additions for tooling. See commit messages for details.

More dev tools

---

tests/test_automation/nightly_anl_bora.sh

Update bora nightly script.

---

utils/afqmctools/afqmctools/hamiltonian/converter.py
utils/afqmctools/afqmctools/utils/pyscf_utils.py
utils/afqmctools/afqmctools/wavefunction/pbc.py

Minor updates for gamma point conversion script and FCIDUMP header format.

Afqmctools updates

---

tests/test_automation/spack_nightly_ubuntu.sh

The main change are:
- Bash function to make the code more compact and cleaner.
- Separate logging of Spack CONFLICTS and FAILURES.
- General hardening of script to account for bash idiosyncrasies.

Spack Regression Test Update Dec 2019

---

external_codes/mpi_wrapper/mpi3/communicator.hpp
external_codes/mpi_wrapper/mpi3/shared_window.hpp
src/AFQMC/Memory/SharedMemory/shm_ptr_with_raw_ptr_dispatch.hpp

removed need for comm& in shared_window

---

src/AFQMC/HamiltonianOperations/Real3IndexFactorization_batched.hpp
src/AFQMC/HamiltonianOperations/Real3IndexFactorization_batched_v2.hpp
src/AFQMC/Hamiltonians/HamiltonianFactory.cpp
src/AFQMC/Hamiltonians/RealDenseHamiltonian.cpp
src/AFQMC/Hamiltonians/RealDenseHamiltonian_v2.cpp
src/AFQMC/Memory/CUDA/cuda_gpu_pointer.hpp
src/AFQMC/Numerics/detail/CUDA/cublas_wrapper.hpp

Fixes bug with chunking in low memory algorithm and distributed hamiltonian for dense hamiltonian.

Fix dense hamiltonian

---

manual/lab_qmc_basics.tex
nexus/docs/nexus_user_guide.tex
tests/estimator/skinetic/skinetic_check.py
tests/performance/NiO/process_perf.py
tests/scripts/check_stats.py
tests/scripts/qtest

process_perf.py was failing due to legacy python 2 iteritems.
This PR allows the performance tests to work and report to cdash. I have verified that all the deterministic tests work and do not give python errors.

Replace python2 iteritems by items

---

manual/vmc.tex

Better walker count rounding with threads description

---

tests/estimator/latdev/latdev_check.py
tests/estimator/skinetic/skinetic_check.py

Update tests/estimator scripts for Python 3

---

src/QMCHamiltonians/NLPPJob.h
src/QMCHamiltonians/NonLocalECPComponent.cpp
src/QMCHamiltonians/NonLocalECPComponent.h
src/QMCHamiltonians/NonLocalECPotential.cpp
src/QMCHamiltonians/NonLocalECPotential.h

NLPPJob struct is more verbose than tuple.

Replace tuple with NLPPJob

---

utils/afqmctools/afqmctools/analysis/average.py
utils/afqmctools/afqmctools/analysis/extraction.py
utils/afqmctools/afqmctools/hamiltonian/mol.py

Removes some debug code and correctly define variable.

Bug fix afqmctools

---

nexus/install
nexus/lib/machines.py
nexus/tests/unit/test_machines.py

Cades at ORNL is transitioning to Slurm.  Part of the machine still uses Moab.  Support both for now.

Nexus: follow Cades transition to Slurm

---

nexus/tests/unit/test_machines.py

address test failure from #2262

update taub to golub in test_machines

---

nexus/lib/grid_functions.py
nexus/lib/pseudopotential.py

This PR implements 2D polar colormap plots to highlight the sign structure of the non-local operator component of semi-local pseudopotentials.

Nexus: add plotting capability for non-local pseudopotentials

---

config/blue_waters.sh

Update Blue Waters configure and build script in response to recent software updates.
Both @kkly1995 and myself have been able to build the QMCPACK executable using this script.
This year marks the last hurrah for Blue Waters, so this script can be removed after Dec. 31 2020.

update blue waters build script

---

nexus/README

Update the README for installation with Python 3.  Explicitly list all dependencies and how to install them.

Nexus: update installation instructions in the README

---

nexus/lib/pseudopotential.py

Nexus: guard against optional matplotlib dependency

---

src/QMCDrivers/CloneManager.cpp
src/QMCDrivers/CloneManager.h

There is no functional change in this PR. Just to facilitate some exercise in #2271

Move acceptRatio function from header to cpp.

---

.github/pull_request_template.md

We can bikeshed here, or we can merge and bikeshed via future PRs.

Initial pull request template

---

utils/afqmctools/afqmctools/hamiltonian/tests/test_kpoint.py
utils/afqmctools/afqmctools/hamiltonian/tests/test_supercell.py
utils/afqmctools/afqmctools/wavefunction/tests/test_pbc.py

Reduces afqmctools unit test running time down from a few minutes to 20 seconds so they can be incorporated into the CI eventually.
Laptop

Faster afqmctools unit test

---

tests/solids/diamondC_1x1x1_pp/qmc_trace_scalars.in.xml
tests/solids/diamondC_1x1x1_pp/qmc_trace_scalars_selective.in.xml

Fix RNG seeds in trace scalar tests.
closes #2315
- Bugfix
- New feature
- No
my desktop

Fix RNG seeds in trace scalar tests.

---

external_codes/mpi_wrapper/mpi3/communicator.hpp
external_codes/mpi_wrapper/mpi3/shared_communicator.hpp

This patch should allow to use the library in BSD, or non-linux environments.
https://github.com/QMCPACK/qmcpack/issues/2323
- Bugfix
- New feature
compatibility with BSD
- No
in Linux, I don't have a BSD to test this.

BSD compatibility

---

tests/test_automation/nightly_ornl_nitrogen.sh
tests/test_automation/ornl_nitrogen_setup.sh

Small updates to record the current working version.
The nompi builds work with these updates by using a serial HDF5 package.
Built with spack version:
git log|head
commit 27bd4a5cdd478dd5d05706cbb634d18c4e96cd54
Author: Thomas Kluyver <takowl@gmail.com>
Date:   Fri Mar 13 14:05:31 2020 +0100
- Bugfix
- No
nitrogen
- NA. Yes/No. Code added or changed in the PR has been clang-formatted
- NA. Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Yes/No. …

Nitrogen nightly script updates

---

src/OpenMP/tests/CMakeLists.txt

Fix breakage due to #2389
- Bugfix
- No
Ryzen-box

Fix ENABLE_OFFLOAD build due to catch_main change.

---

src/QMCWaveFunctions/RotatedSPOs.cpp

Fix RotatedSPOs constructor

---

src/Particle/InitMolecularSystem.cpp

Closes #2421
In step 3, N+1 and N+2 electrons were consuming the same random number and had the same coordinates.
Then no physics works.
- Bugfix
- No
Bora

Properly consume random numbers in initMolecule

---

src/AFQMC/Estimators/tests/test_estimators.cpp
src/AFQMC/HamiltonianOperations/tests/test_hamiltonian_operations.cpp
src/AFQMC/Hamiltonians/tests/test_hamiltonian_factory.cpp
src/AFQMC/Matrix/array_of_sequences.hpp
src/AFQMC/Matrix/csr_matrix.hpp
src/AFQMC/Memory/SharedMemory/shm_ptr_with_raw_ptr_dispatch.hpp
src/AFQMC/Memory/buffer_allocators.cpp
src/AFQMC/Memory/buffer_allocators.h
src/AFQMC/Memory/device_pointers.hpp
src/AFQMC/Numerics/detail/CUDA/Kernels/fill_n.cu
src/AFQMC/Numerics/detail/CUDA/Kernels/fill_n.cuh
src/AFQMC/Numerics/tests/test_dense_numerics.cpp
src/AFQMC/Numerics/tests/test_ma_blas.cpp
src/AFQMC/Numerics/tests/test_sparse_numerics.cpp
src/AFQMC/Numerics/tests/test_sparse_numerics_native.cpp
src/AFQMC/Numerics/tests/test_tensor_contraction.cpp
src/AFQMC/SlaterDeterminantOperations/tests/test_sdet_ops.cpp
src/AFQMC/Walkers/tests/test_sharedwset.cpp
src/AFQMC/Wavefunctions/tests/test_phmsd.cpp
src/AFQMC/config.0.h
src/AFQMC/config.h

PR addresses #2434 . Construction/destruction of shm pointers has been redesigned.
Now they synchronizes over the corresponding mpi3 group of the memory window.
Made changes to csr_matrix and array_of_sequences to accommodate changes.
Fixed issue with APP_ABORT in unit tests to prevent false positives.
- Bugfix
- Yes
gcc7.3, intel19.  Not tested in clang10, since it is not available in LLNL. Will let nightly test.
simply a reminder of what we are going to look …

Fix unit test and nightly

---

src/AFQMC/config.0.h

- Bugfix
- New feature
- Yes
- No
_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This …

Remove unintended macro in config.0.h

---

manual/afqmc.tex
manual/bibliography.bib

Describe AFQMC hamiltonian file formats in the manual.
- No
macbook pro latexmk

Add Afqmc Hamiltonian Description

---

src/io/hdf_archive.h
src/io/hdf_wrapper_functions.h

Minor change in hdf_archive. 1. add pointer to doc. 2. remove confusing initial vector size.
- No
Bora

Minor update hdf_archive

---

manual/developing.tex
manual/linear_algebra.tex

Documentation for linear algebra.
- No
ryzen-box

Intial linear algebra text for real space QMC

---

tests/test_automation/nightly_test_scripts/nightly_ornl.sh
tests/test_automation/nightly_test_scripts/ornl_setup.sh
tests/test_automation/nightly_test_scripts/ornl_versions.sh

Small update to nightly configuration. Readd pgi, cuda. Remove AoS. Typo fix for AMD.
- Bugfix
- Test scripts
- No
sulfur, nitrogen at ORNL

Update nightly scripts

---

examples/afqmc/06-methane_converge_back_prop/README.rst
examples/afqmc/06-methane_converge_back_prop/check_h1e_conv.py

I unwittingly added a matplotlib dependency to the afqmc examples which was not documented. I handle the import error and make a note in the README associated with the example.
- Bugfix
- Yes
macbook pro python3.7
_- Yes This PR is up to date with current the current state of 'develop'

Fix AFQMC workflow example import error.

---

utils/afqmctools/afqmctools/utils/qe_driver.py

Small update to enable kpoints in QE python toolchain.
- New feature
- Yes
Changes to python only.

Add kp support to qe tools

---

CMakeLists.txt
src/AFQMC/Estimators/Observables/atomcentered_correlators.hpp
src/AFQMC/Hamiltonians/FactorizedSparseHamiltonian.h
src/AFQMC/Hamiltonians/KPFactorizedHamiltonian.h
src/AFQMC/Hamiltonians/KPTHCHamiltonian.h
src/AFQMC/Hamiltonians/OneBodyHamiltonian.hpp
src/AFQMC/Hamiltonians/RealDenseHamiltonian.h
src/AFQMC/Hamiltonians/RealDenseHamiltonian_v2.h
src/AFQMC/Hamiltonians/THCHamiltonian.h
src/AFQMC/Memory/device_pointers.hpp
src/AFQMC/Numerics/tests/test_sparse_numerics.cpp
src/AFQMC/Propagators/AFQMCBasePropagator.h
src/AFQMC/Propagators/AFQMCDistributedPropagator.h
src/AFQMC/Propagators/AFQMCDistributedPropagatorDistCV.h
src/AFQMC/Walkers/SerialWalkerSet.hpp
src/AFQMC/Walkers/SharedWalkerSet.hpp
src/AFQMC/Walkers/WalkerSetBase.h
src/AFQMC/Wavefunctions/NOMSD.hpp
src/AFQMC/Wavefunctions/NOMSD.icc
src/AFQMC/Wavefunctions/PHMSD.hpp

Fix clang compilation errors on gpu build.
- Bugfix
- Yes
This PR is up to date with current the current state of 'develop'

Fix AFQMC compilation errors with clang on gpu build

---

src/AFQMC/HamiltonianOperations/KP3IndexFactorization_batched.hpp
src/AFQMC/HamiltonianOperations/Real3IndexFactorization.hpp
src/AFQMC/HamiltonianOperations/Real3IndexFactorization_batched.hpp
src/AFQMC/HamiltonianOperations/Real3IndexFactorization_batched_v2.hpp
src/AFQMC/Propagators/AFQMCDistributedPropagatorDistCV.h
utils/afqmctools/afqmctools/utils/gto_basis_utils.py

Several small bug fixes. Clean some warnings on clang10.
- Bugfix
- Yes

fixed several warnings and several small errors

---

src/QMCHamiltonians/CoulombPBCAA.cpp
src/QMCHamiltonians/tests/test_force.cpp

1. overlapping ions caused inf in Ewald.
2. ensure error message is sent through. Still need a fix a the upper level. No worse than the current situation.
- Bugfix
- No
My ideapad.

Fix unit hamiltonians

---

src/AFQMC/Numerics/determinant.hpp

Fixes a bug I introduced during HIP merge where I commented out some code.
@ye-luo Somehow this passed the CI which is a little troubling because the unit tests should have failed? 
- Bugfix
- No
lassen

Fix commented out code in AFQMC.

---

src/QMCTools/PyscfToQmcpack_Spline.py

Add orbital normalization on bspline converter in order to enable to use converted b-spline wavefunction with orbital norm check on QMCPACK for the following future works for the converter. Pyscf workflow test has fully performed on Intel Xeon and all passed.
- Other (please describe): Minor change in the pyscf converter.
- No
Intel Xeon …

Add orbital normalization on bspline converter.

---

nexus/lib/structure.py

This PR removes a small bug when user adds a reduced kmesh through `add_symmetrized_kmesh` within `structure.py`.
- Bugfix
- No
CADES/ORNL

Nexus: Providing fix for add_symmetrized_kmesh within structure.py

---

docs/LCAO.rst
docs/analyzing.rst
docs/contributing.rst
docs/external_tools.rst
docs/installation.rst
docs/intro_wavefunction.rst
docs/lab_advanced_molecules.rst
docs/lab_qmc_basics.rst
docs/methods.rst
docs/sCI.rst

This PR cuts down some of the warnings returned when building for HTML (or LaTeX pdf) output. These also result in some minor cosmetic fixes. 
- No
- Yes/No. This PR is up to date with current the current state of 'develop'. Yes. 
- Yes/No. Code added or changed in the PR has been clang-formatted. N/A.
- Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed. N/A. 
- Yes/No. Documentation has been added (if appropriate). Yes.

Fixes to sphinx build and some cleanup

---

src/Estimators/tests/EstimatorManagerBaseTest.cpp
src/Estimators/tests/EstimatorManagerNewTest.cpp
src/QMCHamiltonians/StressPBC.cpp

Fix GNU warnings.
- Other (please describe): Remove warning
- No
Ryzen-box

Fix GNU warning

---

utils/afqmctools/afqmctools/wavefunction/converter.py

Fix converter for DMC(CIPSI) trial wavefunction to AFQMC format. Fix casting issue for numpy.uint64. + cosmetic changes.
- Bugfix
- No
python3.7.2, numpy1.16.2 

Fix DMC to AFQMC wavefunction converter.

---

docs/afqmc.rst
docs/index.rst
docs/lab_afqmc.rst
examples/afqmc/01-neon_atom/README.rst
examples/afqmc/02-neon_frozen_core/README.rst
examples/afqmc/03-carbon_triplet_uhf/README.rst
examples/afqmc/04-N2_nomsd/README.rst
examples/afqmc/05-N2_phmsd/README.rst
examples/afqmc/06-methane_converge_back_prop/README.rst
examples/afqmc/07-diamond_2x2x2_supercell/README.rst
examples/afqmc/08-diamond_2x2x2_kpoint_sym/README.rst

Added documentation:
- Wavefunction format
- Include existing tutorials
- afqmctools
- current feature status on cpu / gpu table
@mmorale3 can you check the current feature status table in particular. I wasn't sure about the MSD status with different Hamiltonians.
- No
macbook pro python3.7.7 sphinx3.0.5
- Ye. This PR is up to date with current the current state of 'develop'

Add more AFQMC documentation

---

src/QMCHamiltonians/tests/test_ecp.cpp
src/QMCWaveFunctions/EinsplineSpinorSetBuilder.cpp
src/QMCWaveFunctions/SpinorSet.cpp
src/QMCWaveFunctions/SpinorSet.h
src/QMCWaveFunctions/tests/test_dirac_det.cpp

To make the ownership clean in SpinorSet.
- No
ryzen-box

Change to unique_ptr in SpinorSet

---

docs/developing.rst
src/QMCWaveFunctions/ExampleHeComponent.cpp

From the discussion in #2643, update the documentation on adding a wavefunction.
Also update ExampleHeComponent to match by setting LogValue in evaluateLog.
- Bugfix
- No
laptop

Update handling of LogValue in docs

---

src/QMCWaveFunctions/BsplineFactory/SplineC2C.cpp
src/QMCWaveFunctions/BsplineFactory/SplineC2C.h
src/QMCWaveFunctions/BsplineFactory/SplineC2COMP.cpp
src/QMCWaveFunctions/BsplineFactory/SplineC2COMP.h
src/QMCWaveFunctions/BsplineFactory/SplineC2R.cpp
src/QMCWaveFunctions/BsplineFactory/SplineC2ROMP.cpp
src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp
src/QMCWaveFunctions/BsplineFactory/createComplexSingle.cpp
src/QMCWaveFunctions/CMakeLists.txt

Implement complex spline orbital code path. Existing unit and integration tests cover the added code paths.
- New feature
- No
bora-external

Add SplineC2C OpenMP offload

---

src/Utilities/NewTimer.cpp
src/Utilities/NewTimer.h
src/Utilities/TimerManager.cpp
src/Utilities/TimerManager.h

Review after  #2661
Remove parent timer pointer in the timer.
Add docs in TimerType and TimerManager.
Add safeguard checking push and pop in the timer stack.
- No
Bora

Improve timer and its manager

---

config/build_olcf_summit_Clang.sh
config/build_tulip.sh
src/QMCApp/QMCMain.cpp
tests/test_automation/nightly_test_scripts/nightly_Ye_dell.sh
tests/test_automation/nightly_test_scripts/nightly_Ye_ryzen.sh
tests/test_automation/nightly_test_scripts/nightly_anl_bora.sh

Update and archive all the nightly scripts.
Also fix a typo "accelerator" instead of "accellerator".
- Bugfix
- No
Ryzen-box

Update nighlty scripts and fix a typo

---

nexus/lib/qmcpack_input.py

Adds `LR_handler` QMCPACK input as an option to Nexus
- New feature
- No
Laptop.

Nexus: add LR_handler input

---

examples/afqmc/06-methane_converge_back_prop/reference/test_obs.py

Fixes typo in python script.
- Bugfix
- No
macbook python3.7.7 

Fix AFQMC Workflow Test Script.

---

src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp
src/QMCDrivers/WFOpt/QMCCostFunctionBatched.h

This PR follows #2701 
Remove some raw pointers from the code and replace with unique_ptr.
- No
laptop

Remove some raw pointers from batched cost function

---

nexus/lib/pseudopotential.py

Fix a small bug in pseudopotential plotting.
- Bugfix
- No
Laptop

Nexus: one line fix for pseudopotential plotting

---

src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h

Fix #2742. @camelto2 I checked in VMC only.
- Bugfix
- No
Bora

Fix J2 KEcorr in multi threaded runs.

---

src/AFQMC/Memory/HIP/hip_arch.cpp
src/AFQMC/Numerics/detail/HIP/Kernels/copy_n_cast.hip.cpp
src/AFQMC/Numerics/detail/HIP/Kernels/copy_n_cast.hip.h
src/AFQMC/Numerics/detail/HIP/Kernels/fill_n.hip.cpp
src/AFQMC/Numerics/detail/HIP/Kernels/uninitialized_copy_n.hip.cpp
src/AFQMC/Numerics/detail/HIP/Kernels/uninitialized_fill_n.hip.cpp

Fix some compilation errors that crept in.
- Bugfix
- No
MI60 / rocm 3.7
-No. This PR adds tests to cover any new code, or to catch a bug that is being fixed

Fix AFQMC HIP compilation errors.

---

src/QMCDrivers/DMC/DMCBatched.cpp
src/QMCDrivers/WalkerControlBase.cpp

The batched driver crashes when the NiO performance tests are run.  This fixes an issue seen when they are run on one rank as well as >1.
- Bugfix
- No

Fix batched driver crashes in performance tests

---

src/QMCWaveFunctions/SPOSet.cpp
src/QMCWaveFunctions/SPOSet.h
src/QMCWaveFunctions/tests/test_einset.cpp
src/QMCWaveFunctions/tests/test_hybridrep.cpp

They are not needed in near term and easy to reintroduce. So delete them to reduce the maintenance.
- Other (please describe): delete things not needed.
- No
Bora

Remove unused multi walker API

---

config/build_tulip.sh

Mostly module changes.
- Build recipe changes
- No
tulip

Update tulip build script.

---

nexus/bin/qdens

One line fix for qdens
- Bugfix
- No
Laptop

Nexus: Fix qdens bug in averages

---

src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp

A missing change from #2780. Need to work on CI to cover this when I have some free cycles.
- Bugfix
- No
ryzen-box

One missing change OMP to OMPTarget

---

CHANGELOG.md

Summary of changes since v3.9.2. Still listed as unreleased to allow for more changes ahead of release candidate.
- No
Laptop

Update changelog ahead of release

---

nexus/lib/machines.py

Allow user to submit jobs to new AMD nodes on Cori.
- New feature
- No
Laptop

Nexus: support AMD nodes on Cori

---

src/QMCDrivers/tests/test_MCPopulation.cpp

Also reduce memory usage in test_MCPopulation.
- Bugfix
- No
ryzen-box

Reduce walker count in test_MCPopulation.

---

.github/pull_request_template.md
docs/developing.rst

Update header inclusion rule. Close #2762
Add smart pointer guide
- No

Update development guide

---

src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp

Set the RNG state to be the same during checkConfigurations and correlatedSampling.
The "test" optimize method compares the analytic and finite difference parameter gradients.  If NLPP is involved, and the RNG is not reset before correlatedSampling, the gradients can differ in the comparison by 1-10%.   If everything is correct, and the RNG is reset properly, the gradients differ on the order of 1e-8 to 1e-6.
- Bugfix
- No
laptop, desktop
- Yes. Code added or changed in the PR has …

Reset the RNG state during cost function evaluation

---

docs/spin_orbit.rst

The end tag should be a forward slash which is fixed here.
- No

Small typo in Documentation

---

src/Estimators/EstimatorManagerNew.cpp

Use the right index into the right vector. Otherwise it will probably work until it doesn't. test_estimators and test_estimators_mpi now pass llvm ASAN.
- Bugfix
- No

fixing classic heap overflow

---

tests/molecules/He_ae/CMakeLists.txt
tests/molecules/He_ae/det_He_opt_batch.xml

Add a version of the He_ae optimizer test that calls batch_opt.
- No
laptop

Add batch version of He_ae optimization test

---

src/QMCDrivers/DMC/WalkerControl.cpp

@PDoakORNL noticed this and I clearly did the wrong thing against my will.
It deserves a unit test checking computeCurData function.
- Bugfix
- No
Bora

Fixed dmc.dat in batched DMC driver

---

src/Particle/Walker.h
src/QMCDrivers/DMC/DMCBatched.cpp
src/QMCDrivers/QMCDriverNew.cpp
src/QMCDrivers/QMCDriverNew.h
src/QMCDrivers/VMC/VMCBatched.cpp
src/QMCWaveFunctions/TrialWaveFunction.cpp

Fix #2865. The bug only affects unit test with debug turned.
Rewrite check in VMCBatch to be shared by VMCBatch and DMCBatch.
- Bugfix
- No

Fix #2865 and rewrite a bit error check

---

src/QMCDrivers/DMC/DMCBatched.cpp
src/QMCDrivers/DMC/DMCBatched.h
src/QMCDrivers/DMC/DMCFactoryNew.cpp
src/QMCDrivers/DMC/DMCFactoryNew.h
src/QMCDrivers/QMCDriverFactory.cpp
src/QMCDrivers/QMCDriverFactory.h
src/QMCDrivers/QMCDriverNew.cpp
src/QMCDrivers/QMCDriverNew.h
src/QMCDrivers/VMC/VMCBatched.cpp
src/QMCDrivers/VMC/VMCBatched.h
src/QMCDrivers/VMC/VMCFactoryNew.cpp
src/QMCDrivers/VMC/VMCFactoryNew.h
src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp
src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h
src/QMCDrivers/WFOpt/QMCLinearOptimizeBatched.cpp
src/QMCDrivers/WFOpt/QMCLinearOptimizeBatched.h
src/QMCDrivers/WFOpt/QMCOptimizeBatched.cpp
src/QMCDrivers/WFOpt/QMCOptimizeBatched.h
src/QMCDrivers/WFOpt/QMCWFOptFactoryNew.cpp
src/QMCDrivers/WFOpt/QMCWFOptFactoryNew.h
src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp

To complete some of the review requests from #2870. Renaming + documentation.
- No
epyc-server

Address reviews of #2870

---

.gitignore

Ignore all the untracked files that will be created by nexus tests, polluting the git repo.
- No
Laptop, git client.

Git ignore nexus test output

---

src/Particle/ParticleSetPool.cpp
src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
src/QMCWaveFunctions/WaveFunctionFactory.cpp

Plus a bit printing.
- New feature
- No
epyc-server

Turn on batched SD when Offload.

---

src/Platforms/Host/InfoStream.cpp
src/Platforms/Host/InfoStream.h
src/QMCWaveFunctions/HarmonicOscillator/SHOSet.cpp
src/QMCWaveFunctions/HarmonicOscillator/SHOSet.h
src/QMCWaveFunctions/RotatedSPOs.h
src/QMCWaveFunctions/SPOInfo.cpp
src/QMCWaveFunctions/SPOInfo.h
src/QMCWaveFunctions/SPOSet.cpp
src/QMCWaveFunctions/SPOSet.h
src/Utilities/tests/test_infostream.cpp

Clean up InfoStream internal pause/resume logic. closes #2248
Add more override keyword
- New feature
- No
epyc-server

Clean up InfoStream internal pause/resume logic

---

src/QMCWaveFunctions/BsplineFactory/SplineSetReader.h

More useful info when read failed. Helped me troubleshooting.
- New feature
- No
epyc-server

Includes more detail in the error message at spline h5 read failure

---

tests/solids/diamondC_2x1x1_pp/CMakeLists.txt
tests/solids/diamondC_2x1x1_pp/qmc_long_vmc_dmc_dla.in.xml
tests/solids/diamondC_2x1x1_pp/qmc_short_vmc_dmc_dla.in.xml

Add tests for DLA.
- No
nitrogen. llvmdev+openblas.

Add DLA short and long tests

---

examples/afqmc/06-methane_converge_back_prop/check_h1e_conv.py
examples/afqmc/07-diamond_2x2x2_supercell/scf.py
examples/afqmc/08-diamond_2x2x2_kpoint_sym/scf.py

Trivial Python fixes from #2872 partially address #2851
- Bugfix
- No
i7-8750H, Fedora 33 (gcc 10.2.1, python 3.9.1, h5py 3.1.0)

update AFQMC converter Python scripts

---

src/QMCDrivers/DMC/SODMCUpdatePbyPFast.cpp
src/QMCDrivers/VMC/SOVMCUpdatePbyP.cpp

Some additional changes have been added recently to VMCUpdatePbyP and DMCUpdatePbyPFast. These were not added to the SOVMC/DMC versions, so I'm adding them here. 
-new feature
- No
my workstation

bring SOQMCUpdatePbyP up to date with recent changes

---

nexus/bin/eshdf
nexus/bin/nxs-redo
nexus/bin/nxs-sim
nexus/bin/nxs-test
nexus/bin/qdens
nexus/bin/qmc-fit
nexus/bin/qmca
nexus/install
nexus/lib/versions.py

This PR propagates the Nexus version to all executables in a guarded fashion (single source of truth) and updates the version number.

Nexus: update version ahead of release

---

nexus/tests/unit/test_qdens.py

Remove dangling print statement left inadvertently in PR #2983.

Nexus: remove print statements from test

---

src/Containers/OhmmsSoA/PosTransformer.h
src/Particle/DistanceTableData.h
src/Particle/Lattice/ParticleBConds3DSoa.h
src/Particle/SoaDistanceTableAA.h
src/Particle/SoaDistanceTableAAOMPTarget.h
src/Particle/SoaDistanceTableAB.h
src/Particle/SoaDistanceTableABOMPTarget.h
src/QMCHamiltonians/MomentumEstimator.cpp
src/QMCWaveFunctions/BsplineFactory/HybridRepCenterOrbitals.h
src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h
src/QMCWaveFunctions/Fermion/DiracMatrix.h
src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h
src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h
src/QMCWaveFunctions/Jastrow/PolynomialFunctor3D.h
src/spline2/MultiBspline1D.hpp
src/spline2/MultiBsplineVGHGH.hpp
src/spline2/MultiBsplineVGLH.hpp
src/spline2/MultiBsplineVGLH_OMPoffload.hpp
src/spline2/MultiBsplineValue.hpp
src/spline2/MultiBsplineValue_OMPoffload.hpp

1. Add status check to lapack calls
2. Specify alignment for omp simd  aligned(x, y, z: QMC_SIMD_ALIGNMENT)
3. More const in distance table.
- New feature
- No
Bora

Add lapack status check

---

src/QMCDrivers/VMC/VMCBatched.cpp

Don't print any warmup related messages when there is no warmup
- Bugfix
- No
nitrogen llvmdev nightly config

No warmup info when no warmup in VMCBatched

---

config/build_olcf_summit_Clang.sh

Update build recipe on Summit using Clang compiler. Just reorganize the script a bit.
- No
Summit

Update Summit Clang recipe.

---

src/Particle/PSdispatcher.cpp
tests/solids/diamondC_2x1x1_pp/CMakeLists.txt
tests/solids/diamondC_2x1x1_pp/det_qmc_short_vmcbatch_dmcbatch_mwalkers_serialized.in.xml

Fix walker serialization in batched drivers.
also added a test.
- Bugfix
- No
bora

Fix walker serialization in batched drivers

---

.github/workflows/ci-github-actions.yaml
config/github-actions/ci/run_step.sh
tests/test_automation/github-actions/ci/run_step.sh

Attempting to fix GitHub Actions permission issue for users other than root, so MPI tests can run
Figure out test failures on GitHub Actions workflow
- Bugfix
- No
- No. Code added or changed in the PR has been clang-formatted (NA)

Address failures in GitHub Actions

---

src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantFast.cpp
src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantFast.h

There were bugs introduced in #2947. Bugfix and a bit more code cleaning/optimization.
Closes #3030
- Bugfix
- No

Fix MSD opt bugs and more optimization

---

tests/solids/diamondC_2x1x1-Gaussian_pp_cplx_MSD_excited/vmc_long_ground_noj.in.xml
tests/solids/diamondC_2x1x1-Gaussian_pp_cplx_MSD_excited/vmc_short_ground_noj.in.xml

incorrect input file pointed.
https://cdash.qmcpack.org/CDash/testDetails.php?test=12509819&build=196222
- Bugfix
- No
bora

Fix diamondC_2x1x1-Gaussian_pp_cplx_MSD_excited ground case.

---

src/QMCWaveFunctions/detail/CUDA_legacy/determinant_update.cu

Use lapack for determinant update in the standalone test code. No functional changes. Formatted the test source code only.
- No
nitrogen. Nightly configuration. Compile line as indicated.

Update CUDA_TEST_MAIN determinant update code

---

src/AFQMC/HamiltonianOperations/Real3IndexFactorization.hpp
src/AFQMC/HamiltonianOperations/Real3IndexFactorization_batched.hpp
src/AFQMC/HamiltonianOperations/Real3IndexFactorization_batched_v2.hpp
src/AFQMC/Wavefunctions/NOMSD.hpp
src/AFQMC/Wavefunctions/PHMSD.hpp

Small bug fix on collinear calculations with the Dense hamiltonian.
- Bugfix
- No

Bugfix on Dense hamiltonian for collinear calculations

---

CHANGELOG.md

Update changelog since last release. Based on a by-hand rewrite of github-changelog-generator output.
- No
None.

Update changelog with unreleased changes

---

.github/workflows/ci-github-actions.yaml
tests/test_automation/github-actions/ci/run_step.sh

Reorganize GitHub Actions from discussion in PR #3069
Enable real and complex builds
Attempt to merge real and complex code coverage reports in codecov
Unify coverage and sanitizer matrices
- Refactoring: GitHub Actions CI
- Testing changes: add complex and real CI builds
- No
Must work on GitHub Actions
- No. Code added or changed in the PR has been clang-formatted (NA)

Reorganize GitHub Actions

---

docs/methods.rst

Minimal initial documentation for dmc_batch
- No
laptop

Minimal dmc_batch documentation.

---

CMake/macros.cmake
CMakeLists.txt

Require CMake 3.14 and remove workaround for older versions.
- Yes
simply a reminder of what we are going to look for before merging …

Require CMake 3.14

---

nexus/lib/basisset.py
nexus/lib/pseudopotential.py

Add ability to read PPs in the format of Eric Shirley's numerical HF code.
- New feature
- No. nxs-test passes all tests.
Laptop

Nexus: read numhf format

---

nexus/lib/simulation.py

Addresses issues faced in #3100.  
- Bugfix
- No
Ubuntu Docker image on laptop.

Nexus: use OS environment by default

---

src/QMCTools/tests/CMakeLists.txt

Run qmc-check-affinity, verify no errors. Might help catch MPI and OpenMP issues.
- No
sulfur, llvm, no mpi and openmpi

Test qmc-check-affinity

---

README.md

Update README.md to current status
- No
None

Update prereqs+nightly versions in README.md

---

utils/code_tools/qmcpack-elisp-generators.el
utils/code_tools/qmcpack-style.el

Improved documentation for the elisp code tools.
- No
Leconte

Update for elisp generators documentation

---

src/QMCWaveFunctions/tests/test_DiracMatrixComputeOMPTarget.cpp

fix offload non-cuda build. We will add CI to catch this.
- Bugfix
- No
epyc-server

Remove CUDA contamination which breaks offload.

---

docs/conf.py
docs/hamiltonianobservable.rst
docs/methods.rst
docs/requirements.txt
nexus/sphinx_docs/conf.py

Update sphinx versions and configuration to support current releases. Fix warnings. Note that sphinxcontrib-bibtex v2 is incompatible with v1.
- Bugfix
- New feature
- Yes 
Local mac. RTD CI must pass.

Update sphinx usage

---

CMake/ClangCompilers.cmake
CMake/GNUCompilers.cmake
CMake/IntelCompilers.cmake
CMake/PGICompilers.cmake
CMakeLists.txt
doxygen/config.h
src/Numerics/HDFNumericAttrib.h
src/Particle/ParticleBase/RandomSeqGenerator.h
src/QMCTools/ppconvert/src/ParserClass.cc
src/QMCTools/ppconvert/src/common/Standard.h
src/QMCTools/ppconvert/src/config.h
src/config.h.cmake.in
src/einspline/CMakeLists.txt
src/einspline/bspline_create.c
src/einspline/multi_bspline_create.c
src/einspline/multi_bspline_structs.h
src/einspline/multi_nubspline_create.c
src/einspline/multi_nubspline_structs.h

Per the title, remove several legacy/used include checks and defines
- No
nitrogen, llvm

Remove unused include and library checks

---

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.2.cpp
src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.h
src/QMCWaveFunctions/Fermion/MultiSlaterDeterminant.cpp
src/QMCWaveFunctions/Fermion/MultiSlaterDeterminant.h
src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantWithBackflow.cpp
src/QMCWaveFunctions/LCAO/LCAOSpinorBuilder.cpp
src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp
src/QMCWaveFunctions/LCAO/LCAOrbitalSet.h
src/QMCWaveFunctions/LCAO/LCAOrbitalSetWithCorrection.cpp

To help review other PRs.
- No
epyc-server

Format MSD and LCAO classes.

---

src/einspline/tests/test_3d.cpp
src/einspline/tests/test_one.cpp

This frees owning raw pointers that are currently leaking memory.
This is part of #3083
- Bugfix
- No
simply a reminder of what we are going to …

Fix detected memory leaks in deterministic-unit_test_einspline

---

src/QMCHamiltonians/CoulombPBCAA.h
src/QMCHamiltonians/CoulombPBCAB.h
src/QMCHamiltonians/CoulombPotential.h
src/QMCHamiltonians/LocalECPotential.h
src/QMCHamiltonians/MPC.h
src/QMCHamiltonians/SkEstimator.h
src/QMCWaveFunctions/Fermion/SlaterDet.h

add override keyword
- No
epyc-server

Reduce clang override warning

---

src/QMCWaveFunctions/LCAO/LCAOrbitalBuilder.cpp

fixes #3228
- Bugfix
- No
epyc-server

Workaround MPI bcast(bool) issue

---

src/Containers/OhmmsPETE/TinyVector.h
src/QMCWaveFunctions/EinsplineSet.cpp
src/QMCWaveFunctions/EinsplineSet.h
src/QMCWaveFunctions/EinsplineSetBuilder.h
src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp
src/QMCWaveFunctions/EinsplineSetCuda.cpp
src/QMCWaveFunctions/einspline_helper.hpp

This updates EinsplineSet.h with the correct function signatures so that the base class implementation is no longer called.
Fixes #3252 
- Bugfix
- Yes
- No
simply a reminder of what we are going to look for …

Fix legacy_cuda build

---

tests/solids/LiH_solid_1x1x1_pp/fake_nspin2/hf_vmc_LiH-gamma.xml
tests/solids/LiH_solid_1x1x1_pp/fake_nspin2/hf_vmc_LiH-x.xml

Fixes
https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=226491
- No
epyc-server

Update qmcpack input files in the QE test flow.

---

src/QMCWaveFunctions/Jastrow/OneBodyJastrowOrbitalBspline.cpp

Fix cuda test_wavefunction_jastrow fail

---

CHANGELOG.md

Advertise @ye-luo 's QE6.8 patch
- No
None

Mention QE 6.8 in unreleased changelog

---

src/io/hdf/hdf_stl.h

Patch to overwrite dataset data properly checking for dataset existence.
Related to #3249 
- Bugfix
- No

Check for dataset existence in hdf5 write wrapper

---

src/QMCDrivers/tests/test_QMCCostFunctionBatched.cpp

Get the Hamiltonian derivatives rather than the WF derivatives.
- Bugfix
- No
desktop

Small fix for fill linear matrices test

---

src/QMCWaveFunctions/BsplineFactory/HybridRepCenterOrbitals.h

Closes #3400 . Workaround gcc7 build problem. Since not present with other compilers, presumed a since fixed compiler bug.
- Bugfix
- No
sulfur, nompi, gcc7.5. Build & full deterministic set.

Fix gcc7 builds

---

src/Particle/accept_kernel.cu
src/Platforms/CUDA_legacy/cuda_inverse.cu
src/Platforms/CUDA_legacy/cuda_inverse.h
src/Platforms/CUDA_legacy/devices.h
src/Platforms/CUDA_legacy/gpu_misc.h
src/Platforms/CUDA_legacy/gpu_vector.h
src/Platforms/ROCm/cuda2hip.h
src/Platforms/ROCm/hipBLAS.hpp
src/QMCHamiltonians/ECPComponentBuilder.2.cpp
src/QMCHamiltonians/NLPP.cu
src/QMCWaveFunctions/detail/CUDA_legacy/AtomicOrbitalCuda.h
src/QMCWaveFunctions/detail/CUDA_legacy/PhaseFactors.cu
src/QMCWaveFunctions/detail/CUDA_legacy/delayed_update.cu
src/QMCWaveFunctions/detail/CUDA_legacy/delayed_update.h
src/QMCWaveFunctions/detail/CUDA_legacy/determinant_update.cu
src/einspline/bspline_base_cuda.h
src/einspline/bspline_structs_cuda.h

Adding AMD copyright notice to the files implementing the HIP2CUDA translation.
Affects only copyright info in comments.
No
N/A

Add AMD copyright notice

---

src/QMCWaveFunctions/BsplineFactory/HybridRepCenterOrbitals.h

Declaring the class to be friended seems to be the key. Fixes #3400 
- Bugfix
- No
bora

A cleaner fix for issue 3400.

---

src/QMCHamiltonians/GridExternalPotential.cpp
src/QMCHamiltonians/GridExternalPotential.h

This is part of #3401
- Bugfix
- No
- Yes/No. Code added …

Use correct deleter for UBspline_3d_d

---

nexus/lib/gamess_analyzer.py

For gamess_analyzer.py, in the case that  .F07 punch file is empty or not present, attempt to read .dat punch file.
- New feature
- No. Relevant nxs-test tests pass
Linux laptop

Nexus:  add punch extension

---

CMake/FindAMDLibM.cmake
CMake/FindIBMMASS.cmake

Hard coded -lmass is problematic. Use rely on CMake for handling paths.
- No
Summit

Add IBM::MASS/MASSV targets

---

src/CMakeLists.txt
src/Estimators/SpinDensityInput.cpp
src/Estimators/SpinDensityInput.h
src/Estimators/SpinDensityNew.cpp
src/Estimators/SpinDensityNew.h
src/Estimators/tests/test_SpinDensityNew.cpp
src/Particle/CMakeLists.txt
src/Particle/ParticleSet.h
src/Particle/SpeciesSet.cpp
src/Particle/SpeciesSet.h
src/QMCDrivers/MCPopulation.h

triggered by the move, add more cleaning to SpinDensityNew.
- No
epyc-sever

Move SpeciesSet from Utilities to Particle

---

src/Platforms/CPU/math.hpp
src/Platforms/OMPTarget/OMPTargetMath.hpp

Some oversight.
- Bugfix
- No
epyc-server

Add restrict keyword in sincos wrappers.

---

src/QMCHamiltonians/NonLocalECPotential.cpp

There is a data race in NLPP where the joblist is prepared. The race is caused by sharing the same RNG withing a crowd.
The issue was not exposed because this level of threading is only active when crowd level threading is turned off which is a scenario when I debug codes.
- Bugfix
- No
epyc-server, bora

Fix NLPP race in batched implementation.

---

src/QMCWaveFunctions/ElectronGas/ElectronGasOrbitalBuilder.cpp
src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h
src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.cpp
src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.h
src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.h
src/QMCWaveFunctions/Fermion/MultiSlaterDeterminant.cpp
src/QMCWaveFunctions/Fermion/MultiSlaterDeterminant.h
src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantFast.cpp
src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantFast.h
src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantWithBackflow.cpp
src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantWithBackflow.h
src/QMCWaveFunctions/Fermion/SlaterDet.h
src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
src/QMCWaveFunctions/Fermion/SlaterDetBuilder.h
src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.cpp
src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.h

review after #3397
Fixes #3383
Remove setBF and replace shared_ptr with unique_ptr and references.
- No
epyc-server

Remove setBF

---

src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp

Expand test_TrialWaveFunction_diamondC_2x1x1 to cover NLPP needs.
- No
epyc-server

Expand test_TrialWaveFunction_diamondC_2x1x1

---

src/Particle/DistanceTableData.h
src/Particle/ParticleSet.cpp
src/Particle/SoaDistanceTableAA.h
src/Particle/SoaDistanceTableAAOMPTarget.h
src/Particle/SoaDistanceTableAB.h
src/Particle/SoaDistanceTableABOMPTarget.h
src/Particle/VirtualParticleSet.cpp
src/Particle/tests/test_particle.cpp
src/QMCHamiltonians/PairCorrEstimator.cpp

To follow up-to-date convention.
- No
epyc-server

Rename distance table variables

---

nexus/lib/qmcpack_converters.py
nexus/tests/unit/test_qmcpack_converter_simulations.py
nexus/tests/unit/test_qmcpack_simulation.py

Update convert4qmc usage to modern format.  Please give this PR a quick turnaround as it is for the workshop which is under continuous development.
- Bugfix
- No
Laptop

Nexus: fix convert4qmc usage

---

nexus/lib/versions.py

Fix copy/paste error
- Bugfix
- No

cif2cell_supported not set

---

CMakeLists.txt

Confirm needed packages at CMake instead of during compilation.
- Bugfix
- No
epyc-server

Harden ROCM in CMake.

---

nexus/lib/testing.py
nexus/tests/unit/test_qdens.py

Adds more detailed message upon failure for qdens test.  This should help narrow down the cause of failure on certain test machines.
- No
Workstation

Nexus: make qdens test more informative

---

tests/test_automation/nightly_test_scripts/nightly_olcf_spock.sh

Add performance-NiO tests with `QMC_NIO_MAX_SIZE==8` on spock nightly tests
Add more requested time
Add timestamp for log messages
Related to #3402 
- No
spock, must pass nightly

Expand Spock nightly tests with performance-NiO

---

src/Containers/OhmmsPETE/Tensor.h
src/Containers/OhmmsSoA/TensorSoaContainer.h
src/Containers/OhmmsSoA/VectorSoaContainer.h
src/Particle/Lattice/ParticleBConds.h
src/Particle/ParticleIO/XMLParticleIO.h
src/Platforms/CUDA/CUDAallocator.hpp
src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp
src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp
src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h
src/QMCDrivers/WFOpt/QMCLinearOptimize.h
src/io/hdf/hdf_dataspace.h

Fix typo for doxygen and also adjust all other occurrence.
- No
epyc

Fix typo tparm -> tparam

---

src/Particle/ParticleSet.cpp
src/Particle/ParticleSet.h
src/Particle/createDistanceTable.h
src/Particle/createDistanceTableAA.cpp
src/Particle/createDistanceTableAAOMPTarget.cpp
src/Particle/createDistanceTableAB.cpp
src/Particle/createDistanceTableABOMPTarget.cpp

Closes #3616 
- No
epyc-server

Use unique_ptr in DTs of ParticleSet.

---

tests/performance/C-graphite/sample/dmc-a64-e256-cpu/C-graphite-S256-dmc.xml
tests/performance/C-graphite/sample/dmc-a64-e256-gpu/C-graphite-S256-dmc.xml

Closes #3630 
- Bugfix in tests
- No
epyc-server

Update performance/C-graphite input files.

---

tests/test_automation/github-actions/ci/run_step.sh

Switch point to point manager to ucx
Attempts to fix #3658 
- Bugfix
- Yes

Switch MPI point2point manager to ucx on sulfur

---

README.md

Update the software versions used.
Also intended to see if our CI is working properly
- No
None

Update README.md software versions

---

docs/github_actions.rst

Update CI docs with Intel19 jobs
Test newly added Intel19 jobs on CI
Related to #3639 
- Yes

Update docs with Intel19 jobs

---

src/QMCHamiltonians/ACForce.cpp
src/QMCHamiltonians/ACForce.h
src/QMCHamiltonians/tests/test_force.cpp

Refactored ACForce into a class
Separate declaration (.h) from definition (.cpp)
Initial attempt to add some unit test to `ACForce`, currently at 0% in codecov
Related to #2238 and #3411
- No

Refactor ACForce into a class

---

external_codes/quantum_espresso/add_pw2qmcpack_to_qe-7.0.diff
external_codes/quantum_espresso/download_and_patch_qe7.0.sh

Add pw2qmcpack patch for QE 7.0.
Pass all `ctest -R qe -j32` tests.
- New feature
- No
epyc-server

Add QE 7.0 pw2qmcpack patch.

---

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.2.cpp
src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp

Closes #3690 
- Bugfix
- No
epyc-server

Fix Debug build failure caused by #3689

---

src/QMCTools/ppconvert/test/Oxygen/CMakeLists.txt

reported by #3717
- Bugfix
- No
ryzen-box

Fix the ppconvert test broken by 4587bf5.

---

src/Platforms/CUDA/CUDAruntime.hpp
src/Platforms/CUDA/cuBLAS_missing_functions.hpp
src/QMCWaveFunctions/detail/CUDA/cuBLAS_LU.hpp

Non-functional change. Use "CUDAruntime.hpp" more.
- No
epyc-server

Use more CUDAruntime.hpp

---

src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp

#3755 is missing a change.
- Bugfix
- No
epyc-server

Fix DiracDeterminant makeCopy.

---

src/Particle/LongRange/LRCoulombSingleton.cpp
src/Particle/LongRange/LRCoulombSingleton.h
src/Particle/LongRange/LRHandlerTemp.h
src/QMCHamiltonians/CoulombPBCAA.h
src/QMCHamiltonians/CoulombPBCAB.h
src/QMCHamiltonians/CudaCoulomb.cu
src/QMCHamiltonians/CudaCoulomb.h

Non functional change.
- No
epyc

More const in Coulomb related classes

---

.github/workflows/ci-github-actions-self-hosted.yaml

Reinstate nitrogen-rocm CI tests after measuring nitrogen-cuda CI by itself (little change in overall times)
- Yes
Must pass ornl CI

Reinstate nitrogen-rocm CI

---

tests/test_automation/github-actions/ci/run_step.sh

Update Clang14Dev commit used in sulfur CI
Targets AFQMC Offload cases
Complex cases still not included due to numerical failure.
Fixes #3787
- No

Update Clang14Dev in sulfur CI 

---

src/Particle/LongRange/StructFact.cpp
src/Particle/LongRange/StructFact.h
src/Particle/ParticleSet.cpp
src/Particle/ParticleSet.h

No feature relies on this functionality probably for a decade.
- Other (please describe): Code removal
- No
epyc-server

Remove makeMove/accept/rejectMove in StructFact.

---

tests/molecules/FeCO6_b3lyp_gms/CMakeLists.txt
tests/molecules/FeCO6_b3lyp_gms/det_vmc_noj.in.xml
tests/molecules/FeCO6_b3lyp_gms/det_vmcbatch_noj.in.xml
tests/molecules/FeCO6_b3lyp_pyscf/CMakeLists.txt
tests/molecules/FeCO6_b3lyp_pyscf/det_vmc_noj.in.xml
tests/molecules/FeCO6_b3lyp_pyscf/det_vmcbatch_noj.in.xml

Close #3822 .
Add deterministic test for FeCO6 to catch related issue (eg. #3820) in CI.
- No
Intel Xeon workstation

Add deterministic test for FeCO6

---

src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h
src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h

It doesn't seem to impact much when using LLVM OpenMP offload to NVIDIA but does have a huge impact on AOMP offload to AMD GPU. So add the specialization.
- Other (please describe): performance optimization.
- No
summit, crusher

Specialize batched transfer of psiM_vgl.

---

.github/workflows/ci-github-actions.yaml

Add `main` branch as a target for GitHub Actions CI runners
- No
Must pass CI

Add main branch to GitHub Actions CI target

---

.github/workflows/ci-github-actions.yaml

Add main branch as a target for GitHub Actions CI runners
- No
Must trigger CI on main PR

Add main branch as GitHub Actions CI target [PR into main]

---

src/AFQMC/Estimators/EnergyEstimator.h
src/AFQMC/HamiltonianOperations/Real3IndexFactorization.hpp
src/AFQMC/HamiltonianOperations/THCOpsIO.hpp
src/AFQMC/Hamiltonians/RealDenseHamiltonian.cpp
src/AFQMC/Hamiltonians/RealDenseHamiltonian_v2.cpp
src/AFQMC/Hamiltonians/THCHamiltonian.cpp
src/AFQMC/Matrix/ma_hdf5_readers.hpp
src/AFQMC/Numerics/ma_blas_extensions.hpp
src/AFQMC/Numerics/ma_operations.hpp
src/AFQMC/Wavefunctions/PHMSD.hpp
src/AFQMC/Wavefunctions/PHMSD.icc
src/AFQMC/Wavefunctions/WavefunctionFactory.cpp
src/io/hdf/hdf_multi.h
src/type_traits/container_traits_multi.h

Remove warnings about unsigned to signed conversions.
- No

make narrowing conversions explicit (unsigned to signed)

---

src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp
src/QMCWaveFunctions/BsplineFactory/createComplexSingle.cpp
src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp

See title.
- Bugfix
- No
epyc-server

Less confusing message where there is no GPU.

---

src/Particle/LongRange/tests/test_ewald3d.cpp
src/Particle/LongRange/tests/test_lrhandler.cpp
src/Particle/LongRange/tests/test_srcoul.cpp
src/Particle/LongRange/tests/test_temp.cpp

Noticed larger range with OneAPI compiler.
- No
dell-laptop

Relax MaxKshell range in mixed precision.

---

src/QMCDrivers/QMCDriverFactory.cpp
tests/solids/diamondC_1x1x1_pp/CMakeLists.txt
tests/solids/diamondC_2x1x1-Gaussian_pp_MSD/det_qmc_vmcbatch_dmcbatch_mwalkers.in.xml

Stop execution with clear message.
Mark tests expected to fail.
- Bugfix
- No
epyc-server

Protect batched driver in legacy CUDA

---

docs/installation.rst

Version update for macports instructions
- No
mac laptop

Update macports versions

---

doxygen/qmcpack.cfg

Update the out-dated include list.
- No
ryzen-box

Adjust doxygen included list of folders.

---

src/QMCWaveFunctions/BsplineFactory/SplineOMPTargetMultiWalkerMem.h
src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp

GCC asks for user defined reduction to be available. Clang is more forgiven.
- Bugfix
- No
epyc-server

Add user defined reduction inclusion

---

src/QMCDrivers/RMC/RMCUpdatePbyP.cpp
src/QMCDrivers/WalkerControlBase.cpp
src/QMCHamiltonians/EnergyDensityEstimator.cpp
src/QMCTools/WriteEshdf.cpp
src/QMCWaveFunctions/EinsplineSetBuilderESHDF.fft.cpp
src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp

Reduce Clang warning.
- No
epyc-server

Fix variable 'XXX' set but not used warning

---

src/Particle/DistanceTable.h
src/Particle/SoaDistanceTableAAOMPTarget.h
src/Utilities/ProjectData.h

Minor change.
- No
epyc-server

Refine DistanceTable::mw_move and remove a warning

---

docs/installation.rst

Update QE pw2qmcpack install guide with latest methods.
- No
epyc

Update QE pw2qmcpack install guide

---

README.md

Fix non-updating spack version in README.md
- Bugfix
- No
GitHub

Update spack version shield

---

.github/workflows/ci-github-action-auto-rebase.yaml
external_codes/github_actions/auto_rebase.sh
external_codes/github_actions/trigger-rebase-on-push.sh
tests/test_automation/github-actions/ci/run_step.sh

In reference to issue: https://github.com/QMCPACK/qmcpack/issues/3862
This pr contains configuration for a job to automatically rebase a PR granted the PR body contains the phrase:
!-> Feel free to automatically rebase this PR. <-!
Original WIP PR: #3878
- Other (please describe): Github Actions Pipeline Changes
- No
remote github runners
- No. Documentation has been …

Add Automatic Rebase Github Action Job

---

src/Estimators/InputSection.cpp
src/Estimators/InputSection.h

As a prelude to some more work with this I've tidied up the naming.
clang-tidy seems to think it is ok now.
- No
leconte
- Yes  Code added or changed in the PR has been clang-formatted

Tidying the naming in InputSection

---

src/QMCTools/ppconvert/src/common/Blitz.h

Explicit cast to float. (Was breaking builds with some clang-tidy modernize fixes)
- Bugfix
- No
mac

Add explicit cast in Blitz

---

src/Estimators/EstimatorManagerInput.cpp
src/Estimators/EstimatorManagerInput.h
src/Estimators/EstimatorManagerNew.cpp
src/Estimators/EstimatorManagerNew.h
src/Estimators/tests/test_EstimatorManagerInput.cpp

Seems not worth adding another layer of calls.
- No
epyc-server

Reduce use of variadic templates

---

src/Containers/OhmmsPETE/OhmmsArray.h
src/Containers/OhmmsPETE/tests/test_Array.cpp
src/Estimators/TraceManager.h
src/QMCWaveFunctions/Fermion/BackflowTransformation.cpp
src/QMCWaveFunctions/HarmonicOscillator/SHOSet.cpp

To prepare for the actual use.
- New feature
- No
epyc-server

Expand OhmmsArray APIs.

---

src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp
src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.h
src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp
src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.h
src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp

To achieve optimal performance, these routines needs to be specialized. Continue #3830.
Stage this change from my back pocket to test the latest CI update.
- New feature
- No
epyc-server

Add mock-up mw_accept_rejectMove in MSD.

---

tests/molecules/LiH_ae_MSD/CMakeLists.txt
tests/molecules/LiH_ae_MSD/det_ensemble_blocks_vmc_msdj.txt
tests/molecules/LiH_ae_MSD/det_ensemble_blocks_vmc_msdj_0.xml
tests/molecules/LiH_ae_MSD/det_ensemble_blocks_vmc_msdj_1.xml
tests/molecules/LiH_ae_MSD/det_ensemble_blocks_vmc_msdj_2.xml
tests/molecules/LiH_ae_MSD/det_ensemble_blocks_vmc_msdj_3.xml

Same as #4091 except for Gaussian molecule case.
- No
Sulfur. gcc mpi new config.

Add minimal ensemble test for LCAO MSD

---

src/Message/catch_main.cpp

Add memory printing in unit test main to help monitor memory usage at start.
To keep unit test outputManager behaving the same way as in qmcpack, turn off outputManager on rank>0 to stop repeated printout when running unit test with multiple MPI ranks.
- Bugfix
- New feature
- No
bora

Add memory printing in unit test main

---

src/QMCWaveFunctions/RotatedSPOs.h
src/QMCWaveFunctions/tests/gen_matrix_ops.py
src/QMCWaveFunctions/tests/test_RotatedSPOs.cpp

Use a python script with Sympy to compute the matrix exponential to generate the values for comparison.
- No
desktop

Test matrix exponential for creating a rotation matrix

---

tests/molecules/He_param/CMakeLists.txt
tests/molecules/He_param/He_orb_rot_param_grad_batch.xml

Add batch driver versions of single thread and multi-thread tests for parameter gradient for He with orbital rotation.
Also update the test names with "short-" prefix.
- No
desktop

Add batch driver tests for He orbital rotation parameter gradient

---

nexus/sphinx_docs/user-scripts.rst

Adding documentation for limiting the number of submitted jobs to a queue in Nexus
- No

Adding documentation for limiting the number of submitted jobs to a queue in Nexus

---

src/Message/Communicate.cpp
src/Platforms/CPU/BlasThreadingEnv.cpp

Review after #4149
Remove unused function calls and include lines
- No
epyc-server

Remove unused function calls and include lines

---

src/QMCHamiltonians/NonLocalECPotential.deriv.cpp
src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.cpp
src/QMCWaveFunctions/Fermion/MultiSlaterDetTableMethod.h
src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp
tests/molecules/C2_pp/C2-H5.wfj.xml
tests/molecules/C2_pp/CMakeLists.txt
tests/molecules/C2_pp/opt_det_pp_msdj-H5-param-grad.xml

Minimize code duplication and implement evaluateDerivRatios
- New feature
- No
epyc-server

Refactoring MSD and implement NLPP parameter derivatives in evaluateDerivRatios

---

src/QMCDrivers/WFOpt/CostFunctionCrowdData.cpp
src/QMCHamiltonians/QMCHamiltonian.cpp
src/QMCHamiltonians/QMCHamiltonian.h
src/QMCWaveFunctions/TrialWaveFunction.cpp

Get the parameter derivative routines reported in timer.
- New feature
- No
Theta

Fix timer for derivatives

---

src/Utilities/ProjectData.cpp
src/Utilities/ProjectData.h
src/Utilities/tests/test_project_data.cpp

Add isComplex public function and private member variable
Move inline functions to a single translation unit
Add test
Related to #4099 
- New feature
- No
Ubuntu 22.04, must pass CI

Add isComplex and refactor ProjectData getters

---

src/QMCWaveFunctions/BsplineFactory/SplineR2R.h
src/QMCWaveFunctions/LCAO/LCAOrbitalSet.h
src/QMCWaveFunctions/SPOSet.cpp
src/QMCWaveFunctions/SPOSet.h
src/QMCWaveFunctions/SPOSetBuilder.cpp

Better safeguards targeting internal logic consistency.
- New feature
- No
epyc

Add isRotationSupported() and refine SPOSet.cpp error messages

---

src/AFQMC/Estimators/BackPropagatedEstimator.hpp
src/AFQMC/Estimators/FullObsHandler.hpp
src/AFQMC/Estimators/Observables/full1rdm.hpp
src/AFQMC/Estimators/Observables/realspace_correlators.hpp
src/AFQMC/Matrix/tests/matrix_helpers.h
src/AFQMC/Numerics/ma_blas.hpp
src/AFQMC/Numerics/ma_blas_extensions.hpp
src/AFQMC/Propagators/AFQMCBasePropagator.icc
src/AFQMC/Propagators/AFQMCDistributedPropagatorDistCV.icc
src/AFQMC/SlaterDeterminantOperations/mixed_density_matrix.hpp
src/AFQMC/Walkers/WalkerIO.hpp
src/AFQMC/Walkers/WalkerSetBase.h
src/AFQMC/Walkers/WalkerSetBase.icc
src/AFQMC/Wavefunctions/NOMSD.hpp
src/AFQMC/Wavefunctions/PHMSD.hpp
src/AFQMC/Wavefunctions/PHMSD.icc
src/io/hdf/hdf_multi.h

Update multi deprecated2

---

src/AFQMC/Matrix/tests/matrix_helpers.h

AFQMC test has a missing header file.
This missing header is exposed by a refactoring of Multi.
- No

[AFQMC] add missing header to test

---

src/AFQMC/SlaterDeterminantOperations/SlaterDetOperations_base.hpp

Update multi deprecated size

---

src/AFQMC/HamiltonianOperations/Real3IndexFactorization.hpp
src/AFQMC/Propagators/AFQMCBasePropagator.icc
src/AFQMC/Wavefunctions/NOMSD.icc

remove last deprecated size functions

---

src/AFQMC/HamiltonianOperations/KP3IndexFactorization.hpp
src/AFQMC/HamiltonianOperations/KP3IndexFactorization_batched.hpp
src/AFQMC/HamiltonianOperations/THCOps.hpp
src/AFQMC/Hamiltonians/KPFactorizedHamiltonian.cpp

remove more size functions

---

CMakeLists.txt

Set development version
- No
None

Set development version 3.15.9

---

src/AFQMC/HamiltonianOperations/KP3IndexFactorization.hpp
src/AFQMC/SlaterDeterminantOperations/rotate.hpp

remove last? size functions

---

tests/test_automation/github-actions/ci/run_step.sh

Workaround current failures with 5.3
- Bugfix
- No
None

ROCm fix in CI

---

src/Estimators/EstimatorManagerBase.cpp
src/Estimators/EstimatorManagerBase.h
src/QMCDrivers/SimpleFixedNodeBranch.cpp

Cleanup unused TinyVector and string members
Move public to private members
Related to #3411
- No
Ubuntu 22.04

Refactor EstimatorManagerBase public members

---

docs/methods.rst

Code was not rendered properly.
- No
test by CI

Fix doc render issue

---

.github/workflows/ci-github-actions.yaml

Update codecov action to v3 to upload coverage report
- No
Must pass CI

Update codecov action to v3

---

CHANGELOG.md

Ensure this is not forgotten. CI uses 11.2 for offload builds to avoid this issue.
- No
NA

List CUDA toolkit issue as known problem

---

src/AFQMC/Estimators/tests/test_estimators.cpp
src/AFQMC/HamiltonianOperations/tests/test_hamiltonian_operations.cpp
src/AFQMC/Hamiltonians/tests/test_hamiltonian_factory.cpp
src/AFQMC/Propagators/tests/test_propagator_factory.cpp
src/AFQMC/Wavefunctions/tests/test_phmsd.cpp
src/AFQMC/Wavefunctions/tests/test_wfn_factory.cpp

Changing multi-line strings in src/AFQMC/* to C++11 raw string literals. 
This fixes #3675. Think I found most by searching for `const char*" and don't see value in trying to track down more by hand. 
- No
laptop, Ubuntu 20.04
_Update …

Switch to raw string literals - AFQMC

---

CMake/TestCxx17Library.cmake
src/Particle/ParticleSetPool.cpp

More accurate and verbose message.
- No
epyc-server

Refine code error message

---

src/QMCHamiltonians/tests/test_ewald2d.cpp

Fix narrowing conversion warning #4309 
- No
Ubuntu 22.04, i7 processor, GCC 11.

fix narrowing conversion

---

src/AFQMC/Propagators/tests/test_propagator_factory.cpp

PR #4305 changed XML strings to raw string literals. In the change `restart_file` was included in one of the strings.
This fixes #4317.
- Bugfix
- No …

Fix failing propagator_factory tests

---

CMake/TestCxx17Library.cmake

I stupidly rediscovered this recipe. Add a reminder.
- No
epyc-server

Reminder of adding gcc-toolchain to both cmake flags.

---

tests/test_automation/github-actions/ci/run_step.sh

From 3.20 to v3.21.3 on sulfur and nitrogen
Related to #4335 
- No
sulfur, nitrogen 

Bump ornl CI CMake version

---

src/QMCHamiltonians/DensityEstimator.cpp
src/QMCHamiltonians/DensityEstimator.h

Rename private members
Refactor functions from h to cpp
Remove unused code
Related to General Refactoring #3411
- No
Ubuntu 22.

Cleanup DensityEstimator class

---

src/Particle/HDFWalkerOutput.cpp
src/Particle/HDFWalkerOutput.h

I think `RemoteData` works better storing objects instead of pointers.
- No
simply a reminder of what we are …

Use value semantics with RemoteData

---

src/QMCHamiltonians/ChiesaCorrection.cpp
src/QMCHamiltonians/ChiesaCorrection.h

Rename private members
Refactor functions from h to cpp
Related to General Refactoring #3411
- No
Ubuntu 22.04

Cleanup ChiesaCorrection class

---

nexus/lib/qmcpack_input.py

This PR adds support for the `gpusharing` keyword that is an option for the legacy CUDA code.
- New feature
- No
Workstation

Nexus: add support for gpusharing keyword for legacy CUDA

---

src/QMCHamiltonians/ECPotentialBuilder.cpp

Fixes #4410.   Get the comparison with the `disable_randomize_grid` flag correct.
- Bugfix
- No
desktop

Fix grid randomization message

---

src/QMCApp/QMCMain.cpp

Make it explicit
- New feature
- No
laptop

Reflect QMC_COMPLEX in output.

---

src/QMCHamiltonians/BareKineticEnergy.cpp
src/QMCHamiltonians/BareKineticEnergy.h

Renamed and made private all data members
Refactored functions from h to cpp
Removed unused code
Related to General Refactoring #3411
- No
Ubuntu 22.04

Cleanup BareKineticEnergyClass

---

CMakeLists.txt

Set development version 3.16.9 per release process https://github.com/QMCPACK/qmcpack/wiki/Release-process

Set development version 3.16.9

---

src/QMCWaveFunctions/BsplineFactory/ApplyPhaseC2C.hpp
src/QMCWaveFunctions/BsplineFactory/ApplyPhaseC2R.hpp
src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp
src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp
src/QMCWaveFunctions/BsplineFactory/contraction_helper.hpp
src/spline2/MultiBsplineVGLH_OMPoffload.hpp
src/spline2/MultiBsplineValue_OMPoffload.hpp

Preparation for more re-use of routines.
- No
epyc-server

Refactor low level routines used by Spline SPO offload

---

src/QMCWaveFunctions/BsplineFactory/HybridRepCplx.h
src/QMCWaveFunctions/BsplineFactory/HybridRepReal.h
src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h
src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h
src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp
src/QMCWaveFunctions/BsplineFactory/createComplexSingle.cpp
src/QMCWaveFunctions/tests/test_hybridrep.cpp
tests/solids/diamondC_2x1x1_pp/CMakeLists.txt
tests/solids/diamondC_2x1x1_pp/qmc_short_hybridrep.in.xml

Intended to connect code paths and adjust test. Actual optimized implementation comes after.
- No
epyc-server

Hybridrep mock-up implementation for batched/offload

---

src/QMCHamiltonians/GridExternalPotential.cpp
src/QMCHamiltonians/GridExternalPotential.h

Renamed and made private all data members
Refactored functions from h to cpp
- No
Ubuntu 22.04

Cleanup GridExternalPotential class

---

src/QMCHamiltonians/ForceBase.cpp
src/QMCHamiltonians/ForceBase.h
src/QMCHamiltonians/ForwardWalking.cpp
src/QMCHamiltonians/ForwardWalking.h

Renamed and made private all data members
Refactored functions from h to cpp
Removed unused code
Related to #3411, #4424
- No
Ubuntu 22.04

Cleanup ForwardWalking class

---

src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp
src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp
src/QMCWaveFunctions/tests/test_MO.cpp
src/QMCWaveFunctions/tests/test_einset.cpp
src/QMCWaveFunctions/tests/test_einset_NiO_a16.cpp
src/io/hdf/hdf_wrapper_functions.h

Spo unit tests add resource

---

src/QMCDrivers/VMC/VMC.cpp
src/QMCDrivers/VMC/VMC.h
src/QMCDrivers/VMC/VMCBatched.h

Less legacy. Also remove commented out code that claims to be wrong.
- No
None

Remove unused VMC variables

---

src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp
src/QMCWaveFunctions/BsplineFactory/createComplexSingle.cpp
src/QMCWaveFunctions/tests/test_hybridrep.cpp

I missed some basic change in #4457. Upstream small changes to reduce the size of later PRs.
- New feature
- No
epyc-server

SplineSPO C2R Hybrid rep code path corrected

---

src/Particle/MCWalkerConfiguration.cpp
src/Particle/WalkerConfigurations.cpp
src/QMCDrivers/DMC/WalkerControlMPI.cpp
src/QMCDrivers/DMC/WalkerReconfiguration.cpp
src/QMCDrivers/QMCUpdateBase.cpp
src/QMCDrivers/WalkerControlBase.cpp

Moving some code cleanup out of #4157. Nothing here should change behavior. 
- No
- Yes. …

Cleanup code using walker->Weight

---

src/Particle/HDFWalkerOutput.cpp
src/Particle/MCWalkerConfiguration.cpp
src/Particle/WalkerConfigurations.cpp
src/Particle/WalkerConfigurations.h
src/QMCDrivers/DMC/WalkerControlMPI.cpp
src/QMCDrivers/MCPopulation.cpp
src/QMCDrivers/QMCDriver.cpp
src/QMCDrivers/QMCDriverNew.cpp
src/QMCDrivers/SimpleFixedNodeBranch.cpp
src/QMCDrivers/WalkerControlBase.cpp
src/QMCDrivers/tests/CMakeLists.txt
src/QMCDrivers/tests/test_dmc.cpp
src/QMCDrivers/tests/test_dmc_driver.cpp
src/QMCDrivers/tests/test_vmc.cpp
src/QMCDrivers/tests/test_vmc_driver.cpp
src/QMCDrivers/tests/test_walker_control.cpp
src/Sandbox/restart.cpp

1) make WalkerLists protected.
2) remove setGlobalNumWalkers because it can be derived from offset.
- No
laptop

Housekeeping around walker count handling

---

.github/workflows/ci-github-actions.yaml
config/docker/dependencies/centos-stream/Dockerfile
tests/test_automation/github-actions/ci/run_step.sh

Adds jobs to Github Actions to run ~~GCC9~~ GCC11 No MPI tests on a spack built Centos-Stream docker image.
- No
Ubuntu 20.04

 add docker tests for spack build centos image

---

docs/analyzing.rst
docs/lab_excited.rst
docs/methods.rst
docs/output_overview.rst
docs/spin_orbit.rst

Investigating readthedocs issue #4502
- Bugfix
- No
sphinx run by hand on laptop

Fix documentation

---

docs/methods.rst
src/Estimators/SizeLimitedDataQueue.hpp
src/Estimators/tests/CMakeLists.txt
src/Estimators/tests/test_SizeLimitedDataQueue.cpp
src/QMCDrivers/CMakeLists.txt
src/QMCDrivers/DMC/DMCBatched.cpp
src/QMCDrivers/DMC/DMCDriverInput.cpp
src/QMCDrivers/DMC/DMCDriverInput.h
src/QMCDrivers/DMC/DMCRefEnergy.cpp
src/QMCDrivers/DMC/DMCRefEnergy.h
src/QMCDrivers/DMC/DMCRefEnergyScheme.h
src/QMCDrivers/SFNBranch.cpp
src/QMCDrivers/SFNBranch.h
src/QMCDrivers/tests/test_SFNBranch.cpp

Implement Eref update scheme with history limited. Default remains as the 'legacy' scheme.
Will post figures.
- New feature
- No
polaris

Restrict Eref update history

---

config/build_alcf_theta.sh

Update ALCF Theta recipe to build with gcc (default 9.3.0)
- Other (please describe): build recipe update.
- No
Theta

Update ALCF Theta recipe to build with gcc.

---

src/QMCTools/QMCFiniteSize/QMCFiniteSize.cpp
src/QMCTools/QMCFiniteSize/QMCFiniteSize.h
src/QMCTools/QMCFiniteSize/SkParserASCII.cpp
src/QMCTools/QMCFiniteSize/SkParserASCII.h
src/QMCTools/QMCFiniteSize/SkParserBase.cpp
src/QMCTools/QMCFiniteSize/SkParserBase.h
src/QMCTools/QMCFiniteSize/SkParserHDF5.cpp
src/QMCTools/QMCFiniteSize/SkParserHDF5.h
src/QMCTools/QMCFiniteSize/SkParserScalarDat.cpp
src/QMCTools/QMCFiniteSize/SkParserScalarDat.h

Remove `using namespace std;`  and fix build.
This fixes #4513.
- No
simply a reminder of what we are going to …

Remove using namespace std from header file

---

docs/running_docker.rst

Adds docker image to docs for reference when trying to reproduce CI issues.
- No
n/a

add centos to listed docker files in docs

---

src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp
src/QMCWaveFunctions/LCAO/LCAOrbitalSet.h
src/QMCWaveFunctions/tests/test_MO.cpp
src/QMCWaveFunctions/tests/test_MO_spinor.cpp

Address a few FIXME in LCAO tests by making shared resource ready.
Also added two timers measuring basis and MO timing.
- New feature
- No
epyc-server

Add shared resource in LCAO

---

.github/workflows/ci-github-actions-self-hosted.yaml
tests/test_automation/github-actions/ci/run_step.sh
tests/test_automation/github-actions/ci/run_step_ornl-sulfur-1.sh
tests/test_automation/github-actions/ci/run_step_ornl-sulfur-2.sh

Current sulfur CI is down after major OS upgrade
Refactor sulfur CI sulfur-1 and sulfur-2 CI jobs
Moves from Intel classic compiler `icc` to oneAPI `icx`
Related to #4536
WIP, needs:
- No
sulfur, WIP

Update sulfur CI scripts

---

src/QMCHamiltonians/tests/test_ecp.cpp

Hopefully it makes CI happy.
- No
epyc-server

Relax test_ecp tolerance.

---

src/Estimators/tests/test_MagnetizationDensity.cpp
src/Particle/tests/test_particle.cpp
src/QMCDrivers/tests/test_dmc.cpp
src/QMCDrivers/tests/test_dmc_driver.cpp
src/QMCDrivers/tests/test_vmc.cpp
src/QMCHamiltonians/tests/test_RotatedSPOs_NLPP.cpp
src/QMCHamiltonians/tests/test_bare_kinetic.cpp
src/QMCHamiltonians/tests/test_coulomb_pbcAA.cpp
src/QMCHamiltonians/tests/test_coulomb_pbcAA_ewald.cpp
src/QMCHamiltonians/tests/test_coulomb_pbcAB.cpp
src/QMCHamiltonians/tests/test_coulomb_pbcAB_ewald.cpp
src/QMCHamiltonians/tests/test_ecp.cpp
src/QMCHamiltonians/tests/test_force.cpp
src/QMCHamiltonians/tests/test_force_ewald.cpp
src/QMCHamiltonians/tests/test_stress.cpp

Use a brace initializer to put 3 coordinates on one line.
Apply the changes in #4559 to the rest of the test directories.
- No
desktop

Make the position specs in tests more compact, part 2

---

config/build_alcf_sunspot_icpx.sh
src/Containers/OhmmsPETE/OhmmsMatrix.h
src/Platforms/SYCL/SYCLruntime.cpp
src/Platforms/SYCL/SYCLruntime.hpp

1. Update Sunspot recipe
2. Workaround compiler bug in [src/Containers/OhmmsPETE/OhmmsMatrix.h](https://github.com/QMCPACK/qmcpack/compare/develop...ye-luo:icpx-misc?expand=1#diff-7beb2ce8ea015008f80702fe8d7b17f9153a6390cc359c32e055541034603637) from @jngkim affecting unit tests.
3. use DefaultDeviceDefaultQueue reference instead of copy
- Bugfix
- No
sunspot

Icpx misc code and recipe update

---

src/AFQMC/AFQMCFactory.cpp
src/Estimators/CSEnergyEstimator.cpp
src/Estimators/EstimatorManagerNew.cpp
src/Estimators/TraceManager.h
src/QMCDrivers/DMC/WalkerControl.cpp
src/QMCDrivers/DMC/WalkerControlMPI.cpp
src/QMCDrivers/WFOpt/QMCCostFunctionBase.cpp
src/QMCDrivers/WFOpt/QMCCostFunctionBase.h
src/QMCDrivers/WaveFunctionTester.cpp
src/QMCHamiltonians/ECPComponentBuilder.cpp
src/QMCWaveFunctions/BsplineFactory/BsplineReaderBase.cpp
src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp
src/io/OhmmsData/Libxml2Doc.cpp

Replace the unsafe function `sprintf` with `snprintf` or streams.
This is part of https://github.com/QMCPACK/qmcpack/issues/4438.
- No
my laptop, Ubuntu 20.04
_Update the following with a yes where the items apply. If you're unsure about …

switch from sprintf to std::snprintf

---

src/QMCDrivers/WFOpt/QMCCostFunctionBase.cpp
src/QMCWaveFunctions/VariableSet.h

Replace the unsafe function sprintf with snprintf or streams.
This is part of https://github.com/QMCPACK/qmcpack/issues/4438.
- No
_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate …

Use std::snprintf in QMCCostFunctionBase.

---

src/Message/Communicate.h
src/Message/tests/test_communciate.cpp
src/QMCHamiltonians/OrbitalImages.cpp
src/QMCTools/LCAOHDFParser.cpp
src/QMCTools/QMCGaussianParserBase.cpp
src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h
src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp
src/QMCWaveFunctions/Jastrow/kSpaceJastrowBuilder.cpp
src/QMCWaveFunctions/LCAO/LCAOSpinorBuilder.cpp
src/QMCWaveFunctions/LCAO/LCAOrbitalBuilder.cpp
src/Utilities/ProjectData.cpp

This removes remaining instances of sprintf.
This fixes https://github.com/QMCPACK/qmcpack/issues/4438.
- No
My laptop, Ubuntu 20.04
_Update the following with a yes where …

Remove remaining instances of sprintf outside of external_codes

---

src/Estimators/InputSection.cpp

Remove spammy debug output added to InputSection during develepment.
- Bugfix
- No
osx laptop

Removing debug output for InputSection

---

src/QMCDrivers/WFOpt/CostFunctionCrowdData.cpp
src/Utilities/RandomNumberControl.cpp

Pulling out a couple of micro-optimizations I found while working on #3700.
- Bugfix
- No
simply a reminder of what we are going to look for before merging …

RandomGenerator: Avoid extra construction and memory allocations

---

src/AFQMC/Drivers/DriverFactory.cpp
src/AFQMC/Estimators/tests/test_estimators.cpp
src/AFQMC/Propagators/AFQMCBasePropagator.h
src/AFQMC/Propagators/AFQMCBasePropagator.icc
src/AFQMC/Propagators/AFQMCDistributedPropagator.h
src/AFQMC/Propagators/AFQMCDistributedPropagator.icc
src/AFQMC/Propagators/AFQMCDistributedPropagatorDistCV.h
src/AFQMC/Propagators/PropagatorFactory.cpp
src/AFQMC/Propagators/PropagatorFactory.h
src/AFQMC/Propagators/tests/test_propagator_factory.cpp
src/AFQMC/Walkers/SerialWalkerSet.hpp
src/AFQMC/Walkers/SharedWalkerSet.hpp
src/AFQMC/Walkers/WalkerSetBase.h
src/AFQMC/Walkers/WalkerSetBase.icc
src/AFQMC/Walkers/WalkerSetFactory.hpp
src/AFQMC/Walkers/tests/test_sharedwset.cpp
src/AFQMC/Wavefunctions/tests/test_phmsd.cpp
src/AFQMC/Wavefunctions/tests/test_wfn_factory.cpp

Addresses @PDoakORNL's comment in [4650](https://github.com/QMCPACK/qmcpack/pull/4650#discussion_r1247207052) This is part of #3700.
- No
my laptop, Ubuntu 20.04
_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask. …

AFQMC: Use a reference instead of a pointer.

---

nexus/lib/pwscf_postprocessors.py

Add single keyword to Projwfc input.
- New feature
- No
Workstation

Nexus: add pdos flag for Projwfc

---

src/Estimators/EstimatorManagerNew.cpp

use int64_t when aggregating accept/reject counts.

---

src/Containers/OhmmsPETE/AntiSymTensor.h
src/Containers/OhmmsPETE/SymTensor.h
src/Containers/OhmmsSoA/VectorSoaContainer.h
src/QMCTools/ppconvert/src/common/Blitz.h
src/Utilities/ResourceHandle.h

A few too many consts / non-enough consts found using CodeCheck/Understand.
- Bugfix
- No
gcc12, mac laptop only.

Improve some assignment operators

---

tests/molecules/H_positron/CMakeLists.txt

Update references of positron deterministic test for batched driver since they have changed due to #4668.
- Other (please describe): Update test
- No
Workstation

Update references for positron deterministic test

---

src/Platforms/CPU/CMakeLists.txt
src/Platforms/CPU/math.cpp
src/Platforms/CPU/math.hpp
src/Platforms/tests/CPU/CMakeLists.txt
src/Platforms/tests/CPU/test_math.cpp
src/QMCTools/ppconvert/CMakeLists.txt

Introduce custom isnan to make it always work.
- New feature
- No
epyc-server

Introduce qmcplusplus::isnan

---

src/AFQMC/Estimators/EnergyEstimator.h
src/AFQMC/Wavefunctions/NOMSD.icc
src/Optimize/NRCOptimization.h
src/Platforms/CPU/math.cpp
src/QMCDrivers/GreenFunctionModifiers/DriftModifierUNR.cpp
src/QMCDrivers/Optimizers/DescentEngine.cpp
src/QMCDrivers/QMCUpdateBase.cpp
src/QMCDrivers/QMCUpdateBase.h
src/QMCDrivers/WFOpt/HamiltonianRef.cpp
src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp
src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp
src/QMCHamiltonians/QMCHamiltonian.cpp
src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h

Change std::isnan to qmcplusplus::isnan
Every use under ppconvert remains untouched due to zero code sharing.
- New feature
- No
sunspot

Change std::isnan to qmcplusplus::isnan

---

config/build_nersc_perlmutter_Clang.sh

Add perlmutter recipe for offload builds
- Other (please describe): build recipes
- No
Perlmutter

Add NERSC perlmutter recipe.

---

CMakeLists.txt

Set development version

---

CMakeLists.txt

Set development version 3.17.9

---

CHANGELOG.md

Mention backflow optimization removal in CHANGELOG

---

README.md
tests/test_automation/nightly_test_scripts/nightly_ornl.sh
tests/test_automation/nightly_test_scripts/ornl_setup.sh
tests/test_automation/nightly_test_scripts/ornl_setup_environments.sh
tests/test_automation/nightly_test_scripts/ornl_versions.sh

Update scripts and versions used in nightlies. These latest versions have been used for a couple of days and have no major build issues.
Update and improve project README
- No
sulfur, nitrogen in nightlies

Update nightly ORNL versions and README.md

---

README.md

Improve front page docs
- No
None. Docs only.

Add citation and tutorial section to README.md

---

.github/workflows/ci-github-action-auto-rebase.yaml
.github/workflows/ci-github-actions-self-hosted.yaml
.github/workflows/ci-github-actions-static.yaml
.github/workflows/ci-github-actions.yaml

Just update to the recent action checkout v4.
Some YAML recent VS Code automatic formatting.
- No
N/A

Update CI checkout action to v4

---

config/build_alcf_polaris_Clang.sh
config/build_alcf_theta.sh

Update recipes on ALCF machines.
- No
Polaris and Theta

Update Polaris and Theta build recipes.

---

src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp

Reduce compiler warning.
- Other (please describe): code cleaning
- No
epyc-server

Remove unused codes.

---

src/QMCWaveFunctions/BasisSetBase.h
src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp
src/QMCWaveFunctions/LCAO/LCAOrbitalSet.h
src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.cpp
src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.h

Batched Specialization of VirtualParticle function for the MO evaluation
Implementation of specialized functions for virtual particle in the MO evaluation. 
- Yes
-LAptop
- No. This PR adds tests to cover any new code, or to catch a bug …

Specialization of functions using VirtualParticle for the MO 

---

src/QMCWaveFunctions/BsplineFactory/HybridRepCenterOrbitals.h
src/QMCWaveFunctions/BsplineFactory/HybridRepCplx.h
src/QMCWaveFunctions/BsplineFactory/HybridRepReal.h
src/QMCWaveFunctions/tests/test_MO.cpp
src/QMCWaveFunctions/tests/test_hybridrep.cpp

How bad my old code was ;)
1. move data exchanged between routines into a struct.
2. It used to rely on smooth function values to label regions and now changed to enum. 
- No
laptop

Refactor HybridRepCenterOrbitals

---

src/QMCWaveFunctions/tests/test_hybridrep.cpp

Prefer more compact code.
Also fix https://cdash.qmcpack.org/CDash/testDetails.php?test=28063318&build=440018 failure
- No
epyc-server

Write compact check in hybridrep tests

---

config/build_olcf_summit_Clang.sh

Updated build recipe. Deployed QMCPACK 3.17.1 at `/gpfs/alpine/mat151/world-shared/opt/qmcpack/release-3.17.1/`
- No
Summit

Update OLCF Summit build recipe. Switch to llvm17.

---

docs/intro_wavefunction.rst

Add additional orbital rotation documentation describing the 'history' and 'global' rotation composition methods.
- No
laptop

Add docs on composing rotations

---

src/QMCHamiltonians/QMCHamiltonian.cpp
src/QMCHamiltonians/QMCHamiltonian.h
src/QMCHamiltonians/tests/test_QMCHamiltonian.cpp

Rename `updateNonKinetic` to `updateComponent` and adjust `updateKinetic`. Maximize code reuse.
- No
epyc-server

Consolidate QMCHamiltonian code paths.

---

CMake/FindMKL.cmake

Adjust detection due to mkl file structure change.
- No
Sunspot

Fix mkl_sycl detection for oneapi 2024

---

src/QMCWaveFunctions/BasisSetBase.h
src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp
src/QMCWaveFunctions/LCAO/LCAOrbitalSet.h
src/QMCWaveFunctions/LCAO/SoaAtomicBasisSet.h
src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.cpp
src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.h

Add MW resources to SoaAtomicBasisSet (through SoaLocalizedBasisSet/SoaBasisSetBase)
Prerequisite for offloading AO evaluation
- New feature
- No

SoaAtomicBasisSet resource collection

---

tests/solids/bccH_1x1x1_ae/qmc_short_pw.in.xml
tests/solids/diamondC_2x1x1_pp/det_qmc_vmc_dmc_pw.in.xml

This PR is to update input style for planewave orbitals as it becomes available since #4750.
- No
Workstation

Update input style of testset for planewave orbitals

---

CMake/DetermineDeviceArchitectures.cmake

Use CMAKE_CUDA/HIP_ARCHITECTURES as hints and get them overwritten once QMC_GPU_ARCHS is settled.
- No
JLSE

Respect QMC_GPU_ARCHS as the single source of truth

---

src/QMCWaveFunctions/CMakeLists.txt
src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp
src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp
src/QMCWaveFunctions/NaNguard.cpp
src/QMCWaveFunctions/NaNguard.h
src/QMCWaveFunctions/TrialWaveFunction.cpp
src/QMCWaveFunctions/TrialWaveFunction.h
src/QMCWaveFunctions/tests/CMakeLists.txt
src/QMCWaveFunctions/tests/test_NaNguard.cpp

Add more NaN check.
- New feature
- No
epyc-server

Introduce NaNguard for TWF checking both ratio and gradients

---

src/Numerics/SoaSphericalTensor.cpp
src/Numerics/SoaSphericalTensor.h

Fixes https://github.com/QMCPACK/qmcpack/issues/4810
- No
epyc-server

Fix Clang warning.

---

src/QMCWaveFunctions/tests/gen_matrix_ops.py

Put individual test cases in separate functions.
This should make adding new cases easier (for example, new cases in #4816)
- No
laptop

Improve organization of test cases in gen_matrix_ops.py

---

src/Message/CommOperatorsMPI.h

Prepare for #4821
- New feature
- No
epyc-server

Use throw and add a specialization in Communicate

---

src/Message/CommOperatorsMPI.h
src/Platforms/Host/sysutil.cpp

Remove some old workarounds from the jaguar(?) era
- No
None
- NA . Code added or changed in the PR has been clang-formatted

Remove legacy Cray MPI barriers

---

src/Numerics/SplineBound.hpp
src/Numerics/tests/CMakeLists.txt
src/Numerics/tests/test_SplineBound.cpp
src/spline2/MultiBspline1D.hpp
src/spline2/MultiBsplineEval_helper.hpp
src/spline2/MultiBsplineVGHGH.hpp
src/spline2/MultiBsplineVGLH_OMPoffload.hpp
src/spline2/MultiBsplineValue_OMPoffload.hpp
src/spline2/tests/test_multi_spline.cpp

Intend to use this function in other spline classes.
- No
epyc-server

Move splinebound calculation to Numerics.

---

.github/workflows/ci-github-actions-self-hosted.yaml
tests/test_automation/github-actions/ci/run_step_ornl-sulfur-2.sh

- Bugfix
- New feature
- Yes
- No
_Update the following with a yes where the items apply. If …

Fix CI offload build failure and add checks upon CMake return failure

---

src/QMCApp/QMCMain.cpp

Add the JCP (2020) "advances" paper. Also put current year as copyright end date. Align text.
Closes #4836
- No
Local mac, gcc13

Add 2nd citation in output

---

src/QMCWaveFunctions/BsplineFactory/BsplineReader.cpp
src/QMCWaveFunctions/BsplineFactory/BsplineReader.h
src/QMCWaveFunctions/BsplineFactory/BsplineSet.h
src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilder.h
src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderCommon.cpp
src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilder_createSPOs.cpp
src/QMCWaveFunctions/BsplineFactory/EinsplineSpinorSetBuilder.cpp
src/QMCWaveFunctions/BsplineFactory/HybridRepCplx.h
src/QMCWaveFunctions/BsplineFactory/HybridRepReal.h
src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h
src/QMCWaveFunctions/BsplineFactory/SplineC2C.h
src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h
src/QMCWaveFunctions/BsplineFactory/SplineC2R.h
src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h
src/QMCWaveFunctions/BsplineFactory/SplineR2R.h
src/QMCWaveFunctions/BsplineFactory/SplineSetReader.h
src/QMCWaveFunctions/BsplineFactory/createBsplineReader.h
src/QMCWaveFunctions/BsplineFactory/createComplexDouble.cpp
src/QMCWaveFunctions/BsplineFactory/createComplexSingle.cpp
src/QMCWaveFunctions/BsplineFactory/createRealDouble.cpp
src/QMCWaveFunctions/BsplineFactory/createRealSingle.cpp
src/QMCWaveFunctions/CMakeLists.txt

Class renaming. Also document functions in HybridRepSetReader and SplineSetReader.
Making this PR for easy review.
- No
epyc-server

Rename BsplineReaderBase to BsplineReader

---

README.md

Update README.md with newer versions and examples

---

CMake/TestCXXMainCompiles.cmake
CMakeLists.txt

Add compiler tests before after compiler option customization and after adding OpenMP options.
Should make troubleshooting a lot easier.
- No
laptop

Add more compilation tests in CMake.

---

src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp
src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h

Fixes #4754
- Bugfix
- No
epyc-server

Fix SplineC2ROMPTarget

---

.github/workflows/ci-github-actions.yaml
tests/test_automation/github-actions/ci/run_step.sh

Expand CI to complex in offload to host builds.

---

src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderCommon.cpp
src/QMCWaveFunctions/BsplineFactory/EinsplineSetBuilderESHDF.fft.cpp
src/QMCWaveFunctions/BsplineFactory/OneSplineOrbData.cpp
src/QMCWaveFunctions/BsplineFactory/SplineC2C.cpp
src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp
src/QMCWaveFunctions/BsplineFactory/SplineR2R.cpp
src/QMCWaveFunctions/BsplineFactory/SplineSetReader.cpp
src/QMCWaveFunctions/BsplineFactory/createBsplineReal.cpp

Formatting only.
- Other (please describe): Formatting
- No
none

Clang format files under src/QMCWaveFunctions/BsplineFactory

---

docs/unit_testing.rst

Describe building objects from XML.
- No
desktop

Update unit testing documentation

---

src/QMCTools/ppconvert/src/CMakeLists.txt

Fix an issue exposed by https://github.com/QMCPACK/qmcpack/pull/4870
- No
epys-server

Restrict ppconvert dependency.

---

src/QMCHamiltonians/ECPotentialBuilder.cpp
src/QMCHamiltonians/ECPotentialBuilder.h
src/QMCHamiltonians/NonLocalECPotential.h
src/QMCHamiltonians/tests/test_NonLocalECPotential.cpp
src/QMCHamiltonians/tests/test_SOECPotential.cpp

More forward declaration.
- No
epyc-server

Reduce NonLocalECPComponent.h exposure in header files.

---

src/Estimators/tests/test_OneBodyDensityMatrices.cpp
src/Particle/tests/CMakeLists.txt
src/Particle/tests/MinimalParticlePool.h
src/Particle/tests/test_ParticleSet.cpp
src/Particle/tests/test_VirtualParticleSet.cpp

Add VirtualParticleSet unit tests

---

config/build_alcf_polaris_Clang.sh

Update recipe for Polaris OS/image upgrade.
- No
Polaris

Update ALCF Polaris recipe

---

docs/simulationcell.rst
src/Particle/ParticleIO/XMLParticleIO.cpp
src/Particle/ParticleIO/XMLParticleIO.h

Document attribute condition in particleset attrib.

---

src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp

More accurate message.
- Bugfix
- No
epyc-server

Correct error message.

---

src/Estimators/CMakeLists.txt
src/Estimators/InputSection.cpp
src/Estimators/InputSection.h
src/Estimators/NEReferencePoints.h
src/Estimators/NESpaceGrid.cpp
src/Estimators/NESpaceGrid.h
src/Estimators/SpaceGridInput.cpp
src/Estimators/SpaceGridInput.h
src/Estimators/tests/CMakeLists.txt
src/Estimators/tests/ValidSpaceGridInput.h
src/Estimators/tests/test_InputSection.cpp
src/Estimators/tests/test_NESpaceGrid.cpp
src/Estimators/tests/test_ReferencePoints.cpp
src/Estimators/tests/test_SpaceGridInput.cpp
src/Particle/tests/MinimalParticlePool.h
src/Utilities/for_testing/NativeInitializerPrint.hpp

NESpaceGrid class refactored/ported from QMCHamiltonian/SpaceGrid with new input scheme and a decent start at test coverage.  Last component needed before the ported EnergyDensityEstimator can be PR'd.
- New feature
- No
OSX, x86 v100
- Yes …

NESpaceGrid rebased and squashed.

---

nexus/lib/machines.py
nexus/tests/unit/test_machines.py

Noticed some openmp affinity problems recently when using openmpi. Updating our nexus machines accordingly
- Other (please describe): modify nexus machines for SNL
- No
SNL machines
- Yes. This PR adds tests to cover any new code, or to catch a bug …

nxs: SNL machine update

---

config/build_olcf_frontier_ROCm.sh

Also stop Cray Compiler Wrapper forcing RPATH. Use RUNPATH instead.
- No
Frontier

Update Frontier recipe to ROCm 6.0.0

---

docs/running.rst

Explain how to choose MPI ranks.

---

.github/pull_request_template.md
config/build_nersc_perlmutter_Clang.sh

Closes https://github.com/QMCPACK/qmcpack/issues/4937
- No
Perlmutter

Update Perlmutter recipe.

---

.github/workflows/ci-github-actions.yaml

Use the v4 action and pass the token to hopefully reduce upload failure rate. However, the token will not be available in forks which is our standard way of working.
Widespread problems are reported for v3 in https://github.com/codecov/codecov-action/issues/1359
- No
None. GitHub actions change

Update codecov action

---

src/Containers/OhmmsPETE/OhmmsArray.h
src/Containers/OhmmsPETE/OhmmsMatrix.h
src/Containers/OhmmsPETE/OhmmsVector.h
src/Containers/tests/test_dual_allocators_ohmms_containers.cpp
src/Platforms/DualAllocator.hpp
src/Platforms/OMPTarget/OMPallocator.hpp
src/Platforms/allocator_traits.hpp

To enable partial `updateTo(size, offset)` and `updateFrom(size, offset)`.
- New feature
- No
epyc-server

Adjust dualspace allocator implementation

---

src/Platforms/OMPTarget/ompBLAS.cpp

Very minor change and should not affect correctness.
The main intention is to confirm recent amdgpu driver update.
- Bugfix
- No
epyc

Set the number of teams as the loop bound.

---

src/Containers/OhmmsSoA/VectorSoaContainer.h
src/Platforms/CUDA/cuBLAS_missing_functions.cu
src/Platforms/CUDA/cuBLAS_missing_functions.hpp
src/QMCWaveFunctions/detail/CUDA/matrix_update_helper.cu
src/QMCWaveFunctions/detail/CUDA/matrix_update_helper.hpp

1. Introduce value_type and size_type in VectorSoaContainer to align with other containers.
2. Pass stream handles by value since they are pointers.
- No
epyc-server

Two sets of refactoring changes

---

src/Platforms/CUDA/CUDALinearAlgebraHandles.h
src/Platforms/CUDA/QueueCUDA.hpp
src/Platforms/PlatformKinds.hpp
src/Platforms/PlatformSelector.hpp
src/Platforms/Queue.hpp
src/Platforms/QueueAliases.hpp
src/QMCWaveFunctions/Fermion/DiracMatrixComputeCUDA.hpp
src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h
src/QMCWaveFunctions/tests/test_DiracMatrixComputeCUDA.cpp

~~Please review after merging #4973 and #4974~~
Add a new abstraction class Queue to unify code paths.
- New feature
- No
epyc-server

Add Queue<PlatformKind::CUDA>

---

tests/test_automation/nightly_test_scripts/nightly_ornl.sh
tests/test_automation/nightly_test_scripts/ornl_setup.sh
tests/test_automation/nightly_test_scripts/ornl_setup_environments.sh
tests/test_automation/nightly_test_scripts/ornl_versions.sh

Update/backup nightly scripts with current versions e.g. with use of LLVM 18.1.6.
- No
nitrogen, nitrogen2, sulfur for a few days.

Revise nightly test scripts and spack setup

---

src/Platforms/OMPTarget/QueueOMPTarget.hpp
src/Platforms/QueueAliases.hpp
src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h
src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h

Add `Queue<PlatformKind::OMPTARGET>`
- New feature
- No
epyc-server

Introduce Queue<PlatformKind::OMPTARGET>

---

src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp

Also added a few missing MO timer.
- Bugfix
- No
epyc-server

Change code path selection to at run time in LCAOrbitalSet

---

src/Platforms/AccelBLAS.hpp
src/Platforms/AccelBLASHandle.hpp
src/Platforms/CUDA/AccelBLAS_CUDA.hpp
src/Platforms/OMPTarget/AccelBLAS_OMPTarget.hpp
src/Platforms/tests/test_AccelBLAS.cpp
src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h
src/QMCWaveFunctions/LCAO/LCAOrbitalSet.cpp
src/QMCWaveFunctions/detail/AccelMatrixUpdate.hpp
src/QMCWaveFunctions/detail/CUDA/AccelMatrixUpdateCUDA.hpp
src/QMCWaveFunctions/detail/CUDA/matrix_update_helper.cu
src/QMCWaveFunctions/detail/CUDA/matrix_update_helper.hpp

Also simplify source matrix_update_helper.hpp using templates
- New feature
- No
epyc-server

Add AccelMatrixUpdate wrappers for functions under QMCWaveFunctions/details

---

src/Platforms/OMPTarget/ompBLAS.cpp
src/QMCWaveFunctions/detail/AccelMatrixUpdate.hpp
src/QMCWaveFunctions/detail/OMPTarget/AccelMatrixUpdateOMPTarget.hpp

Review after #5024
AccelMatrixUpdateOMPTarget matches AccelMatrixUpdateCUDA implementation.
- New feature
- No
eypc-server

Implement AccelMatrixUpdateOMPTarget wrapper

---

src/Platforms/OMPTarget/ompBLAS.cpp
src/Platforms/tests/OMPTarget/test_ompBLAS.cpp

Bug introduced in #5023.
When adding unit tests for beta!=0, I set alpha!=1 and hit the bug.
- Bugfix
- No
epyc-server

Fix ompBLAS gemm NT case.

---

config/build_alcf_aurora_icpx.sh
src/Platforms/QueueAliases.hpp
src/Platforms/SYCL/QueueSYCL.hpp
src/Platforms/SYCL/SYCLDeviceManager.cpp
src/Platforms/SYCL/SYCLDeviceManager.h
src/Platforms/SYCL/SYCLruntime.cpp
src/Platforms/SYCL/SYCLruntime.hpp
src/QMCWaveFunctions/Fermion/DelayedUpdateSYCL.h

Also update Aurora recipe
- New feature
- No
Aurora

Add QueueSYCL

---

src/QMCWaveFunctions/Fermion/DelayedUpdateBatched.h
src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp

Clean up DelayedUpdateBatched

---

src/Platforms/SYCL/AccelBLAS_SYCL.hpp
src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp

I don't know why deterministic integration tests didn't fail. I caught this when running actual simulations and then noticed missing unit tests. 
- Bugfix
- New feature
- No
sunspot

Add copy_batch for SYCL and enable unit tests

---

src/Platforms/SYCL/syclBLAS.cpp

The last bug hunted to make batched sing det working on Intel GPUs.
- Bugfix
- New feature
- No
sunspot

Add sycl ger_batch incx and incy support.

---

src/AFQMC/Estimators/EnergyEstimator.h
src/AFQMC/Propagators/WalkerSetUpdate.hpp
src/AFQMC/Propagators/WalkerUpdate.hpp
src/AFQMC/Walkers/WalkerUtilities.hpp
src/AFQMC/Wavefunctions/NOMSD.icc
src/Platforms/CPU/math.cpp
src/Platforms/CPU/math.hpp
src/QMCDrivers/DMC/DMCBatched.cpp
src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h

Review after #5054
Add qmcplusplus::isfinite/isinf
- Bugfix
- No
epyc-server

Add qmcplusplus::isfinite/isinf

---

config/build_olcf_summit_Clang.sh

Update Summit build recipe

---

src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp
src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
src/QMCWaveFunctions/Fermion/SlaterDetBuilder.h

More size checks.
- Bugfix
- No
epyc-server

Check SPOSet size against SD/MSD needs

---

src/Particle/VirtualParticleSet.h
src/Utilities/ResourceHandle.h
src/type_traits/OptionalRef.hpp

I have more use cases and would like to introduce this custom type to avoid lengthy codes.
- New feature
- No
laptop

Introduce OptionalRef.hpp

---

CMake/ctest_script.cmake

Fix for new cdash installation
- No
Successful upload on cdash.qmcpack.org

Update ctest_script.cmake cdash submit location

---

nexus/lib/machines.py
nexus/tests/unit/test_machines.py

Support running Nexus on NREL's Kestrel machine
- Other (please describe): machine suppot
- No
Kestrel

Nexus: support for NREL Kestrel

---

src/QMCHamiltonians/NonLocalECPComponent.cpp
src/QMCHamiltonians/NonLocalECPComponent.h
src/QMCHamiltonians/tests/test_NonLocalECPotential.cpp

Consider this implementation preliminary. I didn't really test test this features with simulations nor added unit test.
- New feature
- No
laptop

Implement determinant locality approximation (DLA) with T-move (TM)

---

external_codes/catch/Readme
external_codes/catch/catch.hpp

Update to the latest and presumably last version of Catch2 v2. Has a couple of small updates including one that may help mac debugging.
Carried over our existing patches per the readme.
- New feature
- No
None.  Using CI to test no mistakes in patching.
- Yes/No. Documentation has been added (if …

Use Catch2 2.13.10

---

tests/test_automation/github-actions/ci/run_step_ornl-nitrogen-1.sh

Query GPU arch in AMDGPU CI

---

src/QMCHamiltonians/NonLocalECPotential.cpp

The bug affects DLA+TMv1.
Tested and got consistent results with DLA+TMv0/1/3.
- Bugfix
- No
bora

Fix DLA+TMv1

---

src/Sandbox/restart.cpp

Less copy using more reference.
- No
laptop

Rewrite internal RNG usage in Sandbox/restart.cpp

---

src/Platforms/tests/OMPTarget/test_class_member.cpp
src/Platforms/tests/OMPTarget/test_deep_copy.cpp

Closes https://github.com/QMCPACK/qmcpack/issues/5125
- Bugfix
- No
epyc-server

Protect omp.h inclusion.

---

config/build_olcf_frontier_ROCm.sh

Closes https://github.com/QMCPACK/qmcpack/issues/5131
- build script changes
- No
frontier

Update Frontier recipe.

---

tests/test_automation/nightly_test_scripts/nightly_ornl.sh
tests/test_automation/nightly_test_scripts/ornl_setup.sh
tests/test_automation/nightly_test_scripts/ornl_setup_environments.sh
tests/test_automation/nightly_test_scripts/ornl_versions.sh

Currently version of the nightly configurations including compiler versions etc.
- No
nitrogen2, nitrogen, sulfur

Update nightly test configurations

---

src/QMCWaveFunctions/VariableSet.cpp
tests/molecules/He_param/CMakeLists.txt

Fixes https://cdash.qmcpack.org/tests/2065241
- Bugfix
- No
laptop

Fix test He_param_grad_load-1-16

---

src/QMCDrivers/CMakeLists.txt
src/QMCDrivers/WFOpt/ConjugateGradient.cpp
src/QMCDrivers/WFOpt/ConjugateGradient.h
src/QMCDrivers/WFOpt/LinearMethod.cpp
src/QMCDrivers/WFOpt/LinearMethod.h
src/QMCDrivers/WFOpt/QMCCostFunctionBase.cpp
src/QMCDrivers/WFOpt/QMCCostFunctionBase.h
src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp
src/QMCDrivers/WFOpt/QMCCostFunctionBatched.h
src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp
src/QMCDrivers/tests/CMakeLists.txt
src/QMCDrivers/tests/test_ConjugateGradient.cpp

This PR refactors part of the new SR optimization introduced in #5017. This cleans up and simplifies the code inside QMCFixedSampleLinearOptimimzeBatched and hopefully makes a new CG interface that is easier to work with and add new features like preconditioning in the future. Also adds a much needed test to this new part of the code
- New feature
- No
macOS
simply a …

Refactor Conjugate Gradient part of SR optimization

---

docs/bibs/methods.bib
docs/methods.rst
src/QMCDrivers/WFOpt/ConjugateGradient.cpp
src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp
src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h

update to SR method. In my previous PR, I accidentally left out applying the regularization to the overlap matrix. This is added back in. Also added control of the CG algorithm via the input file. Some documentation is also added. 
- New feature
- No
mac
- Yes. Code added or …

Update regularization scheme in SR method and add docs

---

src/QMCDrivers/WFOpt/ConjugateGradient.cpp
src/QMCDrivers/WFOpt/ConjugateGradient.h
src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp

add a timer to the ConjugateGradient class
- New feature
- No
mac

add CG timer and remove print statement

---

src/AFQMC/Memory/CUDA/cuda_arch.cpp
src/AFQMC/Memory/CUDA/cuda_arch.h

Resolve an issue similarly to https://github.com/QMCPACK/qmcpack/pull/4814 in AFQMC.
- Bugfix
- No
epyc-server
- Yes. This PR is up to date with current the current state of 'develop']

Fix AFQMC in clang offload gcc toolchain 13 builds

---

src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp

1) remove unused wgt_tot2
2) more compact code
- No
laptop

Remove unused code and write code more compact

---

docs/methods.rst
src/QMCDrivers/Optimizers/OptimizerTypes.h
src/QMCDrivers/WFOpt/ConjugateGradient.cpp

This PR changes the regularization scheme back to just adding a constant to the diagonal of the overlap matrix. If S becomes ill-conditioned, the CG can be slower to converge. In #5156, I changed the regularization to what was supposed to be a scaling of the diagonal elements which was argued in a paper from Sorella to be a better regularization. Effectively, in matrix notation, this would be S-> S(I+diag(S)*eps). Unfortunately, I implemented S(I+eps * I) which scales all elements of S, not just the diagonal. That operation obviously does not reduce the condition number, and some simple test problems I was playing around …

Change regularization in SR

---

tests/molecules/H4_ae/CMakeLists.txt
tests/molecules/LiH_ae_pyscf/CMakeLists.txt
tests/molecules/LiH_pp/CMakeLists.txt
tests/solids/NiO_a4_e48_pp/CMakeLists.txt
tests/solids/bccH_1x1x1_ae/CMakeLists.txt
tests/solids/diamondC_2x1x1-Gaussian_pp_cplx/CMakeLists.txt

Address more of the ongoing short test statistical failures
See cdash for current failures
- No
None

Update more short test error bars

---

src/QMCHamiltonians/NonLocalTOperator.cpp
src/QMCHamiltonians/tests/test_NonLocalTOperator.cpp

closes #5175.
- Bugfix
- No
epyc-server

Properly handle prob=1.0f due to precision conversion

---

config/build_alcf_aurora_icpx.sh

Update Aurora build recipe.

---

src/QMCWaveFunctions/tests/test_einset_LiH.cpp

Fixes https://cdash.qmcpack.org/tests/5984282
- No
bora

Increase d2psiM test tolerance in LiH-x

---

src/QMCHamiltonians/NonLocalECPComponent.cpp

Fix a bug reported by Yasmine@UCL.
- Bugfix
- No
bora

Fix TMDLA in batched DMC driver runs

---

src/Particle/ParticleSet.cpp
src/Particle/RealSpacePositionsOMPTarget.h
src/QMCWaveFunctions/TrialWaveFunction.cpp

Align timers between batch and legacy drivers.
- No
epyc-server

Adjust timers

---

src/QMCWaveFunctions/Fermion/SlaterDet.h
src/QMCWaveFunctions/TrialWaveFunction.cpp
src/QMCWaveFunctions/TrialWaveFunction.h
src/QMCWaveFunctions/WaveFunctionComponent.h

Only API exists. No implementation/consumer.
- No
laptop

Remove WFC::evaluateGradDerivatives

---

docs/installation.rst

Update for versions available and working today.
- No
mac as detailed, today.

Update macports recipe docs

---

CMake/GNUCompilers.cmake

try_compile may fail for various reasons. Output full printout helps troubleshooting.
- Other (please describe): CMake
- No
mac studio

Print out full error in the glibc check.

---

src/Estimators/CMakeLists.txt
src/Estimators/StructureFactorInput.cpp
src/Estimators/StructureFactorInput.h
src/Estimators/tests/CMakeLists.txt
src/Estimators/tests/ValidStructureFactorInput.h
src/Estimators/tests/test_StructureFactorInput.cpp

This PR add the input class for the consolidated structure factor estimator.
Update of manual will be in a later PR.
- New feature
- No

Add StructureFactorInput

---

src/AFQMC/HamiltonianOperations/KP3IndexFactorization_batched.hpp
src/AFQMC/HamiltonianOperations/tests/test_hamiltonian_operations.cpp
src/AFQMC/Numerics/detail/CPU/lapack_cpu.hpp
src/AFQMC/Numerics/detail/utilities.hpp
src/AFQMC/Numerics/determinant.hpp
src/AFQMC/SlaterDeterminantOperations/mixed_density_matrix.hpp
src/AFQMC/Wavefunctions/NOMSD.icc
src/AFQMC/Wavefunctions/tests/test_phmsd.cpp
src/AFQMC/Wavefunctions/tests/test_wfn_factory.cpp
src/Estimators/OneBodyDensityMatrices.cpp
src/Estimators/SelfHealingOverlap.cpp
src/QMCHamiltonians/DensityMatrices1B.cpp
src/QMCHamiltonians/OrbitalImages.cpp
src/QMCHamiltonians/SelfHealingOverlapLegacy.cpp
src/QMCWaveFunctions/HarmonicOscillator/SHOSet.cpp
src/type_traits/complex_help.hpp

Consolidate codes
- No
epyc-server

Remove custom real/imag() overload functions

---

src/AFQMC/Memory/device_pointers.hpp

make afqmc device pointer a proper pointer by providing comparison
- No
Ubuntu 24.04

[afqmc] implement < for device pointer

---

src/QMCDrivers/tests/SetupPools.cpp
src/QMCDrivers/tests/test_WalkerControl.cpp
src/QMCDrivers/tests/test_WalkerControl.h
src/QMCWaveFunctions/Fermion/cuSolverInverter.hpp
src/QMCWaveFunctions/Fermion/rocSolverInverter.hpp

Should address https://github.com/QMCPACK/qmcpack/pull/5260.
Works fine on my 3060Ti with 8GB VRAM.
- Bugfix
- No
epyc-server

Lazy init cu/rocsolver

---

CHANGELOG.md

Update the changelog with the major unreleased changes since the last release. "Minor" PRs have been removed to keep the list short while still e.g listing most of the bug fixes. Changes were approximately grouped and sorted by hand.
Initial list built via variants of
```
gh search prs --merged-at 2025-01-01..2025-01-31 -R QMCPACK/qmcpack \
--json title,url,repository,number -L 1000 \
--jq '.[]|("* " + .title + " [#" + (.number|tostring) +"]("+ .url + ")\n")' 
```
- No

Update unreleased changes

---

docs/examples.rst

Describe current examples + fix a few directory names.
- Yes
local mac, sphinx

Update examples list in docs

---

docs/developing.rst
docs/features.rst
docs/input_overview.rst
docs/installation.rst
docs/introduction.rst
docs/methods.rst
docs/performance_portable.rst

Attempt to update the docs to reflect the current status of the code with batched drivers being the default. Legacy drivers are described as deprecated and to be removed in future.
- No
mac, local sphinx builds

Update docs to match batched driver defaults

---

CMakeLists.txt

Set development version 4.0.9

---

tests/molecules/H4_ae/CMakeLists.txt

Increase error bar to address statistical failures
e.g. https://cdash.qmcpack.org/tests/15755104
- No
None

Make short H4 target descent test reliable

---

tests/solids/diamondC_2x1x1-Gaussian_pp_MSD/CMakeLists.txt

Bad in complex mixed precision with Intel21.
https://cdash.qmcpack.org/tests/15745654
- No
None

Increase ionion tol in short diamondC_2x1x1-Gaussian_MSD_pp test

---

tests/molecules/LiH_ae_MSD/CMakeLists.txt

Address https://cdash.qmcpack.org/tests/15914028
- No
None

Increase tol in short-LiH_ae-vmc_msdj_noj-1-16-variance

---

examples/molecules/He/CMakeLists.txt

Address https://cdash.qmcpack.org/tests/16230549 and similar stochastic errors. Largest deviation see recently -0.02562780 in 
https://cdash.qmcpack.org/tests/15957172
- No
None

Increase example He tolerance

---

src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp

Adjust test tolerance to make intel 21 classic happy.

---

tests/solids/bccH_1x1x1_ae/CMakeLists.txt
tests/solids/bccH_1x1x1_ae/qmc_short_batch_pw.in.xml

Add batched versions of existing pw tests with varied parallelization. Also remove mysterious floating point step count.
- Testing update
- No
Laptop, gcc13

Add batched pw testing for bcc H

---

src/Platforms/CUDA/CUDADeviceManager.cpp
src/Platforms/CUDA/CUDADeviceManager.h
src/Platforms/DeviceManager.cpp
src/Platforms/DeviceManager.h
src/Platforms/OMPTarget/OMPDeviceManager.cpp
src/Platforms/OMPTarget/OMPDeviceManager.h
src/Platforms/SYCL/SYCLDeviceManager.cpp
src/Platforms/SYCL/SYCLDeviceManager.h
src/QMCApp/QMCMain.cpp

Make `QMC_OFFLOAD_MEM_ASSOCIATED` and `QMC_DISABLE_HIP_HOST_REGISTER` reflected in the output file.
- New feature
- No
frontier

Print feature selections via DeviceManager.

---

tests/solids/diamondC_1x1x1_pp/CMakeLists.txt
tests/solids/diamondC_1x1x1_pp/qmc_short_vmcbatch.in.xml
tests/solids/diamondC_1x1x1_pp/qmc_short_vmcbatch_pw.in.xml

Add VMC batched spline and pw tests
Context: Expanding direct checks of batched spline behavior and pw capabilities
- No
GCC14 8 core laptop. pw acceptably fast.

Add diamondC 1x1x1 VMC batched spline and pw tests

---

tests/solids/LiH_solid_1x1x1_pp/CMakeLists.txt
tests/solids/LiH_solid_1x1x1_pp/hf_vmcbatch_LiH-arb-drift.xml
tests/solids/LiH_solid_1x1x1_pp/hf_vmcbatch_LiH-gamma-drift.xml
tests/solids/LiH_solid_1x1x1_pp/hf_vmcbatch_LiH-x-drift.xml

Batched versions of the existing VMC spline cases at different k-points
- No
sulfur, gcc14.

Add batched LiH solid tests

---

docs/intro_wavefunction.rst

GPU implementation available for delayed update (line 799) + many small typos/consistency
- No
None

Update wavefunction docs

---

tests/molecules/FeCO6_b3lyp_gms/CMakeLists.txt

Fixes https://cdash.qmcpack.org/tests/16951821
- No
epyc-server

Relax FeCO6_b3lyp_gms real MP tolerance.

---

CMakeLists.txt
docs/external_tools.rst
src/Utilities/ScopedProfiler.h

Allow more refined profiling.
- New feature
- No
epyc-server

Add HPCToolkit start/stop API support.

---

examples/README.md

Add a mention of nexus examples so that users are less likely to miss them
- No
None

Add README in examples

---

docs/installation.rst

Fix a broken link + tweak nearby text.
- No
None

Fix cdash link in docs + small edit

---

README.md

Add link to full installation instructions and mention config files.
- No
None

Point to installation instructions in README

---

tests/rmg/CMakeLists.txt

Works with the current development version of RMG in the nightlies. The current runs are small so this is not important for performance.
- Bugfix
- No
sulfur, nightlies.

Set RMG workflow test to use single thread

---

tests/molecules/LiH_ae_pyscf/CMakeLists.txt

Address occasional statistical failures
https://cdash.qmcpack.org/testSummary.php?project=1&name=short-LiH_ae_pyscf-vmc_hf_noj-1-16-kinetic&date=2025-03-30
https://cdash.qmcpack.org/testSummary.php?project=1&name=short-LiH_ae_pyscf-vmc_hf_noj-1-16-totenergy&date=2025-03-30
https://cdash.qmcpack.org/testSummary.php?project=1&name=short-LiH_ae_pyscf-vmc_hf_noj-1-16-eeenergy&date=2025-03-26
- Testing changes (e.g. new 
- No
None.
- NA. This PR adds tests to …

Increase tolerances on short-LiH_ae_pyscf tests

---

nexus/sphinx_docs/user-scripts.rst

Add the docs from #5255 , entirely based on Jaron's comments.
~~Need to check CI -- will update after checking readthedocs rendering.~~  Looks good to me on readthedocs.
- No
None.

Nexus: Add job options docs

---

src/QMCWaveFunctions/TWFFastDerivWrapper.cpp

Stop new unused warnings
- No
sulfur, clang19

Remove unused variable in TWFFastDerivWrapper

---

tests/molecules/CHN_ae/CMakeLists.txt

Fix occasional failure in short-chn_ae_cuspCorrection-vmc-1-16-totenergy https://cdash.qmcpack.org/tests/20326724
- No
None

Increase test tolerance for CHN ae cusp vmc energy

---

.github/pull_request_template.md

Mention PR guidance in the PR template.

---

tests/molecules/Be_STO/be_opt.in.xml
tests/molecules/Be_STO/be_sto_nodrift_vmc.in.xml
tests/molecules/Be_STO/be_sto_vmc.in.xml
tests/molecules/Be_STO/be_sto_vmc_legacy.in.xml

Noticed that we have unreasonably short equilibration for these runs. Possible explanation for a rare statistical failure https://cdash.qmcpack.org/tests/20809735
- No
None

Increase Be STO test warmupsteps

---

config/build_nersc_perlmutter_Clang.sh

Update NERSC perlmutter recipe

---

tests/molecules/FeCO6_b3lyp_pyscf/CMakeLists.txt

Address occasional statistical failure e.g. https://cdash.qmcpack.org/tests/21846628
- No
None
* * [X] This PR is up to date with current the current state of 'develop'

Increase deterministic test FeCO6 nl tol

---

tests/solids/diamondC_2x1x1_pp/CMakeLists.txt

Address statistical failures.  e.g. https://cdash.qmcpack.org/tests/21925448 Flux estimator is notably noisy, 26% failure rate over the last week. https://cdash.qmcpack.org/testOverview.php?project=QMCPACK&begin=2025-04-19&end=2025-04-26&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=flux
- No
None
* * [X] This PR is up to date with current the current state of 'develop'
* * [ ] This …

Increase long diamond 2x1x1 flux tol

---

src/CMakeLists.txt

minimal pools is now better documented.
- No
* * [x ] I have read the pull request guidance and develop docs
* * [ x] This PR is up to date with the current state of 'develop'
* * [ x] Code added or changed in the PR has been clang-formatted
* * [ x] This PR adds tests to cover any new code, or to catch a bug that is being fixed
* * [ x] Documentation has been added (if appropriate)

Minimal pools doc

---

docs/developing.rst

Please also follow the [GitHub Pull Request guidance](https://qmcpack.readthedocs.io/en/develop/developing.html#github-pull-request-guidance). As much as possible, try to avoid the ["Don't"s](https://qmcpack.readthedocs.io/en/develop/developing.html#don-t) to help maintain a high development velocity.
Fix the rst from #5497
- Bugfix
- No
None. Check the rtd in CI. …

Typo fix in development docs

---

src/QMCWaveFunctions/Fermion/ci_configuration.h
src/QMCWaveFunctions/Fermion/ci_configuration2.h

Simple cleanup
- Bugfix
- No
GCC13, Ubuntu 24 LTS

Fix signedness comparisons  in ci_configs

---

src/Estimators/tests/CMakeLists.txt
src/QMCApp/CMakeLists.txt
src/QMCDrivers/tests/CMakeLists.txt
src/QMCHamiltonians/tests/CMakeLists.txt
src/QMCWaveFunctions/CMakeLists.txt
src/QMCWaveFunctions/tests/CMakeLists.txt
src/Sandbox/CMakeLists.txt
src/spline2/CMakeLists.txt
src/spline2/MultiBspline.cpp
src/spline2/MultiBspline.hpp
src/spline2/MultiBsplineOffload.cpp
src/spline2/MultiBsplineOffload.hpp
src/spline2/tests/CMakeLists.txt

Making both classes compiled as a library.
- No
epyc-server

Refactor MultiSpline and MultiSplineOffload

---

tests/molecules/He_param/CMakeLists.txt

Please also follow the [GitHub Pull Request guidance](https://qmcpack.readthedocs.io/en/develop/developing.html#github-pull-request-guidance). As much as possible, try to avoid the ["Don't"s](https://qmcpack.readthedocs.io/en/develop/developing.html#don-t) to help maintain a high development velocity.
Simple name fixe
- Bugfix
- No
GCC 14 MPI …

Fix He param tests after 5508

---

nexus/lib/machines.py
nexus/tests/unit/test_machines.py

Adds Aurora to machine.py. It is primarly modified from Perlmutter machine description due to coexisting CPU and GPU queues. Relevant tests are also added. nxs-test seems to run without any error. 
- New feature
- No
MacOs
* * [ ] I have read the pull request guidance and develop docs

Nexus: Aurora added in machines.py

---

tests/test_automation/nightly_test_scripts/nightly_ornl.sh
tests/test_automation/nightly_test_scripts/ornl_setup.sh
tests/test_automation/nightly_test_scripts/ornl_setup_environments.sh
tests/test_automation/nightly_test_scripts/ornl_versions.sh

Latest working versions.
Many updates to handle spack updates as they move toward 1.0 release
Move configuration via SPACK_USER_CONFIG_PATH to allow multiple spack installations without interference
- No
sulfur
* * [ ] This PR adds tests to cover any new code, or to catch a …

Update nightly test scripts for spack updates

---

README.md
docs/installation.rst

Move the list of tested versions to the manual.
In a subsequent PR I plan to remove all the installation info from the README.md and accompany this will updates to this part of the manual to make them clearer and easier to navigate.
- No
None. Check the links and updated text render OK
* * [ ] This PR adds tests to cover any new code, or to catch a bug that is …

Move list of tested library and compiler versions to manual

---

CMake/AddRPATH.cmake
src/Estimators/SpaceGridInput.h
src/Particle/ParticleIO/XMLParticleIO.h
src/Utilities/string_utils.h

Encountered when trying NVHPC 25.5.
- Bugfix
- No
epyc-server

CMake and Warning fixes for nvc++

---

src/Particle/SoaDistanceTableAA.h
src/Particle/SoaDistanceTableAAOMPTarget.h
src/Particle/SoaDistanceTableAB.h
src/Particle/SoaDistanceTableABOMPTarget.h
src/Particle/createDistanceTable.h
src/Particle/createDistanceTableAA.cpp
src/Particle/createDistanceTableAAOMPTarget.cpp
src/Particle/createDistanceTableAB.cpp
src/Particle/createDistanceTableABOMPTarget.cpp

Safer with more const.
- Bugfix
- No
laptop

More const reference to ParticleSet in DT.

---

nexus/lib/qmcpack.py
nexus/lib/qmcpack_input.py

Support opt.vp.h5 parameter files and enable input generation for stochastic reconfiguration.
- New feature
- No
Laptop

Nexus: support opt.vp.h5 files and add stochastic reconfiguration input generation

---

src/AFQMC/Walkers/WalkerSetBase.h

in WalkerSetBase.h
Remove uses of deprecated Multi function .extension(n).
- No
Ubuntu 24.04

remove some uses of deprecated extension paren
