- src/Utilities/NewTimer.cpp
- src/Utilities/NewTimer.h
- src/Utilities/tests/test_timer.cpp
The map for collecting the per-stack timer data used a string representation
of the stack as a key.  Some of the overhead comes from managing these strings.
The new key assigns a small integer timer id to each timer and constructs
the stack in a fixed-size array.
An additional hack to increase performance treats a chunk of timers as a larger
data type for the comparisons needed by the map data structure.
Current settings use 8 bits for the timer id (giving up to 254 timers), and
two 64 bit ints for the stack (16 stack levels).  If these are exceeded, warnings
are printed to the screen and in the .info.xml file.
Use of a hash table (unordered_map) gave roughly the same performance.
> Lower stack timer overhead using fixed-size key.

- src/Message/CommOperatorsMPI.h
_CRAYMPI flag was used on the Titan toolchains in the attic folder but not in the most recent build script.
No clue if someone checked whether this flag is needed or not. The titan weekly tests shows OK without this flag.
Anyway, fix the broken code path since the AFQMC merge.
> fix the building with -D_CRAYMPI on Titan.

- src/Utilities/Clock.h
Read directly from the time base register for a low-overhead timer.
This assumes a 1.6 GHz processor clock.
Remove the Blue Gene / P timer code - I assume no one is using one of these anymore.
> Update timer for BG/Q.

- nexus/library/memory.py
- nexus/library/project_manager.py
Currently the polling output only shows the memory of the python process
running Nexus.  Show the memory used by all the child processes as well.
This is a cleaned-up version of #78
> Nexus: Display memory of child processes

- src/CMakeLists.txt
The information at configure time may be useful for diagnosing failed nightly builds. (The commit info can be obtained from the build log in CDash.)
Requested by @ye-luo in #59 
Output in context:
<pre>
-- Disabling CUDA
-- Ready to build qmcpack
Git branch: config-time-git-info
Git commit hash: d0cdfe3bc29dc5553e5303d502e1e2ce6fce9192-dirty
CMake version 2.8.10 - some unit tests will not be built
Adding tests for QMCPACK
</pre>
> Print git repository info at configure time.

- README
Manual PDF currently serves as primary documentation. The doxygen produced files on docs.qmcpack.org are out of date.
> Remove references to docs.qmcpack.org (should have been directly committed to rc_3.0.0)

- CMake/macros.cmake
- CMakeLists.txt
- src/QMCWaveFunctions/tests/CMakeLists.txt
Set QMC_SYMLINK_TEST_FILES to 'true' (the default) to soft-link the *.h5 files in the tests (saves space).
Set QMC_SYMLINK_TEST_FILES to 'false' to actually copy the files (previous behavior).
In the first commit in this PR, all the test files were soft-linked.  That was changed in the next commit, but the code for that behavior is still present - adjust COPY_DIRECTORY_MAYBE_USING_SYMLINK in CMake/macros.cmake.
This fixes issue #58 
Tested on Vesta and Titan.
> Use symbolic links for *.h5 files in the tests

- src/Platforms/devices.h
- src/QMCApp/qmcapp.cpp
This code allows multiple MPI ranks on a given node to access the same GPU device. Here is a short list of changes:
- code was added to allow treatment of the previously failing case where more MPI ranks are placed on  a node than GPU devices, the new behavior is to "overdrive" the existing GPU devices by cycling through them (e.g. 4 MPI ranks and 2 GPUs leads to rank 0,2 and 1,3 to request GPU device 0 and 1, respectively) 
- care was taken to provide transparent information to the user without adding too many lines of output (typically, only one additional line per node to inform about how many ranks and GPUs are on it is added over the old output)
- removed the redundantly passed parameters to Init_Cuda (the class that stores the values passed is accessible in the scope of Init_Cuda), …
> Added more general GPU initialization code.

- src/QMCWaveFunctions/EinsplineSetBuilderOld.cpp
Fixes #36
Replace default error handler in HDF5 so that we can preferentially print our error message.
> Cleaner error handling when spline file not present

- src/QMCApp/QMCMain.cpp
- src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp
For the smaller NiO benchmarks, the startup time dominates the run time, but
was missed by the timers.  Now the startup time is captured and present
in the total time.
> Add timer for startup time.

- tests/test_automation/nightly_ornl_oxygen.sh
- tests/test_automation/weekly_ornl_oxygen.sh
Updated oxygen nightly and weekly scripts.
QMC_DATA is set to directory containing NiO/*.h5 to activate performance tests for some of the builds.
Also updated to use locally installed OpenMPI for some builds. Performance considerably improved.
> Updated scripts with QMC_DATA set for performance

- src/Particle/ParticleSet.cpp
As systems get larger, the particle position list in the output file gets longer.  At some point, it really takes up too much space in a file that should focus on human readability.
If needed, a record of the initial particle positions should be output some other way - either a separate text file, an XML file, or an HDF file.
Sample truncated output:
<pre>
Summary of QMC systems
=========================================================
ParticleSetPool has:
ParticleSet e : 0 192 384
384
u -4.6770436966e+00  1.0864074410e+01  2.9280799943e+00
u  3.0882453042e+00  4.1204692880e+00  2.6269004106e+00
u  3.8803048685e+00  5.1818523897e+00  4.9100902982e+00
u -6.3915893400e+00  8.0251400115e+00  1.1326594491e+01
u -7.1743533760e+00  8.4448055289e+00  1.0530443287e+01
u -6.5275662801e+00 …
> Limit the length of ParticleSet output.

- src/QMCApp/QMCMain.cpp
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/Utilities/NewTimer.cpp
- src/Utilities/NewTimer.h
- src/Utilities/tests/test_timer.cpp
Add a method to create a timer and add it to the timer manager in one step.
This shortens the code at timer creation sites, updated in a few places.
Add a convenience wrapper to use scoping to start/stop the timer.
Measure the total AFQMC run time. 
I know the branch name says afqmc_timers - this is preliminary work before adding AFQMC timers.
> Improvements to timer code.

- CMakeLists.txt
Do a more precise check to see if the MPI compiler wrapper is being used with an MPI-enabled build..
If not, print a warning message about automatically compiling with MPI.
It should still build if cmake is used with no options.
> Add warning if MPI compiler wrapper not used

- CMakeLists.txt
- src/AFQMC/CMakeLists.txt
- src/AFQMC/Matrix/SparseMatrix.h
- src/AFQMC/Matrix/tests/CMakeLists.txt
- src/AFQMC/Matrix/tests/sparse_matrix_helpers.h
- src/AFQMC/Matrix/tests/test_sparse_matrix.cpp
- src/AFQMC/Numerics/SparseMatrixOperations.cpp
- src/AFQMC/Numerics/SparseMatrixOperations.h
- src/AFQMC/Numerics/tests/CMakeLists.txt
- src/AFQMC/Numerics/tests/gensparse.py
- src/AFQMC/Numerics/tests/sparse_mult_cases.cpp
- src/AFQMC/Numerics/tests/test_sparse_ops.cpp
Add sparse matrix-vector and matrix-matrix multiply routines so AFQMC can be built without MKL.
Also add unit testing for the sparse matrix class and the sparse matrix multiplies.
> AFQMC - add sparse matrix multiply

- src/Utilities/tests/test_timer.cpp
Should fix a unit test failures in unit_test_utilities when timers are not enabled.
> Fix scoped timer unit test when timers disabled.

- nexus/library/nexus.py
- nexus/library/plotting.py
- nexus/library/qmcpack.py
- nexus/library/qmcpack_input.py
- nexus/library/simulation.py
- nexus/library/structure.py
optimal_tilematrix (structure.py) is improved in the following ways:
1) Accelerated computation of candidate tilematrix determinants for target volume matching.
2) Ability to use a mask array to restrict form of tilematrix search, e.g. only look for tilings of the form:
x x 0
x x 0
0 0 x
3) Use of wigner radius to select among cells w/ equivalent inscribing radius.
4) Use of devation of cubic shape (as judged by face diagonals) to select among cells w/ equivalent wigner radius.
5) Prioritization of certain tile matrix aesthetics (diagonal, symmetric, etc) to select among cells w/ equivalent cubicity
Changes result in speedup of ~5x and superior cell selection for typical problem sets over the original algorithm.
Other minor updates include a fix for when the user provides no …
> nexus: improve optimal_tilematrix routine

- manual/dmc.tex
- manual/methods.tex
- manual/output_overview.tex
- src/Particle/tests/CMakeLists.txt
- src/Particle/tests/test_walker.cpp
- src/QMCDrivers/WalkerControlBase.cpp
Fix issue #155 
Add a unit test for write/read of .config.h5 files.  It would not have caught the previous issue, but it's a start.   This unit test also works under MPI with mpirun.
Update checkpoint-related parts of the manual to reflect the current code.
> Fix non-MPI checkpoint and update manual

- CMake/compareGCOV.cmake
- CMake/ctest_script.cmake
- tests/coverage/compare_gcov.py
- tests/coverage/demangle.py
- tests/coverage/read_gcov.py
- tests/coverage/sample.cpp
- tests/solids/diamondC_1x1x1_pp/qmc_short_vmc_dmc_coverage.in.xml
- tests/system/CMakeLists.txt
The code coverage model measures unit test coverage relative to a baseline
run (or runs).  There are three relevant runs:
base - the baseline run (a typical run activating features to test against)
unit - the unit test run
diff - the results from the scripts comparing the coverage of unit relative to base
A test using a shortened diamondC_1x1x1_pp case is used for the base.
The added test has the label 'coverage'.  It should be possible to add more tests
with the 'coverage' label and automatically expand the baseline. (The compiler
coverage code automatically accumulates data from multiple runs)
Running with more than one MPI process will have race conditions when writing the coverage
data, and will likely corrupt it.  There might be ways to address this later.
Scripts in the …
> Add code coverage scripts for GCOV format

- src/LongRange/StructFact.cpp
- src/QMCWaveFunctions/Jastrow/LRTwoBodyJastrow.cpp
- src/QMCWaveFunctions/Jastrow/LRTwoBodyJastrow.h
- src/QMCWaveFunctions/Jastrow/RPAJastrow.cpp
- src/QMCWaveFunctions/Jastrow/RPAJastrow.h
Revive RPA Jastrow.  Accomplished by doing the following:
1.)  Implementing evalGrad, ratioGrad, and evaluateLog to make evaluation consistent with current releases. 
2.)  Add redundant code to LRTwoBodyJastrow and StructFact.cpp to handle the "USE_REAL_STRUCT_FACTOR" use case.
> Kspacejastrow

- src/ParticleIO/ESHDFParticleParser.cpp
- src/QMCApp/ParticleSetPool.cpp
This should gracefully exit in the event that an h5 file is not found for particleset initialization.  Also eliminates H5 chatter, in line with Mark's suggestion.
> Resolve Issue #172

- CMake/ctest_script.cmake
Use SSL for cdash submissions.
> HTTPS required for cdash submissions

- CMake/macros.cmake
- src/QMCDrivers/RMC/RMCUpdateAll.cpp
- src/QMCDrivers/RMC/RMCUpdatePbyP.cpp
- tests/solids/bccH_1x1x1_ae/qmc_long_vmc_rmc.in.xml
- tests/solids/bccH_1x1x1_ae/qmc_short_vmc_rmc.in.xml
- tests/system/CMakeLists.txt
- utils/check_scalars.py
I've added ctests for bccH_1x1x1_ae.  Summary:
1.)  Short test that checks the local energy estimate (mixed).  
2.)  Long test that checks:
a.) LocalEnergy.
b.) Potential Energy (mixed and pure)
c.) Kinetic Energy (mixed and pure)
d.) Electron-electron energy (mixed and pure).  
On my system, RMC agrees with DMC, and the ctests reflect this (hallelujah).
As for chatter, RMC propagator info is now printed from OMP thread 0.
> Add ctests for RMC.  Also eliminate multithread chatter from RMCUpdate

- src/QMCApp/ParticleSetPool.cpp
Error handling (PR #175) should be consistent with the operation that only rank=0 tries to open the file.
> Fix MPI>1 bug due to PR #175 for issue #172.

- examples/molecules/He/CMakeLists.txt
Add the prefix "example_" to the He example test names to make it easier to
include or exclude tests that come from the examples.
The example tests are exceptionally slow on KNL, so it would be useful to easily exclude them from test runs.
> Add example prefix to He examples.

- src/AFQMC/Numerics/tests/test_sparse_ops.cpp
Need to correctly set the number of rows in the matrix in one test, and fully initialize all the input values in another.
> Fix AFQMC unit test for 'numerics'

- src/QMCDrivers/QMCCSLinearOptimizeWFmanagerOMP.h
- src/QMCDrivers/QMCCostFunctionBase.h
- src/QMCDrivers/QMCCostFunctionCUDA.cpp
- src/QMCDrivers/QMCCostFunctionCUDA.h
- src/QMCDrivers/QMCCostFunctionOMP.cpp
- src/QMCDrivers/QMCCostFunctionOMP.h
- src/QMCDrivers/QMCFixedSampleLinearOptimize.cpp
In QMCCostFunctionXXX, fillOverlapHamiltonianMatrices with 2 or 4 arguments are removed.
They were not used and probably not maintained. Contents were basically the same as 3 argument version.
3 argument version is simplified to use only 2 arguments. 2nd and 3rd matrices was identical.
In OneShiftOnly, add a small value to the overlap matrix before inversion to avoid ill-condition.
> Clean up unused fillOverlapHamiltonianMatrices.

- src/AFQMC/Matrix/tests/test_sparse_matrix.cpp
The problem occurs on an empty 1x1 sparse matrix.
The problem seems to afflict the Intel compiler version 17.0.1 20161005 in release mode.
Any access to the A or M variables (to print them, for example) makes the problem disappear.
The workaround is to assign the array elements to temporary variables before testing them.
> Fix AFQMC unit test with Intel compiler.

- build/.gitignore
Two users trying to build code from manual instructions are flummoxed by lack of a "build" directory, which is referenced in manual.  Either we add an empty "build" directory, or we rewrite the incorrect sections of the manual.
> Add empty build directory.

- src/QMCDrivers/DriftOperators.h
scaled drift needed for stable VMC
naive drift can diverge and lead to a precipitous drop in acceptance
rate as time step is increased
> fixed VMCUpdateAll with drift

- src/QMCHamiltonians/ForceChiesaPBCAA.cpp
- src/QMCHamiltonians/ForceChiesaPBCAA.h
- src/QMCHamiltonians/tests/CMakeLists.txt
- src/QMCHamiltonians/tests/test_force.cpp
Bug reported by Paul Yang.
The 'makeClone' method did not copy the 'addionion' flag.
The default value for addionion is true.  If the input file set addionion to false and used threads, the master thread would use 'false' and all the other threads would use 'true'.
Remove the unused MaxGridPoints.
Also add some unit tests.
> Fix forces with threads and addionion=false.

- src/AFQMC/Numerics/SparseMatrixOperations.h
- src/Lattice/UniformCartesianGrid.h
The GCC 7 compiler is stricter about checking template code.
Ill-formed constructs are rejected immediately, rather than waiting for instantiation.
See https://gcc.gnu.org/gcc-7/porting_to.html
The change in AFQMC resides inside a if-check for the type.  This branch is only executed for complex types, but still needs to compile for non-complex types.   std::conj always returns a complex type, but 'myconj' will return the input type.
> Fixes to build with GCC 7.

- src/CMakeLists.txt
- src/OhmmsPETE/tests/CMakeLists.txt
- src/OhmmsPETE/tests/test_matrix.cpp
- src/OhmmsPETE/tests/test_tinyvector.cpp
- src/OhmmsPETE/tests/test_vector.cpp
The particular code tested was driven by code coverage results.  Relative to the current base test, the OhmmsPETE and PETE directories should be covered by unit tests.
No tests for TinyMatrix added because it doesn't appear to be used in the code.
> Add unit tests for OhmmsPETE

- tests/test_automation/weekly_ornl_oxygen_coverage.sh
This is now set to run weekly at 8pm on Sundays. Took only around 1h, so we can consider expanding the test set to include shortened versions of more of the standard integration tests.
See cdash for first scheduled report.
> Initial weekly coverage script for oxygen

- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmc_short_LiH-arb.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmc_short_LiH-gamma.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmc_short_LiH-x.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmcnl_short_LiH-arb.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmcnl_short_LiH-gamma.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmcnl_short_LiH-x.xml
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmc_ref_LiH-arb.out
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmc_ref_LiH-arb.s001.qmca
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmc_ref_LiH-arb.xml
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmc_ref_LiH-gamma.out
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmc_ref_LiH-gamma.s001.qmca
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmc_ref_LiH-gamma.xml
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmc_ref_LiH-x.out
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmc_ref_LiH-x.s001.qmca
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmc_ref_LiH-x.xml
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmcnl_ref_LiH-arb.out
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmcnl_ref_LiH-arb.s001.qmca
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmcnl_ref_LiH-arb.xml
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmcnl_ref_LiH-gamma.out
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmcnl_ref_LiH-gamma.s001.qmca
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmcnl_ref_LiH-gamma.xml
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmcnl_ref_LiH-x.out
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmcnl_ref_LiH-x.s001.qmca
- tests/solids/LiH_solid_1x1x1_pp/qmc-ref/hf_vmc_dmcnl_ref_LiH-x.xml
- tests/system/CMakeLists.txt
and using locality and t-moves approximations.
Note that the locality approximation is small enough in LiH that this is not a strong test of the t-moves scheme, but it should be sensitive to major bugs.
Reference data produced with current git version of QMCPACK. Only the analysis from qmca is included to keep overall file sizes small.
> Add DMC tests and reference data for LiH solid at Gamma/X/Arb twists

- src/QMCDrivers/DMC/DMCOMP.cpp
- src/QMCDrivers/VMC/VMCSingleOMP.cpp
Address the nightly test failure.
> Fix allp move with MP. No need for recomputePsi.

- src/QMCDrivers/DMC/DMCOMP.cpp
- src/QMCDrivers/DMC/DMC_CUDA.cpp
Oddly, DMCOMP doesn't display status of non-local moves, whereas DMC_CUDA does.  This writes a line of output to standard out.
> Add output to DMC CPU driver.  Indicates status of t-moves

- src/QMCDrivers/SimpleFixedNodeBranch.cpp
The DMC population feedback parameter should be controlled by the input
as stated by the manual. It is currently forced to be 1.0.
> do not reset 'feedback' parameter

- manual/installation.tex
Added CMake optional arguments MPIEXEC and MPIEXEC_NUMPROCS_FLAG to the manual under the installation section.
> Manual updates cmake flags

- nexus/library/physical_system.py
- nexus/library/structure.py
Very small change to correct a bug in tiled systems w/ requested low spin.  Useful for systems such as Al, which have a single atom in the primitive cell (necessarily spin polarized with integer electrons), but are spin unpolarized in supercells.
> nexus: fix for net_spin="low" in generate_physical_system

- CMake/python.cmake
- tests/estimator/CMakeLists.txt
- utils/test_import.py
Check a list of python modules to ensure they are installed before adding the estimator tests.
The test for module installation is based on whether the module successully imports or not.
If needed, additional tests of module functionality could be added.
> Add check for python modules for estimator tests.

- nexus/library/bundle.py
- nexus/library/simulation.py
Users attempting to bundle jobs/simulations together that depend on each other causes Nexus to hang.  An example situation: attempting to bundle together SCF and DMC runs.  Put a guard in place (error trap) to ensure that only simulations capable of simultaneous execution (i.e. in a single job) are bundled together.
> nexus: forbid bundling sims that depend on each other

- src/QMCHamiltonians/ECPComponentBuilder.cpp
- src/QMCHamiltonians/ECPComponentBuilder.h
- src/QMCHamiltonians/tests/test_ecp.cpp
Address comments in issue #253.
- initialize the value of is_open to false by default
- Update the filename in the APP_ABORT messages
- change get_file_length to be a member function.
> Initialize is_open value in ReadFileBuffer.

- tests/system/CMakeLists.txt
Discussed in #259 
As currently configured, these tests are too unreliable.
> Remove flux estimator from short tests

- src/QMCDrivers/tests/CMakeLists.txt
- src/QMCDrivers/tests/test_dmc.cpp
- src/QMCWaveFunctions/LinearOrbital.h
Use some simplified wavefunctions for testing - constant orbital (gradient is zero)
and linear orbital (gradient is constant).
The methods in LinearOrbital contain abort statements so only the ones strictly
needed for the unit tests are added.  There is some implementation in 'evaluate',
but since it's not called by these tests, it may not be completely correct.
Move return statements in ConstantOrbital to the end of the function.
The Jupyter notebook that generates the values is here: https://github.com/markdewing/qmc_algorithms/blob/master/Diffusion/DMC_propagator.ipynb
> Add unit tests for DMC walker propagation

- src/QMCHamiltonians/ForceCeperley.h
Solving force unit test failure
REQUIRE( force.c[i] == Approx(coeff[i]) )
with expansion:
4369.5f == Approx( 4375.0 )
> Use full precision in ForceCeperley::InitMatrix

- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_LiH-x-drift.xml
- tests/system/CMakeLists.txt
Missing from our testing and added due to the issue found while checking #219. Currently we test gamma (too easy) and an arbitrary twist that only the complex code can run. This test should run successfully with the real code as well as the complex code.
> Test VMC with drift at non-gamma twist that real code can still run

- tests/coverage/compare_gcov.py
For files that are completely untouched in the unit tests, but have some execution
in the the base tests, the behavior was to mark all the executed lines as uncovered.
This would incorrectly handle lines that are not executed (uncovered) in the base.
These lines should be marked as 'no-code' (not counted in coverage) in the output
directory.
This was most obvious in the case of formic/utils/lmyengine/engine_timing.cpp.
Even though the new optimizer is not called by the base test, there are some static
initializers that get called.   All the executable lines of the file were marked
as uncovered in the output, which was incorrect.  After the fix, only the lines
called by the static initializers are marked as uncovered.
With this fix the percentage coverage rises to 67% locally (probably …
> Coverage - mark lines from files not in unit tests correctly

- src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp
This bug affects non-supercell calculations on non-gamma twists using real valued orbitals with the real code but does not affect the complex code.
Related to part of the short-LiH-x issue #219 @prckent reported.
**It affects both VMC and DMC but VMC short tests didn't complain due to small statistics and large error bar.**
Now all the LiH DMC tests pass.
Some validation VMC runs
Each CPU run generates 3276800000 samples.
Each GPU run generates 409600000 samples.
LocalEnergy               Variance           ratio
arb-cpu-cplx/hf_vmc_LiH-arb  series 0  -8.383875 +/- 0.000051   1.600102 +/- 0.007014   0.1909
arb-gpu-cplx/hf_vmc_LiH-arb  series 0  -8.383593 +/- 0.000146   1.594170 +/- 0.011175   0.1902
gamma-cpu-cplx/hf_vmc_LiH-gamma  series 0  -8.481005 +/- 0.000050   1.623379 +/- 0.006308 …
> Fix LiH x-point bug.

- tests/io/CMakeLists.txt
These tests run quickly enough (<1 min on my laptop) with coverage enabled that
a special version of the input files is not needed.
Use the test with 1 MPI process for coverage, as we don't yet have the capability to do coverage with more than one MPI process.
> Add checkpoint/restart tests to the coverage base

- tests/coverage/compare_gcov.py
For lines where the unit test has coverage, but the base tests do not, the resulting diff was marked as 'covered'.   For consistency, every line not covered in the base tests should be marked as 'No code' in the resulting diff.
(This will drop the overall coverage percentage a few points)
> Fix: unit test has coverage, but base does not.

- tests/coverage/compare_gcov.py
- tests/coverage/merge_gcov.py
- tests/coverage/run_coverage.sh
Fixes because include files do not get coverage handled correctly for unit tests.  Only the coverage information corresponding to one executable is included, the coverage information from all the others is overwritten.  The coverage information should be combined.
There are two types of files produced for coverage:
.gcno - produced at compile-time, contains notes for translating basic blocks to source lines
.gcda - produced at run-time, contains the counts for basic blocks and arcs between then (for branch coverage)
The .gcda files can be merged, but only for multiple runs of the same executable.
(The .gcda files get automatically merged at run time, and newer versions of gcc have a 'gcov-tool' that can merge .gcda files)
This works fine for the system tests, since they all run 'qmcpack'. …
> Add merging of gcov files.

- src/QMCWaveFunctions/Jastrow/BsplineFunctor.h
- src/QMCWaveFunctions/Jastrow/eeI_JastrowBuilder.cpp
1) If rcut > Wigner-Seitz radius + 1e-4, abort
2) If rcut > Wigner-Seitz radius and rcut <= Wigner-Seitz radius + 1e-4, overwrite to Wigner-Seitz radius
3) If rcut <= Wigner-Seitz, respect user input.
Addressing issue #291
> Add tolerance to Jastrow rcut.

- src/Estimators/tests/test_accumulator.cpp
Addresses #290
mean() and mean_and_variance() duplicate the formulas and can have slight differences as a result (divide vs. reciprocal and multiply).   An better eventual fix would be to use identical formulas in both methods.
> Add tolerance to compares for estimators unit test

- src/CMakeLists.txt
- src/QMCApp/CMakeLists.txt
This should ensure the commands to build git-rev.h are triggered on the next build.
This might help with some of the Spack issues.
> Clean up git-rev-tmp.h after each build.

- nexus/executables/qmca
- nexus/executables/qmcfit
- nexus/library/plotting.py
- nexus/library/structure.py
Add ability to calculate the first order Makov-Payne correction for any cell.  Supported in new function 'makov_payne' in structure.py.
Also improve robustness of plotting generally, including tools like qmca.  Previously plots would fail in some environments (e.g. Titan at OLCF) due to default backend issues.  This is now fixed.  Fix contributed by Kayahan Saritas.
> nexus: add makov payne correction, make plotting robust

- src/Lattice/LatticeAnalyzer.h
This pull request addresses bugs in LatticeAnalyzer::find_shorter_base() and secondarily removes the do...while loop in LaticeAnalyzer::find_reduced_basis(), which in conjunction with the bugs in find_shorter_base(), can lead to an infinite loop.  This infinite loop was found using multi-precision and the following unit cell:
`<parameter name="lattice" units="bohr">
7.37924194        2.76721573        2.76721573
2.76721573        7.37924194        2.76721573
2.76721573        2.76721573        7.37924194
</parameter>` 
**Bug fixes in LatticeAnalyzer::find_shorter_base()**
1.)  Changes the definition of eps tolerance to reference the floating point type used in the definition of the lattice vectors, and not "float".  
2.)  For the lattice vector replacement condition ((r2-r2max) < -eps), …
> Lattice analyzer multi-precision bugfix 

- tests/test_automation/nightly_ornl_oxygen.sh
- tests/test_automation/weekly_ornl_oxygen.sh
Updating oxygen test scripts
- No MPI build (long used)
- "Full" for full precision CUDA builds
Only run nightly currently.
> Added CUDA full precision builds

- tests/test_automation/nightly_ornl_oxygen.sh
- tests/test_automation/weekly_ornl_oxygen.sh
Adding SoA builds to oxygen nightly and weekly integration tests.
Added a no-mpi variant, plus all combinations real/complex/full/mixed precision.
> Add SoA variants to tests

- src/QMCWaveFunctions/Fermion/DiracDeterminantBase.cpp
The invertPsiM method already has timers for the inverse, remove timers from the call site.
Move UpdateTimer.stop to the same method which calls UpdateTimer.start.
This should fix the errors in the NiO performance tests .
> Fix timer loop error.

- manual/features.tex
Though both CPU SoA algorithms and GPU algorithms have a similar memory footprint, the algorithms are very different. In principle, GPU implementation can be improved to match the efficiency of SoA ones but not very critical at the moment.
> Minor correction in doc.

- nexus/library/qmcpack_input.py
- src/QMCHamiltonians/MomentumEstimator.cpp
Momentum distribution estimator xml contained a single xml sub-element (<kpoints/>) which contained only a single attribute (grid).  Remove the kpoints element and move the grid attribute to the <estimator/> element.
Add support to Nexus to generate the momentum distribution xml element in the input file.
> clean up nofk input block, add nexus support

- src/ParticleIO/ParticleLayoutIO.cpp
- src/QMCWaveFunctions/Jastrow/DiffTwoBodyJastrowOrbital.h
- src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/TwoBodyJastrowOrbital.h
- src/QMCWaveFunctions/Jastrow/TwoBodyJastrowOrbitalBspline.cpp
- src/QMCWaveFunctions/tests/test_wf.cpp
For issue #282 #20 
1) uu, ud(du) : uu=dd, ud=du
2) uu : uu=dd=ud=du
3) ud(du) : only justified for 1 up + 1 down case, uu=dd=ud=du, uu/dd are not used in the calculation.
4) uu, ud(du), dd : uu, dd, ud=du
I may miss some useful cases.
checked uu, ud, dd case, optimization is correct.
> Align two body Jastrow input behavior.

- src/Estimators/EstimatorManagerBase.cpp
- src/Estimators/EstimatorManagerBase.h
- src/Estimators/tests/test_manager.cpp
- src/QMCDrivers/CMakeLists.txt
- src/QMCDrivers/CloneManager.h
- src/QMCDrivers/CorrelatedSampling/CSRMC.cpp
- src/QMCDrivers/CorrelatedSampling/CSVMC.cpp
- src/QMCDrivers/DMC/DMCOMP.cpp
- src/QMCDrivers/DMC/DMCOMP.master.cpp
- src/QMCDrivers/DMC/DMCOMPOPT.cpp
- src/QMCDrivers/Experimental/DMCMoveAll.cpp
- src/QMCDrivers/Experimental/DMCPbyP.cpp
- src/QMCDrivers/Experimental/GSLOptimize.cpp
- src/QMCDrivers/Experimental/VMCMultiple.cpp
- src/QMCDrivers/QMCDriver.cpp
- src/QMCDrivers/QMCDriver.h
- src/QMCDrivers/QMCUpdateBase.cpp
- src/QMCDrivers/QMCUpdateBase.h
- src/QMCDrivers/RMC/RMCSingleOMP.cpp
- src/QMCDrivers/SimpleFixedNodeBranch.cpp
- src/QMCDrivers/SimpleFixedNodeBranch.h
- src/QMCDrivers/VMC/VMCLinearOptOMP.cpp
- src/QMCDrivers/VMC/VMCMultipleWarp.cpp
- src/QMCDrivers/VMC/VMCPbyPMultiWarp.cpp
- src/QMCDrivers/VMC/VMCPbyPMultiple.cpp
- src/QMCDrivers/VMC/VMCSingleOMP.cpp
- src/QMCDrivers/tests/test_dmc.cpp
- src/QMCDrivers/tests/test_vmc.cpp
This is pull request 1/3 to resolve issue #214.  This renames EstimatorManager to EstimatorManagerBase, and updates all references to EstimatorManager in the code to EstimatorManagerBase.  While just a rename for now, the next pull request will split current functionality between a derived class EstimatorManager and EstimatorManagerBase.
> Rename EstimatorManager EstimatorManagerBase.  

- tests/system/CMakeLists.txt
Closes #334 
Explains too frequent test failures: expected error bar was for long test but only short statistics were being computed.
> Bugfix: Long diamond test was using short inputs

- src/CMakeLists.txt
- src/QMCDrivers/DMC/DMCOMP.cpp
- src/Utilities/RunTimeManager.cpp
- src/Utilities/RunTimeManager.h
The time limit is set with the MaxCPUSecs parameter.
Previously, the time limit was measured from the beginning of the
DMC portion of the run, and continued until the set time runs out.
To effectively set this parameter, the user would need to know how much
time is spent prior to the DMC section, and the duration of each block,
in order to leave enough time for the simulation to shut down cleanly.
The new behavior measures the time elapsed from the beginning of the
run (captured during static initialization of the RunTimeManager object).
The time per DMC block is tracked and used to estimate if there is sufficient
time to run another block.
The time reserved to finish the next block is computed from the existing
average with some margin (to handle variations in block to block time) and
a …
> Change behavior for the DMC CPU time limit.

- CMake/ctest_script.cmake
Overrides N_PROCS if defined. Needed to avoid process limits and perform parallel testing. Updates to OLCF titan and eos scripts will follow. Should not affect any other systems.
> Add N_PROCS_BUILD variable to ctest script

- .gitignore
- manual/installation.tex
Closes #50 
Updates .gitignore to ignore LaTeX intermediates and qmcpack_manual.pdf
> Update edison recipe; Ignore LaTeX-related files

- src/Message/CommOperatorsSingle.h
During the MPI and device matching step, allgather is called. In no MPI build, all gather was not implemented and caused a float point exception (divided by zero).
> Fix divided by zero issue in CUDA noMPI build.

- CMakeLists.txt
- nexus/examples/CMakeLists.txt
- nexus/examples/nexus_example_test.py
- nexus/examples/qmcpack/H2O/H2O.py
- nexus/examples/qmcpack/LiH/LiH.py
- nexus/examples/qmcpack/c20/c20.py
- nexus/examples/qmcpack/diamond/diamond.py
- nexus/examples/qmcpack/diamond/diamond_vacancy.py
- nexus/examples/qmcpack/graphene/graphene.py
- nexus/examples/qmcpack/oxygen_dimer/oxygen_dimer.py
- nexus/examples/qmcpack/pseudopotentials/H.BFD.upf
- nexus/examples/qmcpack/pseudopotentials/H.BFD.xml
- nexus/examples/quantum_espresso/relax_Ge_T_vs_kpoints/relax_vs_kpoints_example.py
Nexus scripts are run with 'generate_only' set to True.
This will at least test the Nexus API and catch breaking changes.
Currently the LiH test fails:
QmcpackInput error:
pseudo does not have the following attributes/elements:
l-local
The 'generate_only' setting is changed in the script by setting a particular value in the globals prior to exec'ing the Nexus script.    It does require a change to the Nexus script being tested.
It would be nice to be able to check this inside of Nexus, rather than requiring each example script to check it.    The modification of the globals only affects the exec'ed file, and does not propagate to the files imported from that file.
Another option would be to set an environment variable, and check that from inside Nexus, but I'm not sure where to insert …
> Add tests for Nexus examples.

- external_codes/catch/catch.hpp
- external_codes/catch/complex_approx.hpp
- src/Configuration.h
- src/QMCWaveFunctions/tests/test_pw.cpp
Create a ComplexApprox class that acts similar to the Approx class in Catch.
It will compare the real and imaginary parts separately. It can also test just
the real part if compare_real_only is set.
The epsilon and scale values settings are not exposed, but it would be easy
to add them.
Also create a ValueApprox typedef for testing ValueType with the appropriate
real or complex setting.   It's not used in this PR, but it will be used in a future PR.
> Add approximate testing for complex values.

- external_codes/catch/complex_approx.hpp
Now works with mixed precision.
Addresses issue #400
> Add float overloads for ComplexApprox comparisons.

- src/QMCWaveFunctions/tests/CMakeLists.txt
- src/QMCWaveFunctions/tests/gen_inverse.py
- src/QMCWaveFunctions/tests/test_dirac_det.cpp
- src/QMCWaveFunctions/tests/test_dirac_matrix.cpp
Test the inverse, determinant, and determinant update in the DiracDeterminantBase
and DiracMatrix classes.
The gen_inverse.py script is included to generate the data for the tests.
> Add tests for Dirac matrix classes.

- config/build_oic.sh
- config/build_ornl_oic.sh
Addresses #349.  A build script is added for OIC5 for builds with C++11 support.  The old toolchain file is still operational for older builds.  Both the build script and toolchain will be removed when OIC5 is decommissioned at the end of FY2018.
> Add build script for OIC

- CMake/macros.cmake
- tests/system/CMakeLists.txt
Revisits #403 as requested.  HEG and Li2 STO tests now in place for 1x16 mpi/threads rather than 16x1 mpi/threads.  In text documentation for QMC_RUN_AND_CHECK has been updated to reflect the change in input order and the addition of an arbitrary number of optional series/checklist pairs.
Once this PR is accepted, issue #394 can be closed.
> move to threaded Li2STO/HEG tests, update ctest doc

- src/QMCDrivers/DMC/WalkerReconfiguration.cpp
- src/QMCDrivers/DMC/WalkerReconfigurationMPI.cpp
- tests/solids/diamondC_2x1x1_pp/qmc_long_vmc_dmc_reconf.in.xml
- tests/solids/diamondC_2x1x1_pp/qmc_short_vmc_dmc_reconf.in.xml
- tests/system/CMakeLists.txt
Minimal fix needed to enable reconfiguration="yes". UnitZeta and DeltaStep (the position of the comb 'teeth') needs to be randomized at each generation to fix the bias error reported in Issue #18.
> Fix reconfiguration="yes" by updating UnitZeta each generation.

- src/formic/utils/lmyengine/block_mat.cpp
- src/formic/utils/lmyengine/davidson_solver.cpp
- src/formic/utils/lmyengine/energy_target_accu.cpp
- src/formic/utils/lmyengine/engine.cpp
- src/formic/utils/lmyengine/engine_numeric.cpp
- src/formic/utils/lmyengine/engine_timing.cpp
- src/formic/utils/lmyengine/matrix_builder.cpp
- src/formic/utils/lmyengine/spam_solver.cpp
- src/formic/utils/mpi_interface.cpp.in
- src/formic/utils/mpi_interface.h.in
- src/formic/utils/numeric.cpp
- src/formic/utils/timing.cpp
The C++ bindings to the MPI library were deprecated and are removed in MPI-3.
This change should enable QMCPACK to compile with newer versions of MPI
implementations.
Addresses issue #326
Some issues:
There is no MPI_* type corresponding to MPI::Bool.  Hopefully translating to
MPI_INT should work okay.
MPI-3 added 'const' to a number of parameters in the C interface.
These 'const' qualifiers had already been present in the C++ interface.
When compiling with MPI-2.2 (or older), the formic wrappers use a
'const T*' to call a function with a non-const 'T *'.
Newer GCC versions (7.1) give an error about converting from 'const' to non-'const'.
The fix is to add const_cast's to remove the 'const' qualifier.
> Use the C MPI API in the formic library.

- CMakeLists.txt
- src/config.h.cmake.in
- src/config/stdlib/limits.h
The iszero function was added to glibc 2.25.
Addresses issue #429.
> Check for iszero function.

- src/formic/utils/mpi_interface.h.in
Depending on how the MPI implementation defines these values, the Intel compiler
may or may not warn about "type qualifier on return type is meaningless".
(If the return value is a class, no warning.  If the return value is a plain type,
then there is a warning.)
Addresses issue #437.
> Remove const from return in formic MPI wrappers.

- manual/design_features.tex
Some of the spelling fixes (found by running the tex file through ispell) to #426 were lost when that branch was updated.
> Spelling fixes to the feature chapter.

- src/QMCDrivers/DMC/DMCUpdatePbyP.h
- src/QMCDrivers/DMC/DMCUpdatePbyPFast.cpp
- src/QMCDrivers/DMC/WalkerControlMPI.cpp
- src/QMCDrivers/DMC/WalkerControlMPI.h
Use new registration function and reference the timer list by an enum name rather than a number.
> Update DMC timers.

- src/QMCWaveFunctions/Jastrow/eeI_JastrowOrbital.h
During optimization, evaluateDerivatives pollutes internal data and causes wrong NLPP evaluation in checkConfigurations. Then the proposed pathological large change of parameters is rejected. Only affects AoS NLPP case.
> Fix a bug in AoS JeeI, SoA was correct.

- src/Utilities/tests/CMakeLists.txt
- src/Utilities/tests/test_partition.cpp
Out of all the FairDivide* functions, this one is most widely used.
> Add unit test for FairDivideLow

- nexus/library/basisset.py
- nexus/library/physical_system.py
- nexus/library/pseudopotential.py
Fix for when supercell has no spin imbalance, but primitive cell technically does (e.g. bcc Na).
Add ability to plot gaussian basis set primitives by width on a log scale.  Useful for comparing/truncating/merging basis sets.
> nexus: tiling fix when net_spin="low", gaussian basis plotting

- src/QMCDrivers/DMC/DMCOMP.cpp
- src/Utilities/Clock.h
- src/Utilities/RunTimeManager.cpp
- src/Utilities/RunTimeManager.h
- src/Utilities/tests/CMakeLists.txt
Extract the cpu time limit code from DMCOMP.cpp to a new class, RunTimeControl.
The remaining code in DMCOMP.cpp is a pattern for the code to be added to the other drivers.
The one change beyond refactoring is to add the MPI broadcast of the loop decision.  This prevents the case where different processors make different decisions about continuing the loop, which would cause QMCPACK to hang.
> Generalize time limit code

- src/QMCDrivers/DMC/DMCOMP.cpp
Some compilers (Intel) require the actual definition of bcast with a bool argument.  Presumably others convert the bool to an int.
Add the CommOperators.h include so the code compiles with the Intel compiler.
> Fix broadcast of bool from CPU time limit.

- nexus/library/structure.py
When a structure object was provided directly to generate_structure via generate_physical_system, the k-point grid was erroneously added prior to tiling.  This PR enforces the expected behavior: the k-point grid is first added to the supercell and and then the k-point grid is tiled for the primitive cell.
> nexus: fix k-point add for tiling corner case

- tests/test_automation/jenkins_rhea_cpu.sh
- tests/test_automation/jenkins_rhea_gpu.sh
This PR includes two commits that modify PR #478
- redefine the rm -rf ./* functionality for potentially increased safety
- bugfix where the last GPU test was defined incorrectly
> Ci updates bugfix

- src/QMCDrivers/tests/CMakeLists.txt
Exclude the test if MPI is not being used.
> Fix walker control tests for non-MPI build

- src/QMCWaveFunctions/tests/gen_bspline_jastrow.py
- src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp
Compare with a series of values obtained from a python script (gen_bspline_jastrow.py)
The script generates the comparsion using the B-splines built into Sympy.
The first and second derivatives are also tested now.
The testing is not as extensive as code generating the expression to compare against, but is better than what was there.
> Improve Bspline Jastrow test.

- manual/dmc.tex
Bugfix 
targetwalkers is total walker count, not a per node or thread count.
> Fix targetwalkers entry in dmc.tex

- tests/solids/bccH_2x2x2_ae/CMakeLists.txt
- tests/solids/bccH_3x3x3_ae/CMakeLists.txt
For the bccH_2x2x2_ae test, the check scripts are given relative to bccH_3x3x3_ae.
Separating the test files changed the relative layout of these directories. Change
it to match the new layout.
Also fix the test skipping message in bccH_3x3x3_ae to match the test.
> Modify relative path to derivative check scripts

- src/QMCDrivers/DMC/DMC_CUDA.cpp
- src/QMCDrivers/RMC/RMCSingleOMP.cpp
- src/QMCDrivers/VMC/VMCSingleOMP.cpp
- src/QMCDrivers/VMC/VMC_CUDA.cpp
- tests/solids/bccH_1x1x1_ae/CMakeLists.txt
- tests/solids/bccH_1x1x1_ae/qmc_cpu_limit_rmc.xml
- tests/solids/diamondC_1x1x1_pp/CMakeLists.txt
- tests/solids/diamondC_1x1x1_pp/qmc_cpu_limit_dmc.xml
- tests/solids/diamondC_1x1x1_pp/qmc_cpu_limit_vmc.xml
Add CPU time limit code to VMC CPU and CUDA, DMC CUDA, RMC.
Also add tests.  The time limit is set to 60 seconds, and the corresponding test configuration has a time-out set for 120 seconds.
The test names start with 'cpu_limit'.  They don't seem important enough to include with the 'short' tests.
Partially addresses #379
> Extend CPU limit to new drivers and add tests

- src/Particle/HDFWalkerInput_0_4.cpp
- src/Particle/HDFWalkerOutput.cpp
Hit some issue on Mira when using >= 32768 ranks.
walker offsets (an array) of all the nodes are recorded in the config.h5 for restart.
It was written by every node to the file even though the file is open in collective IO mode.
It is not a problem when the node count was small (<=16384). With a large node count, hdf5 library crashed inside.
Changes to the offset IO:
write: collectively by every node, each contribute its own offset. The last node contributes 2 (for the end)
read: since the next run can be with a different node count, offset now is loaded by the master node and broadcast to all the nodes.
performance:
Both IO operations are measured faster.
Restart miniapp has passed all the checks with 65536 ranks.
restart tests also pass.
Wait for a big run (in a few days) on Mira before …
> Change walker offset IO handling.

- src/QMCDrivers/DMC/WalkerControlMPI.cpp
- src/QMCDrivers/tests/test_walker_control.cpp
Fix bug introduced in PR #488.
FairOffset  is used by the caller of determineNewWalkerPopulation.
So FairOffset needs to be returned from determineNewWalkerPopulation
> Fix WalkerOffset bug due to code extraction change.

- tests/test_automation/nightly_ornl_oxygen.sh
Update oxygen nightly reference script to currently run version. GPU tests are re-enabled specifying Kepler GPU. Note that since oxygen is nearly full, a reevaluation of the test matrix is needed.
> Specify Kepler GPU in nightlies

- src/QMCHamiltonians/ECPComponentBuilder.cpp
- src/QMCHamiltonians/ECPComponentBuilder.h
- src/QMCHamiltonians/ECPotentialBuilder.cpp
Check "charge" in pseudopotential file against the particle description in the QMCPACK xml input.
Also abort when PP elementType mismatches particle description. Previously this case only prints an error without a stop.
closes #399
> Abort the code if PP charge doesn't match.

- src/Utilities/NewTimer.cpp
The code used 'printf' previously and would not redirect timer output appropriately with ensemble runs.
I started to try converting the formatting to C++ style, but gave up.   The existing formatting works fine. 
Now it prints to a temporary buffer which is then output to app_log.  Feels like a hack, but it works.
Partially addresses #87.  The name of the info file still needs to be fixed.
> Switch timer summary output to use app_log

- src/QMCHamiltonians/MomentumEstimator.cpp
Walker weight was missing in the n(k) estimator. Changed sign in the dot product for dot(k,dr), which makes n(k) correct with twist averaging.
> Fix n(k) for walker weight and twist averaging

- src/Estimators/accumulators.h
- src/Estimators/tests/test_accumulator.cpp
- src/config/stdlib/limits.h
This is an incomplete PR to address issue #540 that I need another pair of eyes on. The type_trait guards here should cause a build error when src/Estimators/tests/test_accumulator.cpp:30 is encountered, but everything still seems to build fine for me (except that this integer test still fails). 
Once I see the `accumulator_set<int> a1;` cause a failure, then I'll follow up with another commit to completely remove that test.
The following minimum example properly doesn't compile, so I can't tell what I'm doing wrong in this patch. Probably something silly.
```
#include <type_traits>  
template<typename T, typename = std::enable_if_t<std::is_floating_point<T>::value>>
struct A {       
void afoo(T t)  {   std::cout << "in afoo()" << '\n';  }
};
int main() {         
int i; 
double d; …
```
> type_trait guards for accumulator_set/iszero()

- config/build_olcf_eos.sh
- config/build_olcf_titan.sh
- config/build_ornl_oic.sh
The build scripts for titan, eos, and oic5 have been updated in the config folder. On titan the script compiles real and complex codes for AoS, SoA and GPU. On eos and oic5 the scripts compile real and complex codes for AoS and SoA.
> Modified configuration files for titan, eos, and oic5

- src/Numerics/tests/test_cartesian_tensor.cpp
Some compilers are having trouble with the single large test in test_cartesian_tensor.
Break it into multiple smaller test cases.
For hessian and third derivatives, the laplacian is not computed.  Remove the checks in those cases (it worked before because the previously computed laplacian values were still present)
> Break up the cartesian tensor test.

- src/Numerics/tests/test_cartesian_tensor.cpp
With optimization on, the compile time for this test gets large.  Too large to pay the cost on every compile.
Choose a very small subset of values for regular unit tests.
The larger set of tests is still present and can be activated when needed.
> Use subset of values for CartesianTensor unit test

- CMake/ClangCompilers.cmake
The -Wno-undefined-var-template option was added in clang 3.9.
Add a version check so this flag is not added for older versions of clang.
Clang 3.8 and earlier issue a warning about the flag which then causes the C++ 11 check to fail.
> Check clang version for undefined-var-template.

- CMake/macros.cmake
Also clears up the cmake deprecation warning about policy CMP0026 (issue #425)
(warning present since cmake 3.9). 
I don't know if anyone plans to use these functions, but they are currently unused.
> Removed unused CMake testing functions.

- nexus/library/hdfreader.py
- nexus/library/qmcpack_quantity_analyzers.py
This is a companion PR to #560 for Nexus handling of stat.h5 data with the value_squared field removed.  
To cover the full range of functionality runs were performed with v3.1.1 and #560 including density, spin density, energy density, and MPC estimators with and without twist averaging and analyzed with Nexus.
The updated code is backwards compatible with old data (value and value_squared present) and also works with new data (only value present).
> nexus: fix qmcpack analyzer to handle stat.h5 without value_squared

- src/ParticleIO/ParticleLayoutIO.cpp
Only atomic units are supported for now.  Abort with an error if different
units are given.
> Check units on lattice, if given.

- src/Utilities/ProgressReportEngine.cpp
- src/Utilities/ProgressReportEngine.h
Except for any error output, the default output stream for the ReportEngine is now the debug stream.
Partially addresses #35
> Sent output of ReportEngine to debug stream

- manual/input_overview.tex
- manual/output_overview.tex
Describe id and series attributes on the project tag.
Describe RNG intialization and the random tag.
This descriptions were put in the Input Overview chapter.  They don't quite seem to belong there, but they don't seem large enough to warrant a separate chapter.
Update description of checkpoint files from XML to HDF.
> Describe random number initialization in manual

- src/config.h.cmake.in
I believe that the way GNU's __builtin_assume_aligned() is being called is incorrect, and not having the intended effect (equivalent to the Intel version).
This should be the fix.
C.f. https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html
> fix bug in GNU __builtin_assume_alinged() usage

- src/QMCWaveFunctions/Fermion/SlaterDetOpt.cpp
- src/QMCWaveFunctions/Fermion/SlaterDetOpt.h
These files probably got merged after I did PooledMemory on my local branch.
Due to the existence of base class functions. Compilers didn't compilain.
So orbital optimization is broken by #521 
This PR basically corrects the call API and then the orbital rotation is correct
```
Start 166: short-H2-orb-opt-16-1
1/8 Test #166: short-H2-orb-opt-16-1 .................   Passed   29.71 sec
Start 167: short-H2-orb-opt-16-1-totenergy
2/8 Test #167: short-H2-orb-opt-16-1-totenergy .......   Passed    0.03 sec
Start 176: short-H4-orb-opt-16-1
3/8 Test #176: short-H4-orb-opt-16-1 .................   Passed   44.46 sec
Start 177: short-H4-orb-opt-16-1-totenergy
4/8 Test #177: short-H4-orb-opt-16-1-totenergy .......***Failed    0.02 sec
Start 178: short-H4-orb-opt-dmc-16-1
5/8 Test #178: …
```
> Fix orbital rotation failure due to PooledMemory.

- nexus/executables/qfit
Bug in the code caused reblocking lengths to be computed incorrectly.  Simple fix.
> nexus: fix qfit for variable length input data

- src/Particle/AsymmetricDistanceTableData.h
- src/Particle/ParticleSet.cpp
- src/Particle/SymmetricDistanceTableData.h
AoS distance tables must be computed when a walker is loaded (pre-v3.2 behaviour).
With this change, setActive does nothing for AoS.
This change also saves some computing when nsubsteps>1 with AoS.
> Fix J3 AoS when Nthread<Nwalker.

- src/QMCDrivers/DMC/WalkerControlMPI.cpp
- src/QMCDrivers/WalkerControlBase.cpp
- src/QMCDrivers/WalkerControlBase.h
This PR changes the memory handling of walker creating and annihilation.
This is the second PR for #609 
In the old algorithm,
1. sortWalkers makes decision of walker creating and annihilation. good_w and bad_w are assigned and good walkers have counters (ncopy_w) recording how many copies it should have. bad_w are freed.
2. copyWalkers first copy good walkers based on ncopy_w.
3. With MPI loadbalancing, walkers are sent from nodes with more walkers to nodes with less walkers. When walkers are transferred, their memory is freed.
In the new algorithm,
1. largely unchanged but the bad walkers are not freed.
2. First do the old step 3, send walkers from good_w, and decrease copy counter if a copy is sent. On the receiving side, bad_w are used to accept walkers from other nodes until bad_w is …
> Branching memory

- tests/molecules/H4_ae/CMakeLists.txt
- tests/molecules/H4_ae/H4.wfs_2.xml
This is updating the reference for the short-H4-orb-opt test, as requested in #602. An optimized Jastrow was added, since without it the variations between runs were always huge, and so difficult to get consistency.
> Update short-H4-orb-opt test

- src/Numerics/tests/test_e2iphi.cpp
Some elements of the array were uninitialized, and some machines the values would be NaN.
> Initialize array correctly in test_e2iphi.

- CMake/FindMKL.cmake
- config/build_alcf_mira.sh
- config/build_alcf_theta.sh
FindMKL was not behaving properly on my desktop.
The reason is the following
CMAKE_FLAGS only accept -DVAR:TYPE=VALUE form.
COMPILE_DEFINITIONS is the right one to use. It will invoke add_definitions and allows any flag.
https://cmake.org/cmake/help/v3.2/command/try_compile.html
I actually investigated the problem a year ago #11 but now I have a solution instead of a workaround.
The change has been checked on a linux workstation as well as Cray X40.
Hope this also resolves the LLNL pain.
> Fix FindMKL

- manual/dmc.tex
- manual/running.tex
- src/Particle/Walker.h
- src/QMCDrivers/DMC/WalkerControlMPI.cpp
- src/QMCDrivers/DMC/WalkerControlMPI.h
- src/QMCDrivers/WalkerControlBase.cpp
- src/QMCDrivers/WalkerControlBase.h
- src/qmc_common.cpp
- src/qmc_common.h
This PR introduce two optimization in the walker send/recv. This is the third PR for #609.
1, multiple copy of one walker is sent in one shot. This reduces the amount of data transferred.
2, Using non-blocking send/recv to avoid blocking send/recv serialization. Turned on by default.
Both algorithms will be transferred to reconfiguration in the near future.
Command line option async_swap has been removed as well as the old implementation.
input parameter use_nonblocking is introduced to toggle on/off non-blocking send/recv.
manual has been updated.
> Nonblocking send/recv

- src/Numerics/CUDA/cuda_inverse.cu
- src/Numerics/CUDA/cuda_inverse.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantCUDA.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantCUDA.h
I hit this issue when doing large scale runs on Titan.
Without pivoting, the inversion fails at certain matrices (not singular) and gives inf (not NaN). The failure occurs more frequently when system gets large and orbital value varies more.
With pivoting, the same matrix can be inverted successfully.
A check has been added after the inversion call and the status of every matrix is checked.
Once the review pass, I can rebase this PR to have the history clean.
> Calling cublas inversion with pivot.

- src/Particle/DistanceTableData.h
- src/Particle/SymmetricDistanceTableData.h
- src/QMCHamiltonians/MomentumEstimator.cpp
- src/QMCHamiltonians/MomentumEstimator.h
- src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/OneBodyJastrowOrbital.h
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp
The computation inside momentum estimator has been optimized by rearranging the calculation and reusing data. This is effective for both AoS and SoA.
The evaluateRatiosAlltoOne of J1,J2,J3 with SoA has also been optimized by using specialized implementation.
The test case I used is VO2 48 atom cell. 400 electron. On titan, 2 MPI per node and 8 thread per MPI.
When using 128 samples, I saw huge speed up.
No estimator, 1.564921 sec
With 128 samples, 28.948585 sec
Optimized code with 128 samples, 4.872676 sec.
@kylanpaa Please verify that
> Opt momentum estimator

- manual/dmc.tex
- src/QMCDrivers/WalkerControlBase.cpp
For #631 
The default maxCopy=2 doesn't hit the bug. But I think it is better to have code on the safe side.
In this PR, I just disabled the nonblocking.
if disabling only maxCopy>2 + nonblocking is preferred, I can change this PR.
> Limit maxCopy due to nonblocking send/recv bug

- src/Particle/Walker.h
- src/QMCDrivers/DMC/WalkerControlMPI.cpp
- src/QMCDrivers/WalkerControlBase.cpp
fixes #631
The number of copies is communicated ahead of walkers via blocking send/recv.
The nonblocking receiving no more needs queues.
The performance is slightly better than the previous scheme.
I tried maxcopy=4 but noticed neither bias in the statistics nor improvement in equilibration.
> Fix nonblocking maxcopy

- CMakeLists.txt
- manual/external_tools.tex
- manual/qmcpack_manual.tex
- src/Utilities/NewTimer.h
- src/config.h.cmake.in
Incorporates the suggested changes from #629 
- USE_VTUNE_API generically checks that the include and library files can be found
- USE_VTUNE_TASKS adds the timers-as-tasks code
- adds a manual chapter on 'External Tools'
> Add VTune API support

- CMakeLists.txt
- src/CMakeLists.txt
- src/config.h.cmake.in
- src/qmcpack_version.h
For builds that do not come from a git repository, the git-rev.h file is empty.  Change the code so git-rev.h and git-rev-tmp.h are not referenced, and are not even created.
Hopefully this can address a Spack issue where sometimes either file is not found.
> Skip git-rev files for non-git builds.

- src/QMCWaveFunctions/Jastrow/BsplineFunctor3D.h
- src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/PolynomialFunctor3D.h
- tests/solids/monoO_1x1x1_pp/CMakeLists.txt
- tests/solids/monoO_1x1x1_pp/qmc_j3_long.in.xml
- tests/solids/monoO_1x1x1_pp/qmc_j3_short.in.xml
The new algorithm uses batched computation and optimizes the memory access.
Gain significant speed-up when a large cutoff is used and ion particles are grouped.
Short and long integration tests based on monoO are added requested by #573, no new hdf5 needed.
> optimized JeeI

- src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
The loop for reading CI coefficients in a detlist element skips processing if the coefficient is less than the cutoff value.  Need to advance to the next element in this case.
> Fix infinite loop when reading CI coeffs

- src/Lattice/CrystalLattice.cpp
- src/Lattice/CrystalLattice.h
- src/QMCHamiltonians/MomentumEstimator.cpp
- src/QMCHamiltonians/MomentumEstimator.h
1. The compQ was removed: it can be post-processed rather straightforwardly from n(k).
2. Modified the input options for n(k):
(a) kmax: desired k-points reside within the sphere of radius kmax
(b) kmax0, kmax1, kmax2: maximum k-values for a parallelepiped in which the k-points are located
(c) both (a) and (b): includes k-points within the sphere and those of the parallelepiped outside the sphere
(d) default behaviour (i.e., not defining any kmax values): uses (a) with kmax=2.0 x k_F, where k_F is the Fermi momentum of polarized non-interacting electron gas at corresponding electron density
> Modified the k-grid for the momentum estimator and removed compQ

- tests/molecules/LiH_dimer_ae_gms/CMakeLists.txt
- tests/molecules/LiH_dimer_ae_pyscf/CMakeLists.txt
- tests/molecules/LiH_dimer_ae_qp/CMakeLists.txt
The reference numbers changed by #656 are causing tests failing.
Put back the Gamess reference for gms, qp, pyscf since it is the same calculation and the values of total energy match.
> Put back the Gamess reference for LiH_dimer_ae_*.

- src/Utilities/tests/test_parser.cpp
Initializing vectors and objects with a brace initializer list makes the input/output specification much more compact.
Also use the range-based for-loop syntax to simplified the 'for' expression.
The added function in #670 could really use a unit test in here.
> Update parser test to use C++11

- tests/coverage/read_gcov.py
Occasionally GCC produces negative coverage counts (should be impossible!), and this
causes problems wih the coverage scripts.  The processing stops at the point the
file with the negative count is found.  Which may be why files seem to be missing from
the coverage reports.
Fix is to detect negative counts when reading the file and mark them as uncovered (all the
cases I found with negative counts should have been uncovered).
> Handle the negative count coverage case.

- manual/installation.tex
- src/CMakeLists.txt
While fixing #695 This leaves OSX able to get git rev and I assume other BSD's as well. It works with  cmake 2.8.10.2 on titan.
> fix for BSD's sed

- README.md
- manual/introduction.tex
Update README.md and manual to explicitly state that we use the same license for contributions as current QMCPACK.
> Clarify license for contributions

- CMake/FindMKL.cmake
- CMakeLists.txt
ENABLE_MKL is more general now.
It allows disabling MKL when using Intel compilers.
> Rename ENABLE_OUTSIDE_MKL to ENABLE_MKL.

- CMakeLists.txt
C++11 option verification was not very robust due to the contamination from library detection.
So move it before any libraries.
> Move C++11 verification more ahead for robustness

- src/QMCDrivers/CloneManager.cpp
- src/QMCDrivers/CloneManager.h
- src/QMCDrivers/DMC/DMCOMP.cpp
- src/QMCDrivers/VMC/VMCSingleOMP.cpp
- src/QMCDrivers/tests/CMakeLists.txt
- src/QMCDrivers/tests/diffuse.py
- src/QMCDrivers/tests/test_clone_manager.cpp
- src/QMCDrivers/tests/test_dmc_omp.cpp
- src/QMCDrivers/tests/test_fixed_node_branch.cpp
- src/QMCDrivers/tests/test_vmc_omp.cpp
- src/QMCWaveFunctions/ConstantOrbital.h
For ConstantOrbital.h - added one 'override', but then clang complained about all the
other methods without it.  Using 'override' pointed out a virtual method that was no
longer overriding anything - remove it.
Add diffuse.py for computing unit test values (the values were slightly different than
the existing ones in test_vmc.cpp - update those to match.)
(This follows a general trend of putting the generic derivation/explanantion in
qmc_algorithms, and putting the particular python script for computing the unit test
values along side the unit tests.)
Starting point for tests for SimpleFixedNodeBranch, QMCUpdateBase, CloneManager.  The classes are
set up, but there are no tests there yet.
Added a constructor for initializing CloneManager to a number of threads specified by the test,
not …
> Add unit test for VMCSingleOMP

- CMakeLists.txt
Current [BGQ](https://cdash.qmcpack.org/CDash/viewConfigure.php?buildid=20409) builds are failing.
Add quotation marks around CMAKE_BUILD_TYPE.
Other changes are just putting all the commands in upper case as the rest of file.
> Fix CMake when CMAKE_BUILD_TYPE=None.

- src/Estimators/tests/CMakeLists.txt
Happens in certain scenario.
Adjust the linking order to qmcham before qmcwfs because qmcham depends on qmcwfs.
> Fix unit test linking issue

- src/QMCApp/QMCMain.cpp
Add final DOI of QMCPACK citation paper and preliminary citation info. Copyright line indented to match centering.
```
=====================================================
QMCPACK 3.4.0
(c) Copyright 2003-  QMCPACK developers
Please cite:
J. Kim et al. J. Phys. Cond. Mat. (2018)
https://doi.org/10.1088/1361-648X/aab9c3
=====================================================
```
> Add citation data to header

- manual/qmcpack_papers.bib
These are printed in the order that they appear in the qmcpack_papers.bib file.
Fixed two missing years.  Use of JabRef recommended for further cleanup of this file.
I verified that the same total number of papers was printed before/after this change.
> Sort QMCPACK publications by date

- src/QMCDrivers/DMC/WalkerControlMPI.cpp
- src/QMCDrivers/WalkerControlBase.cpp
- src/QMCDrivers/WalkerControlBase.h
Currently the code aborts if there are no good walkers left on a node after branching within a node.
In a multi-rank run, the situation of no good walkers should be allowed to proceed since new walkers will be received from other ranks. This happens rarely in production stage but happens more frequently during equilibration.
In this PR, the algorithm changes into
1. sortWalkers marks good and bad walkers.
2. allreduce collects the number of good walkers + copies on every rank.
3. applyNmaxNmin avoids too large or too small global population.
4. swapWalkersSimple makes a decision of load balancing and send/recv walkers.
5. copyWalkers generates copies of good walkers.
The step 3 is new. It checks at least one good walker per node based on the global population.
In the old code, max and min …
> Improve per node walker count handling in multi-rank runs after branching

- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.h
- src/Sandbox/diff_j1.cpp
- src/Sandbox/diff_wfs.cpp
- src/Sandbox/miniqmc.cpp
- src/simd/algorithm.hpp
The SoA J1 was written not using the memory pool while J2 and JeeI do.
When a walker with its memory pool loaded, Det and J2 JeeI have the up-to-date value but J1 doesn't.
This is not a problem after all the electrons are proposed to move once but not from the beginning.
This potential risk is secured by checking the ParticleSet.Ready4Measure flag.
However, the flag is delicate and needs a careful maintaining.
This PR changes the algorithm to be aligned as J2 and JeeI. No more need to recompute since it is loaded from the memory pool and the needed size is small, order Nelec.
The state flag ParticleSet.Ready4Measure is also removed.
This PR also fixed the missing names of ParticleSet objects in Sandbox apps.
> Adjust one body Jastrow SoA algorithm

- manual/afqmc.tex
- manual/multideterminants.tex
- manual/qmcpack_papers.bib
Update QMCPACK bibliography and fix internal cross-referencing.
The manual now builds with no undefined labels.
> Bibliography and cross referencing improvements

- src/QMCDrivers/DMC/DMCUpdateAll.cpp
- tests/solids/diamondC_1x1x1_pp/CMakeLists.txt
- tests/solids/diamondC_1x1x1_pp/qmc_long-meshf.in.xml
- tests/solids/diamondC_1x1x1_pp/qmc_long.in.xml
- tests/solids/diamondC_1x1x1_pp/qmc_long_kspace.in.xml
- tests/solids/diamondC_1x1x1_pp/qmc_short-meshf.in.xml
- tests/solids/diamondC_1x1x1_pp/qmc_short.in.xml
- tests/solids/diamondC_1x1x1_pp/qmc_short_hybridrep_batched.in.xml
- tests/solids/diamondC_1x1x1_pp/qmc_short_kspace.in.xml
- tests/solids/diamondC_1x1x1_pp/qmc_short_kspace_4_4.in.xml
- tests/solids/diamondC_1x1x1_pp/qmc_short_vmc_dmc_allp.in.xml
See more details in #753 for the bug and use that issue to track progress.
This PR adds an integration test for VMC and DMC with all particle moves on diamondC 1x1x1.
Reference values of VMC and DMC are taken from pbyp moves.
This PR largely rewrite the DMC driver routine makes the DMC tests passing but VMC part remains failing. PR #423 also touched the VMC driver but I have no idea if the VMC was broken even before.
> Fix all-particle move DMC driver

- src/Particle/ParticleSet.cpp
- src/QMCDrivers/DMC/DMCUpdateAll.cpp
- src/QMCDrivers/VMC/VMCUpdateAll.cpp
- src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/OneBodyJastrowOrbital.h
- src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp
- tests/solids/diamondC_1x1x1_pp/CMakeLists.txt
- tests/solids/diamondC_1x1x1_pp/qmc_long_vmc_dmc_allp.in.xml
- tests/solids/diamondC_1x1x1_pp/qmc_short_vmc_dmc_allp.in.xml
Some left over fix for #754 and #755.
allp DMC Tmove is fixed in the driver with LogValue fix in Jastrow factors.
LogValue needs to be updated by acceptMove such that Psi.getLogPsi() returns the correct value at any time.  Unit tests are updated.
allp VMC failing in SoA is fixed by adding the missing neighbour list construction needed by NLPP. This is not exposed by bccH tests.
The allp VMC tests on diamond had too large time step. This is also fixed and they pass stably now.
> Fixes for all particle move VMC/DMC drivers

- src/Particle/AsymmetricDistanceTableData.h
- src/Particle/DistanceTableData.h
- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/Particle/SoaDistanceTableAA.h
- src/Particle/SoaDistanceTableAB.h
- src/Particle/SoaDistanceTableBA.h
- src/Particle/SymmetricDistanceTableData.h
- src/Particle/tests/test_particle.cpp
- src/QMCDrivers/DMC/DMCUpdateAll.cpp
- src/QMCDrivers/QMCCostFunctionOMP.cpp
- src/QMCDrivers/VMC/VMCUpdateAll.cpp
In the SoA code, electron-ion table not only carries the distances but also a neighbour list for NLPP evaluation. In many cases, when all the distance tables are evaluated from scratch, the neighbour lists need to be updated but only possible through calling donePbyP which is supposed to be used by PbyP drivers only.
This PR changes the default behaviour that the neighbour list is updated automatically when the full table is recomputed. So in most places, the calls to donePbyP can be removed and drivers not tested for SoA may work out of the box.
The only performance penalty I can think of is in optimization when not using NLPP in the correlated sampling. The penalty should be very very small.
> Clean up the use of donePbyP in drivers

- tests/molecules/H2O_dimer_sep_pp/CMakeLists.txt
It was my mistake to mark the tests failing for mixed precision.
> Enable Tmove tests with mixed precision.

- src/QMCWaveFunctions/EinsplineSetBuilder.h
- src/QMCWaveFunctions/SplineAdoptorReaderP.h
- src/QMCWaveFunctions/SplineHybridAdoptorReaderP.h
- src/QMCWaveFunctions/einspline_helper.hpp
Add the orbital norm check requested by #761.
It many be able to catch #675. 
I ran all the short tests and they are fine.
> Add orbital norm check in SplineAdoptor Readers

- src/Message/Communicate.cpp
- src/QMCApp/qmcapp.cpp
Move qmc_common.initialize out of Communicate and into QMCApp.
This simplifies the MPI-related code a little bit.
> Move init in qmc_common to QMCApp

- external_codes/quantum_espresso/README
- external_codes/quantum_espresso/add_pw2qmcpack_to_qe-6.2.1.diff
- manual/installation.tex
- src/QMCWaveFunctions/SplineAdoptorReaderP.h
- src/QMCWaveFunctions/SplineHybridAdoptorReaderP.h
Add orbital norm check in pw2qmcpack of the qe 6.2.1 patch.
Update orbital norm check error message in QMCPACK.
Closes #763
Update manual section about the installation of pw2qmcpack.
Closes #681
> Update pw2qmcpack + manual

- CMake/ctest_script.cmake
- tests/test_automation/nightly_anl_bora.sh
Currently if a hostname is not recognized, the nightly tests script will abort.
Every time we add a machine, the script needs to be updated. This is not good.
This PR allows using a generic setting and pass extra parameters via environment variables or arguments.
The script for bora.alcf.anl.gov is an example.
> Allow unlisted testbeds

- nexus/executables/qmca
Fix a small bug introduced in #600 relating to the -a option.
> nexus: fix qmca prefix list when performing twist averaging

- nexus/executables/qmca
Trace plots were often too zoomed out by default in qmca.  A visual range of +/- 2 sigma is restored as the default.
> nexus: fix default trace plot range in qmca

- nexus/executables/qmca
Add new command line option to qmca (-j).  Used to join/concatenate multiple series as if they appeared as a single file originally.  Equilibrated data are removed prior to join.
As a preparatory step, also make twist averaged calculation more precise.  Specifically, twist average the raw file data first, then perform analysis on the twist averaged data.
> nexus: add ability to join subsequent series as a single data source in qmca

- src/QMCHamiltonians/ECPComponentBuilder.2.cpp
Save the AtomicNumber read by the NLPP casino format parser for validation
Fixes  #865
> Fix the NLPP casino format parser

- src/QMCWaveFunctions/BsplineFactory/HybridAdoptorBase.h
- src/QMCWaveFunctions/BsplineFactory/HybridCplxAdoptor.h
- src/QMCWaveFunctions/BsplineFactory/HybridRealAdoptor.h
- src/QMCWaveFunctions/BsplineFactory/SplineC2CAdoptor.h
- src/QMCWaveFunctions/BsplineFactory/SplineC2RAdoptor.h
- src/QMCWaveFunctions/BsplineFactory/SplineR2RAdoptor.h
- src/QMCWaveFunctions/EinsplineSetBuilder.h
- src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp
- src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp
- src/QMCWaveFunctions/SplineAdoptorReaderP.h
- src/QMCWaveFunctions/SplineHybridAdoptorReaderP.h
- src/spline/einspline_impl.hpp
- src/spline/einspline_util.hpp
When I first developed the reader for constructing orbitals in the hybrid orbital representation, I copied the whole reader for regular splines and add extra stuff. Overtime, I figured out what are the necessary pieces for the extra work for hybrid. So the largely duplicated lines can be removed.
This PR defines the extra work as virtual functions implemented in the reader for hybrid.
The old reader also has diverged code paths for serial and parallel. The serial is added to avoid memory issue but only works for using 1 MPI tasks. Now I do in-place construction using a single implementation and there is no scratch memory issue.
> Merge SplineAdoptorReaderP and SplineHybridAdoptorReaderP

- nexus/library/fileio.py
- nexus/library/periodic_table.py
- nexus/library/vasp_input.py
This PR draws POSCAR file I/O from deeper in the Nexus tree up to the more independent fileio.py module level.  CHGCAR I/O added to enable, e.g. conversion from XCrysDen xsf files to CHGCAR.  
Currently the POSCAR I/O functionality is duplicative w.r.t. portions within structure.py and vasp_input.py.  When tests for these code sections are in place later on, the duplicated code portions in these files will be replaced with usage of the PoscarFile class in fileio.py
> Nexus: enable POSCAR and CHGCAR file I/O

- nexus/library/gamess_input.py
This is a very simple bugfix for a problem reported by Cody Melton.  Originally the GIarray constructor was called improperly.
> nexus: fix array initialization in GAMESS input class

- nexus/executables/ntest
- nexus/library/pwscf_input.py
- nexus/library/qmcpack_input.py
- nexus/library/simulation.py
- nexus/library/sqd_input.py
- nexus/library/structure.py
- nexus/library/vasp_input.py
Improve user example tests in two ways: 
1) Split the user example tests into many, i.e. one for each user example test directory rather than a single monolithic test encompassing all of them. 
2) Improve input file fidelity checks in the case of periodic boundary conditions.  Due to rounding errors, an atom at position 0 may be assigned a position at either 0 or L, which are equivalent in PBC but not w.r.t. plain float comparison.  Check whether a comparison of reference and generated input files is failing on the basis of different atomic positions alone and whether the positions differ w.r.t. PBC or not.
> Nexus: improve user example tests

- nexus/library/qmcpack_converters.py
Nexus originally expected convert4qmc to produce a wfnoj.xml file.  This file is only produced if the -nojastrow flag is provided and so workflows not involving this flag will not complete successfully, since convert4qmc is erroneously assumed to have failed (no wfnoj.xml file present).  
This PR fixes the issue by judging convert4qmc completion as successful if either wfj.xml or wfnoj.xml are produced.  Either file is now accepted as wavefunction input to QMCPACK.
Issue reported by Chandler Bennett.
> Nexus: fix convert4qmc workflow in the case -nojastrow is not provided

- src/Numerics/tests/CMakeLists.txt
- src/Numerics/tests/test_transform.cpp
A simple test for converting a functor to a grid, which is used in representing atomic orbitals.
> Add test for transform to grid.

- tests/converter/test_aldet1/gold.wfnoj.xml
- tests/converter/test_aldet5/cmd_args.txt
In PR #892, the -optDetCoeffs flag was added to the converter and the default for optimizing determinant coefficients changed to False.
Update the tests to match.  For aldet1, change the gold file to match the default.  For aldet5, add the flag.
> Update converter tests with optDefCoeffs flag

- CMakeLists.txt
- config/build_olcf_titan.sh
- manual/installation.tex
Installation guide updated to work, build_olcf_titan.sh fixed
cmake no longer needs to be run twice on titan
> Titan requires cmake3 doesn't need 2 cmakes

- src/QMCWaveFunctions/tests/test_MO.cpp
Add a call to ions.update to ensure that RSoA.copyIn get called.
It appears that ions must be updated before elec (because the call to elec.update uses
data from ions).
With this change, the run has no uninitialized value errors from valgrind (w/o the change, there are some uninit values errors)
The test failure is here.  I could not reproduce it.  Fix is a guess.
https://cdash.qmcpack.org/CDash/testDetails.php?test=2544595&build=24654
> Attempt fix for test_MO with Intel SoA build

- src/QMCWaveFunctions/tests/CMakeLists.txt
Address the SOA build failures. closes #910
> Skip cusp correction test in SOA build

- src/QMCWaveFunctions/MolecularOrbitals/AtomicBasisBuilder.h
- tests/molecules/FeCO6_b3lyp_pyscf/CMakeLists.txt
- tests/molecules/LiH_dimer_ae_gms/CMakeLists.txt
- tests/molecules/LiH_dimer_ae_pyscf/CMakeLists.txt
- tests/molecules/LiH_dimer_ae_qp/CMakeLists.txt
pyscf uses spherical tensor and only SoA can run.
> Set LCAO pyscf tests based on SOA_SUCCESS

- manual/jastrow_one_body_pade.tex
- src/QMCWaveFunctions/Jastrow/PadeFunctors.h
Now pade2 no more accept parameter but var/Var.
As @jtkrogel pointed out that 'parameter' should only accept a name/value pair and will be parsed by designated parser(validation will be added in the future).
close #413
> Align pade2 input tag as pade

- external_codes/quantum_espresso/README
- external_codes/quantum_espresso/add_pw2qmcpack_to_qe-6.3.diff
- external_codes/quantum_espresso/download_and_patch_qe6.3.sh
- manual/installation.tex
The 5.3 patch is kept since the 6.2.1 patch has not been released in the past.
Compared to 6.2.1 patch, 6.3 patch adds the atomicnumber tag in the ion section of ptcl.xml file generated by pw2qmcpack to avoid NLPP satinity check failure.
Currently pw2qmcpack doesn't provide the input blocks for QMCPACK and hopefully this will be added in the near future.
> Add pw2qmcpack patch for QE 6.3

- src/Configuration.h
- src/Particle/Walker.h
- src/QMCDrivers/CorrelatedSampling/CSVMCUpdateAll.cpp
- src/QMCDrivers/WaveFunctionTester.cpp
- src/QMCHamiltonians/PulayForce.cpp
- src/QMCHamiltonians/StressPBC.cpp
- src/QMCWaveFunctions/AGPDeterminant.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.cpp
- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminant.cpp
- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantWithBackflow.cpp
- src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.cpp
- src/QMCWaveFunctions/PlaneWave/PWOrbitalBuilder.cpp
When I first added the type, the name was not chosen consistently.
ParticleXXX_t refers all the particles.
SingleParticleValueXXX_t refers one particle.
> Consistent name SingleParticleXXX

- src/Particle/AsymmetricDistanceTableData.h
- src/Particle/DistanceTableAA.cpp
- src/Particle/DistanceTableAB.cpp
- src/Particle/DistanceTableData.h
- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/Particle/SoaDistanceTableAA.h
- src/Particle/SoaDistanceTableBA.h
- src/Particle/SymmetricDistanceTableData.h
- src/QMCDrivers/tests/test_dmc.cpp
- src/QMCDrivers/tests/test_vmc.cpp
- src/QMCHamiltonians/CoulombPBCAB.cpp
- src/QMCHamiltonians/ECPotentialBuilder.cpp
- src/QMCHamiltonians/NonLocalECPotential.cpp
- src/Sandbox/FakeWaveFunction.h
- src/Sandbox/diff_distancetables.cpp
- src/Sandbox/diff_j1.cpp
- src/Sandbox/diff_wfs.cpp
- src/Sandbox/miniqmc.cpp
The neighbour lists carried by distance tables are removed. The only consumer, NLPP evaluation, is updated with an interchange of ion and electron loop.
The neighbour list is supposed to be global. For example, the neighbour list for the electrons near an ion within a cutoff can be used for J1, J3, NLPP, Coulomb. However, due to the need of different cutoffs, the neighbour list cutoff needs to be chosen the maximal value and then filtering is applied again per use. So this actually becomes not efficient. Due to the need of extra memory and consistency maintaining, the neighbour list becomes unfavourable. Thus removed.
> Remove neighbourlist in distance tables

- src/QMCHamiltonians/ForceBase.cpp
Ion-Ion force computation should be done in the force estimators, and not in ForceBase.  In addition to not handling boundary conditions appropriately, this piece of code also causes QMCPACK to segfault since the ion-ion distance table has transitioned to SoA format.
> Eliminate ion-ion force computation from ForceBase

- src/LongRange/LRHandlerTemp.h
- src/QMCHamiltonians/CoulombPBCAB.cpp
The Esler style long-range breakup has the wrong sign for LRHandlerTemp::evaluateLR(r), but the error is compensated by an incorrect sign when computing the LocalECP in CoulombPBCAB.cpp.  LocalECP energy now correct when using Ewald or Esler breakups.
> Fix incorrect sign in LR Breakup

- utils/check_stats.py
Add a new standalone script (check_stats.py) to be used to implement estimator tests in the ctest framework.  The script is meant to be general purpose for stat.h5 files much in the same way check_scalars.py is for scalar.dat files.
To facilitate testing, new scalar-like streams of data are generated from the underlying estimator data: 1) full sums of estimator data per block, 2) a user specified number of partial sums of estimator data per block.  The statistical mean and error bar is then computed for each scalar-like stream.
Multiple types of tests are performed:   1) Check that full sum means are within nsigma of reference means, 2) Similar checks for partial sum means, but with nsigma correctly adjusted to account for the number of partial sums so that the overall test of partial …
> Add check_stats script for testing estimators

- src/QMCHamiltonians/DensityMatrices1B.cpp
This PR fixes the manifesting problem with the 1RDM, namely that zeros are populated in the stat.h5 file output.
The overarching issue is a currently unresolved bug in the flow of Traces logic, as it applies to the special case of Traces being used to stream e.g. energetic information to estimators.  Even when the streaming of data is requested, this currently does not happen.
Since this data is only strictly necessary for the energy density matrix (1REDM), a workaround is put in place to allow computation of the 1RDM when the 1REDM is turned off via the input file.
Following this PR, the 1RDM works as originally implemented and is appropriately diagonal for a system w/o a Jastrow (tested explicitly for a small diamond cell).  Further correctness tests and efficiency improvements remain …
> Workaround for 1RDM zero problem

- nexus/library/numerics.py
- nexus/library/qmcpack_quantity_analyzers.py
Density matrix analyzer needed to be updated to account for the removal of value_squared from the stat.h5 output.  Also fixed the issuance of several warnings related to complex to real conversion (computations all kept in complex now, except for the matrix trace which must be real).
Example usage:
```
from qmcpack_analyzer import QmcpackAnalyzer
qm = QmcpackAnalyzer(‘qmc.in.xml’,analyze=True)
nm = qa.qmc[0].DensityMatrices.number_matrix
print nm
```
Data structure of "nm" printed above:
```
B: number of statistical blocks
M: number of orbitals/states in basis
S: number of significant states (determined by occupation number)
occ_tol default : 1e-3
coup_tol default: 1e-4
stat_tol default: 2.0
nm                - number (a.k.a. density) matrix
u                 - up electron matrix
data …
```
> Nexus: fix density matrix analyzer

- CMake/ctest_script.cmake
- tests/test_automation/nightly_anl_bora.sh
- tests/test_automation/nightly_anl_cetus.sub
expose more environment variables
N_PROCS_BUILD to restrict the number of processors during compilation
N_CONCURRENT_TESTS to restrict the number of tests running simultaneously.
TEST_SITE_NAME, name to be shown on the site column on cdash.
In principle, all the per machine configurations are no more needed.
Using the following in the job script.
CC, CXX, N_PROCS, N_PROCS_BUILD, N_CONCURRENT_TESTS, TEST_SITE_NAME
There was a bug in the script
`IF ( DEFINED $ENV{N_PROCS_BUILD} )`
If N_PROCS_BUILD is defined a value 18, it is checking if 18 is defined.
should be
`IF ( DEFINED ENV{N_PROCS_BUILD} )`
> Fix ctest script

- src/QMCWaveFunctions/MolecularOrbitals/CuspCorr.cpp
- src/QMCWaveFunctions/MolecularOrbitals/CuspCorr.h
- src/QMCWaveFunctions/MolecularOrbitals/LCOrbitalSetWithCorrection.cpp
- src/QMCWaveFunctions/MolecularOrbitals/LCOrbitalSetWithCorrection.h
- src/QMCWaveFunctions/tests/test_cusp_corr.cpp
Using a structure rather than an array should make the code a little easier to understand.
Also add some headers to describe the columns in the newOrbs* output files.
> Store cusp correction parameters in structure.

- src/QMCWaveFunctions/TrialWaveFunction.cpp
TrialWavefunction::ratioGrad should update PhaseDiff after computation of Psi(r')/Psi(r), and not PhaseValue.  This is also corroborated by use of PhaseDiff in TrialWavefunction::ratio().
> Incorrect handling of phase info in ratioGrad

- src/QMCWaveFunctions/MolecularOrbitals/NGOBuilder.cpp
- src/QMCWaveFunctions/MolecularOrbitals/NGOBuilder.h
- src/QMCWaveFunctions/lcao/RadialOrbitalSetBuilder.h
This commit affects the molecular code - both SoA and AoS versions.
The SoA code always uses quintic splines.  Remove the use of cubic splines in the AoS code.
Partially addresses #1051
> Remove unused references to cubic splines.

- src/config/stdlib/math.h
- src/spline2/MultiBspline.hpp
round is in the C++11 standard.
sincos/sincosf is protected for Mac OS.
std::modf handles both float and double.
> Tidy up math functions

- src/QMCWaveFunctions/tests/test_einset.cpp
The value winds up out of tolerance in newer clang compilers.  The new value comes from clang 6 in debug mode.
Debug and release values from gcc 4.8.4 are also closer to this value.
> Update value in test_einset.cpp

- nexus/library/pwscf.py
Problem reported by Kayahan Saritas and reproduced by @kylanpaa.
When running QE nscf in a different directory than scf, Nexus uses rsync to copy the scf output directory to the nscf location so that the original scf files remain untouched (useful when performing multiple nscf from a single scf).
In this case, if Nexus is interrupted by the user after submitting the nscf job, upon rewaking it tries to rsync a second time which can overwrite the running or completed nscf output with the old scf files.
This PR fixes the problem by writing a single record file into the nscf output directory upon successful completion of rsync and only performing an rsync if this file is not present.
Additionally, compression (-z) is turned off, which results in significantly faster file transfer.
> Nexus: fix nscf rsync overwrite problem resulting from interrupt

- nexus/library/simulation.py
Problem reported by Allison Dzubak.
The skip_submit flag allows the user to write files (including the flow of dependency information) but avert automatic queue submission.  This allows the user to inspect the files before submission and also to opt to submit by hand, if desired.
The manifesting problem was that if skip_submit is used, a Nexus script is closed, and then skip_submit is turned off prior to rerunning the script, occasionally Nexus will not submit the job contrary to expectations.
This PR attempts to fix the bug by never saving state if skip_submit is used.  Additionally, the changes made here allow Nexus to shutdown cleanly (by marking the skipped simulation and its dependents as blocked) when skip_submit is used since this used to lead to monitoring a job that never was …
> Nexus: fix skip submit monitoring hang

- nexus/executables/ntest
Addresses #1028 (hopefully).
The ntest script was not originally designed to handle simultaneous execution of multiple instances of itself.  To avoid conflict with prior executions, ntest used to remove the prior execution directory and start from scratch.  This is fine for sequential executions, but not concurrent ones.
This PR attempts to fix the problem by no longer removing the prior execution directory in its entirety, but only piecemeal as a particular test enters a sub-directory to run.  I've verified that this approach works both when running all tests sequentially multiple times and when running all tests concurrently.
> Nexus: attempt to make ntest thread safe

- nexus/executables/qmca
This PR allows control over the floating point format used by qmca to report statistical results.  A new command line flag (--fp) accepts any Python floating point format string.
Original output:
```
>qmca -e 20 -q 'ekp' *g000*scalar*
vmc.g000  series 0 
LocalEnergy           =         -629.7563 +/-           0.0052 
Kinetic               =           256.394 +/-            0.042 
LocalPotential        =          -886.150 +/-            0.042 
```
Example output with 16.8f:
```
>qmca -e 20 -q 'ekp' --fp 16.8f *g000*scalar*
vmc.g000  series 0 
LocalEnergy           =     -629.75631828 +/-       0.00516018 
Kinetic               =      256.39372968 +/-       0.04156487 
LocalPotential        =     -886.15004796 +/-       0.04212690 
```
Example output with 8.6e:
```
>qmca -e 20 -q 'ekp' --fp …
```
> Nexus: enable control over qmca floating point output

- nexus/library/fileio.py
- nexus/library/qmcpack_quantity_analyzers.py
The xsf read and write was changed to Fortran order for data grids, and thus, the transpose options used for manipulation of electron densities are not needed anymore.
> Modified Nexus xsf read and write

- nexus/library/qmcpack_input.py
This is a quick fix for reads of misformatted estimators.  The code now aborts with an error message instead of crashing if a user has written (and tries to read) an input file with unnamed/untyped estimators.
> Nexus: error trap reads of misformatted estimators

- CMakeLists.txt
- src/QMCApp/QMCMain.cpp
ENABLE_SOA was not cached in the past but needed to be captured by the testing system for parsing flags.
Now it also print a message in the header indicating SoA optimization is enabled.
> Cache ENABLE_SOA in CMakeLists and print in header

- src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h
"using WaveFunctionComponent::ratio;" was added twice and caught by clang.
> Remove the redeclaration of ratio.

- nexus/library/quantum_package.py
- nexus/library/quantum_package_input.py
- nexus/library/simulation.py
Add input variable "converge_dets" to enable auto restart of selected CI runs that have not reached the target number of determinants.
This PR follows (depends on) #1112.
> Nexus: enable QM Package restart for selected CI

- nexus/library/quantum_package.py
- nexus/library/quantum_package_input.py
This PR depends on #1113.
SCF runs are now checked for successful completion.  In the event that failure is detected, execution of all dependent runs is blocked.
Also add a small fix for writes of floating point values.
> Nexus: add failure check to QM Package SCF runs

- src/QMCWaveFunctions/BsplineFactory/HybridAdoptorBase.h
- src/QMCWaveFunctions/BsplineFactory/HybridCplxAdoptor.h
- src/QMCWaveFunctions/BsplineFactory/HybridRealAdoptor.h
- src/QMCWaveFunctions/BsplineFactory/SplineAdoptorBase.h
- src/QMCWaveFunctions/BsplineFactory/SplineAdoptorReaderP.h
- src/QMCWaveFunctions/BsplineFactory/SplineC2CAdoptor.h
- src/QMCWaveFunctions/BsplineFactory/SplineC2RAdoptor.h
- src/QMCWaveFunctions/BsplineFactory/SplineHybridAdoptorReaderP.h
- src/QMCWaveFunctions/BsplineFactory/SplineR2RAdoptor.h
In the C2R case, the splines are reordered based on whether one or two orbitals are generated.
When the splines are constructed in parallel over MPI, the construction uses the old older reading from h5 and then dump the splines into memory with the new order. This makes the the communication at the end of the parallel construction very complicated.
In this PR enables parallel construction directly in the new order and then all the communication part becomes simple and the lines of code reduce.
> Reorder splines for simpler parallel construction

- src/.clang-format
in order to make one super long line i.e.
call(
par1, ... parN); //~120 characters
> preventing some function calls from breaking before first parameter

- CMake/FindVectorMath.cmake
Closes #526
A warning will be issued when MKL is not used. This still allows the compilation to go.
```
CMake Warning at CMake/FindVectorMath.cmake:45 (MESSAGE):
Using glibc 2.23 which contains a buggy libmvec crashing QMCPACK.
Workaround needed for this issue.
```
My workaround is putting a newer libmvec on the LD_LIBRARY_PATH.
At the compile time, the old lib will still be used. I don't even know how to change that.
> Print a warning for the buggy glibc 2.23 in cmake.

- CMake/IntelCompilers.cmake
Add the space to ensure this only matches options where -x is at the beginning.
Issue showed up passing the option "-cxxlib=/path/linux-rhel7-x86_64".
The '-x' in the middle of the expression would satisfy the match condition.
> Add space in front of -x check for Intel compilers

- tests/test_automation/nightly_ornl_oxygen.sh
Current script. Uses ctest test track hack. Needs #1122 in later revision. This script can already be used to begin updating scripts to the new dashboard and test labeling for systems other than oxygen .
Includes intel2019, gcc8, clang6/7 and pgi2018 support, and extensive use of spack packages.
> Update nightly oxygen test script

- manual/running.tex
Additional description. Closes #957 , which was not essential because the description was already there.
> Improve description of verbosity in manual

- README.md
- manual/installation.tex
Covers the unstable label and the different test types now implemented. @jtkrogel may wish to go into more details in a subsequent update, e.g. the different label categories. Also updates the description of the nightlies.
Closes #1147
> Update manual testing description consistent with new labeling scheme

- nexus/library/simulation.py
The PR contains two small commits needed to support the demos given in the Nexus user and developer meeting today.
Fix a recently introduced bug in job bundling (interaction with skip_submit) and color blocked simulations in black when graphing simulation workflows.
> Adjustments and fixes for user meeting

- src/einspline/tests/test_3d.cpp
Fixes failing PGI unit test https://cdash.qmcpack.org/CDash/testDetails.php?test=3571223&build=32626
The unit test of the natural (non-periodic) 3D spline gives a NaN with PGI for a grid point exactly on the outermost spline grid limits. By moving the test point inside the limits by 5\*epsilon we avoid a presumed bounds error inside einspline and the NaN return value. 5\*epsilon is required to pass; 4*epsilon still results in NaN.
> Fix precision issue in 3D natural spline unit test

- tests/performance/NiO/process_perf.py
Dropping 'OMP' in the file and class names in #1178 also drops it from the timer names.
Add the new timer names to the script that processes the nightly performance results.
Fixes #1183
> Update timer names in performance script

- src/Numerics/Quadrature.h
Closes #1180 
Ugly solution but this file already has other magic numbers defined similarly. I am surprised the second tolerance is not too small for large integration grids.
> Define delta for assert in Quadrature.h

- src/CMakeLists.txt
- src/Message/catch_mpi_main.hpp
- src/Message/tests/CMakeLists.txt
- src/Message/tests/test_communciate.cpp
In particular, test the splitting constructor used for ensemble runs.
Test that it splits the processes as expected and creates the group leader communicator.
Purpose is to ensure this functionality doesn't regress when moving to the new MPI wrapper.
Add MPI initialization to the Catch MPI header.   The OHMMS::Controller initialization can
be removed from some of the unit tests that have it.
The test is designed to run under multiple MPI processes, but test system doesn't
handle this yet.  This test can be run manually to check that it works for different
numbers of MPI processes.
> Add unit test for Communicate class

- src/Message/catch_mpi_main.hpp
Fixes #1232.
Adding the initialization of Communicate in the no-MPI case calls a different constructor than the default serial constructor.
An alternate approach would be to fix that constructor, but the serial version of Communicate will be removed eventually so there's no need to fix it.
> Fix noMPI build with test_message.

- CMake/ClangCompilers.cmake
- CMake/GNUCompilers.cmake
- CMake/IntelCompilers.cmake
- CMakeLists.txt
- manual/installation.tex
- src/CMakeLists.txt
- src/Message/Communicate.cpp
- src/Message/Communicate.h
- src/Message/catch_mpi_main.hpp
- src/QMCApp/qmcapp.cpp
- src/QMCTools/convert4qmc.cpp
- tests/test_automation/jenkins_rhea_cpu.sh
- tests/test_automation/jenkins_rhea_gpu.sh
Includes some updates from the mpi3 wrapper repo that are needed to compile, especially with gcc 5.3 on Rhea.   Also need load the boost module on Rhea to get a newer boost (1.58)
This PR puts the new mpi3 wrapper in charge of initializing MPI, and the old OOMPI wrappers are initialized from that by passing an MPI communicator.
A check is on the Intel compiler version is added and the manual updated.
> Use MPI3 wrapper

- src/QMCWaveFunctions/lcao/MultiQuinticSpline1D.h
store values to avoid repeated calls to exp
> Store r values in vector for 1D quintic splines

- src/io/hdf_archive.cpp
Fixes segfaults in gaussian orbital test cases.
Gaussian orbital HDF readers use this pointer.  The code should be changed to pass the Communicate pointer to these functions directly rather than use the pointer in hdf_archive.
> Pass Communicate pointer in hdf_archive.

- CMake/PGICompilers.cmake
- CMakeLists.txt
Move the CMake C++ standard settings before the compiler-specific configuration files.
The compiler configuration files can then override these settings if necessary.
> Fix PGI compiler build with GCC 7

- CMakeLists.txt
- README.md
- manual/installation.tex
Addresses #1254
This is for AFQMC.  The real-space version may have more relaxed version requirements,
but this version seems available most everywhere and for simplicity a single
version requirement is added.
> Set minimum boost version to 1.61.0

- tests/performance/adjust_qmcpack_input.py
- tests/scripts/test_labels.py
Use print function in performance adjustment script.
Use items rather than iteritems in test_labels.
Addresses #1256
> Make setup python scripts 2/3 compatible

- manual/installation.tex
The existing SummitDev recipe can not work on Summit since the XL compiler is not C++14 capable.
> Replace SummitDev recipe with Summit

- nexus/bin/qmca
Update qmca quantity abbreviations to include RMC, CSVMC, and AFQMC quantities.
Also tighten the logic surrounding total samples, total time and efficiency.  The logic changes consider the minimum amount of information needed to compute each quantity separately.  This way the maximum set of quantities is made available to the user.
> Nexus: update qmca quantities and tighten logic

- src/AFQMC/Drivers/AFQMCDriver.cpp
Small fix to ensure the user is requesting a checkpoint file. Currently the AFQMC code will crash because dumpToHDF5 is not fully implemented yet.
> Don't attempt to dump HDF5 if nCheckpoint = 0.

- tests/reference_data/scalar_reference_full.dat
Add a file with newly regenerated reference means and error bars for scalar type test runs.  The reference data in the file was created with the qtest script.  See additional notes in the file itself for details.  
The data in the file will be used to update erroneous statistical tests.  Additionally, the file contains reference data for more quantities than we are currently testing against, which will allow us to add tests of more quantities down the road if we see fit.  It is envisioned that more data will be added to the file as more statistical tests undergo similar quality checks and reference data updates.
A significant subset of the reference runs were performed independently by Hyeondeok using the same reference versions of the code, but a different machine and build environment. …
> Add regenerated scalar reference data

- src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
i ran the 10 times by hand both the short and long tests.
The table method code-path pass stably while the traditional code path still sometimes fails.
Remove the safe guard to get tests running properly during the night.
> Allow multi det with mixed precision.

- src/QMCHamiltonians/QMCHamiltonian.cpp
Closes #675
With Intel and XL, the checking is always enabled.
With GNU, Clang and PGI, the checking needs to be enabled by passing `-D CMAKE_BUILD_TYPE=Debug` to cmake
> Add NaN guard in QMCHamiltonian.

- src/OhmmsSoA/VectorSoaContainer.h
- src/Particle/SoaDistanceTableAA.h
- src/Particle/SoaDistanceTableBA.h
- src/QMCWaveFunctions/Fermion/DelayedUpdate.h
- src/QMCWaveFunctions/lcao/LCAOrbitalSet.cpp
- src/simd/Mallocator.hpp
- src/simd/algorithm.hpp
- src/simd/allocator.hpp
Several issues here,
SoaDistanceTableAA::update is either mis documented or doing someting different. What are the valid values for iat? I'm reasoning this out and will write a unit test, but if you feel responsible for this feel free to chime in.
The underlying simd::copy_n `/src/simd/algorithm.h` function when called as in SoaDistanceTableAA after getAlignedSize and not just as an alias of std::copy_n may not be causing an error its still incorrect code if it is intended to 'copy a cache line' of data allocated with aligned_alloc or posix_memalign. While in release you can copy from an invalid pointer to T1* you shouldn't. This does trip a heap buffer read overflow in LLVM ASAN. However you can legally copy from the allocated memory via void* of one aligned_alloc vector data region to …
> Fix for distance table soa heap buffer read overflow

- CMakeLists.txt
- doxygen/config.h
- manual/hamiltonianobservable.tex
- src/CMakeLists.txt
- src/QMCDrivers/CMakeLists.txt
- src/QMCHamiltonians/HamiltonianFactory.cpp
- src/QMCWaveFunctions/CMakeLists.txt
- src/QMCWaveFunctions/ElectronGas/ElectronGasComplexOrbitalBuilder.cpp
- src/QMCWaveFunctions/ElectronGas/ElectronGasOrbitalBuilder.cpp
- src/QMCWaveFunctions/Jastrow/BsplineFunctor.h
- src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/TwoBodyJastrowOrbital.h
- src/QMCWaveFunctions/MolecularOrbitals/MolecularSPOBuilder.h
- src/QMCWaveFunctions/SPOSetBuilderFactory.cpp
- src/QMCWaveFunctions/WaveFunctionFactory.cpp
- src/Sandbox/CMakeLists.txt
- src/Sandbox/README.md
- src/config.h.cmake.in
The default had been set to 3, and was only changed to build the sandbox apps.
Remove the ifdefs in most places, and replace with QMC_BUILD_SANDBOX_ONLY where appropriate.
Fixes #1051.
> Remove QMC_BUILD_LEVEL

- src/QMCWaveFunctions/lcao/LCAOrbitalBuilder.cpp
- src/QMCWaveFunctions/lcao/LCAOrbitalSet.cpp
- src/QMCWaveFunctions/lcao/LCAOrbitalSet.h
- src/QMCWaveFunctions/lcao/LCAOrbitalSetWithCorrection.cpp
- src/QMCWaveFunctions/lcao/LCAOrbitalSetWithCorrection.h
The builder is responsible to deal with ReportLevel.
> Remove ReportLevel in LCAOrbitalSet

- nexus/lib/fileio.py
Small fix for XSF to CHGCAR conversion.  Bug introduced with changes to internal representation of XSF data a while back (C vs. Fortran array order).
> Nexus: fix CHGCAR conversion

- CMakeLists.txt
- tests/test_automation/jenkins_rhea_cpu.sh
- tests/test_automation/nightly_anl_bora.sh
Turn off AFQMC by default. 
Turn on AFQMC in the CI script when appropriate.
> Adjust AFQMC cmake configuration

- src/AFQMC/Drivers/AFQMCDriver.h
- src/AFQMC/Drivers/BenchmarkDriver.h
- src/AFQMC/Drivers/Driver.h
- src/AFQMC/Estimators/BackPropagatedEstimator.h
- src/AFQMC/Estimators/EnergyEstimator.h
- src/AFQMC/Estimators/EstimatorBase.h
- src/AFQMC/Estimators/OneRdmEstimator.h
- src/AFQMC/Estimators/WalkerDMEstimator.h
- src/AFQMC/HamiltonianOperations/HamOpsIO.hpp
- src/AFQMC/HamiltonianOperations/SparseTensorIO.hpp
- src/AFQMC/HamiltonianOperations/THCOpsIO.hpp
- src/AFQMC/Hamiltonians/HamiltonianFactory.cpp
- src/AFQMC/Walkers/WalkerIO.hpp
- src/io/hdf_archive.h
- src/io/hdf_multi.h
- src/type_traits/container_proxy.h
- src/type_traits/container_proxy_multi.h
Removes include of boost::multi template specialisations from being included in hdf_archive by default. Prevents boost::multi related warnings when building the real space code with intel.
> Isolate boost::multi hdf template specialisations.

- src/AFQMC/CMakeLists.txt
- src/AFQMC/Estimators/BackPropagatedEstimator.h
- src/AFQMC/Estimators/BasicEstimator.h
- src/AFQMC/Estimators/EnergyEstimator.h
- src/AFQMC/Estimators/EstimatorBase.h
- src/AFQMC/Estimators/EstimatorHandler.h
- src/AFQMC/Estimators/tests/CMakeLists.txt
- src/AFQMC/Estimators/tests/test_estimators.cpp
- src/AFQMC/Wavefunctions/NOMSD.icc
Prints back propagated RDMs to file with a controllable blocking parameter to reduce output. I also added a unit test. In the process of writing the test I discovered a bug for UHF trial wavefunctions, which is also now fixed.
> Re-enable AFQMC estimator HDF5 estimator output

- nexus/lib/structure.py
Small change to protect calls to SeeK-path.  The pwscf_input test now passes again.
> Nexus: guard calls to SeeK-path

- src/QMCWaveFunctions/EinsplineSetCuda.cpp
The code region using MPI appears to be dynamically executed only if there is more than one rank.  Using HAVE_MPI to ifdef it out should be safe.
> Fix the no-MPI CUDA compilation.

- src/Numerics/OneDimCubicSpline.h
- src/Numerics/OneDimGridBase.h
- src/Numerics/OneDimQuinticSpline.h
The cubic spline state was extracted to a new class, CubicSplineEvaluator.
Ye said the grid manager optimization was not used, so removing it should not cause a performance problem.
All the evaluation routines were made `const` (including those from the quintic splines).
The internal quintic spline routines were made private.
> Remove cubic spline state

- nexus/lib/structure.py
This is just fixing missed variable passing pathways.  The generate_crystal_structure function will get cleaned up down the road once structure tests are in place.
> nexus: small plumbing fix related to use_prim

- nexus/bin/nxs-test
- nexus/lib/machines.py
Add Summit machine class and specializations need to submit and monitor jobs on Summit.  
When using  typical options to Nexus jobs, i.e. nodes/threads, maximal filling of the node is assumed and jsrun is configured appropriately.  Usage of gpu's is on by default (with one per resource group assumed), but can be turned off by supplying `gpus=0` to a job.  In the event that a user supplies options to jsrun, Nexus generates no options of its own (the user must supply everything). 
Tests are added for rendered jsrun commands.
> Nexus: add support for Summit

- src/QMCHamiltonians/NonLocalECPComponent.cpp
- src/QMCHamiltonians/NonLocalECPComponent.h
- src/QMCHamiltonians/tests/test_ecp.cpp
This PR adds a function to NonLocalECPComponent to spit out the contributions to the Nonlocal pseudopotential force coming from ionic derivatives of $Psi_T$.  This also adds a unit test of this feature.
> Add Calculation of Pulay Terms to NonLocalECPComponent

- src/QMCHamiltonians/BareKineticEnergy.h
- src/QMCHamiltonians/tests/test_bare_kinetic.cpp
This adds a function for computing the ionic gradient of the local potential energy (BareKineticEnergy).  A unit test is added which tests the value, HF term (there's none), and "Pulay" term.  These reference values are constructed by explicit finite differences of the local kinetic energy in the wave function tester.
> Add Local Kinetic Energy "Pulay Term" Contribution

- src/QMCWaveFunctions/BasisSetBase.h
- src/QMCWaveFunctions/CMakeLists.txt
- src/QMCWaveFunctions/SPOSetBuilderFactory.cpp
- src/QMCWaveFunctions/lcao/CuspCorrectionConstruction.cpp
- src/QMCWaveFunctions/lcao/CuspCorrectionConstruction.h
- src/QMCWaveFunctions/lcao/LCAOrbitalBuilder.cpp
- src/QMCWaveFunctions/lcao/LCAOrbitalBuilder.h
- src/QMCWaveFunctions/lcao/LCAOrbitalSet.cpp
- src/QMCWaveFunctions/lcao/LCAOrbitalSet.h
- src/QMCWaveFunctions/lcao/SoaAtomicBasisSet.h
- src/QMCWaveFunctions/lcao/SoaLocalizedBasisSet.h
This PR enables complex LCAO infrastructure.
The design is to support complex MO using complex basis set (complex AO with real radial functions).
The actually functionality will be completed by @anbenali 
Significant changes are
1. Separate functions for cusp correction from LCAOrbitalBuilder to its own header and cpp files.
2. Rename RealBasisSetBase to SoaBasisSetBase which now serves both real and complex.
3. Orbital optimization and cusp currections are not enabled in the complex build.
> Enable LCAO in complex build

- nexus/bin/qmca
This enables qmca to save the averaged data from the -a option to scalar files for
each series. This will allow one to use qmc-fit to perform a time-step
extrapolation on twist averaged data, for example. One only needs to add the option --save_average, and it will store avg.sXXX.scalar.dat files for each series. Then use qmc-fit on the new scalar files to extrapolate your twisted averaged data.
> QMCA save averaged data to scalar files

- src/QMCTools/ppconvert/CMakeLists.txt
- src/QMCTools/ppconvert/src/common/RadialWF.cc
When -ffast-math is used with GNU and Clang, some values become NaN and cause infinite loops in ppconvert. This PR only workaround the problem. It **does not** fix the cause of the NaN.
> Exclude -ffast-math when building ppconvert

- src/QMCWaveFunctions/Fermion/DelayedUpdate.h
- src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminant.h
- src/QMCWaveFunctions/tests/test_dirac_matrix.cpp
1. Fix Tmove v1 and v3 when using both batched algorithm and delayed updates
2. Move the state machine invRow_id to the DiracDeterminat class
3. ratio, ratioGrad, evalGrad inside DelayedUpdate class is not necessary and moved back to DiracDeterminat.
> Fix TM1/3 when using both batched algorithm and delayed updates

- src/QMCHamiltonians/NonLocalECPotential.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp
1) clang 6 surfaced a missing header inclusion for comparing types.
2) clang 6 warning also spotted a bug from #1405 
3) I made a mistake in #1404. A timer stop is missing.
> Small bug fixes to NonLocalECPotential and DiracDeterminant

- src/QMCHamiltonians/CoulombPBCAA.cpp
- src/QMCHamiltonians/CoulombPBCAA.h
- src/QMCHamiltonians/CoulombPBCAB.cpp
As the title says:  this adds a code path so that AA particle sets (read ions) can have forces computed correctly within the SoA build.  Moreover, there was a forgotten term in the expression for the CoulombPBCAB force, which has been added.   Ion-Ion force validated against quantum espresso, and electron-ion force separately validated.
> Add CoulombAA SoA Force path.  CoulombAB bug fix.

- src/QMCHamiltonians/LocalECPotential.cpp
- src/QMCHamiltonians/LocalECPotential.h
- src/QMCHamiltonians/NonLocalECPComponent.cpp
- src/QMCHamiltonians/tests/test_ecp.cpp
This PR does the following to allow force computation in the real build (targeting openBC's):
1.)  Fixes a known bug in the nonlocalPP evaluation with real build.  I've removed the QMC_COMPLEX=1 guard in the test_ecp unit test, and everything should pass.
2.)  Implements Hellman-Feynman force evaluation for LocalECPotential (SoA only).  Basically a copy-paste job from CoulombPBCAB.cpp.
> Allow Pseudopotential Forces in Real Build

- src/Message/Communicate.cpp
- src/QMCApp/QMCMain.cpp
Close #1423 
Now the code stops correctly reporting the following without a crash.
```
I/O warning : failed to load external entity "PTCL_XML"
ERROR File PTCL_XML is invalid
I/O warning : failed to load external entity "WFS_XML"
ERROR File WFS_XML is invalid
ERROR ERROR: No target particle e exists.
ERROR Illegal input. Missing particleset 
ERROR Input document does not contain valid objects
```
> Fix error handling of XML include.

- src/QMCHamiltonians/QMCHamiltonianBase.cpp
- src/QMCWaveFunctions/OptimizableSPOSet.cpp
- src/QMCWaveFunctions/SPOSet.cpp
- src/QMCWaveFunctions/SPOSet.h
- src/QMCWaveFunctions/WaveFunctionComponent.h
1. QMCHamiltonianBase::addEnergy was missing an abort, causing the CUDA code to crash when certain unimplemented functionality was used (user reported).
2. Tidied many APP_ABORT calls for consistency.
3. I noticed that unit_test_hamiltonian calls WaveFunctionComponent::evalGradSource incorrectly. The function in the base class should never be called. The abort there was commented out, and still is. Simulations run correctly with the abort present, so this is an issue in the test setup.
> Add and tidy applications aborts

- manual/introduction.tex
1- `/examples/molecules/simple-H2O.xml` has been moved to 
`/examples/molecules/H2O/simple-H2O.xml`. 
2- `nexus/executables` -> `nexus/bin/`
Update the manual accordingly.
> introduction.tex: Fix path

- src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.h
#1428 introduced a bug and caused segmentation fault due to missing resizing of vectors.
This PR should fix problems like https://cdash.qmcpack.org/CDash/testDetails.php?test=4493186&build=47567
> Fix backflow

- manual/lab_advanced_molecules.tex
Fix labels and their use. Remove reference to gold atom basis set since this does not exist.
With this fix the current manual builds with no undefined references
> Fix undefined references in advanced molecules lab

- src/QMCWaveFunctions/PlaneWave/PWOrbitalBuilder.cpp
If the wavefunction unit tests are run under MPI, they halt here opening the orbital HDF file.  Change the mode to read-only so multiple nodes could open the file simultaneously.
This code is not performance critical nor used much, so updating it to read the HDF file properly in parallel is not a priority.
> Open HDF orbital file in read-only mode in PW code

- CMake/Testlibstdc++.cmake
A different syntax is needed for cmake<3.8
> Fix CMake/Testlibstdc++ for cmake<3.8

- src/Message/Communicate.cpp
- src/Message/Communicate.h
A bug was introduced in #1437.
OOMPI object must be destructed before the MPI raw communicator gets freed.
I was doing that by calling the destructor by hand before freeing the raw communicator.
This is wrong because the destructor will be called again by the auto generated code in the Communicate class and try to access the communicator which has been freed already.
The solution is using a helper class which has a destructor freeing the raw communicator.
As long as it is declared before the OOMPI object, the destruction order is correct.
> Enforce the destruction of myMPI after myComm

- src/QMCTools/check-affinity.cpp
A race condition existed between mpi process.  This pull request fixes the issue.
Modification:
1.  "OpenMP enables..." is printed only once. 
2. For loop over MPI_rank + MPI_barrier.
> Update check_affinity: Ordered by MPI_rank

- nexus/docs/build_nexus_user_guide.sh
- nexus/docs/nexus_user_guide.tex
Build the NEXUS user guide with xelatex consistent with QMCPACK manual. With this change the user guide now builds. Shell escape still required for pygments and minted package use. Fixed missed/duped references.
> NEXUS user guide builds with xelatex and fixes

- src/AFQMC/Numerics/helpers/determinant.hpp
Just found this problem on my desktop.
I asked OLCF to enable 1.61 on rhea so I can test against the minimum version we support.
> Fix AFQMC compilation with boost 1.61

- config/blue_waters.sh
- config/build_alcf_mira.sh
- config/build_alcf_theta.sh
- config/build_olcf_eos.sh
- config/build_olcf_titan.sh
- config/build_ornl_cades.sh
- config/build_ornl_oic.sh
This naive update to the example/reference build scripts ensures that executables are still named correctly by specifying ENABLE_SOA=0 for non-soa builds.
> Update configs for SOA default

- tests/solids/diamondC_afqmc_1x1x1_complex/CMakeLists.txt
UHF test benchmark will be updated in future due to change in wavefunction.
> Use correct test input path for short/long afqmc tests.

- tests/converter/converter_test.py
Fixing #1480  by forcing H5diff to fail only for differences that are greater than the limit delta given as 0.000001 in the atomic positions.  This issue comes from using ParticleSet to define the atoms position and Particle set takes RealType wich can be either Float or double.
> Bug 1480 - Fix HDF5 converter tests via tolerance

- src/QMCWaveFunctions/tests/test_soa_cusp_corr.cpp
The "Ethanol MO with cusp" did not clean up at the end, leading to failures in other unit tests (ReadMolecularOrbital*) on some machines.
This should fix the wavefunction unit test failures seen in #1467
> Fix wavefunction unit tests

- CMakeLists.txt
Following discussions, the development source will be labeled with patch version 9, i.e. the version will report as x.y.9. No patch 9 version will ever be released. This should help distinguish development builds from released versions. The next version will normally be x.y+1.0 or x.y.1 if we need to make a bugfix.
> Update patch version to indicate development code

- src/Optimize/VariableSet.cpp
- src/Optimize/VariableSet.h
Replace "indx_pair_type" with a fully spelled "index_pair_type".
Dropping the 'e' makes is hard to see that it is abbreviated and only saves one letter. (Translation: I mistype it all the time.)
This type is only used internal to VariableSet - this renaming should be local and safe.
> Expand indx abbreviation to index in Optimize

- src/CMakeLists.txt
- src/Optimize/VariableSet.cpp
- src/Optimize/VariableSet.h
- src/Optimize/tests/CMakeLists.txt
- src/Optimize/tests/test_variable_set.cpp
Add an option to put header generation in the print function. 
Add names for all the columns.   Add column widths.
Force the values into scientific notation to have a consistent width.
Add option to left pad by a number of spaces, so the tables can fit into output scheme of indicating sections by indentation.
Add unit tests.
New output looks like
```
Name         Value Type Recompute Use Index
---- ------------- ---- --------- --- -----
uu_0  5.680176e-01    1         1  ON     0
uu_1  3.699138e-01    1         1  ON     1
uu_2  2.108829e-01    1         1  ON     2
uu_3  9.267632e-02    1         1  ON     3
```
The current code prints headers at the point where the code calls 'print', so header generation was made optional to enable gradual conversion of each call point to use the new …
> Organize variational parameter output tables.

- src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h
- src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp
Addresses #1533 as part of #861.
The new SoA implementation was checked against AoS deterministically using a modified version of the NiO L2 statistical integration test.  Checks were performed without Jastrow (worked already), J1 only, and J1+J2, see below.
```
>qmca -e 0 -q e 0*J0/*scalar*
01_aos_deterministic_J0/NiO-fcc-S1-vmc  series 1  LocalEnergy  =  -368.208074 +/- 2.183875 
04_soa_deterministic_J0/NiO-fcc-S1-vmc  series 1  LocalEnergy  =  -368.208074 +/- 2.183875 
>qmca -e 0 -q e 0*J1/*scalar*
02_aos_deterministic_J1/NiO-fcc-S1-vmc  series 1  LocalEnergy  =  -323.706678 +/- 11.355735 
05_soa_deterministic_J1/NiO-fcc-S1-vmc  series 1  LocalEnergy  =  -323.706678 +/- 11.355735 
>qmca -e 0 -q e 0*J2/*scalar*
03_aos_deterministic_J2/NiO-fcc-S1-vmc  series 1  LocalEnergy  = …
```
> SoA implementation of J1/J2 evaluateHessian

- src/Particle/DistanceTable.h
- src/Particle/DistanceTableAA.cpp
- src/Particle/DistanceTableAB.cpp
- src/Particle/DistanceTableData.h
- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/Particle/VirtualParticleSet.cpp
Currently the distance table output occurs during the middle of wavefunction output.
Store the description and output it later during the ParticleSetPool output.
> Cache distance table description for later output

- src/Numerics/MinimizeOneDim.h
This addresses a case with the cusp correction where the starting function value is around 1e18, and is very sharply peaked near the starting value. The step size is not large enough to reach the minimum in 1000 iterations.
The algorithm succeeds if another step size increment is added at 1000 iterations and the max iteration count raised to 10000.
> Expand minimum bracket search for cusp correction

- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMP.h
The allocator bug has been fixed when fixing the unit test before the v3.7 release.
> Remove workaround in SplineC2ROMP

- src/QMCDrivers/GreenFunctionModifiers/DriftModifierBase.h
- src/QMCDrivers/GreenFunctionModifiers/DriftModifierUNR.cpp
In addition to issuing a warning at compile time, clang causes the code to abort if the function takes a return value but no return statement is present.
Also add a virtual destructor to the base class to address another clang warning.
> Fix clang warnings in GreenFunctionModifiers

- src/QMCWaveFunctions/BasisSetBase.h
- src/QMCWaveFunctions/lcao/LCAOrbitalSet.cpp
- src/QMCWaveFunctions/lcao/LCAOrbitalSet.h
- src/QMCWaveFunctions/lcao/SoaLocalizedBasisSet.h
- src/QMCWaveFunctions/tests/gen_mo.py
- src/QMCWaveFunctions/tests/test_MO.cpp
This implements all analytic ion derivatives of the LCAO-type single-particle orbitals required for ZVZB force estimation--in particular, ionic derivatives of the SPO, SPO electron gradients, and SPO electron laplacians.  I've also added unit tests of these new API's, with reference values generated from finite differences.  This code is included in src/QMCWaveFunction/tests/gen_mo.py.
> Implement Ionic Derivatives of LCAO-type SPO's for SoA

- nexus/lib/qmcpack_result_analyzers.py
Quick fix for processing of jastrow dependencies following optimization when using only unreweighted variance.
> Nexus: fix jastrow dependency for unreweightedvariance

- CMake/ClangCompilers.cmake
- CMakeLists.txt
New versions of CMake (3.14 at least) complain about cached variable types that are not one of the expected types.  If an unknown type is found, it is treated as a string - this behavior does not change, but now it issues a warning.
> Fix cached variable types in CMake

- src/AFQMC/Drivers/DriverFactory.cpp
Very minor formatting change for energy printout of starting determinant so I don't have to add the numbers together myself.
> Tidy energy print and print total energy of starting determinant.

- src/AFQMC/Walkers/WalkerIO.hpp
Sendbuff array was not being resized to zero causing gatherv_n to hang
if number of walker blocks to write > 1. sendcounts is determined from
SendBuff.num_elements().
> Fix value of sendcount passed to gatherv_n in dumpHDF5.

- src/QMCDrivers/GreenFunctionModifiers/DriftModifierBuilder.cpp
- src/QMCDrivers/QMCDriver.cpp
Close #1584.
Function QMCDriver::process is supposed to handle consecutive driver input blocks without destroying and creating the same driver. I introduced a bug by recreating DriftModifier without updating its pointer used in QMCUpdateBase. With this PR, DriftModifier can be created only once unless a driver is destroyed. The side effect of this fix is that DriftModifier is not allowed to switch between multiple consecutive DMC blocks. This is only a minor issue.
I thinking in the future, we should get rid of reusing drivers. Every driver input section should be a fresh one. The destroying and creating cost is really negligible. This also get rid of the unintended setting left from a previous driver input section.
> Fix crashing due to mishandling of DriftModifier pointers

- nexus/lib/qmcpack.py
Fix the handling of the H5 orbital file path when using convert4qmc to "convert" the orbitals from PySCF to QMCPACK.
Unlike other cases, convert4qmc does not actually create an h5 file in this case.   Instead a pre-existing h5 file made at the save_to_qmcpack step from PySCF needs to be used.  This fix passes the correct path info along, which comes from the xml input files created by convert4qmc.
This fix is needed for the workshop, please expedite.
> Nexus: Fix orbital file path handling for pyscf to qmcpack

- src/QMCHamiltonians/BareKineticEnergy.h
Temporary arrays to handle casting between real and complex types were improperly sized.  They should be Nelec elements long, not Nion's long.
> Fix bug in Kinetic Energy Pulay term calculation

- nexus/lib/pyscf_input.py
Fix for Pyscf workflows involving k-points.  Regardless of whether input structure is in Angstrom or Bohr units, Pyscf expects k-points in Bohr units.
This update is needed for the workshop, please expedite.
> Nexus: pyscf expects kpoints in bohr regardless of input units

- src/Numerics/MinimizeOneDim.h
- src/QMCWaveFunctions/lcao/CuspCorrection.cpp
Three changes to address issues seen in #1542 
1. Increase the bracketing iteration count to 100,000 and add another step size increase at 10,000
2. Catch the std::runtime exception thrown if the bracketing reaches the maximum iteration count, and abort the code with a better message.   Unhandled exceptions are not reported well, especially under MPI.
3. Add a small offset to the wavefunction correction in the effective local energy calculation to prevent division by zero.
> Fix cusp for NaN's and catch bracketing failures

- src/OhmmsPETE/OhmmsMatrix.h
- src/OhmmsPETE/OhmmsVector.h
- src/OhmmsSoA/VectorSoaContainer.h
- src/OpenMP/OMPallocator.hpp
- src/spline2/MultiBspline.hpp
This PR enforces a container and its allocator using the same data type.
This is a restriction stronger than std::vector.
std::vector documentation says "The behaviour is undefined if Allocator::value_type is not the same as T".
> Require the same data type between container and allocator

- src/QMCWaveFunctions/lcao/SoaCuspCorrectionBasisSet.h
Closes #1623
This is a workaround. phi, dphi, d2phi are allocated and freed locally and may cause performance penalty.
A more clean fix is needed as #1624 described.
> Fix cusp correction evaluation.

- src/QMCWaveFunctions/lcao/CuspCorrection.cpp
- src/QMCWaveFunctions/lcao/CuspCorrection.h
Finding the optimal cusp correction parameters is a nested loop - finding phi0 in the inner loop and Rc in the outer loop.  The original algorithm would always start phi0 in the inner loop from the value of phi at 0.0 for each new value of Rc  This change saves the optimal value of phi0 from the previous Rc and uses it as the starting value in the inner loop for the next Rc.  Assuming that the optimal phi0 doesn't vary much with Rc, this should speed up the search in subsequent inner loops.
The change reduces the total number of iterations required in a few examples.
> Minor performance optimization for cusp correction

- src/QMCWaveFunctions/ExampleHeComponent.h
The clang compiler complains.  Keep it happy.
> Add missing override statements in example He wavefunction 

- nexus/lib/pwscf_input.py
The PWSCF input parameter "starting_charge" was miscategorized as a simple float, whereas it is really an array of floats.  This prevented appropriate input generation when using this parameter.
Other arrays that are dimensioned by ntyp were explicitly checked for correct categorization.
> Nexus: fix miscategorized starting_charge

- src/QMCWaveFunctions/tests/test_user_jastrow.cpp
Fixes the test for mixed precision builds compiled with clang.
Note that the comparison epsilon is set to h as well, but this is not what makes the test pass.  Printing the values shows the finite difference value with the larger h is much closer to the analytic value.
Fixes #1669
> Change finite difference spacing for user jastrow test

- src/QMCHamiltonians/DensityMatrices1B.cpp
- src/QMCHamiltonians/DensityMatrices1B.h
This PR addresses #975.
I did a series of performance profiling runs by rejigging the NiO performance tests to include the 1RDM.  These tests showed that a ~4x performance penalty is found for production system sizes when using 1 non-local sample per atom.  Higher sampling densities would result in proportional cost increases (2x more samples leads to 2x slowdown).  Below is a plot showing the BlockCPU time in DMC vs. number of atoms/samples relative to a run of the same size containing no estimator.
By inserting timers into the 1RDM eval, I was able to see the fraction of time spent on each sub-component.  Components include ratio eval, spo eval (labeled "basis" below), and matrix products.  As a function of system size, the ratio eval clearly dominates (approaches 100% of the overall …
> Optimize ratio evaluation in 1RDM estimator

- nexus/bin/nxs-test
- nexus/lib/pwscf_input.py
- nexus/tests/reference/user_examples/qmcpack/H2O/runs/scf.in
- nexus/tests/reference/user_examples/qmcpack/LiH/runs/nscf.in
- nexus/tests/reference/user_examples/qmcpack/LiH/runs/scf.in
- nexus/tests/reference/user_examples/qmcpack/c20/runs/c20/scf/scf.in
- nexus/tests/reference/user_examples/qmcpack/diamond/runs/diamond/scf/scf.in
- nexus/tests/reference/user_examples/qmcpack/diamond/runs/diamond_vacancy/relax/relax.in
- nexus/tests/reference/user_examples/qmcpack/diamond/runs/diamond_vacancy/scf/scf.in
- nexus/tests/reference/user_examples/qmcpack/graphene/runs/graphene/nscf/nscf.in
- nexus/tests/reference/user_examples/qmcpack/graphene/runs/graphene/nscf_opt/nscf.in
- nexus/tests/reference/user_examples/qmcpack/graphene/runs/graphene/scf/scf.in
- nexus/tests/reference/user_examples/qmcpack/oxygen_dimer/scale_1.0/scf.in
- nexus/tests/reference/user_examples/quantum_espresso/relax_Ge_T_vs_kpoints/runs/relax/kgrid_111/relax.in
- nexus/tests/reference/user_examples/quantum_espresso/relax_Ge_T_vs_kpoints/runs/relax/kgrid_222/relax.in
- nexus/tests/reference/user_examples/quantum_espresso/relax_Ge_T_vs_kpoints/runs/relax/kgrid_444/relax.in
- nexus/tests/reference/user_examples/quantum_espresso/relax_Ge_T_vs_kpoints/runs/relax/kgrid_666/relax.in
Update test reference data to reflect changes made by PR #1665.  PR #1665 updated the definition for the SuperMUC machine (corrected number of cores) which is now accomodated in the tests.  That PR additionally changed the default option for PWSCF card inputs from "alat" to "bohr".  This has also been updated in the test data.
Additional options were also added for input generation to specify any kind of card option, which was used to regain backwards compatibility with older inputs.
> Nexus: update tests for recent changes

- src/CUDA/tests/test_CUDAallocator.cpp
- src/OhmmsPETE/OhmmsVector.h
OhmmsVector::resize_impl(0) caused error in CUDALockedPageAllocator which tries to register a null pointer. Between protect the allocator or the container. I think protect the container is better because we don't know what happens if an arbitrary allocator will be put in. The added unit test reproduces the issue and this PR fixes the issue.
> Protect 0 in the copy constructor of OhmmsVector

- src/Numerics/Ylm.h
- src/ParticleBase/RandomSeqGenerator.h
- src/QMCTools/BMakeFunc.cpp
- src/QMCWaveFunctions/BsplineFactory/SplineC2CAdoptor.h
- src/QMCWaveFunctions/BsplineFactory/SplineC2RAdoptor.h
- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMP.h
- src/QMCWaveFunctions/BsplineFactory/SplineR2RAdoptor.h
- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantWithBackflow.cpp
- src/config/stdlib/Constants.h
- src/config/stdlib/math.h
- src/einspline/tests/test_3d.cpp
- src/einspline/tests/test_one.cpp
- src/spline2/tests/test_multi_spline.cpp
1. Most of time M_PI is defined in math.h but this is not part of the language standard.
So define M_PI, if M_PI was not previously defined in included files.
2. `<memory>` is needed by smart pointers.
3. Intel workaround needs to cover all 19 updates.
Closes #1696
> Fix build issues

- README.md
Write down the "two year rule" and fix typos and leftovers in the README.
The list of tested software versions corresponds exactly to what is tested on oxygen. This is now done in an easily updatable manner.
> Two year rule and software versions in README.md

- README.md
Latest releases of 2018 and 2019 Parallel Studio XE used
> Increased Intel testing

- CMakeLists.txt
Fixing #1574 we now set this policy.  Most except for FindCUDA which use CUDA_TOOLKIT_ROOT_DIR most of the Find<PACKAGE_NAME>.cmake modules follow this policay as well. I don't think we should map CUDA_ROOT --> CUDA_TOOLKIT_ROOT_DIR since we will should switch to CUDA as a language support and this eccentricity of the FindCUDA.cmake is well known, i.e. we're all used to CUDA_TOOLKIT_ROOT_DIR.
> fixing CMP0074 policy setting to prevent cmake warnings

- src/QMCHamiltonians/ECPotentialBuilder.cpp
- src/QMCHamiltonians/NonLocalECPComponent.cpp
- src/QMCHamiltonians/NonLocalECPComponent.h
- src/QMCHamiltonians/NonLocalECPotential.cpp
- src/QMCHamiltonians/NonLocalECPotential.deriv.cpp
- src/QMCHamiltonians/NonLocalECPotential.h
- src/QMCHamiltonians/NonLocalECPotential_CUDA.cpp
- src/QMCHamiltonians/tests/test_ecp.cpp
More concise access control.
`friend class NonLocalECPotential_CUDA;` is introduced only as a temporal workaround.
> Add private/public in NonLocalECPComponent

- manual/installation.tex
Missing h; put on newline for easier cut and paste.
> Fix Box.com URL

- tests/solids/diamondC_1x1x1_pp/CMakeLists.txt
k-space Jastrow tests always fail on CUDA build because it is not implemented on CUDA build.
ERROR Need specialization of WaveFunctionComponent::calcGradient for WaveFunctionComponent.
ERROR Required CUDA functionality not implemented. Contact developers.
So, k-space Jastrow tests on diamondC_1x1x1_pp testset are disabled for CUDA build.
> Disable k-space Jastrow test on diamondC_1x1x1 on CUDA build

- src/Configuration.h
- src/Estimators/EstimatorManagerBase.h
- src/Estimators/ScalarEstimatorBase.h
- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/Particle/Walker.h
- src/QMCDrivers/DMC/DMCUpdatePbyPFast.cpp
- src/QMCDrivers/QMCLinearOptimize.cpp
- src/QMCDrivers/QMCOptimize.cpp
- src/QMCDrivers/RMC/RMCUpdateAll.cpp
- src/QMCDrivers/SimpleFixedNodeBranch.cpp
- src/QMCDrivers/SimpleFixedNodeBranch.h
- src/QMCDrivers/VMC/VMCUpdatePbyP.cpp
- src/QMCDrivers/WalkerControlBase.h
- src/QMCHamiltonians/ForceCeperley.h
- src/QMCHamiltonians/QMCHamiltonianBase.h
- src/QMCHamiltonians/observable_helper.h
EstimatorRealType was initially introduced when I worked on the mixed precision in CPU code.
FullPrecRealType is the right name to reflect its actual use.
> Rename EstimatorRealType to FullPrecRealType.

- nexus/lib/bundle.py
For nersc machines, the 'constraint' flag is dropped when bundling. This commit contains proposed fix.
> NERSC bundling

- src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp
If spin up and spin down are the same when constructing SPO's, there is an early return that skips the stop timer call.  This leads to incorrect nesting and some negative times in the results.  Use a scoped timer wrapper to let the compiler handle all the return paths.
The C-graphite performance tests show the problem - incorrect nesting of DMC under Startup and the negative exclusive time for Startup.
```
Stack timer profile
Timer                                       Inclusive_time  Exclusive_time  Calls       Time_per_call
Total                                         40.2266    39.3282              1      40.226648092
Startup                                      0.8984   -38.9094              1       0.898411989
DMC                                       30.5521     6.0097 …
```
> Use a scoped timer for the spo_timer

- utils/afqmctools/afqmctools/wavefunction/mol.py
Remove walker_type string in favour of uhf bool.
> Fix UHF logic for afqmc molecular wavefunction.

- src/QMCWaveFunctions/SPOSet.h
Start to populate multi walker batching interfaces.
The prefix `mw_` is a tag indicating these interfaces are intended to operate on multiple walkers in a batch.
evaluateValue, evaluateVGL are chosen to avoid the old problem of calling all the functions evaluate.
> Add batched interfaces in SPOSet.

- src/OhmmsData/libxmldefs.h
- src/QMCHamiltonians/SOECPComponent.h
Closes #1779 
libc++ treat subnormal number conversion as badbit when operating istream. The badbit but not eof status caused infinite loop and timeout in the nightlies (bgclang and oxygen clang). With this fix, the infinite loop is avoided and the code prints
```
failbit detected when reading type (type_info::name) d, value 2.21025771677336e-308
```
file Zn.ccECP-SO.xml needs a fix to put subnormal number as zero. I also don't like tabs in that file.
Also removed a compiler warning for not providing a return.
> Fix infinite loop related to SO ECP handling

- src/Utilities/InfoStream.cpp
- src/Utilities/InfoStream.h
InfoStream is causing memory leak in the unit test.
Redefine nullstream and filestream ownership.
prevStream and currStream are only used to pick up streams and don't handle ownership.
> Redefine ptr ownership and fix leak in InfoStream

- tests/test_automation/nightly_anl_bora.sh
On Bora, a dual socket node, I found it very convenient to use numactl (widely available) to run all my CPU nightly tests on socket 1 and all my GPU nightly on socket 0 where the GPU is attached. This also prevents a multi threaded test running on both sockets.
> Update bora script with affinity control

- manual/developing.tex
It was accidentally removed while integrating the edits
> Restore manual section on adding a wavefunction

- src/QMCApp/QMCDriverFactory.cpp
- src/QMCDrivers/VMC/VMCFactory.h
fixes #1848 caused by only passing the part of the bitset. @markdewing pointed this out in the #1810 review.
> Pass the entire what to do bitset to VMCFactory

- tests/scripts/test_labels.py
This PR is for #1826 .
Add intermittently failing tests to the intermittent_stat_fail list on test_labels.py in order to remove them from the nightly dashboard.
Here is the list for added testsets.
'short-diamondC_1x1x1_pp-vmc_sdj_kspace-1-16',
'short-diamondC_2x1x1_pp-dmc_sdj-1-16',
'short-diamondC_2x1x1_hybridrep_pp-vmc_sdj',
'short-bccH_1x1x1_ae-dmc_sdj',
'short-NiO_a4_e48_pp-dmc-TMv1v3_sdj',
'long-heg_14_gamma-sj-1-16',            
'short-chn_ae_cuspCorrection-vmc',
'short-li2_sto-sj_dmc',
'short-LiH_dimer_ae_qp-vmc_hf_noj',
'short-LiH_dimer_ae_pyscf-vmc_hf_noj',
'short-LiH_ae-vmc_msdj-1-16',
'short-LiH_ae-vmc_msdj_noj-1-16',        
'vmc_short_C2_pp_msdj-H5',
Please let me know if there is missing test on the list.
Hyeondeok Shin
> Move statistically failing tests from nightly to unstable category

- src/QMCDrivers/QMCCorrelatedSamplingLinearOptimize.cpp
- src/QMCDrivers/QMCDriver.h
- src/QMCDrivers/QMCDriverNew.h
- src/QMCDrivers/QMCFixedSampleLinearOptimize.cpp
- src/QMCDrivers/QMCLinearOptimize.cpp
- src/QMCDrivers/QMCLinearOptimize.h
Addresses #1854
The timers in QMCLinearOptimize are used in derived classes QMCFixedSampleLinearOptimize and QMCCorrelatedSamplingLinearOptimize.  The pointers to myTimers elements caused seg faults as the array is no longer initialized.  Update the timers in those classes.
Also remove the myTimers array from the QMCDriver base to catch these problems at compile time.
> Fix timer crash in optimizer

- nexus/lib/pwscf_analyzer.py
In this PR, a fix is made that avoids band read failure when a hybrid
functional is used in the calculation. During a hybrid calculation,
band data is printed multiple times in the output (once for each scf
convergence). The changes here make sure that nfound, index, and the
band objects are re-initialized each time '- SPIN UP -' is seen in
the output.
> Fix band read for hybrids

- external_codes/catch/complex_approx.hpp
Addresses an issue with the Intel compiler where a complex float constant would not be passed properly to a function accepting a complex double.
Also add constructors for non-complex double and float to avoid ambiguity errors with non-complex constants.
solves part of #1871
> Add more constructors to ComplexApprox

- utils/afqmctools/afqmctools/hamiltonian/kpoint.py
- utils/afqmctools/afqmctools/hamiltonian/supercell.py
- utils/afqmctools/afqmctools/inputs/from_pyscf.py
- utils/afqmctools/afqmctools/wavefunction/pbc.py
Some fixes for AFQMC pyscf PBC integral/wavefunction generation scripts following update for non-integer occupancies.
1. Fixes inconsistent multiplication of nkpts since nelectron is now the total number of electrons in the supercell.
2. Fixes bug when generating trial in MO basis
3. Fixes order of writing wavefunction and hamiltonian so that wavefunction and hamiltonian can be written to same file.
> Fix pbc scripts

- src/io/hdf_dataproxy.h
- src/io/hdf_hyperslab.h
Reading bool in hdf must save initial value to prevent uninitialized values in case of missing intended dataset.
It should fix converter_test_LiH_pyscf failure on multiple platforms.
https://cdash.qmcpack.org/CDash/testDetails.php?test=6111561&build=78400
In addition, I add one more header inclusion. Hopefully it fixes the Clang 4.0 compilation error. I don't have clang 4.0 at hand for testing.
> Fix hdf reading boolean

- utils/afqmctools/afqmctools/wavefunction/converter.py
Fix for real space to afqmc wavefunction converter. I didn't realise the real/imaginary parts of the ci coefficients were stored in different data sets.
> Read/write imaginary part of ci coefficient.

- CMakeLists.txt
- tests/CMakeLists.txt
Should fix test breakages for nightlies due to a lack of pyscf.
> Add PYSCF_BIN variable to guard afqmc workflow tests.

- nexus/bin/nxs-test
- nexus/lib/versions.py
Although the `dateutil` module is widely available (every local install of Python I've ever seen), it is not part of the Python standard library.  This PR removes the dependency on `dateutil`.
Issue reported by @PDoakORNL.  Peter, please can you confirm that tests now pass with your specialized Spack install?
> Nexus: remove dependence on dateutil

- src/Particle/createDistanceTableAA.cpp
- src/Particle/createDistanceTableAB.cpp
If an AoS distance table is requested in a build with ENABLE_SOA=1, abort with an error message.
This continues the work in #1846 to isolate the AoS code and addresses the request in #1897 to make the error more obvious.
> Abort with error message for AoS distance tables.

- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp
Using RefVector in TrialWaveFunction basically requires changing all the lower levels using the same pattern. Instead of doing all the places, let us do it layer by layer. This PR restores using pointers when calling WFC such that the existing virtual function specializations in derived class can work as needed.
PS: there is a small fix for the tests on GPU as well.
> Using pointers instead of RefVector when calling WFC

- utils/afqmctools/afqmctools/hamiltonian/converter.py
- utils/afqmctools/afqmctools/hamiltonian/tests/test_converter.py
- utils/afqmctools/afqmctools/utils/testing.py
Incorrect logic lead to symmetry equivalent integrals being printed. I added to the unit test to check for this.
> Fix writing of 4-fold symmetric FCIDUMPs

- nexus/lib/structure.py
Fix seldom used `skew` function.  Issue reported by Chandler Bennett.
> Nexus: fix skew function

- src/QMCHamiltonians/LatticeDeviationEstimator.cpp
- src/QMCWaveFunctions/CMakeLists.txt
- src/QMCWaveFunctions/IonOrbital.cpp
- src/QMCWaveFunctions/LatticeGaussianProduct.cpp
- src/QMCWaveFunctions/LatticeGaussianProduct.h
- src/QMCWaveFunctions/LatticeGaussianProductBuilder.cpp
- src/QMCWaveFunctions/LatticeGaussianProductBuilder.h
- src/QMCWaveFunctions/WaveFunctionFactory.cpp
- tests/estimator/CMakeLists.txt
- tests/estimator/latdev/free/flatdev.py
- tests/estimator/latdev/free/two.xml
- tests/models/sho/vmc_sho.xml
Responding to #861 and #1897.
I added a better test for `LatticeDeviationEstimator`, then added SOA implementation for `LatticeDeviationEstimator` and `IonOrbital`.
> SOA versions of `latdev` and `ionwf`

- nexus/lib/qmcpack_method_analyzers.py
Changing the initial value of "nblocks_exclude" to zero.
This suppresses the warning below when "nblocks_exclude"
is never re-assigned to a non-negative value.
QmcpackAnalyzer warning:
runtime exception encountered
Traceback (most recent call last):
File "../nexus/lib/qmcpack_analyzer.py", line 482, in analyze
QAanalyzer.analyze(self,force=force)
File "../nexus/lib/qmcpack_analyzer_base.py", line 487, in analyze
v.analyze(force)
File "../nexus/lib/qmcpack_analyzer_base.py", line 494, in analyze
self.analyze_local()
File "../nexus/lib/qmcpack_result_analyzers.py", line 397, in analyze_local
energies.append(dmc.scalars.LocalEnergy.mean)
AttributeError: 'DmcAnalyzer' object has no attribute 'scalars'
Comment from Jaron regarding this:
When the user does not provide a value for …
> Nexus: QmcpackAnalyzer Warning

- nexus/bin/nxs-test
- nexus/tests/unit/test_physical_system.py
- nexus/tests/unit/test_structure.py
This PR adds protection against scipy calls in some structure tests.  This was causing failures on CDash: https://cdash.qmcpack.org/CDash/testDetails.php?test=6227452&build=81102
Structure comparisons are also hardened.  If an atom is close to a box corner, tiling can result in different orderings of the final tiled atoms due to numerical sensitivity.  Fallbacks are added to check atomic species and position equality fully within the full minimum image convention.
> Nexus: harden structure and physical system tests

- nexus/lib/numerics.py
- nexus/tests/unit/test_numerics.py
This is a small update to fix a namespace collision in the `equilibration_length` function in the `numerics` module.  A test has been added that failed prior to the fix.
> Nexus: fix use of random in equilibration_length

- utils/afqmctools/bin/pyscf_to_afqmc.py
The converter now prints `# Finished.` when it has completed.  This will make it easier for users and Nexus alike to catch unsuccessful execution.
> Add a completion message to pyscf_to_afqmc.py

- src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
- src/QMCWaveFunctions/PlaneWave/PWOrbitalBuilder.cpp
- src/QMCWaveFunctions/PlaneWave/PWOrbitalSet.cpp
- src/QMCWaveFunctions/PlaneWave/PWOrbitalSet.h
- src/QMCWaveFunctions/PlaneWave/PWRealOrbitalSet.cpp
- src/QMCWaveFunctions/PlaneWave/PWRealOrbitalSet.h
- src/QMCWaveFunctions/SPOSet.h
- src/QMCWaveFunctions/WaveFunctionComponent.cpp
- src/QMCWaveFunctions/WaveFunctionComponent.h
Closes #1844
Typedef like the following are kept for indicating c++ smartpointers usage in the future refactoring.
`typedef PWBasis* PWBasisPtr`
`PWBasisPtr, SPOSetPtr, WaveFunctionComponentPtr, DiffWaveFunctionComponentPtr` are introduced in the initial attempt of using smart pointers.
> remove ENABLE_SMARTPOINTER

- external_codes/mpi_wrapper/mpi3/shared_window.hpp
- src/AFQMC/Memory/SharedMemory/shm_ptr_with_raw_ptr_dispatch.hpp
The comm member of the shared_window object goes away, so there needs to be another way to get the communicator object for the barrier call.   Alfredo suggested the replacement code pattern.
The intranode code has been deleted from the gitlab repo, but is kept here until it can be replaced.
This completes the sync from the main mpi3 directory (and implementation subdirectories). The test and fake directories may not be in sync.
> Sync shared_window.hpp from gitlab

- CMakeLists.txt
- src/QMCWaveFunctions/WaveFunctionFactory.cpp
cmake_policy affects project() invocation which uses try_compile underneath.
I noticed this when trying CMAKE_EXE_LINKER_FLAGS.
> Move cmake_policy before project

- src/QMCDrivers/tests/test_DescentEngine.cpp
This unsurprisingly causes crashes (sometimes) in release builds. This clears one of the remaining CI issues with #1998 
Also I think this hidden "default" constructor is a bad smell.
> Fix Unitialized XMLNodePtr in test_DescentEngine

- src/QMCDrivers/DMC/DMC_CUDA.cpp
- src/QMCDrivers/VMC/VMC_CUDA.cpp
- tests/test_automation/nightly_olcf_summit.sh
Fix summit CUDA failures in determinsitic tests.
https://cdash.qmcpack.org/CDash/index.php?project=QMCPACK&date=2019-10-17
Bug introduced in #1998 not caught due to missing working CUDA tests in nightlies.
> Fix CUDA runs due to NLPP RNG = nullptr

- src/Particle/ParticleSet.cpp
Fixes #1995.
A commit between v3.7 and v3.8 removed requesting AoS distance table in the spline SPO builder.
The first call to addTable adds e-e table in SoA. During PbyP loadWalker, RSoA didn't get updated and thus causes wrong values in Coulomb e-e energy.
This bug only affects the case that no Jastrow is used with AoS build. LCAO is not affected.
> Fix AoS no Jastrow

- nexus/bin/qmca
Enable calculation of a finite size corrected energy value when only MPC is present.
@zenandrea, please can you confirm that this works for you as expected?  Usage: `qmca -q ce *scalar*`.
> Nexus: output corrected energy via qmca with MPC alone

- tests/molecules/H2_ae/CMakeLists.txt
- tests/molecules/H4_ae/CMakeLists.txt
To reduce the red tests on Cdash due to #1893
> Skip orbital rotation tests on AoS build

- src/QMCDrivers/MCPopulation.cpp
- src/QMCDrivers/MCPopulation.h
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCDrivers/QMCDriverNew.h
- src/QMCDrivers/SimpleFixedNodeBranch.cpp
- src/QMCDrivers/WalkerControlBase.cpp
- tests/solids/diamondC_2x1x1_pp/qmc_short_vmcbatch_dmcbatch.in.xml
This occurs after the starting walkers for the section are established. The default handler is a no-op.
I also returned the reuse of MCPWalker optimization.
This follows #2029
> All QMCHamiltonians now have their setNonLocalMoveHandler called.

- src/QMCHamiltonians/PairCorrEstimator.cpp
The SoA version is missing the +1 offset for the pair_id index to the normalization factor.
Closes #1699
> Fix g(r) for SoA

- src/QMCHamiltonians/tests/test_force_ewald.cpp
After #2019 and #2033, the `ForceChiesaPBCAA` estimator now produces the correct VMC forces. Huge shout-out to @tiihonej and @rcclay for fixing these bugs! This PR turns the found bugs into unit tests to secure this bare force estimator.
For prosperity, I have included a test that shows the current results agree with those in PRB **93**, 035121 (2016) [rs1.25-i5.zip](https://github.com/QMCPACK/qmcpack/files/3768594/rs1.25-i5.zip)
@rcclay , does this fix #331?
> add more unit tests for ForceChiesa

- utils/afqmctools/afqmctools/hamiltonian/kpoint.py
#2036 failed to correctly account for momentum transfer symmetry. This bug fix skips transfers that can't exist in the hdf5 file by symmetry.
> Fix serial write kpoint symmetry issue

- src/QMCDrivers/Crowd.cpp
- src/QMCDrivers/Crowd.h
- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCDrivers/VMC/VMCBatched.cpp
- src/QMCDrivers/tests/test_Crowd.cpp
- src/QMCWaveFunctions/TrialWaveFunction.cpp
1. Keep crowd class fit. many temporal result arrays moved inside driver functions since they are used locally.
2. driver Rng array directly take RandomNumberControl::Children pointers. Pointer ownership transfers if Rng is activated and deactivated. Remove a make_seeds() to recover reproducibility compared to the non-batched driver. Part of the deterministic tests can be used by the batched driver directly now.
3. Fix VMC without drift.
Q: how to update the failing deterministic test for the new batched driver.
Because in PBC calculation, the non-batched driver use makeMoveAndCheck which reject moves with displacement larger than half of the box while the batched driver doesn't use check since it complicates the driver a lot and doesn't seem helpful overall. This check doesn't impact …
> batch driver cleaning and fixes

- manual/additional_tools.tex
- manual/analysis.tex
- nexus/bin/qdens
This PR includes the provisional `qdens` tool that can be used to obtain (twist averaged) up, down, up+down, and up-down densities from spin density data outputted by QMCPACK in `stat.h5` files.
This tool will have a limited lifetime as it will be superseded in the hopefully not too distant future by a general purpose tool to post process arbitrary quantities produced by QMCPACK in `stat.h5` files.  See also #1786.
> Enable density postprocessing

- src/LongRange/LRHandlerSRCoulomb.h
- src/LongRange/tests/CMakeLists.txt
- src/LongRange/tests/test_ewald3d.cpp
- src/LongRange/tests/test_srcoul.cpp
As promised in #2041. This PR adds finite difference tests for `LRHandler`s.
> add unit tests for derivatives of LRHandlers

- src/LongRange/LRHandlerTemp.h
small amendment to #2047, abort is using `LRHandlerTemp` derivatives per @prckent suggestion.
> abort if trying to use LRHandlerTemp derivatives

- nexus/lib/physical_system.py
- nexus/lib/qmcpack.py
- src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp
Add Jastrow name as a label so that multiple one-body Jastrows can be used.
There is also a 1-line change to `physical_system.py` to run all-electron simulation of hydrogen.
After these changes, the input attached in #2037 can be generated using nexus.
> Improve support for multiple J1

- CMake/FindMKL.cmake
Ubuntu >= 18.10 provide MKL via package manager.
I tried not to hard code full path but reply on CMake searching system paths.
> Allows using system MKL in FindMKL

- src/LongRange/LRHandlerBase.h
- src/LongRange/tests/test_temp.cpp
1. Fix a test_longrange failure is caused by uninitialized value. This is more OS dependent instead of architecture.
2. When using Approx from catch, it needs to be used on the side with variable precision. Unfortunately my change doesn't kill the mixed precision failure because the handler.LR_rc is always in double precision but it was copied from Lattice.LR_rc which is compute in single precision. It needs  separate fix. My quick look indicates a lot of mess in src/LongRange.
> Fix uninitialized value

- src/QMCWaveFunctions/lcao/LCAOrbitalBuilder.cpp
Fix case where SuperTwisit 0 0 0 still has Complex component - Was previously forced to put imaginary part to 0. (case of super cells 3x3x3 5x5x5 etc.. )
> Fix LCAO supertwist (0 0 0) with complex part

- src/QMCTools/PyscfToQmcpack.py
When using  `PyscfToQmcpack` with Python3 and a non-cartesian basis, a Python bug was present leading the crash of the scrips with:
```
File "diamondC_1x1x1_pp_LCAO.py", line 66, in <module>
from PyscfToQmcpack import savetoqmcpack
File "/private/tmp/tetet/PyscfToQmcpack.py", line 550, in savetoqmcpack
eigenset_unsorted=GroupDet.create_dataset("eigenset_unsorted_0",(NbMO,NbAO),dtype="f8",data=mo_coeff_unsorted)
File "/Users/tapplencourt/miniconda/miniconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
File "/Users/tapplencourt/miniconda/miniconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 95, in make_new_dset
raise ValueError("Shape tuple is incompatible with data")
ValueError: Shape …
```
> PyscfToQmcpack: Solve Python3 error

- tests/converter/converter_test.py
Needed for #2126 to run correctly.
The spaces/tabs issue breaks any converter test running under Python 3 (or at least Anaconda Python 3.7.3, which is what I tested with)
> Update converter tests to be compatible with Python 3

- nexus/lib/qmcpack_input.py
This PR removes the setting of spline_radius and spline_npoints values
by nexus given that QMCPACK sets its own defaults for these quantities.
Thank you @jtkrogel for your assistance with this PR.
> Nexus: Default Hybrid Rep params

- src/LongRange/tests/test_srcoul.cpp
LR_kc is floating point so must compare to approx
This is proving to  be an irritation on power9 with llvm
> Fix longrange test

- src/QMCHamiltonians/CoulombPBCAA.cpp
- src/QMCHamiltonians/EwaldRef.h
closes #2142.
The sums in the reference implementation were terminated whenever the contribution over a cubic shell was less than a specified tolerance.  In the cubic NiO series for some cell sizes, the contribution over a cubic shell can vanish.  This lead to the behavior documented in #2142.
The ion-ion energy per 4 atom NiO cell is listed below for the original reference and native QMCPACK implementations:
```
Reference         QMCPACK        
4 atom  -239.29814998004  -239.2981423734
8 atom  -239.29814997992  -239.2981710054
16 atom  -239.29814997956  -239.2980872025
32 atom  -186.17910785715  -239.2983961978
64 atom  -217.33657911019  -239.2981926791
```
The fix is to instead sum the absolute value of each of the point contributions over the shell and terminate only when this …
> Fix reference Ewald

- manual/dmc.tex
- src/Particle/ParticleSet.cpp
- src/QMCApp/InitMolecularSystem.cpp
- src/QMCApp/ParticleSetPool.cpp
- src/QMCDrivers/QMCUpdateBase.cpp
- src/QMCDrivers/tests/test_clone_manager.cpp
- src/QMCDrivers/tests/test_dmc.cpp
- src/QMCDrivers/tests/test_dmc_driver.cpp
- src/QMCDrivers/tests/test_vmc.cpp
- src/QMCDrivers/tests/test_vmc_driver.cpp
- src/QMCHamiltonians/tests/test_bare_kinetic.cpp
- src/QMCHamiltonians/tests/test_coulomb_CUDA.cpp
- src/QMCHamiltonians/tests/test_coulomb_pbcAA.cpp
- src/QMCHamiltonians/tests/test_coulomb_pbcAA_ewald.cpp
- src/QMCHamiltonians/tests/test_coulomb_pbcAB.cpp
- src/QMCHamiltonians/tests/test_coulomb_pbcAB_ewald.cpp
- src/QMCHamiltonians/tests/test_ecp.cpp
- src/QMCHamiltonians/tests/test_force.cpp
- src/QMCHamiltonians/tests/test_force_ewald.cpp
- src/QMCWaveFunctions/tests/test_einset.cpp
Closes #945
If zero particle count is spotted in a particleset, the code now instructs users to clean up the input.
In the #945 Na atom case, both particle set and SPO check zeros and stop the code before hitting a segfault.
A lot of changes in this PR are fixing unit tests which contain particleset with one set of subparticles but specifying two species (u and d).
> Fix zero down spin

- nexus/lib/structure.py
In the case that the user would prefer not to recenter the set of kpoints
> Nexus: Add recenter option to add_kpoints

- src/LongRange/tests/test_srcoul.cpp
test_srcoul.cpp and test_temp.cpp both defined EslerCoulomb3D. If the EslerCoulomb3D:df functions are not actually inlined (for instance in a debug build) ODR is violated and you have undefined behavior. Clang + ld or lld will link the first defined df function (in test_temp.cpp) at link time resulting in test failure. Inline is not a guarantee.
> fix violation of ODR in test_longrange

- tests/coverage/compare_gcov.py
- tests/coverage/demangle.py
- tests/coverage/merge_gcov.py
- tests/coverage/read_gcov.py
Most of the changes are print statement to print function.
The iterkeys and iteritems methods were changed to keys and items.   This has the potential to affect performance because these methods return a list rather than an iterator, but that doesn't seem to be an issue when running the coverage tests.
The updated code works with python 2 and python 3
Python 3 - https://cdash.qmcpack.org/CDash/viewCoverage.php?buildid=95216
Python 2- https://cdash.qmcpack.org/CDash/viewCoverage.php?buildid=95318
> Update coverage scripts to be Python 3 compatible

- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantWithBackflow.cpp
The old workaround for "internal compiler error" cannot be further expanded and I put a new cleaner workaround here.
The order of the two lines of dot1 does matter with intel >=19 compilers.
Since intel is switching to clang based compiler, I doubt effort any will be put in the old compiler.
> Workaround intel compiler bug

- src/QMCHamiltonians/CoulombPBCAA.cpp
- src/QMCHamiltonians/EwaldRef.h
Further improve the situation of #2158, 2-4x speed up although it is still slow.
Changes are
1. Rearrange loops to reuse results.
2. Improve vectorization.
Now with 128 atom NiO, EwaldRef takes 297 sec on 16 core Xeon which should not be too bad for production runs.
If MPI is really needed, we can replace the current threading level with MPI and put threading in the inner levels. This will not help single MPI runs which most our tests do.
If we add MPI, the check code must be moved to the builder instead of the Coulomb class.
> Optimize EwaldRef

- nexus/bin/nxs-sim
- nexus/bin/nxs-test
- nexus/lib/testing.py
- nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/c20/runs/c20/opt/opt.in.xml
- nexus/tests/reference/user_examples/qmcpack/rsqmc_misc/graphene/runs/graphene/opt/opt.in.xml
- nexus/tests/unit/test_nxs_redo.py
- nexus/tests/unit/test_nxs_sim.py
- nexus/tests/unit/test_qdens.py
- nexus/tests/unit/test_qmc_fit.py
- nexus/tests/unit/test_qmca.py
This PR addresses #2186.  All Nexus executables now successfully run without Nexus being installed.  
All tests except the user examples pass when both `PATH` and `PYTHONPATH` are empty.  The user example tests pass provided Nexus is installed  (`PYTHONPATH=/your/path/to/nexus/lib`).  
Additionally, `nxs-test` can be used in query mode (e.g. `nxs-test --list` or `nxs-test --ctestlist`) without having a NumPy installation, as is needed to supply correct labels to `ctest` during QMCPACK configuration.
A small fix was applied to the QMCPACK reference optimization inputs to account for the updated defaults in #2128.
> Nexus: fix test path issues

- tests/scripts/check_deriv.py
- tests/scripts/check_grad_lap.py
Python 3 is more strict about separating strings and bytes and requires explicit conversion between the two.   Add encode and decode calls as necessary.  Default encoding is UTF-8.
Scripts still work with python 2.
Partially addresses #2188
I also tried making a wrapper around mmap to encapsulate the decoding and encoding in the 'find' and 'readline' methods.  It worked fine, but was overkill for these scripts.
> Update python mmap usage to python 3

- src/LongRange/LRCoulombSingleton.cpp
- src/LongRange/LRCoulombSingleton.h
- src/ParticleIO/ParticleLayoutIO.cpp
- src/QMCApp/ParticleSetPool.cpp
- src/QMCHamiltonians/CoulombPotentialFactory.cpp
- src/QMCHamiltonians/ForceChiesaPBCAA.cpp
- src/QMCHamiltonians/ForceChiesaPBCAA.h
- src/QMCHamiltonians/tests/test_coulomb_CUDA.cpp
- src/QMCHamiltonians/tests/test_force.cpp
First cut of this.  This PR adds the XML tag "LR_handler" to the lattice description and to the wave function specification when parsing ion sets and lattices from an ESHDF5 file.  
This will break with XML files which follow Juha's declaration of LR handler type in the Chiesa force estimator...  but hopefully this is an overall simplification.  
Example of a lattice declaration:  
`<simulationcell>
<parameter name="lattice" units="bohr">
3.77945227        0.00000000        0.00000000
-0.00000000        3.77945227        0.00000000
-0.00000000       -0.00000000        3.77945227
</parameter>
<parameter name="bconds">
p p p
</parameter>
<parameter name="LR_dim_cutoff"       >    15                 </parameter>
<parameter name="LR_handler"       >    ewald                 </parameter> …
> Add XML selection of LR Handler

- src/QMCDrivers/CMakeLists.txt
- src/QMCDrivers/DMC/DMC.cpp
- src/QMCDrivers/DMC/DMC.h
- src/QMCDrivers/DMC/SODMCUpdatePbyP.h
- src/QMCDrivers/DMC/SODMCUpdatePbyPFast.cpp
- src/QMCDrivers/VMC/SOVMCUpdatePbyP.h
- src/QMCDrivers/VMC/VMC.cpp
- src/QMCDrivers/tests/test_dmc_driver.cpp
This PR adds the required changes for DMC with dynamic spin moves. This alongside  #2147 finishes the VMC/DMC capability and completes step 5 of #1770. 
Similar to the VMC implementation, you simply need to add SpinMoves=yes to the DMC XML input, and equivalently the SpinMass can be changed in order to effectively modify the timestep for the spin variables, as outlined in  Melton, Bennett, & Mitas J. Chem. Phys. 144, 244113 (2016); https://doi.org/10.1063/1.4954726
Spin-orbit ECP evaluation to come
> DMC with dynamic spin variables

- tests/scripts/check_stats.py
The division operator needs updating as the single slash returns a floating point number by default in python 3.  The double slash is needed for integer division.
The 'range' builtin now returns a range object and needs to be converted to a list to recover the python 2 behavior.   The 'xrange' builtin no longer exists, as the changes to 'range' make it unnecessary.
Partially addresses #2188.
This script should still work with python 2
> Update check_stats.py for python 3

- src/Particle/tests/test_distance_table.cpp
The original test was made sensitive to PBC. The displacement of the pair of electrons used for checking was exactly half of one of the basis vectors. So numerical sensitivity can actually reverse the direction which is still valid. So I need to drag the electron a bit away from the high symmetry point to avoid this situation.
Not sure if this is related to https://cdash.qmcpack.org/CDash/testDetails.php?test=7129211&build=99071
> Fix test_particle

- nexus/lib/machines.py
This PR protects against proliferation of bytes objects through the execution path (and subsequent type mismatch errors caused by them).
@tiihonej will check that this code works.
> Nexus: protect against returned bytes from Popen

- nexus/lib/machines.py
Small update to allow a user to request `squeue -u` by providing their userid in `settings` (`user` keyword).
> Nexus: allow squeue by user whenever username is provided

- CMakeLists.txt
Fixes the following by using the same prescription as for other cached ints, i.e. a string.
```
-- CMAKE_BUILD_TYPE is RELEASE
CMake Warning (dev) at CMakeLists.txt:166 (SET):
implicitly converting 'int' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.
-- defining the float point precision
```
> Avoid int to string conversion warning for WALKER_MAX_PROPERTIES

- src/QMCApp/WaveFunctionPool.cpp
#2224 hit this code path but I cannot see a good reason.
I added the desired behaviour in the source comment.
After this fix, #2224 will hit
```
Fatal Error. Aborting at Einspline needs the source particleset
```
and we can implement the desired behaviour discussed in #2224.
> Bypass createESParticleSet check if target has been built

- nexus/lib/qmcpack_quantity_analyzers.py
Currently, the `SpinDensityAnalyzer` will not accept the case when
the user specifies `dr` rather than `grid`. This PR allows users
to specify either.
> Nexus: Allow use of `dr` in `SpinDensityAnalyzer`

- CMakeLists.txt
- src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.h
- src/QMCWaveFunctions/lcao/SoaLocalizedBasisSet.h
Additional fixes addressing issues with #2238 
many of the evalSource... functions show assumption that the ions reference held as state and the ions passed in are nearly equivalent, at least from forces they are not and segmentation faults result.  Of course some of this may have appeared to work in Release builds, but it wasn't.  I still have crashes with the legacy driver, forces, and OMP_NUM_THREADS > 0, but they are caused by accesses within the omp sections (race condition?) and I leave that to someone else.
> Force estimator fix

- config/build_olcf_summit_XL.sh
- config/load_olcf_summit_modules.sh
Required to configure successfully. Default OLCF Summit Python3 module.
> Python3 in Summit build scripts

- src/Numerics/HDFNumericAttrib.h
- src/Numerics/HDFSTLAttrib.h
- src/OhmmsData/HDFStringAttrib.h
- src/QMCApp/ParticleSetPool.cpp
- src/QMCWaveFunctions/EinsplineSetBuilderOld.cpp
- src/QMCWaveFunctions/MolecularOrbitals/NGOBuilder.cpp
- src/QMCWaveFunctions/PlaneWave/PWOrbitalBuilder.cpp
- src/io/hdf_archive.cpp
- src/io/hdf_archive.h
Changed from using H5Eset_auto and H5Eget_auto to H5Eset_auto2 and H5Eget_auto2. The version 2 APIs were introduced in HDF5 1.8.0. QMCPACK already specifies version 2 APIs (H5Dcreate2), so this introduces no new requirements in terms of minimum HDF5 version required.
These changes are needed because the HDF5 DAOS VOL connector does not have the version 1 APIs implemented and hence will not work DAOS when using HDF5.
> Use H5Eset/get_auto version 2 APIs

- src/CMakeLists.txt
- src/MinimalContainers/CMakeLists.txt
- src/QMCWaveFunctions/Jastrow/TwoBodyJastrowOrbital.h
- src/QMCWaveFunctions/Jastrow/eeI_JastrowOrbital.h
- src/Sandbox/einspline_spo.hpp
Rearrange MinimalContainers cmake.
The source code change is only for reducing GCC reorder warnings.
> Fix restart miniapp linking

- src/Message/CommOperatorsMPI.h
Needed in complex builds.  For issue #2246
This may or may not fix the issue.  I ran into an issue on my laptop and made this fix a while ago.
However, I cannot find the right configuration of settings and compiler to reproduce the error.    So I'm submitting this change to see if it fixes the nightly tests.
> Fix for missing bcast specialization.

- src/QMCWaveFunctions/EinsplineSpinorSetBuilder.cpp
The test is only active with complex builds, and the segfault only shows up when running more than one MPI process.
The problem showed up when investigating #2246
> Fix Einspline SpinorSet from HDF test under MPI

- nexus/lib/structure.py
Previously, if get_atomic_numbers is called after the user supplies an indexed atomic symbol for an element in structure.elem (e.g., elem=['Si1', 'Si2'] etc.), the code would abort. The following PR, allows the user to use indexed labels.
> Nexus: Allow for atom symbol indexing

- CMakeLists.txt
The suggested HDF5 version is out of date.  Version 1.8 or newer is needed, or the code will not compile.  The HDF5_VERSION variable (from FindHDF5) does not get set with 1.6 - checking the version is not going to be useful.  The last 1.6 version was released in 2009, so people running into this version is unlikely to be an issue anyway.
No suggested version is given, since the version choice affects parallel IO performance, not correctness.
Prompted by #2251
> Update HDF5 not found message.

- manual/particleset.tex
- src/Particle/ParticleSet.cpp
To handle #2224, allow an empty ParticleSet to be created if it has the special name "empty".
Replaces #2234 
Example input:
```
<particleset name="empty" random="no">
<group name="u" size="0">
<parameter name="charge">0</parameter>
</group>
</particleset>
```
> Allow empty particleset in the input

- tests/test_automation/jenkins_oxygen_cpu.sh
Full precision real build only since nexus ntest tests are independent of QMCPACK.
Closes #2263
> Add nexus ntest to jenkins_oxygen_cpu.sh

- nexus/bin/nxs-redo
- nexus/lib/generic.py
After the move to Python 3, old Python 2 workflows could not be read or expanded upon with the updated code.  A number of projects are mid-stride (straddling Python 2 and Python 3 Nexus through the execution of the project) and users will benefit by being able to load archived workflows created during the Python 2 era.
This PR adds a simple fix based on how pickle files are loaded by trying to load with an encoding compatible with the Python 2 files if the original load fails.
> Nexus: add interoperability support for old (Python 2) workflow data

- src/QMCDrivers/MCPopulation.h
- src/QMCDrivers/tests/CMakeLists.txt
- src/QMCDrivers/tests/SetupPools.cpp
- src/QMCDrivers/tests/SetupPools.h
- src/QMCDrivers/tests/test_WalkerControlMPI.cpp
- src/QMCDrivers/tests/test_WalkerControlMPI.h
- src/Utilities/MPIExceptionWrapper.hpp
- src/Utilities/tests/CMakeLists.txt
- src/Utilities/tests/test_mpi_exception_wrapper.cpp
I also introduce a very simple abstraction Utilities/MPIExceptionWrapper.hpp to wrap unit test code using MPI exceptions thrown therein aren't lost and APP_ABORT is called.  This will help make sure we aren't chasing ghosts because someone has called the test directly with the "wrong" number of ranks or somehow overridden the rank count set by ADD_MPI_UNIT_TEST.
> Catch wrong number of ranks to MPI unit tests.

- src/QMCHamiltonians/CMakeLists.txt
CUDA_ADD_LIBRARY seems not stateless.
```
ADD_LIBRARY(qmcham ${HAMSRCS})
ADD_LIBRARY(qmcham_unit ${HAMSRCS})
```
caused qmcham_unit target to build the cuda part of qmcham and caused a race with actually qmcham building its CUDA part.
This can be reproduced by `make test_drivers` and
```
src/QMCHamiltonians/CMakeFiles/qmcham.dir/qmcham_generated_NLPP.cu.o
```
shows up.
This PR takes out the *cu portion of ${HAMSRCS} and makes it a library which both qmcham and qmcham_unit depend on.
My workstation
_Put an x in the boxes that apply. You can also fill these out after creating
the PR. …
> Workaround CUDA_ADD_LIBRARY bug.

- utils/afqmctools/afqmctools/hamiltonian/converter.py
- utils/afqmctools/afqmctools/hamiltonian/mol.py
- utils/afqmctools/afqmctools/hamiltonian/tests/test_mol.py
- utils/afqmctools/afqmctools/inputs/energy.py
- utils/afqmctools/afqmctools/inputs/from_pyscf.py
- utils/afqmctools/afqmctools/inputs/tests/test_from_pyscf.py
- utils/afqmctools/afqmctools/utils/io.py
- utils/afqmctools/afqmctools/utils/qmcpack_utils.py
- utils/afqmctools/afqmctools/wavefunction/converter.py
- utils/afqmctools/afqmctools/wavefunction/mol.py
- utils/afqmctools/bin/pyscf_to_afqmc.py
Fix for AO->MO transformation matrix which has lost MOs due to linear dependencies. Addresses  #2291.
I added a test for this and in the process needed the ability to recompute the HF energy. The HF energy can be printed by the used if the verbosity is set to high (-vvv).
Unit tests and problematic case raised in issue. Tested on macbook pro python3.7.4, pyscf v1.7.0
> Bug fix for molecular linear dependency issue #2291

- utils/afqmctools/afqmctools/inputs/tests/test_from_pyscf.py
- utils/afqmctools/afqmctools/wavefunction/mol.py
- utils/afqmctools/bin/pyscf_to_afqmc.py
- utils/afqmctools/bin/wfn_to_hdf5.py
Follow up for #2292 which deals with case when overlap is singular and we want to work in orthogonalised AO basis. Replaces inverse with pseudo inverse in this case as transformation matrix is rectangular. 
Also tidied some help message in converter.
Laptop
> Fix linear dependency issue 

- utils/afqmctools/afqmctools/inputs/from_pyscf.py
- utils/afqmctools/bin/pyscf_to_afqmc.py
PR #2294 removed the `gdf` command line option to `pyscf_to_afqmc.py`, but the option was still being passed to `write_qmcpack` which was breaking it.
> Finish removing gdf option for afqmctools

- .github/pull_request_template.md
Update formatting to avoid checklist progress feature in PR listings.
Per GitHub support, these can not be disabled.
_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is …
> Avoid checklists in PR template

- src/QMCDrivers/WFOpt/QMCCorrelatedSamplingLinearOptimize.cpp
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp
- src/QMCDrivers/WFOpt/QMCLinearOptimize.cpp
- src/QMCDrivers/WFOpt/QMCLinearOptimize.h
- src/QMCDrivers/WFOpt/QMCOptimize.cpp
- src/QMCDrivers/WFOpt/QMCOptimize.h
The 'skipVMC' and 'warmupBlocks' parameters are unused in the code (and the tests and examples).   Remove them.
- Other (please describe): Code cleanup
- No
laptop
- N/A This PR adds tests to cover any new code, or to catch a bug that is being fixed
- N/A Documentation has been added (if …
> Remove unused WF optimization parameters

- src/QMCHamiltonians/ECPotentialBuilder.cpp
- src/QMCHamiltonians/SOECPotential.cpp
- src/QMCHamiltonians/SOECPotential.h
This PR implements the evaluation of the Spin-Orbit Potential, that was introduced in  #2312 . Just like the ECPotential Builder manages and creates the Local and NonLocalPotentials, it now creates another potential for the total Spin-Orbit contributions if it notices that any of the pseudo xml files include SO terms. 
An input flag is also given to determine whether the spin-orbit terms should be physical or not, i.e. <pairpot type="pseudo" ... physicalSO="yes/no">. This would allow for perturbative style treatment similar to [arXiv:1809.04133](https://arxiv.org/abs/1809.04133), where the SO contribution is not included in the total energy. If physicalSO="yes", it will be included in the local energy. 
- New feature
- No
my workstation
_Update the following with a yes where the items …
> SOECPotential implementation

- src/QMCDrivers/QMCDriverInput.h
If `walkers_per_rank_` defaults to zero, a vmc_batch section without 'walkers' specified will divide by zero in `calc_default_local_walkers`. The `num_crowds_` variable gets set to zero, and there is a division by `num_crowds_`.
This also makes the code behave consistent with the manual (minimum of one walker per rank)
- Bugfix
- No
laptop …
> Change the default walkers per rank to one

- nightly_ornl_nitrogen.sh
- ornl_nitrogen_setup.sh
Nightly scripts and spack install for nitrogen (dual AMD 7542 2.9GHz 32 core running RHEL8). Uses amdblis for BLAS. Does not use amdlibflame or amdfftw since these are not yet in spack. QE is built for gcc compilers.
These scripts are an initial starting point and in future versions will be modified to use spack_supported_software_versions, to add LLVM 10, use more optimized libraries etc.
(Openblas was found to be unreliable and to crash in the QMCPACK performance tests due to memory allocation and thread issues internal to Openblas. )
- Other (please describe): Integration tests
- No
Nitrogen
simply a reminder of what we are going to look for before merging your …
> Nitrogen nightly scripts

- CMakeLists.txt
Since #1124 our call to `cmake_minimum_required(VERSION)` already sets policies CMP0065 and below to `NEW`.  Remove explicit settings.
- No
Linux.
> cmake: Drop redundant settings for policies CMP0065 and below

- src/Particle/ParticleSet.cpp
- src/QMCDrivers/tests/test_vmc_driver.cpp
Fix the fact that saveWalker does not update spin variables.  This should be the last known bug for SOVMC with and without drift.
Bug fix and additional asserts in unit test to catch the bug.
- Bugfix
- No
Workstation.
> Spin update fix

- tests/test_automation/Jenkinsfile_ornl_vm
Removes unecessary custom workspace parameter from common pipeline call in the testing vm Jenkins file.  Will also trigger testing of new CI security upgrade from the private CI repos.
This change allows removal of all but one script approval for the CI runner, no dangerous approvals are required at all.
- No
CI testing VM x86_64
- Yes This PR is …
> removing uneeded parameter to commonpipline from Jenkinsfile_vm

- nexus/lib/qmcpack.py
Display a more informative error message when a user attempts to pass optimized wavefunctions per twist to a subsequent calculation.  Partially addresses #2378.
Prior message:
```
Qmcpack error:
analyzer did not compute results required to determine jastrow
exiting.
```
Updated message:
```
Qmcpack error:
Wavefunction optimization was performed for each twist separately.
Currently, the transfer of per-twist wavefunction parameters from
one QMCPACK simulation to another is not supported.  Please either
redo the optimization with a single twist (see "twist" or "twistnum"
options), or request that this feature be implemented.
exiting.
```
Updated error message.
- No
Laptop.
_Update the following with a yes where the items apply. If you're unsure about any of them, …
> Nexus: more informative error message for twist-based optimization

- src/QMCDrivers/DMC/SODMCUpdatePbyPFast.cpp
- src/QMCDrivers/GreenFunctionModifiers/DriftModifierBase.h
- src/QMCDrivers/GreenFunctionModifiers/DriftModifierUNR.cpp
- src/QMCDrivers/GreenFunctionModifiers/DriftModifierUNR.h
- src/QMCDrivers/VMC/SOVMCUpdatePbyP.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminant.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h
- src/QMCWaveFunctions/Fermion/SlaterDet.h
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/WaveFunctionComponent.h
- src/QMCWaveFunctions/tests/test_dirac_det.cpp
PR #2388 should have actually changed it to ComplexType, since spindrift is always complex. 
-datatype for spindrift
- No
linux, intel build
> change ValueType to ComplexType  for spin drift

- src/Particle/InitMolecularSystem.cpp
- src/Particle/ParticleSetPool.cpp
- src/Particle/tests/test_particle_pool.cpp
- src/ParticleIO/XMLParticleIO.cpp
- src/QMCDrivers/DMC/DMC.cpp
- src/QMCDrivers/DMC/DMC.h
- src/QMCDrivers/QMCDriver.cpp
- src/QMCDrivers/QMCDriver.h
- src/QMCDrivers/VMC/VMC.cpp
- src/QMCDrivers/VMC/VMC.h
- src/QMCTools/CMakeLists.txt
- src/QMCTools/QMCGaussianParserBase.cpp
closes #2390
Skip spin initialization in CUDA builds to restore deterministic tests.
Now if SpinMoves is requested, legacy CUDA aborts.
- Bugfix
- No
bora
> Fix cuda testing

- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMP.cpp
- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMP.h
- src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminant.h
- src/QMCWaveFunctions/Fermion/SlaterDet.cpp
- src/QMCWaveFunctions/Fermion/SlaterDet.h
- src/QMCWaveFunctions/SPOSet.cpp
- src/QMCWaveFunctions/SPOSet.h
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/WaveFunctionComponent.h
- src/QMCWaveFunctions/tests/test_einset.cpp
- src/QMCWaveFunctions/tests/test_hybridrep.cpp
Replace std::vector<T*> with RefVector<T> for clear ownership.
- No
Bora
> Fully adopt RefVector in WFC and SPOSet

- src/OpenMP/tests/CMakeLists.txt
- src/qmc_common.cpp
I pushed a wrong fix in #2395. It should be corrected now.
Once I have some bandwidth, I will add a CI instance for ENABLE_OFFLOAD.
- Bugfix
- No
Summit
> Amend PR #2395 and restore git hash printing in header.

- manual/installation.tex
Update the QMCPACK manual with respect to the current state of Spack
- No
I compiled the LaTeX for the QMCPACK manual on my mac laptop. Manual formatting looks fine.
> Spack Manual Update April 2020

- src/Platforms/OpenMP/ompBLAS.cpp
Protect OpenMP user-defined reduction with macro for compilers incapable of handling it.
user-defined reduction is not an offload-only feature but a generic one in OpenMP.
- No
Ryzen-box
> Protect OpenMP user-defined reduction with macro.

- external_codes/catch/complex_approx.hpp
- external_codes/catch/log_complex_approx.hpp
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
Now the pass tolerance of ComplexApprox and LogComplexApprox imaginary and polar parts can be inputted independently. Note that these two files are from us even placed in the catch folder.
Hopefully it addresses #2402. We will need the nightly tests to confirm.
- Bugfix
- No
Bora, checked Intel and clang
Ryzen-box, checked gcc.
> Add epsilon control to ComplexApprox and LogComplexApprox

- src/Numerics/Quadrature.h
Adjust tolerance to pass gcc8 and 50 quadrature point rule check in mixed precision on CI nodes.
- Bugfix
- No
ALCF CI nodes.
> Adjust CheckQuadratureRuleReal tolerance

- src/AFQMC/HamiltonianOperations/tests/test_hamiltonian_operations.cpp
- src/AFQMC/Hamiltonians/tests/test_hamiltonian_factory.cpp
- src/AFQMC/Propagators/tests/test_propagator_factory.cpp
- src/AFQMC/Wavefunctions/tests/test_phmsd.cpp
- src/AFQMC/Wavefunctions/tests/test_wfn_factory.cpp
- src/QMCTools/convertpw4qmc.cpp
- src/QMCTools/ppconvert/src/ParserClass.cc
sys/stat.h seems causing problem on nitrogen.
Trying just removing them.
- Bugfix
- No
Bora
> Remove sys/stat.h inclusion

- src/QMCApp/qmcapp.cpp
Closes #2247
OpenMPI nicely warns me of calling MPI_Abort after MPI_Finalize.
From https://en.cppreference.com/w/cpp/language/throw
> As the control flow moves up the call stack, destructors are invoked for all objects with automatic storage duration constructed, but not yet destroyed, since the corresponding try-block was entered, in reverse order of completion of their constructors.
Since #2014, the env was inside the try scope and its destructor called MPI_Finalize in the try scope before calling MPI_Abort in the catch.
- Bugfix
- No
Bora
> Exception must be handled inside MPI scope.

- CMakeLists.txt
- src/AFQMC/config.0.h
- src/config.h.cmake.in
- src/qmcpack.settings
Added ENABLE_STACKTRACE to guard the use of boost/stacktrace in AFQMC code. Since this is only used for development, it needs to be turned on manually for now. In the future, if needed, we could add controls from cmake. 
- Bugfix
- Yes …
> added preprocessing flag to guard stacktrace, turned off by default

- src/QMCWaveFunctions/lcao/LCAOrbitalSet.cpp
This fixes a previously undiscovered bug where if OrbitalSetSize>number of electrons in a determinant, then the force routines in LCAO would fly past the end of the arrays they were supposed to be filling.  This pegs the orbital calculation to the size of the input array, as is done for all the other calculator functions in this class.  
- Bugfix
- No
Intel Xeon Haswell
- No. Documentation has been …
> LCAO Force Bug Fix

- manual/additional_tools.tex
- src/QMCDrivers/WaveFunctionTester.cpp
This fixes a problem where the random number generator was no longer properly initialized for use in WaveFunctionTester.  This meant that simple Hamiltonian evaluation would crash if it had a non-local pseudopotential.  The random number generator is now initialized before launching the various tests.  
A little documentation on the various tests and syntax for running wftester is also added to the manual.  
- Bugfix
- No
Intel Xeon Haswell
- Yes. Code added or changed in the PR …
> WaveFunctionTester RNG bug fix 

- src/QMCHamiltonians/CoulombPBCAA.cpp
- src/QMCHamiltonians/CoulombPBCAB.cpp
- src/QMCHamiltonians/tests/test_force.cpp
This adds a few checks to protect from crashes in PBC force calculations, some of which would happen in PBC calculations with Nelec != Nnuc. Also add a few simple unit tests to protect the checks. 
- Bugfix
- No
GNU (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, Intel Xeon
> Add checks and tests for PBC Coulomb forces

- src/QMCHamiltonians/CoulombPBCAB.cpp
Due to an oversight from copying the pattern for the long-range coulomb evaluate(), an extra factor of the ion charge was multiplied by the coulomb energy.  This PR fixes the overcounting.  
- Bugfix
- No
Xeon Haswell.  
> Fix Long Range CoulombPBCAB Force Charge Error.  

- nexus/bin/eshdf
When per orbital kinetic energies are requested, the kpoint index is included in printout.
- New feature/interface improvement
- No
Workstation
> Nexus: Add kpoint index to eshdf output

- manual/installation.tex
Update the Spack section of the QMCPACK manual to reflect recent changes. Main change is that the QMCPACK-to-QE converter has now moved from the QMPACK to the QE Spack package. There are also some minor clean-up and additions.
- Other (please describe): Strictly a manual update
- No
Manual compiles on a Mac laptop
- …
> Spack Manual Update May 2020

- tests/scripts/test_labels.py
Move all statistical tests into the unstable category.  All tests should still run and report on CDash based on non-failure of QMCPACK execution.
- No
laptop
> Label all statistical test result checks as unstable

- manual/afqmc.tex
- utils/afqmctools/afqmctools/hamiltonian/converter.py
- utils/afqmctools/bin/test_afqmc_input.py
Following up on the ECP call, it was mentioned that it would be useful to have a script to check the AFQMC file format. I added test_afqmc_input.py which does this for the Hamiltonian at least. I already had a function to return the data sets as a dictionary so I just call this with some better exception handling + error messages. Addresses #2458.
Fatal exceptions are raised and silent ones (for datasets which aren't used further in constructing the dictionary) are checked after the fact. @jtkrogel mentioned this could be useful for the nightlies.
- New feature
- No
python 3.7.7 macbook pro
- Yes. This PR adds tests to cover any new code, or to catch a …
> AFQMC hamiltonian sanity checker

- src/Utilities/tests/test_pooled_memory.cpp
`1L << 31` overflows long type. Use `(1L << 30) + (1L << 29)` instead
- Bugfix
- No
raspberrypi4
> Fix overflow of long type warning

- src/AFQMC/Utilities/hdf5_consistency_helper.hpp
Fixes "warning: control reaches end of non-void function" in the nightlies.
- Bugfix
- No
xeon. I needed some combination of -Wall -Wextra -Wpedantic to reproduce the warning.
> Fix AFQMC return type compiler warning

- src/AFQMC/Numerics/tests/test_tensor_operations.cpp
- src/AFQMC/Wavefunctions/tests/test_wfn_factory.cpp
Modified unit test to avoid operator assignment with initializer lists to multi arrays.
This has problems in intel compilers. Construction from initializer lists works, so using that instead.
- Bugfix
- Yes
> Fix tensor test

- tests/solids/CMakeLists.txt
AFQMC statistical tests were developed when there was no CUDA code. These are failing on the cdash but shouldn't be run. 
- Bugfix
- No
lassen
> Remove AFQMC statistical test

- src/QMCApp/qmcapp.cpp
From user report
https://groups.google.com/d/msg/qmcpack/Zv3d7v3AxsE/RM38gZQQBAAJ
The global communicator is split by the number of jobs in an ensemble. If the number of MPI ranks is insufficient, the code should stop with a proper error.
- Bugfix
- No
Bora
> Proper error message for insufficient MPI ranks for an ensemble job

- docs/conf.py
Simple change to naming that should become visible at https://qmcpack.readthedocs.io/en/develop/
As I test I have also enabled readthedocs to build the PR
- No
None. 
> Change project name in sphinx config

- src/QMCDrivers/QMCDriverFactory.cpp
- src/QMCDrivers/VMC/VMCBatched.cpp
- src/QMCDrivers/VMC/VMCBatched.h
- src/QMCDrivers/VMC/VMCFactoryNew.cpp
- src/QMCDrivers/VMC/VMCFactoryNew.h
- src/QMCDrivers/tests/test_VMCBatched.cpp
Updated version of #2493 
As pointed out by @ye-luo, we don't need to keep the specification for the number of samples backwards compatible (for now).  This simplifies the logic.
Now the number of samples is controlled by the number of blocks, number of steps, number of walkers, and the number of nodes.   The number of substeps can be used to adjust the number of steps between each sample.
- New feature
- No
Laptop
- …
> Enable sample collection in VMCBatched driver

- README.md
- tests/test_automation/nightly_test_scripts/nightly_ornl.sh
- tests/test_automation/nightly_test_scripts/ornl_setup.sh
- tests/test_automation/nightly_test_scripts/ornl_versions.sh
Updated scripts including workaround for presumed GCC AVX512 bug on sulfur (Intel CascadeLake 6248R), GCC10 -fallow-argument-mismatch configuration edit for illegal interfaces in parts of QE, and initial spack build with RHEL GCC9 toolchain.
This configuration was used overnight (17-18 June) with good success on cdash. Deterministic failures are predominantly mixed precision related and due to QMCPACK variability.
- Bugfix
- No
sulfur and nitrogen.
> Updated ORNL nightly scripts and spack configuration

- src/Particle/MCWalkerConfiguration.cpp
- src/Particle/SampleStack.cpp
- src/Particle/SampleStack.h
- src/Particle/tests/test_sample_stack.cpp
Previously, the call to setMaxSamples would delete the storage by calling clearEnsemble, and then reserve and allocate new storage.
Removing the clearEnsemble call from setMaxSamples will allow calling setMaxSamples multiple times with no reallocation (assuming the input value is the same).
Preserve the behavior where MCWalkerConfiguration calls it by adding the clearEnsemble call.
Add a method to reset the sample count to zero.  This will avoid a reallocation of the memory between optimization loop iterations.
- No
laptop
- Yes. This PR …
> Remove clearEnsemble from setMaxSamples in SampleStack

- src/QMCDrivers/VMC/VMCBatched.cpp
- src/QMCDrivers/VMC/VMCBatched.h
The number of samples collected depends on the number of walkers per node (MPI rank). This value is not known until setup is complete (and calcDefaultLocalWalkers has been called). This means enable_sample_collection could not be safely called until after this point.
This change removes that ordering dependency.  The tradeoff is that setMaxSamples is called in two places.  The change 7a64cb57d5451752510cd67bafb93a5de97fec6a (PR #2557) means that potentially calling setMaxSamples twice should have no effects (extra memory allocations, etc).
- No
laptop …
> Make enable_sample_collection independent of calling order for VMCBatched setup

- tests/scripts/check_traces.py
- tests/solids/diamondC_1x1x1_pp/CMakeLists.txt
Current deterministic test for traces check is failing in mixed-precision build because current tolerance (1e-8) is too small to handle numeric sensitivity on mixed precision build.
This PR is to test for mixed precision build with separated tolerance of 1e-6, which is small enough as much to work as deterministic test. 
- No
Intel Xeon
- Yes. This PR …
> Add tolerance option to check_traces.py

- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMP.cpp
- src/spline2/MultiBsplineVGLH_OMPoffload.hpp
- src/spline2/MultiBsplineValue_OMPoffload.hpp
Optimize offload kernels for Clang. Workaround a current code generation/optimization issue in Clang.
The impact on XL is negligible.
Currently I'm forced to split "parallel" and "for" to have "parallel" and "target teams distribute" in the same compiler translation unit.
Eventually, I prefer to move "omp parallel" to the "omp for" side and perhaps use "omp loop" eventually.
- Other (please describe): performance optimization.
- No
Summit
> Optimize offload kernels for Clang

- src/Containers/OhmmsPETE/OhmmsVector.h
- src/Containers/OhmmsSoA/VectorSoaContainer.h
DiracDeterminants and potentially other WFC for MPI sent walkers in DMCBatched don't register data as this wipes out certain state they get by being "copies" of the gold or good walkers, but they still have the some OhmmsVector allocations from construction.  This is due to trying to remove some of the state trasforms that walkers pointlessly go through in legacy, someday it should be possible to just construct on from data coming over MPI rather than have to have one that has gone through a long series of state changes and then has just certain data copied into it from the Walker.DataSet. 
However a check in OhmmsVector assumes that the path to an attach reference will always pass through a registerData or be done by an unallocated OhmmsVector. This breakls future PRs for the batchedDMC. …
> Remove state sequence constraint on OhmmsVector 

- src/Particle/LongRange/LRCoulombSingleton.cpp
- src/Particle/LongRange/LRCoulombSingleton.h
- src/QMCHamiltonians/CoulombPBCAA.cpp
- src/QMCHamiltonians/CoulombPBCAA.h
- src/QMCHamiltonians/CoulombPBCAB.cpp
- src/QMCHamiltonians/CoulombPBCAB.h
- src/QMCHamiltonians/ForceChiesaPBCAA.h
- src/QMCHamiltonians/tests/test_coulomb_CUDA.cpp
- src/QMCHamiltonians/tests/test_coulomb_pbcAA_ewald.cpp
- src/QMCHamiltonians/tests/test_coulomb_pbcAB.cpp
- src/QMCHamiltonians/tests/test_coulomb_pbcAB_ewald.cpp
- src/QMCHamiltonians/tests/test_force_ewald.cpp
- src/QMCTools/QMCFiniteSize/QMCFiniteSize.cpp
- src/QMCTools/QMCFiniteSize/QMCFiniteSize.h
The ownership of handler in LRCoulombSingleton is vague due to using pointers. 
getHandler returns initial pointer if a new handler is created or a clone of the initial handler.
In this PR, the initial handler is owned by the LRCoulombSingleton and getHandler always returns a clone of the owned handler.
So far all the handlers are not const enough. So In CoulombPBC classes, every class has to own a handler clone, I cannot judge this is really needed or handlers can be shared (thread-safe). So far no change of the old behaviour. When all the long range pieces code are refactored in the future, several C++ design aspects must be closely looked at.
- No
- Yes. Code …
> Define LRCoulombSingleton handler ownership.

- nexus/bin/qmc-fit
- nexus/bin/qmca
Update the matplotlib import pattern in the `qmca` and `qmc-fit` executables.  The matplotlib library in the past sometimes required cycling through backend options to find a working solution.  This functionality has been subsumed within matplotlib itself since the Nexus imports were made, and the specialized imports are no longer necessary.  
This PR removes the additional backend search and instead of aborting when a matplotlib import error is caught, a warning is instead printed:  
```
Warning:
Python library matplotlib raised uncaught exceptions during import.  Plots may or may not work.
```
This is motivated by experience that has shown that matplotlib may still successfully generate plots even when such exceptions are thrown.  The warning can be suppressed via an additional command …
> Nexus: fix matplotlib import in qmca

- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_He.cpp
Add flex_evaluateDeltaLog  as part of moving all the calls in QMCCostFunction::checkConfigurations to have flex versions.
Question: The flex_evaluateLog function has a special case for a single element wavefunction/particleset list.  Is this important?  The flex_evaluateDeltaLog code does not have this special case.
- New feature
- No
laptop
- Yes  This PR adds tests to cover any new code, or to catch a bug that is …
> Add flex_evaluateDeltaLog

- src/QMCWaveFunctions/tests/test_TrialWaveFunction_He.cpp
Fixes #2600
The SPOSetBuilderFactory contains a static map that needs to be cleared between tests.
This commit also removes a potential lifetime issue with particle_set_map.
- Bugfix
- No
laptop, Intel 19.0 compiler
> Fix test_TrialWaveFunction_He unit test segfault

- src/QMCDrivers/QMCDriverNew.cpp
- tests/performance/NiO/CMakeLists.txt
- tests/performance/adjust_qmcpack_input.py
batched drivers need `walkers_per_rank` instead `walkers` input tag.
- Bugfix
- No
Ryzen-box
> Update batched_driver performance tests walker input tag

- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_He.cpp
This the the function to be called during correlated sampling.
Note that compared to evaluteDeltaLog, the dummy G and L are passed in as parameters rather than allocated in the function.  This pushes the temporary allocations to the caller of this function, and avoids performing memory allocation here.
- New feature
- Yes
laptop
- Yes …
> Add second flex_evaluateDeltaLog

- CMakeLists.txt
Allow MVAPICH2 when version>=2.4 or disable-registration-cache is enabled.
Note: Cray machines are not affected because Cray MPI is not recognized as MVAPICH2 even if  it is MVAPICH2 derived.
- Yes
ALCF Cooley
> Allow MVAPICH2 >=2.4 which fixed the aligned_alloc issue

- nexus/bin/qmca
- nexus/lib/qmcpack.py
- nexus/lib/structure.py
Add enhancements to better support twist averaging with Nexus and `qmca`.
Nexus now writes `*.twist_info.dat` files alongside the replicated QMCPACK inputs used in twist averaging.  The files contain the twist weight, which can be non-uniform for symmetrized twists, along with the twist/k-point in real space and QMCPACK's unconventional representation of the twist (placed in the interval [-0.5,0.5) in lattice cell units and then inverted).  Example contents for a set of twists:
```
>cat pbe/dmcJ2_prod/*twist_info.dat 
1.000000   -0.000000000000   0.000000000000   0.000000000000   -0.000000000000  -0.000000000000  -0.000000000000
2.000000    0.129939294061   0.000000000000   0.000000000000   -0.333333333333  -0.000000000000  -0.000000000000
2.000000   -0.000000000000   0.150040972757 …
```
> Nexus: Improve support for twist averaging

- src/QMCWaveFunctions/lcao/LCAOrbitalBuilder.cpp
- tests/solids/diamondC_1x1x1-Gaussian_pp/CMakeLists.txt
- tests/solids/diamondC_2x1x1-Gaussian_pp/CMakeLists.txt
- tests/solids/diamondC_2x1x1-Gaussian_pp_kpts/CMakeLists.txt
Closes #2566. When Real wavefunction is run with complex code, the complex coeffs were not found. Now the complex coeffs are set to 0. 
Protections for tests have been added so they do not run with CUDA build.  
- Bugfix
- No
Laptop
> Fix PBC-LCAO real tests when run with complex code

- src/Numerics/SmoothFunctions.cpp
- src/Particle/LongRange/StructFact.cpp
- src/Platforms/CPU/e2iphi.h
- src/QMCHamiltonians/CoulombPBCAA_CUDA.cpp
- src/QMCHamiltonians/CoulombPBCAB_CUDA.cpp
- src/QMCWaveFunctions/AtomicOrbital.h
- src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h
- src/QMCWaveFunctions/BsplineFactory/SplineC2C.cpp
- src/QMCWaveFunctions/BsplineFactory/SplineC2R.cpp
- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMP.cpp
- src/QMCWaveFunctions/EinsplineSet.cpp
- src/QMCWaveFunctions/EinsplineSet.h
- src/QMCWaveFunctions/EinsplineSetBuilderOld.cpp
- src/QMCWaveFunctions/EinsplineSetBuilderReadBands_ESHDF.cpp
- src/QMCWaveFunctions/EinsplineSetCuda.cpp
- src/QMCWaveFunctions/ElectronGas/ElectronGasComplexOrbitalBuilder.h
- src/QMCWaveFunctions/ElectronGas/ElectronGasOrbitalBuilder.h
- src/QMCWaveFunctions/Jastrow/kSpaceJastrow.cpp
- src/QMCWaveFunctions/MuffinTin.cpp
- src/QMCWaveFunctions/einspline_helper.hpp
- src/QMCWaveFunctions/lcao/LCAOrbitalBuilder.cpp
- src/QMCWaveFunctions/lcao/SoaAtomicBasisSet.h
- src/config/stdlib/math.hpp
currently sincos calls may or may not go through <config/stdlib/math.hpp> wrapper.
To enforce our wrapper layer, sincos(float/double) functions have been added to qmcplusplus namespace.
all the calls are modified to call qmcplusplus::sincos explicitly and avoid calling ambiguous sincos without a namespace.
- No
Bora
> Move sincos under qmcplusplus namespace

- src/Particle/MCWalkerConfiguration.cpp
- src/Particle/VirtualParticleSet.cpp
- src/QMCHamiltonians/NonLocalECPComponent.cpp
- src/QMCHamiltonians/NonLocalECPComponent.h
- src/QMCHamiltonians/NonLocalECPotential.cpp
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
In NLPP, the batch leader, wf_list[0], for ratio computation changes dynamically and causes excessive memory usage because batch leader is responsible for scratch memory. This PR fixes batch leader during NLPP evaluation.
- Bugfix
- No
Ryzen-box
> Use fixed batch leader in NLPP

- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMP.cpp
- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMP.h
- src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h
- src/QMCWaveFunctions/Fermion/MatrixUpdateOMP.h
- src/QMCWaveFunctions/SPOSet.cpp
- src/QMCWaveFunctions/SPOSet.h
- tests/solids/diamondC_2x1x1_pp/CMakeLists.txt
- tests/solids/diamondC_2x1x1_pp/qmc_short_sdbatch_vmcbatch_4b.in.xml
- tests/solids/diamondC_2x1x1_pp/qmc_short_vmcbatch_4b.in.xml
Before this PR, the invRow values on host are copied from host to a buffer, then transferred to the device and consumed by the offload SPO. With batched determinants, invRows are already on the device and no tranfer is needed. This PR removes the transfer.
add an integration test for batched VMC + batched DiracDeterminant by modifying the batched VMC + non-batched DiracDeterminant test.
- Other (please describe): performance optimization.
- No
Summit, Ryzen-box
> Use invRow device poionters when evaluating NLPP ratios in batches

- tests/solids/diamondC_1x1x1-Gaussian_pp/CMakeLists.txt
- tests/solids/diamondC_1x1x1-Gaussian_pp/det_qmc_short.in.xml
- tests/solids/diamondC_2x1x1-Gaussian_pp/CMakeLists.txt
- tests/solids/diamondC_2x1x1-Gaussian_pp/det_qmc_short.in.xml
As requested in #2611, deterministic tests for PBC-Gaussian 1x1x1 and 2x1x1 diamond are added.
References were generated in QMCPACK 3.9.2 and current develop version. 
Tests are all passed including mixed precision build but tolerance for the mixed precision will be adjusted after checking tolerances in cdash. 
Closes #2611 
- Add test
- No
Workstation (Intel Xeon)
> Add deterministic test for PBC-Gaussian 1x1x1 and 2x1x1 diamond

- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMP.cpp
- src/spline2/MultiBsplineVGLH_OMPoffload.hpp
- src/spline2/MultiBsplineValue_OMPoffload.hpp
Optimize kernels. The functions for spline evaluation becomes elementary functions.
The loop over bands and its "omp for" are moved to SplineC2ROMP.
We only need "omp parallel for" + loop. Basically all such loops are data parallel loops.
I have seen evaluateVGL kernel time decreasing almost by half but total runtime decreases little.
This indicates the need of asynchronous offload. Host timer is about 3-5x of kernel time.
- Other (please describe): Performance optimization
- No
Summit, Ryzen-box
> Optimize spline SPO OpenMP offload kernels

- utils/determinants_tools.py
This PR fix the `determinant_tool` which analyses the determinants stored in HDF5 to print information about them.
This tool was broken for a negative number (and the bug was ofc in the only non-tested function...). 
In HDF5, for legacy reasons, we store the determinant as a list of signed integers in the HDF5. All the algorithms in this script assume unsigned integers, so we need to convert them prior to any analysis.  
The bugs were in the mismatch of data-type. Some of the value was converted to Python native data-type where others were still numpy data-type. This PR fixes this issue.  The only change is `s -> int(s)` in line 34 / 48.
- Bugfix
- No
Python3. Didn't add new dependency. 
-  This PR is up to date with current the current state of 'develop'
- Yes. This PR adds tests to …
> Fix determinant tool for negative number

- nexus/bin/qdens
This PR is similar to #2607, but now expanding the enhanced functionality to the `qdens` post-processing script.  Densities can now be automatically twist averaged with appropriate weights, provided the QMC runs with symmetrized k-points were performed with Nexus.  If at some future time QMCPACK itself becomes more twist/k-point aware, these benefits can be extended to all QMCPACK runs.
- New feature
- No
Laptop.
> Enhance twist averaging in qdens

- tests/solids/LiH_solid_1x1x1_pp/CMakeLists.txt
This PR is to change test name "deterministic-short-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-1" to "deterministic-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-1" in order to unify test name template for the deterministic test. 
- No
Intel Xeon
> Remove "short" title on test name "deterministic-short-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-1"

- README.md
- docs/installation.rst
- src/QMCWaveFunctions/BsplineFactory/SplineC2COMP.cpp
- src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h
- tests/test_automation/nightly_test_scripts/nightly_anl_bora.sh
ompReduction.h header was missing in SplineC2COMP.cpp. It doesn't matter for Clang which supports complex reduction with and without openmp user defined reduction (UDR).
In addition, this PR put the README.md aligned with installation.rst and update nightly test script on Bora.
- Bugfix
- Yes. I noticed IBM XL fails on complex build. With UDR, I got linker error. Without UDR, I got compiler ICE.
Summit.
> Include ompReduction.h in SplineC2COMP.cpp

- src/QMCTools/qmcfinitesize.cpp
Minor change, however, helpful for new users running the tool.
The usage is printed when number of arguments is less than what is needed for successful execution.
Also fixes issue where 'qmcfinitesize --help' prints nothing.
- Other (please describe): Minor "fix". Before this PR 'qmcfinitesize --help' leads to no printout
- No
Desktop
- No. Documentation has been added (if …
> Restructure how CLI arguments are read for qmcfinitesize

- CMake/macros.cmake
- tests/molecules/He_ae/CMakeLists.txt
- tests/molecules/He_ae/reference.det_He_opt.s001.opt.xml
The scheme copying the test source folder to the build folder is suboptimal. First, the cmake step takes long on a slow filesystem.
Second, a lot of copied files are actually unused, specially qmc-ref.
In this PR, all the files from the test source folder will be symlinked. All the subdirectories are ignored.
If a needed file is outside the test source folder or in a subdirectory, making a soft link to the test source folder resolves the issue.
On my desktop with an SSD, the cmake time change is not noticeable but the whole build folder drop from 800MB to only 40MB.
Copying precisely only the needed files has been attempted but more complicated than I thought. We do know the exact input file but not other files still used in the calculation/check.
- No
Ryzen-box
- …
> Symlink all the files from test folders to the build folder

- src/Utilities/RunTimeManager.cpp
- src/Utilities/RunTimeManager.h
Add explicit template instantiations for RunTimeManager.
The release build works without these, but the debug build fails with a linker error.
- Bugfix
- No
laptop, gcc and clang
> Fix link error in debug build with RunTimeManager

- src/QMCDrivers/CorrelatedSampling/CSVMC.cpp
- src/QMCDrivers/DMC/DMC.cpp
- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCDrivers/DMC/DMC_CUDA.cpp
- src/QMCDrivers/QMCDriver.cpp
- src/QMCDrivers/QMCDriver.h
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCDrivers/QMCDriverNew.h
- src/QMCDrivers/RMC/RMC.cpp
- src/QMCDrivers/VMC/VMC.cpp
- src/QMCDrivers/VMC/VMCBatched.cpp
- src/QMCDrivers/VMC/VMCLinearOpt.cpp
- src/QMCDrivers/VMC/VMC_CUDA.cpp
- src/QMCDrivers/WFOpt/QMCCorrelatedSamplingLinearOptimize.cpp
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp
- src/QMCDrivers/WFOpt/QMCLinearOptimize.cpp
- src/QMCDrivers/WFOpt/QMCLinearOptimize.h
- src/QMCDrivers/WFOpt/QMCLinearOptimizeBatched.cpp
- src/QMCDrivers/WFOpt/QMCLinearOptimizeBatched.h
- src/QMCDrivers/WFOpt/QMCOptimize.cpp
- src/QMCDrivers/WFOpt/QMCOptimizeBatched.cpp
- src/QMCDrivers/WaveFunctionTester.cpp
- src/QMCDrivers/tests/QMCDriverNewTestWrapper.h
I wanted to add a driver scope timer but the current way of destroying a driver makes it super hard.
Stage what I changed so far. QMCType becomes const and set via constructor.
- No
Bora
> Set QMCType via constructor

- CMakeLists.txt
- README.md
- docs/installation.rst
- src/QMCApp/QMCMain.cpp
- src/QMCApp/qmcapp.cpp
- src/Utilities/NewTimer.h
- src/Utilities/TimerManager.cpp
- src/Utilities/TimerManager.h
Default level is "coarse".
I don't see timing difference running a 16 electron system with timer=none and without timer built in (current develop branch).
Closes #2663 
offload info printing is added and closes #2664 
- No
Bora
- Yes.  Code added or changed in the PR has been clang-formatted
> Build with timer on by default

- src/Utilities/TimerManager.cpp
- src/Utilities/TimerManager.h
close #2676
Due to missing include <array>
- Bugfix
- No
Ryzen-box
> Fix Clang and libcxx compilation

- README.md
- tests/test_automation/nightly_test_scripts/nightly_ornl.sh
- tests/test_automation/nightly_test_scripts/ornl_setup.sh
- tests/test_automation/nightly_test_scripts/ornl_update.sh
- tests/test_automation/nightly_test_scripts/ornl_versions.sh
Current versions of the nightly scripts and spack setup run on nitrogen and sulfur. When the problems are understood, later PRs will help resolve some of the observed PySCF issues. Later PRs will expand ClangDev builds once proven stable.
* Minor version increases
* Added AOMP compiler and offload builds for gfx906.
* Check for AOMP presence to workaround LLVM 10 inability to install due to libomptarget using compilers outside of spack sandbox. 
* Added Clang development version builds, currently for one CPU build configuration only.
* Effort to avoid near duplicate package installations with spack, which can result in ambiguities and also slows installation. Duplicate python installs are currently avoided, but a duplicate of the old openmpi version is created. This can be tolerated since …
> Update ORNL testing scripts, add AOMP and ClangDev

- src/QMCTools/QMCGaussianParserBase.cpp
- tests/converter/converter_test.py
Recent change in convert4qmc surfaced a bug. It is caused by uninitialized variables.
I don't know why gcc didn't catch it by -Wmaybe-uninitialized -Wuninitialized
This PR also adds converter output printing to files.
- Bugfix
- No
Ye-Dell-Laptop
> Fix converter uninitialized variables

- CMake/ClangCompilers.cmake
- tests/converter/converter_test.py
1. subprocess.Popen switches to universal_newlines(3.5, maybe earlier) from text(3.7) to lower python version requirements.
2. protect -Wmisleading-indentation for clang >=10
- Bugfix
- No
bora, dell-laptop, ryzne-box
> Miscellaneous clang warning and python script changes

- src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
This is a simple fix to allow the multideterminant code to actually detect the CI coefficients from xlm input. Currently, all CI coefficients would be found as zero, because the ci coefficient was set before a put for the real and imaginary parts, so it was never correctly set. 
- Bugfix
- No
my workstation
- Yes. …
> allow complex build for multideterminants with xml input

- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp
- src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp
1. error stream/file in C/C++ is unbuffered. No need to flush.
2. our app_error() always print "ERROR " as long as it is invoked. app_error().flush() triggered this and misled users.
- Bugfix
- No
Bora
> No need of app_error().flush()

- src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp
In the batched cost function, use ParticleSet::flex_update instead of calling 'update' on each particle set individually.
- No
laptop
> Use ParticleSet::flex_update in batched cost function

- nexus/bin/qmca
Fix twist averaging when analyzing only a single calculation with twist_info files.
- Bugfix
- No
Laptop
> Nexus: fix twist averaging with single batch prefix

- src/Platforms/Host/OutputManager.h
- src/QMCTools/GamesXmlParser.cpp
Closes #2712 
Print app_warning to infoLog which is stdcout
PS: kill an additional uninitialized values warning.
- Bugfix
- No
Bora
> app_warning to standard output

- src/AFQMC/Memory/CUDA/cuda_arch.cpp
- src/AFQMC/Memory/CUDA/cuda_arch.h
- src/AFQMC/Memory/HIP/hip_arch.cpp
- src/AFQMC/Memory/HIP/hip_arch.h
- src/AFQMC/Numerics/detail/CUDA/blas_cuda_gpu_ptr.hpp
- src/AFQMC/Numerics/detail/CUDA/lapack_cuda_gpu_ptr.hpp
- src/AFQMC/Numerics/detail/CUDA/old_blas_cuda.hpp
- src/AFQMC/Numerics/detail/CUDA/sparse_cuda_gpu_ptr.hpp
- src/AFQMC/Numerics/detail/HIP/blas_hip_gpu_ptr.hpp
- src/AFQMC/Numerics/detail/HIP/lapack_hip_gpu_ptr.hpp
- src/AFQMC/Numerics/detail/HIP/sparse_hip_gpu_ptr.hpp
Uses arch::malloc/free/memcopy consistently throughout the code. Previously cuda/hipMalloc etc were called in many places without checking the error code, this PR replaces these calls with already existing arch::malloc which does the error checking internally.
- Refactoring (no functional changes)
- No
clang10+rocm3.6 and gcc/7.3.1+cuda9.2.88
> Replace cuda/hip specific memory allocation and copying routines with arch versions.

- nexus/lib/observables.py
Replace use of deprecated clock function by process_time. clock was deprecated in python v3.3 and has been removed in the latest versions. process_time has been available since v3.3 https://docs.python.org/3.5/library/time.html#time.clock 
ntest_nexus_observables was failing on sulfur for this reason. clock was only used in observables.py
- Bugfix
- No
sulfur with python@3.8.5%gcc@10.2.0
- No - already present. This PR adds tests to cover any new code, or to catch a bug that is being fixed
> Use process_time not deprecated clock in Nexus

- src/QMCHamiltonians/LatticeDeviationEstimator.cpp
- tests/scripts/check_deriv.py
also fix short-sho-grad_lap-1-1-check with Python 3
closes #2483 
tested by running
```
ctest -R short-*sho*
```
- No
Fedora 32 workstation with E5-2620 v2; icc (ICC) 19.1.2.254 20200623
_Update the following with a yes where the items …
> remove bind2nd

- src/QMCWaveFunctions/DiffWaveFunctionComponent.cpp
- src/QMCWaveFunctions/DiffWaveFunctionComponent.h
- src/QMCWaveFunctions/ElectronGas/ElectronGasComplexOrbitalBuilder.cpp
- src/QMCWaveFunctions/ElectronGas/ElectronGasOrbitalBuilder.cpp
- src/QMCWaveFunctions/Fermion/SlaterDet.cpp
- src/QMCWaveFunctions/Fermion/SlaterDet.h
- src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
- src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.cpp
- src/QMCWaveFunctions/LCAO/LCAOrbitalSet.h
- src/QMCWaveFunctions/PlaneWave/PWOrbitalBuilder.cpp
- src/QMCWaveFunctions/RotatedSPOs.cpp
- src/QMCWaveFunctions/RotatedSPOs.h
- src/QMCWaveFunctions/SPOSetBuilder.cpp
- src/QMCWaveFunctions/SPOSetBuilderFactory.cpp
- src/QMCWaveFunctions/SPOSetBuilderFactory.h
- src/QMCWaveFunctions/SPOSetScanner.h
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/WaveFunctionComponentBuilder.cpp
- src/QMCWaveFunctions/WaveFunctionComponentBuilder.h
- src/QMCWaveFunctions/tests/MinimalWaveFunctionPool.h
- src/QMCWaveFunctions/tests/test_pw.cpp
The two maps owned and maintained in SlaterDetBuilder and SlaterDet are not necessary any more as SPOSet will eventually be unique_ptr no more shared by determinants as we are approaching clean spo determinant input style and memory clean code. In a spin restricted case, the sposet object for spin up and down no more share the same pointer but share coefficients only. So we are not loosing anything in this change.
Additional changes:
1. Moved RotatedSPO interception from SPOSetBuilderFactory to SPOSetBuilder which is more natural.
2. SPOSetScanner moved from SlaterDetBuilder to SPOSetBuilderFactory.
- No
Bora. Tested all short tests.
- Yes. Code added or changed …
> Remove two SPOSet map in SlaterDetBuilder and SlaterDet

- src/QMCHamiltonians/SOECPComponent.cpp
- src/QMCHamiltonians/tests/soecp_eval_reference.cpp
- src/QMCHamiltonians/tests/test_ecp.cpp
This fixes a bug in the evaluation of the SOECPComponents. Essentially there was a mismatch in the normalization of integrals involved as well as a swapped conjugation of spherical harmonics. When I implemented the reference evaluation, I made the same mistake. I noticed this when comparing against my QWalk implementation and some calculations from DIRAC. This fix is reflected in the evaluation and unit tests. 
- Bugfix
- No
my workstation, gcc 9.2 
simply a …
> Fix soecp evaluation

- src/QMCWaveFunctions/tests/Carbon1x1x1-tw1_gen_mos.py
- src/QMCWaveFunctions/tests/egas_spinor_test.py
- src/QMCWaveFunctions/tests/gen_bspline_jastrow.py
- src/QMCWaveFunctions/tests/gen_inverse.py
- src/QMCWaveFunctions/tests/gen_mo.py
- src/QMCWaveFunctions/tests/read_qmcpack.py
The change are mostly changing print statements to print functions.
A few places xrange was replaced by range.
In gen_bspline_jastrow.py, there is a workaround for a Sympy bug ( https://github.com/sympy/sympy/issues/19262 )
Closes #2728
- Bugfix
- Yes - These scripts will not work with Python 2.  The rest of the code made a jump to python 3 a while ago.
laptop
- N/A Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a …
> Update QMCWaveFunctions/tests scripts for Python 3

- src/CMakeLists.txt
- src/Message/AppAbort.cpp
- src/Message/AppAbort.h
- src/Message/CMakeLists.txt
- src/Message/Communicate.cpp
- src/Message/Communicate.h
The APP_ABORT macro creates a situation where you can't simply break on any fatal error in QMCPACK. In gdb and lldb you won't catch at breakpoint set to a line in a macro definition. So if you want to catch all fatal errors in the debugger APP_ABORT is a problem. The macro is wide spread and tracking down where it actually was called from can be a pain.
This PR creates an actual function called by APP_ABORT so a breakpoint can be set to catch calls to APP_ABORT with the calling context intact.
- New feature
- No
Leconte
- Yes. This PR is …
> Catchable APP_ABORT

- docs/bibs/methods.bib
- docs/bibs/spin-orbit.bib
- docs/features.rst
- docs/hamiltonianobservable.rst
- docs/index.rst
- docs/methods.rst
- docs/spin_orbit.rst
This PR adds some of the needed documentation in order to carry out spin-orbit calculations in QMCPACK for VMC/DMC. I added information in each of the relevant sections (Hamiltonian and Observables, Quantum Monte Carlo methods, etc) as well as a dedicated Spin-Orbit calculations in QMC section. I documented each of the relevant changes in the qmcpack input files in order to carry out one of these calculations, as well as provide some of the theory since this is likely unfamiliar to many users. 
- No
macbook
_Update the following with a yes where the …
> Spin-orbit documentation

- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/QMCHamiltonians/QMCHamiltonian.cpp
- src/QMCHamiltonians/QMCHamiltonian.h
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/TrialWaveFunction_CUDA.cpp
Add top level timers for TrialWaveFunction and Hamiltonian to have more organized timer output.
```
DMCBatched::InitWalkers                       0.0340     0.0254              1       0.034037331
Hamiltonian::ElecElec                       0.0001     0.0001              1       0.000065253
Hamiltonian::IonIon                         0.0000     0.0000              1       0.000001764
Hamiltonian::Kinetic                        0.0000     0.0000              1       0.000002104
Hamiltonian::LocalECP                       0.0000     0.0000              1       0.000030988
Hamiltonian::NonLocalECP                    0.0026     0.0002              1       0.002607762
ParticleSet::computeNewPosDT              0.0012     0.0012           1020       0.000001153
WaveFunction::J1OrbitalSoA_J1_V …
```
> Add top level timers for TrialWaveFunction and Hamiltonian

- CMake/IntelCompilers.cmake
- src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h
- src/QMCWaveFunctions/Fermion/SlaterDet.cpp
- src/QMCWaveFunctions/Fermion/SlaterDet.h
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/WaveFunctionComponent.cpp
- src/QMCWaveFunctions/WaveFunctionComponent.h
- src/QMCWaveFunctions/WaveFunctionFactory.cpp
- src/QMCWaveFunctions/WaveFunctionFactory.h
- src/QMCWaveFunctions/WaveFunctionPool.cpp
- tests/solids/diamondC_2x1x1_pp/CMakeLists.txt
- tests/solids/diamondC_2x1x1_pp/qmc_short_vmcbatch_4b_asynctwf.in.xml
add WFC::mw_ratioGradAsync and WFC::ratioGradAsync to support leverage asynchronous OpenMP tasking.
This is a very very preliminary implementation.
Would like to merge this to test more compilers from nightly tests.
`<wavefunction tasking="yes">` triggers the async code path.
Add a safeguard for Intel compiler and raise minimal requirement to 19.0
- New feature
- No
Bora
> Async ratio and grad computation + Require Intel >=19

- CMake/ClangCompilers.cmake
7 is needed to get omp task compiled correctly.
- No
@prckent  tested it.
> Raise clang minimal version to 7

- CMakeLists.txt
- config/build_tulip.sh
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h
FindLAPACK handles correctly BLAS/LAPACK passed in via compiler wrappers by marking the search successful and leaving entries just empty. So we don't need to write bypass logic in our cmake. By removing that, we gain the capability of overriding BLAS/LAPACK from cray compiler wrappers. Due to Cray moving to newer Modules environment, the old way of unload cray-libsci becomes not feasible.
This PR also includes a small optimization beneficial overall and actually seems to fix issues of using Cray compiler.
- Optimization and compiler fix
- No
Tulip.
Cori. Theta is not tested due to maintenance but the software stack is very close to Cori. In general, we use ENABLE_MKL anyway.
Bora.
> Update cray-libsci handling in CMake

- docs/installation.rst
Update macports and brew install instructions.
Note that to build on mac or BSD the fix to macros.cmake in #2769 is also required.
- No
Laptop, as detailed in docs, using today's macports and brew.
> Update mac install instructions

- CMakeLists.txt
- src/Utilities/NewTimer.cpp
- src/Utilities/NewTimer.h
Use NVTX calls to allow timer regions to show up on NVidia profiling tools.
These also work with OpenMP offload.  The CMakeLists.txt file has been updated to allow USE_NVTX_API with ENABLE_OFFLOAD.  This may require CUDA_TOOLKIT_ROOT_DIR to be specified when running cmake.
- New feature
- No
laptop
- No. Documentation has been added …
> Add NVTX calls for timers

- config/build_ornl_cades.sh
Updates modules to be loaded at CADES
- No
CADES. CPU real (non-skylake) build was tested to pass deterministic tests, and the Skylake build seems to run project calculations fluently. 
Parallel HDF5 modules are broken/not compatible with (at least) Intel19. Trying to load them causes a warning, but CMake successfully reverts to serial HDF5. Maybe this needs to be sorted out with CADES support.
> Update CADES build script modules

- CMake/Testlibstdc++.cmake
Based on #2790 investigation.
- No
CI node
> More traps for bad combination of Intel and libstdc++

- src/QMCTools/LCAOHDFParser.cpp
- src/QMCTools/convert4qmc.cpp
QP format h5 doesn't include eigenvalues. Made the parsing in convert4qmc more flexible.
Should make converter_test_LiH_qp pass.
In convert4qmc main(), add a try catch block for exceptions.
- Bugfix
- No
laptop
> Fix convert4qmc when eigenval_0 is missing in h5.

- nexus/bin/qmca
The `--save_average` option in `qmca` was broken due to a local namespace collision with the globally assigned name for the `numpy` module (imported as `np`).  The fix is to use a different local variable name.
- Bugfix
- No
Laptop
> Nexus: fix module overwrite bug in qmca

- src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp
- src/QMCWaveFunctions/tests/test_wf.cpp
This generalizes the hard coded cusp condition to -2 q_i q_j mu_ij / (d \pm 1). In the 1D case, the denominator is always taken to be the plus case ([see footnote 45](https://arxiv.org/abs/2003.06506)). 
- Bugfix
- New feature
- No
Workstation (i7 2600s)
- Yes/No? This PR adds tests to cover any new code, or to catch a bug that is being fixed
Should a test be added with various particle masses? 
> Generalized 2 particle cusp

- docs/intro_wavefunction.rst
- src/QMCWaveFunctions/EinsplineSetBuilder_createSPOs.cpp
This exposes the skipChecks to the xml input. This is a workaround for the fact the eshdf from convertpw4qmc does not include the atomic number. 
Addresses the issue in #2811 
- New feature
-- No
my workstation, gnu 9.2.0
- No. This PR adds tests to …
> Expose skipChecks in einspline orbs

- docs/requirements.txt
Require use of old version of sphinxcontrib-bibtex. Temporary fix until we learn how to use v2.0 with rtd and also make any required updates.
rtd settings also changed to use the requirements file.
- Bugfix
- No
None.
> sphinxcontrib-bibtex version fix for readthedocs

- src/Particle/CMakeLists.txt
- src/Particle/MCWalkerConfiguration.cpp
- src/Particle/MCWalkerConfiguration.h
- src/Particle/ParticleSet.h
- src/Particle/WalkerConfigurations.cpp
- src/Particle/WalkerConfigurations.h
- src/Particle/tests/test_walker.cpp
- src/QMCDrivers/MCPopulation.cpp
- src/QMCDrivers/MCPopulation.h
- src/QMCDrivers/tests/test_SimpleFixedNodeBranch.cpp
MCWalkerConfiguration was overloaded. It is both a particleset and a list of lightweight walkers. The later role has been moved to WalkerConfigurations which is the object carried between QMC sections and restart.
the batched drivers will only interact with WalkerConfigurations instead of the whole MCWalkerConfiguration.
- No
Ryzen-box
> Refactor MCWalkerConfiguration

- src/Optimize/VariableSet.cpp
- src/Optimize/VariableSet.h
- src/Optimize/testDerivOptimization.h
- src/QMCDrivers/WFOpt/QMCCostFunction.cpp
- src/QMCDrivers/WFOpt/QMCCostFunction.h
In the complex build, the call to `GradCost` in `testDerivOptimization` was calling the empty base class version `QMCCostFunctionBase` due to a parameter mismatch.  The parameter gradients would come out as all zero.
Add 'override' to catch the issue, fix the signature, and add more override's to keep clang happy.
Change a parameter to const and pass-by-reference in `testDerivOptimization`.
Increase the number of digits printed out in the parameter gradient file.
Add const to the `print` function in `VariableSet` (from debugging a Jastrow optimization issue).
- Bugfix
- 
- No
laptop
_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask. …
> Fix call to GradCost in complex build

- nexus/lib/pwscf_input.py
- nexus/lib/qmcpack_property_analyzers.py
Fixing an error in nexus' QmcpackAnalyzer, which occasionally fails to read Jastrow coeffiecients, resulting in warning. The solution came from @jtkrogel.
Also, fix QE input handling of starting magnetization, and add support for the following QE inputs: cell_dofree, lspinorb, noncolin.
- Bugfix
- New feature
- No
- CADES
> Nexus: fix a Jastrow read error/warning, add several QE inputs

- src/QMCApp/QMCMain.cpp
- src/QMCApp/QMCMain.h
- src/QMCDrivers/CorrelatedSampling/CSVMC.cpp
- src/QMCDrivers/DMC/DMC.cpp
- src/QMCDrivers/DMC/DMC_CUDA.cpp
- src/QMCDrivers/QMCDriver.cpp
- src/QMCDrivers/QMCDriver.h
- src/QMCDrivers/QMCDriverFactory.cpp
- src/QMCDrivers/QMCDriverFactory.h
- src/QMCDrivers/QMCDriverInterface.h
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCDrivers/QMCDriverNew.h
- src/QMCDrivers/RMC/RMC.cpp
- src/QMCDrivers/VMC/VMC.cpp
- src/QMCDrivers/VMC/VMCLinearOpt.cpp
- src/QMCDrivers/tests/test_QMCDriverFactory.cpp
- src/QMCDrivers/tests/test_QMCDriverFactory_CUDA.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantCUDA.h
Once a QMC section execution is completed, the driver is saved in last_driver object.
On a following QMC section, a new driver is created and last_driver is only release when it is being overwritten again.
In this PR, last_drive is only kept when a QMC input section is in a loop and gets cleaned up when the loop finishes.
If not a loop, a QMC driver object is destructed once that section execution is completed.
- No
ryzen-box
> Restrict use of last_driver and clean up the life cycle of driver objects

- src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp
- src/QMCHamiltonians/OperatorBase.cpp
The `mw_evaluateWithParameterDerivatives` code needs to handle `dlogpsi` as an input, and `dhpsioverpsi` as an output (more precisely, an input that needs to be updated)
For the batch cost function in `checkConfigurations`, the `includeNonLocalH` value needs to be passed to the lambda so the NLPP value can be removed from the fixed energy when present.  Unfortunately, most of the diff is due to formatting changes from clang-format.
For the correlated sampling part, `compute_nlpp` needs to be passed to the lambda, and the branch that calls `QMCHamiltonain::flex_evaluateValueAndDerivatives` added.
- Bugfix
- No
laptop
simply a …
> Fix NLPP derivatives

- src/QMCDrivers/MCPopulation.h
- src/QMCDrivers/QMCDriverNew.h
- src/QMCDrivers/WaveFunctionTester.cpp
- src/QMCDrivers/tests/ValidQMCInputSections.h
- src/QMCDrivers/tests/test_DMCBatched.cpp
- src/QMCDrivers/tests/test_QMCDriverNew.cpp
- src/QMCWaveFunctions/Fermion/SlaterDet.cpp
- src/QMCWaveFunctions/Fermion/SlaterDet.h
- src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.cpp
The driver unit test was failing on graphic card with 8 GB memory, the root cause was that the DiracDeterminant objects are not freed in properly in SlaterDet. The second change is reducing the number of walkers + reserve in unit test from 32+16 to 8+2, the reduction of memory usage allows GPUs with 4GB memory to pass that unit test and it should help out cdash to be more green.
More clean up fix by changing raw pointer to lvalue unique_ptr will come after. Much more affected files and more testing needed.
- Bugfix
- No
> Fix memory leak in slaterdet

- src/QMCHamiltonians/tests/test_ecp.cpp
- src/QMCWaveFunctions/ElectronGas/ElectronGasComplexOrbitalBuilder.cpp
- src/QMCWaveFunctions/ElectronGas/ElectronGasOrbitalBuilder.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminant.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantCUDA.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantCUDA.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.h
- src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp
- src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.h
- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminant.cpp
- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminant.h
- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantFast.h
- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantWithBackflow.cpp
- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantWithBackflow.h
- src/QMCWaveFunctions/Fermion/SPOSetProxyForMSD.cpp
- src/QMCWaveFunctions/Fermion/SPOSetProxyForMSD.h
- src/QMCWaveFunctions/Fermion/SlaterDet.cpp
- src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
- src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.cpp
- src/QMCWaveFunctions/PlaneWave/PWOrbitalBuilder.cpp
- src/QMCWaveFunctions/PlaneWave/PWOrbitalBuilder.h
- src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
- src/QMCWaveFunctions/tests/test_dirac_det.cpp
Use smart pointers of SPOSet in single det and multi dets. Reduce potential memory leak.
1. single det class uses shared_ptr. The sharing aspect is only intended for a list of single dets in multi-det slow code path. In most cases, it should be used as unique_ptr. Comments added in the source code.
2. Multi det uses unique_ptr.
- Bugfix
- No
Bora
> Smart pointers of SPOSet in singledet and multidet

- src/Message/tests/test_communciate.cpp
- src/Particle/MCWalkerConfiguration.cpp
- src/Particle/MCWalkerConfiguration.h
- src/Particle/ParticleSetPool.cpp
- src/Particle/ParticleSetPool.h
- src/Particle/tests/test_particle_pool.cpp
- src/Particle/tests/test_sample_stack.cpp
- src/QMCDrivers/MCPopulation.cpp
- src/QMCHamiltonians/tests/test_ecp.cpp
- src/QMCHamiltonians/tests/test_hamiltonian_pool.cpp
- src/QMCWaveFunctions/tests/test_MO_spinor.cpp
- src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
- src/QMCWaveFunctions/tests/test_einset.cpp
- src/QMCWaveFunctions/tests/test_einset_spinor.cpp
- src/QMCWaveFunctions/tests/test_example_he.cpp
- src/QMCWaveFunctions/tests/test_hybridrep.cpp
- src/QMCWaveFunctions/tests/test_kspace_jastrow.cpp
- src/QMCWaveFunctions/tests/test_lattice_gaussian.cpp
- src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp
- src/QMCWaveFunctions/tests/test_pw.cpp
- src/QMCWaveFunctions/tests/test_rpa_jastrow.cpp
- src/QMCWaveFunctions/tests/test_spo_collection_input_LCAO_xml.cpp
- src/QMCWaveFunctions/tests/test_spo_collection_input_MSD_LCAO_h5.cpp
- src/QMCWaveFunctions/tests/test_spo_collection_input_spline.cpp
- src/QMCWaveFunctions/tests/test_wavefunction_factory.cpp
Make sure ParticleSet gold copy owned by ParticleSetPool got freed properly.
- Bugfix
- No
bora
> Delete pointers owned by ParticleSetPool

- nexus/bin/qmc-fit
Expand integer type check of reblock_factors input to qmc-fit to include numpy integer types.  This enables correct application of a single user provided reblocking factor to each timestep data series.
This issue was reported by Gopal Iyer.
- Bugfix
- No
Laptop
> Nexus: fix type check for reblock_factors in qmc-fit

- external_codes/catch/complex_approx.hpp
- external_codes/catch/log_complex_approx.hpp
As `std::numeric_limits<T>` is used, `<limits>` header file should be included.
- Bugfix
- No
Bora
> Add include limits C++ header

- src/QMCWaveFunctions/TrialWaveFunction.cpp
If recompute is true (which it is for NLPP derivatives), need to call mw_evaluateLog to ensure the matrix inverses are computed
prior to the NLPP derivative computation.   This needs to done for wavefunction components that were *not* updated in the first part of the function.
The test case (NiO) that shows the problem has a determinant part with no variational parameters.
The cost function has two parts that compute the derivatives - the first one does setup and derivative computation (`checkConfigurations`).  The second one does correlated sampling (`correlatedSampling`), and only computes parts of the wavefunction that change (i.e that have optimizable variational parameters).
The problem doesn't manifest in `checkConfiguations` because evaluateLog is called on all wavefunction …
> Fix evaluation of non-optimizable components in flex_evaluateDeltaLog.

- CMake/macros.cmake
- docs/integration_tests.rst
Al.ccECP.xml was not being copied, breaking Al periodic Gaussian tests. e.g. https://cdash.qmcpack.org/CDash/testDetails.php?test=11358261&build=172864 . Trivial bug introduced with mid-December cmake macro update for selective file copies.
- Bugfix
- No
None. Fix based on cdash error log.
> Copy ccECP in CMake

- src/QMCHamiltonians/ACForce.cpp
- src/QMCHamiltonians/ACForce.h
- src/QMCHamiltonians/CMakeLists.txt
- src/QMCHamiltonians/CoulombPotentialFactory.cpp
- src/QMCHamiltonians/NonLocalECPotential.cpp
- src/QMCHamiltonians/NonLocalECPotential.h
- src/QMCHamiltonians/OperatorBase.cpp
- src/QMCHamiltonians/OperatorBase.h
- src/QMCHamiltonians/QMCHamiltonian.cpp
- src/QMCHamiltonians/QMCHamiltonian.h
- src/QMCHamiltonians/SpaceWarpTransformation.cpp
- src/QMCHamiltonians/SpaceWarpTransformation.h
- src/QMCHamiltonians/tests/CMakeLists.txt
- src/QMCHamiltonians/tests/Na2.structure.xml
- src/QMCHamiltonians/tests/test_spacewarp.cpp
This implements a preliminary reference version of the space-warp transformation for ZVZB force estimators, given in https://doi.org/10.1063/1.3516208.  Currently, Grad_i(E_L) w.r.t. electron coordinates is handled through finite differences, but replacement with analytic derivatives should reasonably occur within the current infrastructure.  
- New feature
- No
Local intel Xeon server.
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed.  
> Reference Space Warp Transformation for ZVZB Forces

- tests/test_automation/nightly_test_scripts/nightly_ornl.sh
- tests/test_automation/nightly_test_scripts/ornl_setup.sh
- tests/test_automation/nightly_test_scripts/ornl_update.sh
- tests/test_automation/nightly_test_scripts/ornl_versions.sh
Latest versions of nightly integration scripts for nitrogen+sulfur. Includes updated PySCF build. These are in use but a few problems remain. The gccnew route (gcc 10.2, all the python dependencies etc.) that is most used in testing is believed to be complete and fully functional.
Versions of installed packages are selected based on those that could be made to work while roughly following the two-year support rule. Several new workarounds are needed for new spack problems that prevent standard packages from building on these systems, e.g. perl (any compiler), python (gccold fails but gccnew is OK). The problems seem to mainly result from missing build and runtime dependencies in the spack packages resulting in unintended usage of system libraries that may not be suitable.
- Build related …
> Update recipes for nightly tests

- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp
The VMC timers for these objects have the same scope as the object lifetime (that is - timer starts in the constructor, and stops in the destructor).
The call to make_unique creates the new object first, and then deletes the old object.  This causes an incorrect ordering in the timers. (The new timer starts before the old timer stops.)
This results in an error message - "Timer stack pop not matching push". The printed timer results also show VMC nested under VMC.
The fix is to force the old object to destroyed before the new object is created.
- Bugfix
- No
laptop
simply a reminder of what we are going to look for before merging …
> Hack for correct VMC timer ordering

- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/QMCWaveFunctions/Fermion/DiracDeterminant.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminant.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h
- src/QMCWaveFunctions/Fermion/SlaterDet.cpp
- src/QMCWaveFunctions/Fermion/SlaterDet.h
- src/QMCWaveFunctions/Jastrow/J1OrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/WaveFunctionComponent.cpp
- src/QMCWaveFunctions/WaveFunctionComponent.h
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
In order to clean up buffers, I need this new set of APIs to do the compute work used to be in updateBuffer.
Slow fallback is in-place to ensure correctness.
- New feature
- No
Bora
> Add evaluateGL apis to TWF

- src/Particle/MCSample.h
- src/QMCDrivers/Crowd.cpp
- src/QMCDrivers/Crowd.h
- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCDrivers/DMC/DMCBatched.h
- src/QMCDrivers/DMC/WalkerControlMPI.cpp
- src/QMCDrivers/MCPopulation.cpp
- src/QMCDrivers/MCPopulation.h
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCDrivers/VMC/VMCBatched.cpp
- src/QMCDrivers/WalkerControlBase.cpp
- src/QMCWaveFunctions/TrialWaveFunction.cpp
Using a buffer to fuse data transfer is efficient but error prone. This PR removes almost all buffer operations in batched drivers leveraging #2848.
1. This PR also reduced interaction with the list of lightweight walkers owned by MCPopulation. The eventual goal is to get them removed. the list of lightweight walkers is only intended to used outside drivers or carry data between drivers not inside drivers.
2. Restore the recompute capability for determinants.
3. DMC without MPI is fixed as tests reporting pass. Consider the test check was not made tight. It can be buggy. With MPI still getting bad memory access.
Since the buffer motion is cleaned up, the walker exchange part is my next target.
- No
Bora
- Yes. This PR is up to date …
> Drop WF buffers used in batched drivers

- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_LiH-arb-drift.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_LiH-arb.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_LiH-gamma-drift.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_LiH-gamma.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_LiH-x-drift.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_LiH-x.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_LiH-x_hybridrep.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmc_short_LiH-arb.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmc_short_LiH-gamma.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmc_short_LiH-x.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmcnl_short_LiH-arb.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmcnl_short_LiH-gamma.xml
- tests/solids/LiH_solid_1x1x1_pp/hf_vmc_dmcnl_short_LiH-x.xml
- tests/solids/LiH_solid_1x1x1_pp/md_cc_vmc_LiH-gamma.xml
- tests/solids/LiH_solid_1x1x1_pp/md_rc_vmc_LiH-gamma.xml
Increase equilibration from 100 to 400 steps to hopefully reduce sporadic many-sigma failures seen in converter tests. Increased error bars may also be needed in a later PR. Tests are significantly longer than equilibration time so runtime impact should be negligible.
- Bugfix
- No
sulfur
> Increase LiH 1x1x1 equilibration

- src/Concurrency/ParallelExecutorOPENMP.hpp
- src/QMCDrivers/VMC/VMCBatched.cpp
- src/Utilities/NewTimer.cpp
- src/Utilities/TimerManager.cpp
- src/Utilities/TimerManager.h
- src/Utilities/tests/test_timer.cpp
1. Some error traps in NewTimer class are moved to TimerManager. Now if an error was detected, the code will stop instead of just print an error. Usually an error in the timer indicates pathological call flow, it is better to do a hard stop. Because exception can be thrown via TimerManager::pop_timer() called by ScopedTimer destructor, it is better to print the full error message right away instead of via runtime_error object which may get lost due to destructors being implicitly noexcept by default.
2. A bug was fixed in timer unit test.
3. The fix to unpaired timer call is trivial.
- Bugfix
- No
Epyc-server
> Enhance TimerManager and fix a missing timer stop() call in VMCbatched driver

- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCDrivers/WFOpt/QMCCostFunctionBatched.h
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h
- src/QMCDrivers/WFOpt/QMCLinearOptimizeBatched.cpp
- src/QMCDrivers/WFOpt/QMCLinearOptimizeBatched.h
- tests/molecules/He_ae/CMakeLists.txt
The counterpart to #2700 for the linear optimizer.   Mostly changing names and moving a few things around to match QMCDriverNew.
Two changes that are not among the above
- `QMCLinearOptimizeBatched::put` was removed (rather than rename to process).  It is not called, and confusingly duplicates code in `QMCFixedSampleLinearOptimizeBatched`.
- Rng handling in the QMCDriverNew destructor.   The previous code leads to a segfault (null Rng pointer) when VMC follows an optimizer run.   See the comment for more details.
The test deterministic-He_ae-opt_vmc-batch-1-1-totenergy fails.  I think the value just needs to be updated, but I need to look into it more.
- New feature
- No
laptop
_Update the following …
> Change base class of linear optimizer to QMCDriverNew

- src/QMCDrivers/CMakeLists.txt
- src/QMCDrivers/WFOpt/OutputMatrix.cpp
- src/QMCDrivers/WFOpt/OutputMatrix.h
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.cpp
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimize.h
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.cpp
- src/QMCDrivers/WFOpt/QMCFixedSampleLinearOptimizeBatched.h
Output linear method matrices (overlap and Hamiltonian) in scalar.dat format.
They can be processed with qmca and check_scalars.py, and compared between the batched and non-batched versions of the code.
A separate option (`freeze_parameters`) disables updating the parameters so the output can be used for statistics.
Enable by adding the parameters `output_matrices` and `freeze_parameters` to the qmc block
```
<qmc method="linear_batch" move="pbyp" checkpoint="-1">
<parameter name="output_matrices">yes</parameter>
<parameter name="freeze_parameters">yes</parameter>
```
- New feature
- No
laptop
simply a reminder of what we are …
> Output linear matrices

- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
bug fix on a buffer size. spotted in batched_driver performance tests.
- Bugfix
- No
epyc-server
> Fix bug in DiracDeterminantBatched

- src/QMCDrivers/DMC/WalkerControl.h
- src/QMCDrivers/MCPopulation.cpp
- src/Utilities/TimerManager.cpp
- src/Utilities/TimerManager.h
1. protect TWF::makeClone call under "omp critical". offload classes makeClone should be thread-safe but it is not the case. Not fully understand the issue. Put a workaround now.
2. "omp critical" cannot be nested use mutex in timer manager.
3. fix clang warning
- Bugfix
- No
epyc-server
> Fix parallel walker creation in batched drivers

- nexus/bin/qdens
- nexus/lib/qmcpack_input.py
Add support for input file read/write and output postprocessing (via qdens) of current form of batched spin density estimator.
- New feature
- No
Laptop
> Nexus: support batched spin density estimator

- src/AFQMC/Numerics/detail/CPU/lapack_cpu.hpp
- src/AFQMC/SlaterDeterminantOperations/rotate.hpp
- src/Platforms/CPU/BLAS.hpp
- src/Platforms/CPU/Blasf.h
Reduce Clang warning and remove MKL bits in BLAS.hpp, Blas.f because AFQMC doesn't use these header files.
- No
Bora
> Fix AFQMC clang unused function warning

- src/Particle/Walker.h
- src/QMCDrivers/DMC/DMCFactoryNew.cpp
- src/QMCDrivers/VMC/VMCFactoryNew.cpp
- tests/solids/diamondC_2x1x1_pp/CMakeLists.txt
Fix breakage #2855 and protect inaccessible code pathes which their tests skipped.
- Bugfix
- No
epyc-server
> Fix legacy CUDA DMC breakage

- src/QMCHamiltonians/CudaCoulomb.cu
- src/QMCHamiltonians/NLPP.cu
- src/QMCWaveFunctions/detail/CUDA_legacy/determinant_update.cu
Fix reported bugs by Andrea Zen / Dario Alfe where the legacy CUDA code will give clearly wrong energies for certain calculations. The symptom is a total energy as well as several subcomponents of the total energy that vary significantly with walker count. This problem was initially discovered via non-sensical DMC results, but the problems also occur in VMC.
Bugs are traced to handful of potential race conditions in the kernels associated with Coulomb energy evaluation. These bugs are present in Volta generation and more recent GPUs due to their independent thread scheduling. Our regular testing for e.g. carbon diamond did not identify them.
A side effect of these fixes is that the legacy CUDA code now appears to be completely deterministic.
Despite the extra syncthreads calls, running …
> Fix race conditions in CUDA kernels causing incorrect energies

- src/AFQMC/Hamiltonians/RealDenseHamiltonian.cpp
- src/AFQMC/Hamiltonians/RealDenseHamiltonian_v2.cpp
- src/AFQMC/Walkers/WalkerIO.hpp
- src/AFQMC/Walkers/tests/test_sharedwset.cpp
- src/Numerics/OneDimCubicSpline.h
- src/Numerics/OneDimGridFunctor.h
- src/Numerics/OneDimLinearSpline.h
- src/Numerics/OneDimQuinticSpline.h
- src/OhmmsApp/RandomNumberControl.cpp
- src/Particle/HDFWalkerInput_0_4.cpp
- src/Particle/HDFWalkerOutput.cpp
- src/Particle/HDFWalkerOutput.h
- src/Platforms/CPU/BLAS.hpp
- src/Platforms/CUDA/CUDAallocator.hpp
- src/Platforms/allocator_traits.hpp
- src/Platforms/tests/OMPTarget/test_class_member.cpp
- src/QMCWaveFunctions/tests/FakeSPO.cpp
- src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/tests/test_dirac_det.cpp
- src/Utilities/BoostRandom.h
- src/io/hdf/hdf_hyperslab.h
- src/io/tests/hdf/test_hdf_hyperslab.cpp
Make io/hdf only accept size_t not int. Seems a nice thing to have.
PGI complains about "void static". Changed to "static void"
Make some suspicious virtual function overriding explicit.
Restart tests pass.
- No
epyc-server
> Make hdf5 io interfaces respect size_t and reduce NVHPC compiler warnings

- src/CMakeLists.txt
- src/QMCDrivers/Crowd.cpp
- src/QMCDrivers/Crowd.h
- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCDrivers/DMC/WalkerControl.cpp
- src/QMCDrivers/DMC/WalkerControl.h
- src/QMCDrivers/MCPopulation.h
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCDrivers/VMC/VMCBatched.cpp
- src/QMCDrivers/tests/WalkerConsumer.h
- src/QMCWaveFunctions/BsplineFactory/BsplineSet.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h
- src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h
- src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h
- src/QMCWaveFunctions/Fermion/SlaterDet.cpp
- src/QMCWaveFunctions/Fermion/SlaterDet.h
- src/QMCWaveFunctions/SPOSet.cpp
- src/QMCWaveFunctions/SPOSet.h
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/WaveFunctionComponent.h
- src/Utilities/Resource.h
- src/Utilities/ResourceCollection.cpp
- src/Utilities/ResourceCollection.h
- src/Utilities/tests/CMakeLists.txt
- src/Utilities/tests/test_ResourceCollection.cpp
- tests/solids/diamondC_2x1x1_pp/CMakeLists.txt
- tests/solids/diamondC_2x1x1_pp/qmc_short_sdbatch_vmcbatch_dmcbatch.in.xml
Add Resource and ResourceCollection for managing shared resource of a set of walkers (crowd/population).
They are unit tested.
introduce CUDALinearAlgebraHandles resource to MatrixDelayedUpdateCUDA. No more create one per walker.
Also add more mw_ routines specialization in DiracDeterminantBatched and spline SPO.
Ready for connecting batched matrix inversion.
Address #2874 VMCBatched is ready.
- New feature
- Yes. DMC batch is broken but fixed by a follow-up PR. better to review separately.
Epyc-server
> Manage crowd shared resource

- src/AFQMC/Estimators/tests/test_estimators.cpp
- src/AFQMC/HamiltonianOperations/tests/test_hamiltonian_operations.cpp
- src/AFQMC/Propagators/tests/test_propagator_factory.cpp
- src/AFQMC/Utilities/test_utils.hpp
- src/AFQMC/Wavefunctions/tests/test_phmsd.cpp
- src/AFQMC/Wavefunctions/tests/test_wfn_factory.cpp
I noticed that AFQMC unit tests skip runs and report pass if h5 files for hamiltonian and wf are not found. I think this goes against the purpose of unit test. Now I converged all the file checks to a single routine and I would like to eventually throw error if files are not found. So far I cannot do this change because test deterministic-unit_test_afqmc_phmsd fails with missing files.
- No
epyc-server
> Converging AFQMC unit test file check

- src/QMCTools/ppconvert/src/NLPPClass.cc
- src/QMCTools/ppconvert/src/NLPPClass.h
- src/QMCTools/ppconvert/src/common/Blitz.h
- src/QMCTools/ppconvert/src/common/CubicSplineCommon.h
- src/QMCTools/ppconvert/src/common/DFTAtom.cc
- src/QMCTools/ppconvert/src/common/Fitting.cc
- src/QMCTools/ppconvert/src/common/Grid.h
- src/QMCTools/ppconvert/src/common/IO.cc
- src/QMCTools/ppconvert/src/common/IOASCII.cc
- src/QMCTools/ppconvert/src/common/IOASCII.h
- src/QMCTools/ppconvert/src/common/IOVar.h
- src/QMCTools/ppconvert/src/common/IOVarASCII.h
- src/QMCTools/ppconvert/src/common/IOVarBase.h
- src/QMCTools/ppconvert/src/common/MatrixOps.cc
- src/QMCTools/ppconvert/src/common/MatrixOps.h
- src/QMCTools/ppconvert/src/common/NLPP.cc
- src/QMCTools/ppconvert/src/common/NLPP.h
- src/QMCTools/ppconvert/src/common/NonlinearFit.h
- src/QMCTools/ppconvert/src/common/OptimizedBreakup.h
- src/QMCTools/ppconvert/src/common/Potential.cc
- src/QMCTools/ppconvert/src/common/RadialWF.cc
Remove the use of global namespace in source of ppconvert (`using namespace blitz / std; `).
This will help refactor the code.
- No
> remove global namespaces blitz and std

- nexus/lib/pseudopotential.py
When writing pseudopotential to QMCPACK form, there is an issue if the local channel is _h_ -- namely, the _l_-value of the local channel (l_local) is set to -1 in this case. This PR resolves this. 
Note: The channels are now coded up to 'i'. Furthermore, I think the CASINO code also has the same issue. If so, I can fix this as well along with this PR.
- Bugfix
- No
Laptop
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being …
> Nexus: Add h-channel to list of possible local channels in pseudopotential.

- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
- tests/solids/diamondC_2x1x1_pp/det_qmc_short_vmcbatch_dmcbatch_mwalkers.in.xml
- tests/solids/diamondC_2x1x1_pp/det_qmc_short_vmcbatch_mwalkers.in.xml
- tests/solids/diamondC_2x1x1_pp/qmc_short_vmcbatch_4b.in.xml
1. @markdewing suggested this fix. Removing the 1 electron special case which has been covered by the generic case.
2. Add batch="no" to deterministic tests which have corresponding batch="yes" tests already.
- Bugfix
- No
bora
> Fix determinisitic opt test failures in offload

- src/AFQMC/Drivers/AFQMCDriver.cpp
- src/AFQMC/Estimators/BasicEstimator.h
Stop AFQMC block timer at the end of the simulation.
block_timer is stopped in `BasicEstimator::print_timers` right before it prints to output, then started right after print.
This leaves the block_timer running after the last block.
- Bugfix
- No
Fedora 32, E5-2620 v2, gcc 10.2.1, intel 19.1.2
> stop block_timer at blocks end

- src/Containers/OhmmsPETE/OhmmsMatrix.h
- src/Particle/ParticleSet.cpp
- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
1. DMC batched driver was rejecting a move twice when fixed node sign change happens. This was caused by debug build assertions.
2. Batched determinant has a race when CUDA transfer has not been completed but OpenMP transfer was asked for. This was the root cause of unstable deterministic tests. Also debug build defensive assertion caught this. Additional assertions have been added.
- Bugfix
- No
Bora
> Fix two bugs in walker batched runs

- src/AFQMC/Drivers/DriverFactory.cpp
- src/AFQMC/Propagators/tests/test_propagator_factory.cpp
- src/AFQMC/Utilities/test_utils.hpp
- src/AFQMC/Wavefunctions/WavefunctionFactory.cpp
- src/AFQMC/Wavefunctions/WavefunctionFactory.h
- src/AFQMC/Wavefunctions/tests/test_wfn_factory.cpp
Concentrate wavefunction restart logic in `WavefunctionFactory::getHamOps`.
Allow user to restart without changing the input file as discussed in #2872
Once this PR is merged, issue #2851 should be fully addressed.
`WavefunctionFactory::fromASCII` is poised for deprecation, so I put an abort when that code path hits restart.
- Bugfix
- No
Fedora 32, E5-2620 v2, gcc 10.2.1, intel 19.1.2
> revamp wavefunction restart logic in AFQMC

- docs/developing.rst
- src/Particle/DistanceTableData.h
- src/Particle/DynamicCoordinates.h
- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/Particle/RealSpacePositions.h
- src/Particle/RealSpacePositionsOMPTarget.h
- src/Particle/SoaDistanceTableAA.h
- src/Particle/SoaDistanceTableAAOMPTarget.h
- src/Particle/SoaDistanceTableAB.h
- src/Particle/SoaDistanceTableABOMPTarget.h
- src/QMCDrivers/CorrelatedSampling/CSVMCUpdatePbyP.cpp
- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCDrivers/DMC/DMCUpdatePbyPFast.cpp
- src/QMCDrivers/DMC/DMCUpdatePbyPL2.cpp
- src/QMCDrivers/DMC/SODMCUpdatePbyPFast.cpp
- src/QMCDrivers/RMC/RMCUpdatePbyP.cpp
- src/QMCDrivers/VMC/SOVMCUpdatePbyP.cpp
- src/QMCDrivers/VMC/VMCBatched.cpp
- src/QMCDrivers/VMC/VMCUpdatePbyP.cpp
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
1. Clean up the accept/reject single particle move logic. Two modes regular and forward mode documented in PartcleSet.h
2. Full documentation for DynamicCoordinates class.
- Refactoring with api changes
- No
Epyc-server
> Explicit two modes of distance table operations

- src/AFQMC/Numerics/detail/CUDA/sparse_cuda_gpu_ptr.hpp
Warning removal.
- No
epyc-server
> Stop cusparse(11.4) warning since CUDA 11.2.1.

- src/QMCDrivers/Crowd.cpp
- src/QMCDrivers/Crowd.h
- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCDrivers/DMC/WalkerControl.cpp
- src/QMCDrivers/DMC/WalkerControl.h
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCDrivers/QMCDriverNew.h
- src/QMCDrivers/VMC/VMCBatched.cpp
- src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp
- src/QMCDrivers/tests/test_Crowd.cpp
- src/QMCDrivers/tests/test_SFNBranch.cpp
- src/QMCHamiltonians/NonLocalECPComponent.cpp
- src/QMCHamiltonians/NonLocalECPComponent.h
- src/QMCHamiltonians/NonLocalECPotential.cpp
- src/QMCHamiltonians/NonLocalECPotential_CUDA.h
- src/QMCWaveFunctions/CMakeLists.txt
- src/QMCWaveFunctions/TWFdispatcher.cpp
- src/QMCWaveFunctions/TWFdispatcher.h
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/TrialWaveFunction.h
- src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_He.cpp
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
When called from the driver, the flex API is doing dispatch to single walker or multi walker on per-call basis. It is often enter corner cases when the number of walker in a crowd drops to 1. This PR change
```C++
TrialWaveFunction::flex_evaluate()
{
if(nw >1)
{ batched operation }
else if (nw ==1)
{ single walker }
}
```
into
```C++
TrialWaveFunction::mw_evaluate()
{
{ batched operation }
}
```
and
```C++
TWFdispatcher::flex_evaluate()
{
if (use_batch)
TrialWaveFunction::mw_evaluate
else
loop over walker
{ single walker }
}
```
use_batch is selected per driver. Input control will be added once the ParticleSet flex_ APIs are updated.
- New feature
- No
epyc-server
> Split flex_ APIs in TWF

- src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp
The default for the second argument, skipSK, is false.
Fixes #2959
- Bugfix
- No
desktop
- N/A Documentation has been added (if appropriate)
> Restore previous arguments to flex_update

- src/QMCTools/PyscfToQmcpack_Spline.py
Close #2956 
Removed dataset.value attribute in PyscfToQmcpack_Spline.py. This is no longer available since h5py 3.0.0.
- Bugfix
- No
Intel Xeon
> Remove dataset.value attribute on PyscfToQmcpack_Spline.py

- CMake/macros.cmake
- examples/solids/pyscf-inputs/diamondC_1x1x1_pp_Bspline.py
- examples/solids/pyscf-inputs/diamondC_1x1x1_pp_LCAO.py
- src/QMCTools/PyscfToQmcpack_Spline.py
- tests/pyscf/CMakeLists.txt
Periodic PySCF runs check SCF convergence + check for text indicating our custom HDF5 files were created.
Fix a missing wfj copy that broke the bspline test.
- Bugfix
- No
Nitrogen, ~nightly configuration.
(When running ctest interactively I need to set OMP_NUM_THREADS=1 presumably due to threading issues with OpenBLAS or PySCF causing a bad SCF. The nightlies currently run OK.)
> Improve and fix PySCF tests

- src/Particle/CMakeLists.txt
- src/Particle/PSdispatcher.cpp
- src/Particle/PSdispatcher.h
- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/Particle/VirtualParticleSet.cpp
- src/Particle/VirtualParticleSet.h
- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCDrivers/DMC/WalkerControl.cpp
- src/QMCDrivers/MultiWalkerDispatchers.h
- src/QMCDrivers/QMCDriverInput.cpp
- src/QMCDrivers/QMCDriverInput.h
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCDrivers/VMC/VMCBatched.cpp
- src/QMCDrivers/WFOpt/QMCCostFunctionBatched.cpp
- src/QMCHamiltonians/Hdispatcher.cpp
- src/QMCHamiltonians/Hdispatcher.h
- src/QMCHamiltonians/NonLocalECPComponent.cpp
- src/QMCHamiltonians/QMCHamiltonian.cpp
- src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.cpp
- src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h
- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.cpp
- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h
- src/QMCWaveFunctions/BsplineFactory/SplineOMPTargetMultiWalkerMem.h
- src/QMCWaveFunctions/TWFdispatcher.cpp
- src/QMCWaveFunctions/TWFdispatcher.h
- src/QMCWaveFunctions/tests/test_TrialWaveFunction.cpp
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp
- src/Utilities/ScopedProfiler.h
1, Split flex_ APIs in ParticleSet to PSdispatcher.h
2. Introduce "crowd_serialize_walkers" driver input tag to force flex_ API loop over single walker calls. default no. It covers all the flex_ calls to ParticleSet, TrialWaveFunction and QMCHamiltonian.
In batched driver
1. crowd_serialize_walkers=no default case
batched_driver -> dispatcher::flex_update -> ParticleSet::mw_update (mw_ API fails back to serial internally if no specialization exists)
2. crowd_serialize_walkers=yes. This is intended for CPU only runs to bypass any overhead or CPU unfriendly implementation in batched code paths.
batched_driver -> dispatcher::flex_update -> loop over ParticleSet::update
- New feature
- No
epyc-server
> Split flex_ APIs in ParticleSet

- src/Particle/DistanceTableData.h
- src/Particle/ParticleSet.cpp
- src/Particle/SoaDistanceTableAA.h
- src/Particle/SoaDistanceTableAAOMPTarget.h
- src/Particle/SoaDistanceTableAB.h
- src/Particle/SoaDistanceTableABOMPTarget.h
- src/QMCDrivers/DMC/DMCUpdatePbyPFast.cpp
- src/QMCDrivers/QMCUpdateBase.cpp
- src/QMCDrivers/QMCUpdateBase.h
- src/QMCDrivers/VMC/VMCUpdatePbyP.cpp
- src/QMCWaveFunctions/LinearOrbital.h
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/tests/test_TrialWaveFunction_He.cpp
- tests/heg/heg_54_J2rpa/CMakeLists.txt
1. Add debug build checkLogAndGL assertion in non-batched code. Fortunately, caught nothing.
2. Move distance table partial update logic out of DT::update() to DT::updatePartial() more straight forward logic.
3. Fix https://cdash.qmcpack.org/CDash/testDetails.php?test=9533311&build=190366
4. Fix #2966 by bypassing a unit test not suitable for legacy CUDA. 
- Bugfix
- No
Bora
> Introduce debug build GL check in non-batched drivers and fix two tests

- src/AFQMC/Utilities/taskgroup.h
Remove extra restriction on "nnodes" because check already performed in setup.
also fix missed raw pointer from #2951
- Bugfix
- No
Lassen
> Remove extraneous restriction on "nnodes"

- src/AFQMC/Memory/device_pointers.hpp
solve problems in Jenkins
https://jenkins-ci.cels.anl.gov/job/QMCPACK-CI-Clang10-AFQMC-CUDA/347/label=compute002.mcs.anl.gov,type=Real-Mixed-enable-CUDA/console
- Bugfix
- No
Lassen, clang 10, cuda
> Clang CUDA AFQMC workaround device_allocator by defining uninitialized_copy at the allocator level

- nexus/bin/nxs-test
- nexus/lib/observables.py
- nexus/lib/testing.py
- nexus/tests/unit/test_qdens.py
- nexus/tests/unit/test_rmg_input.py
Fix failing tests on Summit.  Most of these are due to lack of guards for optional modules.  The test failure in #2958 was due to lack of an absolute tolerance on comparisons of near zero (+- machine epsilon) floating point values.
This PR addresses #2958.
- Bugfix
- No
Summit
> Nexus: fix tests on Summit

- src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.h
Request full ion-electron table ready at loadWalker for LCAO to fix spin-orbit case.
Without spin-orbit, evalGrad doesn't recompute SPO but read from stored values.
With spin-orbit, such values are recomputed. When LCAO is used, the old electron-ion pair distances are required.
For this reason, request full ion-electron table ready at loadWalker.
- Bugfix
- No
Ryzen-box
> Request full ion-electron table ready at loadWalker for LCAO

- src/QMCWaveFunctions/Fermion/DiracDeterminantBase.h
- src/QMCWaveFunctions/Fermion/SlaterDet.cpp
- src/QMCWaveFunctions/Fermion/SlaterDet.h
- src/QMCWaveFunctions/TrialWaveFunction.cpp
- src/QMCWaveFunctions/WaveFunctionComponent.cpp
- src/QMCWaveFunctions/WaveFunctionComponent.h
- src/QMCWaveFunctions/WaveFunctionPool.cpp
1. Use taskloop instead of task+taskwait. Keep the code simple
2. Write canonical loop in TWF. timer index is computed in-place instead of using the loop.
- No
Bora, Epyc-server
> Remove ratioGradAsync

- src/QMCApp/QMCMain.cpp
In QMC_CUDA case, the GPU to MPI rank assignment is handled differently from all the rest cases. So Just don't print in this place. The same info has been printed before this line.
```
Rank =    0  Free Memory = 268400 MB
1 MPI ranks on node(s) sulfur.ornl.gov with 1 appropriate CUDA devices.
<- Rank 0 will use CUDA device #0 (Tesla V100-PCIE-16GB)
Rank 0: relative rank number = 0, number of devices = 1
Assigned device numbers: 0
Default MAX_GPU_SPLINE_SIZE_MB is 81920 MB.
Input file(s): det_qmc_short_vmc_dmc.in.xml 
=====================================================
QMCPACK 3.10.9
```
Closes #3008
- Bugfix
- No
Bora
> Not print accelerator in QMC_CUDA build

- src/Particle/DistanceTableData.h
- src/Particle/DynamicCoordinates.h
- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/Particle/ParticleSetPool.cpp
- src/Particle/RealSpacePositionsOMPTarget.h
- src/Particle/SoaDistanceTableAAOMPTarget.h
- src/Particle/SoaDistanceTableABOMPTarget.h
- src/Particle/VirtualParticleSet.h
- src/QMCDrivers/Crowd.cpp
- src/QMCDrivers/Crowd.h
- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCDrivers/DriverWalkerTypes.h
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCDrivers/VMC/VMCBatched.cpp
- src/QMCDrivers/tests/test_Crowd.cpp
- src/QMCHamiltonians/NonLocalECPComponent.cpp
- src/QMCHamiltonians/NonLocalECPComponent.h
- src/QMCHamiltonians/NonLocalECPotential.cpp
- src/QMCHamiltonians/NonLocalECPotential.h
- src/QMCWaveFunctions/BsplineFactory/SplineC2COMPTarget.h
- src/QMCWaveFunctions/BsplineFactory/SplineC2ROMPTarget.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h
- src/Utilities/ResourceCollection.cpp
- src/Utilities/ResourceCollection.h
multi walker shared resources are assigned not to the leader of a crowd but a crowd with a leader. Memory views are set up and clean up when such assignment/release happens. This allows the distance table offload better optimized. 
- New feature
- No
epyc-server, summit
> Change ParticleSet resource management API

- src/Particle/DistanceTableData.h
- src/Particle/PSdispatcher.cpp
- src/Particle/PSdispatcher.h
- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/Particle/ParticleSetPool.cpp
- src/Particle/SoaDistanceTableABOMPTarget.h
- src/QMCDrivers/DMC/DMCBatched.cpp
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCHamiltonians/NonLocalECPComponent.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
- src/Utilities/ResourceCollection.h
Review after #3015
1. Add recompute mask to loadWalker to reduce recompute impact.
2. Take advantage of mask in mw_recompute in DiracDeterminantBatch
3. turn on distance table offload by default.
- New feature
- No
epyc-server, Summit
> Adjust recompute at the begining of a DMC step

- src/Platforms/OMPTarget/OMPallocator.hpp
- src/Platforms/OMPTarget/OffloadAlignedAllocators.hpp
- src/QMCDrivers/MCPopulation.h
- src/QMCDrivers/QMCDriverNew.cpp
- src/QMCHamiltonians/NonLocalECPComponent.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h
- src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h
- src/Utilities/ResourceCollection.cpp
1. Move multi walker memory to shared resource to stop increasing memory consumption over time.
2. Remove the 1 walker code path under NonLocalECPComponent::mw_evaluateOne(). An oversight from previous refactoring. The massive change shown here is caused by formatting.
- Bugfix
- New feature
- No
Summit
> Use multi walker memory shared resource in determinant update engines and remove 1 walker code path in NLPP

- src/Particle/SoaDistanceTableABOMPTarget.h
- src/QMCHamiltonians/CoulombPBCAA.cpp
1. Calling particleset update() in the constructor of CoulombPBCAA only make sense for inactive particles (ions).
2. In SoaDistanceTableABOMPTarget, actively free single walker memory before multi walker shared buffer is resized to avoid keep the memory twice.
- Bugfix
- No
Summit
> Use update call for inactive particleset only in CoulombPBCAA

- src/QMCWaveFunctions/Fermion/DiracDeterminantWithBackflow.h
- src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.cpp
- src/QMCWaveFunctions/Fermion/SlaterDetWithBackflow.h
Fix a breakage introduced in #3012
SlaterDetWithBackflow::evaluateLog has been corrected. All other changes are just adding override keyword to prevent future mistakes.
- Bugfix
- No
Bora
> Fix SlaterDetWithBackflow virtual function override mismatch

- src/QMCHamiltonians/tests/test_coulomb_CUDA.cpp
The unit test didn't mark Coulomb on ion inactive. Failure showed up in nightly.
- Bugfix
- No
epyc-server
> Fix legacy CUDA unit test.

- src/Particle/SoaDistanceTableABOMPTarget.h
The CUDA error shows up when there is odd number of electrons with full precision real build code.
When using a fused memory buffer for transferring data, it is necessary to fill larger objects than smaller ones. pointers 64 bit before RealType 64 bit or 32 bit before int 32bit.
- Bugfix
- No
Summit
> Resolve misaligned address in CUDA

- src/QMCWaveFunctions/Jastrow/DiffTwoBodyJastrowOrbital.h
- src/QMCWaveFunctions/tests/CMakeLists.txt
- src/QMCWaveFunctions/tests/test_DiffTwoBodyJastrowOrbital.cpp
Addresses #2814 (at least partially)
Add a unit test that will fail in one case where the offsets are not computed correctly.
Fix the offset calculation in the case the first function does not have any optimizable parameters.
- Bugfix
- No
laptop
> Fix index problem with 2-body Jastrow optimization

- nexus/lib/pwscf_analyzer.py
Small change to pwscf_analyzer. QE can print touching eigenvalues, e.g., `-144.9938-144.9938`, which then prevents the bands from being stored.
- Bugfix
- No
ORNL CADES
> Fix pwscf analyzer when eigenvalues touch

- docs/developing.rst
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h
- src/QMCWaveFunctions/Fermion/MatrixDelayedUpdateCUDA.h
- src/QMCWaveFunctions/Fermion/MatrixUpdateOMPTarget.h
This really bothered me in later code. If the naming convention indicates some thing is a type, please don't write
_TYPE
Type
Change DET_ENGINE_TYPE template parameter to DET_ENGINE
- No
Leconte
> Rename DET_ENGINE_TYPE to DET_ENGINE

- src/Optimize/VariableSet.cpp
- src/QMCWaveFunctions/Jastrow/DiffTwoBodyJastrowOrbital.h
- src/QMCWaveFunctions/tests/test_DiffTwoBodyJastrowOrbital.cpp
Remove inactive variables from myVars in order to construct correct mappings from sub-component variables to component variables, and from component variables to global variables (active).
Fixes #2814.  I believe this change also renders the change in #3040 moot.
- Bugfix
- No
Desktop
- N/A. Documentation has been added (if …
> Fix two body Jastrow optimizstion with inactive variables

- README.md
- codecov.yaml
Add status badges in Readme for the `develop` branch statuses of GitHub releases and CI actions, Spack, Codecov, Readthedocs, License
Filter out external codes in coverage
It just adds badges to Readme to have statuses, and GitHub and third-party links in one place.
Filters our external code from codecov coverage report.
- Other (please describe): simple standard badges
- No
Must be tested on GitHub markdown parser 
- No. Code added or changed in the PR has been clang-formatted (N/A)
- No. This PR adds tests to cover any new code, or to catch a bug …
> Add status badges in Readme

- LICENSE
- nexus/LICENSE
Remove the historical and confusing disclaimers about code covered by licenses other than the main UIUC/NCSA one. We have gone through the repository and removed or replaced historical sources thought to be covered by other licenses.
This PR does not attempt to update the main license. However I'll note that the developed by text  is certainly not current and the URL given is no longer valid. We'll have to consult about how to amend it in future. 
Added after initial PR: based on discussion below, removed the development history text from the NEXUS license file as well.
- Bugfix
- No
None. Docs only.
- NA. This PR adds tests to …
> Cleanup license file

- src/AFQMC/Estimators/Observables/full2rdm.hpp
- src/AFQMC/HamiltonianOperations/KP3IndexFactorization.hpp
- src/AFQMC/HamiltonianOperations/KP3IndexFactorization_batched.hpp
- src/AFQMC/HamiltonianOperations/Real3IndexFactorization.hpp
- src/AFQMC/HamiltonianOperations/Real3IndexFactorization_batched.hpp
- src/AFQMC/HamiltonianOperations/Real3IndexFactorization_batched_v2.hpp
- src/AFQMC/HamiltonianOperations/SparseTensor.hpp
- src/AFQMC/HamiltonianOperations/SparseTensorIO.hpp
- src/AFQMC/HamiltonianOperations/THCOps.hpp
- src/AFQMC/HamiltonianOperations/sparse_matrix_energy.hpp
- src/AFQMC/Hamiltonians/FactorizedSparseHamiltonian.cpp
- src/AFQMC/Hamiltonians/Hamiltonian_Utilities.hpp
- src/AFQMC/Hamiltonians/KPFactorizedHamiltonian.cpp
- src/AFQMC/Hamiltonians/THCHamiltonian.cpp
- src/Sandbox/einspline_spo.cpp
- src/Utilities/tests/test_timer.cpp
- src/config/stdlib/math.hpp
With out this fix, passing `-DQMC_COMPLEX=1` or `-DQMC_COMPLEX=ON`  to cmake behaves differently.
fixes #3036
- Bugfix
- No
epyc-server
> Use macro if defined(SWITCH) rather than if SWITCH.

- CMake/macros.cmake
In #3096, I tried to use `file(COPY ...)` to avoid an additional call to `EXECUTE_PROCESS`, but that changed behavior. I don't see anything in the documentation to get the same behavior as `copy_directory` without using `GLOB`. Instead of making things more complicated, this reverts that line to what it was previously.
Fixes #3101
- …
> Switching from copy_directory to file(COPY ...) changed behavior

- tests/solids/diamondC_1x1x1_pp/CMakeLists.txt
Close #3107 
Close #2765 
Deterministic-diamondC_1x1x1_pp-vmc-dmc-trace_scalars are failing in Sulfur and Ye-Ryzen-Box with ~ 1.2e-6 tolerance which is still acceptable for the mixed precision build. This PR is to adjust tolerance from 1.0e-6  to 2.0e-6 in order to cover the variations in the mixed precision build. 
- Bugfix
- No
Intel Xeon
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being …
> Adjust tolerance of deterministic-diamondC_1x1x1_pp-vmc-dmc-trace_scalars for mixed precision build

- CMakeLists.txt
- src/config.h.cmake.in
- src/qmcpack.settings
1. explicit list C and CXX in project language
2. identify compiler collection by CMAKE_CXX_COMPILER_ID only. The C one is ignored.
3. Error out if CMAKE_CXX_COMPILER_ID and CMAKE_C_COMPILER_ID don't match.
4. Use CMake project() to handle QMCPACK version.
- No
epyc-server
> [CMake] Cleanup compiler detection and change version handling

- src/Platforms/CUDA/CUDATypeMapping.hpp
- src/Platforms/CUDA/cuBLAS.hpp
- src/QMCWaveFunctions/detail/CUDA/cuBLAS_LU.cu
- src/type_traits/type_manipulation.hpp
Replace macro for CUDATypeMapping with template function doing the same thing.
Plus some improvement of naming.
Use the `castCUDAType` function for all the cases this occurs in `cuBLAS.hpp`
Workaround lack of second const on array of const pointers in batched API of cuBLAS.
- No
Leconte
This is WIP because it should be rebased on develop after #3122 has been merged.
- No. This PR is up to date with current the current state of 'develop'
> No more macro for cuda type casting

- config/build_olcf_summit_XL.sh
- src/Platforms/CUDA/CUDATypeMapping.hpp
Recent changes use more C++14 on the CUDA side and I have difficulty to teach the host compiler of nvcc using newer C++ so switch nvcc host compiler from XL to gcc when XL is used on Summit.
- No
Sunmit
> Update XL build recipe.

- .github/workflows/ci-github-actions.yaml
Restrict upload to codecov to QMCPACK org to prevent forks trying to access codecov.
- Bugfix: unintended consequence in forks that keep `develop` up to date showing errors when trying to upload to codecov
- Yes
Must pass GitHub Actions checks
- No. Code added or changed in the PR has been clang-formatted (NA)
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed (bug in forks)
> Restrict codecov coverage report upload from QMCPACK org

- nexus/lib/structure.py
This PR allows the user to supply an initial guess for the optimal tiling matrix. In some cases, this will allow the user to reach better tilings without the need to increase the search space through the `dn` argument.
- New feature
- No. All nxs-test cases pass.
Desktop
> Nexus: Add Tref (initial tilematrix) argument to optimal_tilematrix

- config/docker/dependencies/ubuntu/openmpi/Dockerfile
Migrate from `libopenblas-dev` to `libopenblas-openmp-dev` in Dockerfile and container used for CI (already pushed) with QMCPACK dependencies.
- Testing changes (e.g. new unit/integration/performance tests) : new container dependency
- No
Docker container running on Ubuntu 20.04, CI must pass with new updated container. …
> Update to libopenblas-openmp in Dockerfile and CI container

- nexus/lib/pwscf_analyzer.py
- nexus/lib/qmcpack.py
- nexus/lib/qmcpack_converters.py
- nexus/lib/simulation.py
Enable nexus to setup grand-canonical twist average grid using DFT Fermi energy and KS eigenvalues.
Activated when an occupation dependency is give to `generate_qmcpack`, e.g. `(p2q, 'gc_occupation')`
Tested using the attached BCC Li example:
[bcc-li-n16.zip](https://github.com/QMCPACK/qmcpack/files/6424040/bcc-li-n16.zip)
- New feature
- No
Fedora 32, E5-2620 v2, gcc 10.2.1, intel 19.1.2
- No. This PR adds tests to cover any new code, or to catch a bug …
> Nexus: support grand-canonical twist averaging

- nexus/lib/qmcpack_input.py
Add support for `maxcpusecs` and `max_seconds` inputs to QMCPACK in Nexus.
- New feature
- No
Laptop.
- Yes  This PR is up to date with current the current state of 'develop'
> Nexus: add max_seconds input

- src/QMCWaveFunctions/CMakeLists.txt
- src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.cpp
- src/QMCWaveFunctions/Jastrow/J2OrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/RPAJastrow.cpp
- src/QMCWaveFunctions/Jastrow/RPAJastrow.h
- src/QMCWaveFunctions/Jastrow/RadialJastrowBuilder.cpp
- src/QMCWaveFunctions/Jastrow/TwoBodyJastrowOrbitalBspline.h
- src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp
- src/QMCWaveFunctions/tests/test_rpa_jastrow.cpp
- src/QMCWaveFunctions/tests/test_wavefunction_factory.cpp
Split J2OrbitalSoA in to header and cpp files.
Fix breakage from last night. https://cdash.qmcpack.org/CDash/testDetails.php?test=13317843&build=209109
The bug existed before but triggered on legacy CUDA build.
- Bugfix
- No
epyc-server
> Split J2OrbitalSoA and fix unit test

- src/QMCHamiltonians/tests/CMakeLists.txt
Split it into coulomb, ham and force to speed up execution and results parsing.
Workaround texture limit https://cdash.qmcpack.org/CDash/testDetails.php?test=13317902&build=209114
This is caused by legacy CUDA not freeing texture and multiple runs of uni test cases exhausted the reserved pool.
- Bugfix
- No
epyc-server
> Split hamiltonian unit test

- src/QMCHamiltonians/NonLocalECPotential.h
- src/QMCWaveFunctions/tests/test_DiracMatrixComputeCUDA.cpp
- src/QMCWaveFunctions/tests/test_DiracMatrixComputeOMPTarget.cpp
Yesterday I pushed abusively slow unit tests to develop.  This should be ~1000 times faster.
- Bugfix
- No
Leconte
> Fixing slow matrix inversion unit tests.

- docs/hamiltonianobservable.rst
- src/QMCHamiltonians/ECPotentialBuilder.cpp
- src/QMCHamiltonians/tests/CMakeLists.txt
- src/QMCHamiltonians/tests/test_ion_derivs.cpp
- src/QMCTools/ppconvert/src/ParserClass.h
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/Fermion/DiracDeterminantBatched.h
- src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.2.cpp
- src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.cpp
- src/QMCWaveFunctions/Fermion/MultiDiracDeterminant.h
- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantFast.cpp
- src/QMCWaveFunctions/Fermion/MultiSlaterDeterminantFast.h
- src/QMCWaveFunctions/Fermion/SlaterDetBuilder.cpp
- src/QMCWaveFunctions/tests/CMakeLists.txt
- src/QMCWaveFunctions/tests/FakeSPO.cpp
- src/QMCWaveFunctions/tests/test_DiracDeterminant.cpp
- src/QMCWaveFunctions/tests/test_DiracDeterminantBatched.cpp
- src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp
- src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp
- tests/solids/diamondC_1x1x1-Gaussian_pp_MSD/CMakeLists.txt
- tests/solids/diamondC_2x1x1-Gaussian_pp_MSD/CMakeLists.txt
1. Implement batched NLPP in MSD.
2. mark "Fast" tag as deleted
3. NLPP input tag changes. Input value "default" is removed. No input given actually means default. Add "non-batched" to explicitly call the non-batched code path.
- New feature
- Yes. but I don't think algorithm="default" is actually used anywhere but development only
epyc-server
> Add MSD evaluateRatios and mark Fast tag as deleted

- docs/installation.rst
Fix ubuntu installation in docs. Add missing `sudo` and `install` keywords.
- No
Ubuntu 20.04, personal laptop
> Fix ubuntu installation in documentation

- .gitignore
- src/Particle/LongRange/LRHandlerBase.h
- src/Particle/LongRange/LRRPABFeeHandlerTemp.h
- src/Particle/LongRange/LRRPAHandlerTemp.h
- src/QMCWaveFunctions/DiffWaveFunctionComponent.h
- src/QMCWaveFunctions/WaveFunctionComponent.h
Minor PR to re-enable doxygen API documentation generation as it's currently broken due to latex symbols.
- Bugfix
- No
Ubuntu 20.04
> Fix doxygen formulas 

- src/Estimators/CSEnergyEstimator.cpp
- src/Estimators/CSEnergyEstimator.h
- src/Estimators/LocalEnergyEstimator.cpp
- src/Estimators/LocalEnergyEstimator.h
- src/Estimators/LocalEnergyOnlyEstimator.h
- src/Estimators/RMCLocalEnergyEstimator.cpp
- src/Estimators/RMCLocalEnergyEstimator.h
- src/Estimators/SpinDensityNew.cpp
- src/Estimators/SpinDensityNew.h
- src/Estimators/tests/FakeEstimator.h
- src/Estimators/tests/FakeOperatorEstimator.h
- src/Estimators/tests/test_local_energy_est.cpp
Consistently use covariant return types for the clone() member function in classes that inherit from ScalarEstimatorBase and OperatorEstBase.
This was found in #3190
- Bugfix
- No
simply a reminder of what we …
> Consistent use of covariant return type

- config/docker/dependencies/ubuntu/clang-latest/Dockerfile
- config/docker/dependencies/ubuntu/openmpi/Dockerfile
- docs/running_docker.rst
Add vim and serial hdf5 dev in docker images (already published in DockerHub) used for GitHub Actions CI.
- Other (please describe): Docker containers
- No
Ubuntu 20.04, CI will pull these containers
> Update docker images for CI

- CMake/PGICompilers.cmake
- src/Particle/SoaDistanceTableABOMPTarget.h
- src/Platforms/CMakeLists.txt
- src/Platforms/OMPTarget/CMakeLists.txt
- src/Platforms/OMPTarget/ompReduction.hpp
- src/Platforms/OMPTarget/test_user_defined_reduction_complex.cpp
- src/QMCHamiltonians/NonLocalECPComponent.cpp
- src/QMCWaveFunctions/BsplineFactory/HybridRepSetReader.h
1. NVHPC doesn't support user defined reduction(UDR). In this PR, CMake first test UDR. If it doesn't work try implicit reduction of complex, if it still doesn't work, stop.
2. Suppress a few PGI warnings.
NVHPC 21.5 now compiles fine but still has issues at run time.
The warnings are not PGI specific, we suppressed them in other compilers. @williamfgc good targets for software improvements.
- No
epyc-server
> Fix NVHPC OpenMP offload compilation and suppress a few warnings

- nexus/lib/qmcpack_input.py
Add support for the QMCPACK `delay_rank` keyword to Nexus.  Usage: `generate_qmcpack(..., delay_rank=5)`.
Persistence in the input (e.g. across inclusions of optimized wavefunctions from prior runs) is not guaranteed.  Later, a relocation of the keyword is preferred.  See also #3204.
- New feature
- No
Laptop
> Nexus: add delay_rank input

- src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h
- src/QMCWaveFunctions/Jastrow/eeI_JastrowBuilder.cpp
- src/QMCWaveFunctions/Jastrow/eeI_JastrowBuilder.h
Replace raw pointer with `std::unique_ptr` in `J3Unique` container as it produced a leak caught by `asan/lsan`.
Make `eeI_JastrowBuilder` a class and move `putkids` to a private scope.
This is a minor PR only affecting `deterministic-unit_test_wavefunction_jastrow`. It doesn't reinstate the test as there a more direct leaks.
- Bugfix: leak fix
- No
Ubuntu 20.04 , must pass CI
> Address leak related to functor in JastrowBuilder

- src/Message/CMakeLists.txt
- src/QMCWaveFunctions/tests/CMakeLists.txt
Compiling catch_main is slow. So better to keep fewer catch_main variants.
catch_benchmark_main is removed as catch_main turns on benchmark by default.
Overall compilation time change is noticeable but it becomes more friendly to partial build.
- No
epyc-server
> Fewer catch_main

- src/Particle/LongRange/EwaldHandler.cpp
- src/Particle/LongRange/EwaldHandler.h
- src/Particle/LongRange/EwaldHandler3D.cpp
- src/Particle/LongRange/EwaldHandler3D.h
- src/Particle/LongRange/LPQHIBasis.cpp
- src/Particle/LongRange/LPQHIBasis.h
- src/Particle/LongRange/LPQHISRCoulombBasis.cpp
- src/Particle/LongRange/LPQHISRCoulombBasis.h
- src/Particle/LongRange/LRBasis.h
- src/Particle/LongRange/LRBreakup.h
- src/Particle/LongRange/LRCoulombSingleton.cpp
- src/Particle/LongRange/LRHandlerBase.h
- src/Particle/LongRange/LRHandlerSRCoulomb.h
- src/Particle/LongRange/LRHandlerTemp.h
- src/Particle/LongRange/LRRPABFeeHandlerTemp.h
- src/Particle/LongRange/LRRPAHandlerTemp.h
- src/Particle/LongRange/TwoDEwaldHandler.h
- src/Particle/LongRange/tests/test_srcoul.cpp
- src/Particle/LongRange/tests/test_temp.cpp
- src/QMCHamiltonians/CoulombPBCAA.cpp
- src/QMCHamiltonians/CoulombPBCAA.h
- src/QMCHamiltonians/CoulombPBCAA_CUDA.cpp
- src/QMCHamiltonians/CoulombPBCAB.cpp
- src/QMCHamiltonians/CoulombPBCAB.h
- src/QMCHamiltonians/CoulombPBCAB_CUDA.cpp
- src/QMCHamiltonians/tests/test_coulomb_CUDA.cpp
- src/QMCHamiltonians/tests/test_coulomb_pbcAB.cpp
- src/QMCHamiltonians/tests/test_coulomb_pbcAB_ewald.cpp
- src/QMCWaveFunctions/Jastrow/LRBreakupUtilities.h
Review after merging #3235
Before this PR, shared_ptr are used for long range handler and short range pair functions in Coulomb PBC AA class. In fact when particle sets are active, the shared_ptr is used as unique_ptr. The AB class use unique_ptr.
In this PR, all the evaluation functions of  long range handler and short range pair functions are defined const (thread-safe).
So a shared copy of long range handler and short range pair function can be used among all the walkers safely. Both makeClone functions become calling compiler generated copy constructor.
- No
epyc-server
> Mark most LRHandler evaluate functions const and clean up its usage in Coulomb

- src/QMCWaveFunctions/tests/CMakeLists.txt
- src/QMCWaveFunctions/tests/test_DiffOneBodyJastrowOrbital.cpp
This PR extends the testing to cover the evaluate Derivatives for One Body Jastrow factors.
- No
Ryzen workstation (5900X)
> One Body Jastrow evaluateDerivatives test

- src/Particle/DTModes.h
- src/Particle/DistanceTableData.h
- src/Particle/ParticleSet.cpp
- src/Particle/ParticleSet.h
- src/Particle/SoaDistanceTableAB.h
- src/Particle/SoaDistanceTableABOMPTarget.h
- src/Particle/tests/CMakeLists.txt
- src/Particle/tests/test_DTModes.cpp
- src/QMCWaveFunctions/Jastrow/JeeIOrbitalSoA.h
- src/QMCWaveFunctions/LCAO/SoaLocalizedBasisSet.cpp
DTModes records operations switches required by distance table consumers.
Use strongly typed enum.
Intended to avoid unnecessary D2H transfer when offloading Jastrow factors.
The avail 'modes' are not final. Will adjust as the implementation goes.
- New feature
- No
epyc-server
> Add DTModes which represents switches used in distance tables.
